### ISSUE TITLE
API disabled in the context of body_filter_by_lua

### ISSUE THREAD

**Issue by Horus-K** [openresty/openresty#1011]
openresty/1.19.9.1

I want to be able to write the response body synchronously to redis, please tell me how to achieve this

```
location / {
            proxy_pass https://xxx.com;
            body_filter_by_lua_block {
                local res_body = ngx.arg[1]

                if ngx.arg[2] then
                    local redis = require "resty.redis"
                    local red = redis:new()

                    red:set_timeout(1000)

                    local ok, err = red:connect("", 6379)
                    if not ok then
                        ngx.log(ngx.ERR, "failed to connect to Redis: ", err)
                        return
                    end

                    local res_key = "response_body"
                    local res, err = red:set(res_key, res_body)

                    if not res then
                        ngx.log(ngx.ERR, "failed to set value in Redis: ", err)
                    end

                    red:close()
                end
            }
        }
```

```
[error] 28120#27792: *5 failed to run body_filter_by_lua*: ./lualib/resty\redis.lua:63: API disabled in the context of body_filter_by_lua*
stack traceback:
        [C]: in function 'tcp'
        ./lualib/resty\redis.lua:63: in function 'new'
        body_filter_by_lua(nginx.conf:45):7: in main chunk while sending to client, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "https://xxxx:443/", host: "127.0.0.1"
```

**Comment by oowl** [comment]
From the openresty lua-nginx-module doc [body_filter_by_lua](https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#body_filter_by_lua)
> Note that the following API functions are currently disabled within this context due to the limitations in Nginx output filter's current implementation:
    Output API functions (e.g., [ngx.say](https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#ngxsay) and [ngx.send_headers](https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#ngxsend_headers))
    Control API functions (e.g., [ngx.exit](https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#ngxexit) and [ngx.exec](https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#ngxexec))
    Subrequest API functions (e.g., [ngx.location.capture](https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#ngxlocationcapture) and [ngx.location.capture_multi](https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#ngxlocationcapture_multi))
    Cosocket API functions (e.g., [ngx.socket.tcp](https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#ngxsockettcp) and [ngx.req.socket](https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#ngxreqsocket)).

`body_filter_by_lua` phase can not support lua yield, all yield feature can not use in here (include cosocket), obviously, redis client must have cosocket APi for TCP request. So this issues is by design. You can use `ngx.timer` warpping your redis logic to a fly task (separate with the current request)

**Comment by Horus-K** [comment]
like this, But this will cause the body to be response early
```
 location = /async {
     keepalive_timeout 0;
     content_by_lua_block {
         ngx.say("got the task!")
         ngx.eof()  -- well written HTTP clients will close the connection at this point
         -- access MySQL, PostgreSQL, Redis, Memcached, and etc here...
     }
 }

```
Is there any way to make the response body happen after it is written to redis

**Comment by oowl** [comment]
> like this, But this will cause the body to be response early
> 
> ```
>  location = /async {
>      keepalive_timeout 0;
>      content_by_lua_block {
>          ngx.say("got the task!")
>          ngx.eof()  -- well written HTTP clients will close the connection at this point
>          -- access MySQL, PostgreSQL, Redis, Memcached, and etc here...
>      }
>  }
> ```
> 
> Is there any way to make the response body happen after it is written to redis

Try  https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#ngxlocationcapture

it will capture all the response body in lua `content` or `access` phase, and then you can write to redis and the downstream client. But everything was a trade off, if you use it, it will let your nginx process upstream response body to dowstream body by non streaming way.

**Comment by Horus-K** [comment]
I will use golang to proxy this request to redis, which is feasible
