### ISSUE TITLE
upgrading to latest nginx version

### ISSUE THREAD

**Issue by opensrcken** [openresty/openresty#104]
Nginx is now at 1.9.1. Is a matching upgrade of ngx_openresty forthcoming? What would it take to perform this upgrade myself?

**Comment by agentzh** [comment]
@opensrcken Yes, OpenResty 1.9.x.x will come soon. But I need to release OpenResty 1.7.10.2 first, which is the planned "tick" release according to the current "tick-tock" release model.

**Comment by wojons** [comment]
@agentzh 

what is in 1.7.10.2? and is there anything that can help get you to 1.7.10.2

**Comment by agentzh** [comment]
@wojons A lot of fixes in many components for 1.7.10.2. I will release a release candidate for 1.7.10.2 today or tomorrow on the openresty-en mailing list. It'll be great if you can help test the release candidates out on your side and report back any problems. This will speed up the formal release of 1.7.10.2 and help me move on to 1.9.x.x as soon as possible (hopefully in the next week or so). Thanks a lot!

**Comment by wojons** [comment]
@agentzh signed up for the mailing list have no idea why i did not do this awhile ago i will start testing it when you push it out. and i promise to no longer call it openrusty.

**Comment by agentzh** [comment]
@wojons OpenResty 1.7.10.2 RC1 was already out 13 hours ago:

https://groups.google.com/d/topic/openresty-en/AbwKJG0uATo/discussion

**Comment by wojons** [comment]
sadly i noticed that about 5 minutes after i posted it and felt dumb

**Comment by pinghe** [comment]
Nginx is now at 1.9.4.  included feature: multiple "sub_filter" directives can be used simultaneously.

upgrade ?

**Comment by agentzh** [comment]
@pinghe OpenResty 1.9.3.2 has to be released before the nginx core upgrade. See http://openresty.org/faq.html#does-openresty-follow-nginxs-mainline-releases

**Comment by Sweetchuck** [comment]
Is this issue still alive?

name | version | date
-- | -- | --
nginx        | 1.15.2    | 2018-07-24
nginx        | 1.13.6    | 2017-10-10
openresty | 1.13.6.2 | 2018-05-14

**Comment by agentzh** [comment]
The original issue is for nginx 1.9.x and the current latest openresty release is already based on nginx 1.13.6. So I'm closing this issue.

We're working on upgrading to nginx 1.15.x, as already mentioned in the release note of the openresty 1.13.6.2 version.
