### ISSUE TITLE
OpenResty for CentOS 7

### ISSUE THREAD

**Issue by williamcaban** [openresty/openresty#116]
I found the RPM SPEC does not work in a  CentOS 7 so I created one that works and uses systemd. In case anyone wants to integrate in the code or use it, I have published it at the following github repository https://github.com/williamcaban/ngx_openresty-rpm-spec

The following **NGINX** modules are enabled with the RPM SPEC:

- http\_iconv\_module
- http\_postgres\_module
- select\_module
- poll\_module
- file-aio
- http\_realip\_module
- http\_addition\_module
- http\_xslt\_module
- http\_image\_filter\_module
- http\_geoip\_module
- http\_sub\_module
- http\_dav\_module
- http\_flv\_module
- http\_gzip\_static\_module
- http\_auth\_request\_module
- http\_random\_index\_module
- http\_secure\_link\_module
- http\_degradation\_module
- http\_stub\_status\_module
- http\_ssl\_module
- with-http\_realip\_module
- mail
- mail\_ssl\_module
- google\_perftools\_module
- pcre
- pcre-jit
- md5-asm
- sha1-asm
- libatomic

**Comment by agentzh** [comment]
@williamcaban Thanks for sharing though it's a pity that the core component of OpenResty, the ngx_lua module, is not enabled in this according to your list above ;)

**Comment by williamcaban** [comment]
Done. Explicit support for pcre-jit, luajit, lua51 added to the build

**Comment by dol** [comment]
btw: Your package requires 'postgresql'. I recommend using a ['Weak dependencies'](http://www.rpm.org/wiki/PackagerDocs/Dependencies#Weakdependencies).

**Comment by williamcaban** [comment]
@dol I'm going to explore the alternative on having subpackages so that specific modules (i.e http_postgres_module) get their own subpackage and see if I can break dependencies among those. Right now, if I use weak dependencies and the user tries to use the http_postgres_module without having the libraries, it will have a fatal error during the loading process and I want to avoid that.

**Comment by 1dot75cm** [comment]
I write the RPM SPEC for el5 - el7, fc21 - fc23. It's very powerful. Please test.
https://copr.fedoraproject.org/coprs/mosquito/nginx/builds/

**Comment by 1dot75cm** [comment]
@williamcaban thank you hard work. Now, it's full support with el5 - el7, fc21 - fc23.
build result: https://copr.fedoraproject.org/coprs/mosquito/nginx/build/123983/

**Comment by luto** [comment]
Google People, the spec now lives at https://github.com/FZUG/repo/blob/master/rpms/openresty/openresty.spec

**Comment by agentzh** [comment]
Hi guys! OpenResty now offers official RPM package and yum repositories for CentOS/RHEL 5.x ~ 7.x and Fedora 22 ~ 24:

http://openresty.org/en/linux-packages.html

http://openresty.org/en/rpm-packages.html

The spec files and other sources are in the following GitHub repository:

https://github.com/openresty/openresty-packaging

You're welcome to contribute to the official packages :)
