### ISSUE TITLE
init_by_lua&init_by_lua_file nginx: [emerg] unknown directive "init_by_lua" in ...

### ISSUE THREAD

**Issue by liujianping** [openresty/openresty#13]
test init_by_lua&init_by_lua_file directive at http & server & location section ，all failed：
output ： [emerg] unknown directive init_by_lua&...

I compiled openresty with the configure:
./configure --prefix=/opt/openresty --with-luajit --without-http_redis2_module --with-http_drizzle_module  --with-http_iconv_module -j2
at my mac.

**Comment by higkoo** [comment]
I've custom the path, see the same error.
Have a try:
 `resty --nginx /usr/sbin/openresty -e 'ngx.say("hello")'`

**Comment by agentzh** [comment]
@higkoo Please do not hijack closed issues. And you fail to give enough details. I cannot reproduce the problem with the latest OpenResty 1.11.2.5 release on Mac OS X and Linux:

```
agentzh@imac5k ~ $ resty -e 'ngx.say("hello")'
hello
```

```
agentzh@fedora64 ~ $ resty -e 'ngx.say("hello")'
hello
```

And I'm pretty sure it works fine on Win32 as well.

If you get this error, then it means you are using the wrong nginx binary or your `ngx_lua` module is so ancient that it does not have this directive yet.
