### ISSUE TITLE
关于“ngx_redis”模块的一些建议

### ISSUE THREAD

**Issue by yanji0520** [openresty/openresty#145]
在项目中，redis用的是cluster，前端通过openrestry连接redis-cluster时，会出现redis-cluster的“ASK 转向/MOVED 转向”信息，导致获取的数据不正确，是否有什么办法，在连接redis-cluster能够准确定位到正确的redis上

**Comment by agentzh** [comment]
@yanji0520 Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/#Community Thanks for
your cooperation.

Regarding your question, the ngx_redis module does not support the new Redis 3.0 cluster feature yet.

**Comment by yanji0520** [comment]
In the project,redis uses the cluster,when the front end connects redis-cluster by openrestry,the message"ASK turn/MOVED turn" of redis-cluster would appear,resulting  the acquired data is not correct,whether there is any way,it can be able to accurately locate to the correct redis when connect redis-cluster.

**Comment by agentzh** [comment]
@yanji0520 Both ngx_redis and ngx_redis2 were created way before Redis added the cluster protocol so there's no wonder that they do not understand those redirect responses (yet).

**Comment by agentzh** [comment]
@yanji0520 You could, however, use custom hasing to distribute your requests to multiple redis nodes and perform failover and etc in your own (Lua) code in nginx.
