### ISSUE TITLE
Can't exec "cc" when I run configure

### ISSUE THREAD

**Issue by exoristi** [openresty/openresty#146]
Hi,
I am trying to install the latest version of openresty (1.9.7.1) but when I run ./configure I get the following error (gcc is installed):

```
platform: msys (msys)
cp -rp bundle/ build
cd build
cd LuaJIT-2.1-20151219
Can't exec "cc": No such file or directory at ./configure line 588.
make TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/openresty/luajit
==== Building LuaJIT 2.1.0-beta1 ====
make -C src
make[1]: cc: Command not found
make[1]: Entering directory `/c/ngx_openresty-1.9.7.1/build/LuaJIT-2.1-20151219/src'
make[1]: cc: Command not found
make[1]: cc: Command not found
make[1]: cc: Command not found
make[1]: cc: Command not found
make[1]: cc: Command not found
Makefile:262: *** Unsupported target architecture.  Stop.
make[1]: Leaving directory `/c/ngx_openresty-1.9.7.1/build/LuaJIT-2.1-20151219/src'
make: *** [default] Error 2
ERROR: failed to run command: make TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/openresty/luajit
```

I tried to run ./configure --with-luajit-xcflags='-std=gnu99'  but I got the same error.
Is there something that I have missed?
Thanks!

**Comment by agentzh** [comment]
@exoristi You need to specify the `--with-cc=gcc` option on Windows. Check out the following document for more details on building OpenResty in Win32:

https://github.com/openresty/openresty/blob/master/doc/README-win32.md#details-about-the-building-process

BTW, official binary packages on Windows can be found here:

https://openresty.org/#Download

**Comment by exoristi** [comment]
@agentzh
I have already tried `--with-cc=gcc` for both 1.9.7.1 and 1.9.7.2 versions but I got more errors
see: [https://github.com/exoristi/logs/blob/master/openresty.txt](url)


I got different errors when I ran:
`
./configure --with-cc=gcc \
    --prefix= \
    --with-cc-opt='-DFD_SETSIZE=1024' \
    --with-select_module \
    --with-ipv6 \
    --sbin-path=nginx.exe \
    --with-pcre-jit \
    --with-luajit-xcflags="-DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT" \
    --with-pcre=objs/lib/pcre-8.37 \
    --with-zlib=objs/lib/zlib-1.2.8 \
    --with-openssl=objs/lib/openssl-1.0.2d \
    -j5
`
[https://github.com/exoristi/logs/blob/master/openresty2.txt](url)

**Comment by agentzh** [comment]
@exoristi Are you sure you are using the latest MinGW gcc?

**Comment by exoristi** [comment]
@agentzh gcc version 3.4.4 (msys special)

**Comment by agentzh** [comment]
@exoristi Your MinGW gcc is just too old for compiling LuaJIT. Mine is 4.8.1 in my Windows 10 system:

```
agentzh@win64 /c/agentzh/openresty-1.9.7.3 $ gcc --version
gcc.exe (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by agentzh** [comment]
@exoristi Please upgrade to the latest MinGW gcc toolchain in your Windows system.

**Comment by geoyws** [comment]
If you are using Amazon's EC2 to host OpenResty, remember to install the development tools that are not installed by default because not everyone compiles software. http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/compile-software.html

**Comment by exoristi** [comment]
I tried the latest version of gcc and installed msys2 as well. I still get the same errors so I gave up and installed 'ngx_openresty-1.9.3.2-win32' instead which works fine so far.

**Comment by agentzh** [comment]
@exoristi That's weird. Since gcc 4.8.1 *must* have the `stdint.h` header. Maybe you were still using the old gcc binary due to bad PATH environment? Anyway, use of the official Win32 build of OpenResty is recommended. I'm closing this for now.

**Comment by hizorro88** [comment]
yum install gcc
