### ISSUE TITLE
windows下怎么编译

### ISSUE THREAD

**Issue by liqile** [openresty/openresty#149]
文档中没找到

**Comment by agentzh** [comment]
@liqile Please do not use Chinese here. If you really want to use Chinese, please join the openresty (Chinese) mailing list instead. Please see https://openresty.org/#Community

Regarding your question, please see this official document: https://github.com/openresty/openresty/blob/master/doc/README-win32.md

**Comment by warmchang** [comment]
Read the "README-win32.txt" in "openresty-1.9.7.X.tar.gz", setup the environment ,and run "util/build-win32.sh".

Good lukey!
