### ISSUE TITLE
Create official Docker Hub image

### ISSUE THREAD

**Issue by pataquets** [openresty/openresty#151]
As it also exists for Nginx: https://hub.docker.com/_/nginx/
Even two different versions could be created:
- One, based in the official Nginx image and adding the lua as a dynamic loading module
- Another with the full compile build from source tree

Docker Hub automated builds would come handy to create different image tags, matching git tags/branches.

**Comment by agentzh** [comment]
@pataquets Yeah, this is something we could look into :)

**Comment by agentzh** [comment]
@pataquets But I'd go for the second option only otherwise it's not really "OpenResty".

**Comment by neomantra** [comment]
@agentzh  The task is basically creating a Dockerfile.   Would you include the Dockerfile in the OpenResty repo?   Otherwise, one can make another project that, as part of the Docker image build process, downloads the release tarball from openresty.org

Another consideration is what "base" operating system to use (i.e. the FROM directive).

**Comment by neomantra** [comment]
Here's an example Dockerfile using Ubuntu 14.04 as a base:

```
FROM ubuntu:trusty

MAINTAINER OpenResty <docker@openresty.org>

ENV RESTY_VERSION 1.9.7.3

# Download and extract the OpenResty release
ADD https://openresty.org/download/openresty-$RESTY_VERSION.tar.gz /tmp/openresty-$RESTY_VERSION.tar.gz
RUN tar xzf /tmp/openresty-$RESTY_VERSION.tar.gz -C /tmp
RUN rm /tmp/openresty-$RESTY_VERSION.tar.gz
WORKDIR /tmp/openresty-$RESTY_VERSION

# Install dependencies
RUN apt-get -y update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libreadline-dev libncurses5-dev libpcre3-dev \
        libssl-dev perl make build-essential

# Build
RUN ./configure
RUN make
RUN make install

# Cleanup
RUN rm -rf /tmp/openresty-$RESTY_VERSION.tar.gz
```

There are other considerations (like passing custom configure options), but we can grow that.

**Comment by neomantra** [comment]
FWIW, the Nginx Dockerfile uses Debian Jessie and install's nginx.org's debian packages.

**Comment by agentzh** [comment]
@neomantra Are you interested in creating and maintaining the official docker hub image? I'd like to be the person sending requests instead of doing the hard work :) Please let me know how I can help you in any ways.

**Comment by agentzh** [comment]
@neomantra IIRC, I used to register an openrestyorg docker hub account. Let me know if you like to share that account.

**Comment by agentzh** [comment]
@neomantra Yeah, there's plans to provide official binary packages of OpenResty for debian, ubuntu, centos, and etc. But we're not there yet.

**Comment by agentzh** [comment]
@neomantra BTW, regarding your sample dockerfile, I think it's better to

1. enable options like `--with-ipv6` and `--with-pcre-jit` by default in the binary build's `./configure` command.
2. pass `-jN` option to both the `./configure` and `make` commands to speed up the build.
3. use `--with-pcre=PATH` and `--with-openssl=PATH` options in `./configure` to ensure we always include the latest versions of the PCRE and OpenSSL libraries (no matter what the system provided versions are).
4. Add an init script to easily start and stop the openresty as a service (we can steal NGINX's init script and apply some changes to fit OpenResty's needs).

I'm not really a docker person. There might be other tweaks needed. But feel free to educate me if I'm wrong :)

**Comment by agentzh** [comment]
Hmm, FWIW, I think we'd better have a debug version of OpenResty which is built with `./configure --with-debug --with-no-pool-patch` in addition to the default production version. As you can see, I'd like to be the one proposing things :)

**Comment by neomantra** [comment]
@agentzh   I don't mind being a point of contact, i.e. the MAINTAINER in the Dockerfile. Maybe add me to the OpenResty GitHub organization and we make a project something like `openresty-docker` under it?  It would be that repo that the Docker registry builds from.

In that case, let's stick with Ubuntu for a distro (if somebody wants something different they can fork and we can make other branches)?

Your suggestions seem reasonable.  Regarding 3, are you suggesting also custom-installing PCRE and OpenSSL in the Dockerfile?

With all these options, there's two divergent setups:
 1. somebody just wants to docker pull openresty and have some default openresty that works straight from the official Docker Registry.  The registry also supports tags, so we can make another one like a "debug" one
 2. there's somebody who wants to clone the repo, build their custom image with their specific settings, and save that image to their own registry or local machine).  For example, you can make your own debug one -- we can also suggest some good settings for that.  We just need to make entry points to facilitate adding args to ./configure.

You are probably more familiar with how people like to configure OpenResty, so whatever you want the defaults to be I'll make it so.

**Comment by agentzh** [comment]
@neomantra With `--with-pcre=PATH` and `--with-openssl=PATH`, the nginx build system will automatically build these libraries from source and statically link against them. What we need to do is just to download and unpack the source tarballs of these libraries so that we can reference in the `./configure` command line :)

I've already added you to the openresty github organization. Please let me know if you need anything further from me :) Thanks for your contribution!

**Comment by neomantra** [comment]
Great.   Are these the active versions of those libs? (from the Wiki)
```
wget https://www.openssl.org/source/openssl-1.0.2f.tar.gz
tar -zvxf openssl-1.0.2f.tar.gz

wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.38.tar.gz
tar -xvf pcre-8.38.tar.gz
```

I won't be able to do this properly until next week, but @pataquets has a Dockerfile they can play with.  Any other comments/suggestions are welcome.

**Comment by agentzh** [comment]
@neomantra The version of PCRE looks good but I'd suggest use of OpenSSL 1.0.2e for OpenResty 1.9.7.3 because 1.0.2f introduces some minor incompatibilities that are fixed only in newer NGINX cores (1.9.12+). We can bump the version of OpenSSL later when we have OpenResty 1.9.12.x :)

**Comment by neomantra** [comment]
I just created this repository https://github.com/openresty/docker-openresty

The "build" aspect of it is all done.  Need to work out the "run" aspect.   Once I am happy with that, we can push to Docker Hub.

I'm going to close this ticket.  Please continue Docker-related discussion in docker-openresty issues.

**Comment by schickling** [comment]
@neomantra please give us a ping here once the Docker image is ready to use 👍

**Comment by neomantra** [comment]
I actually pushed the repos to Docker Hub yesterday.  See:

https://hub.docker.com/r/openresty/openresty
https://github.com/openresty/docker-openresty

There is no scaffolding -- it is a base container with OpenResty built in it.  There's a ticket for deciding if/how to expand it (https://github.com/openresty/docker-openresty/issues/2).
