### ISSUE TITLE
How to update a component of openresty?

### ISSUE THREAD

**Issue by wangyinsheng** [openresty/openresty#153]
HI,
   current openresty is :
         openresty 1.2.8.6
         lua-cjson-1.0.3

I want to update the lua-cjson libaray to lua-cjson-2.1.0 without updating openresty.
what should i do?
I tried to replace `openresty/lualib/cjson.so`  with the new one, but it donot work as i expect.
here is error log
`nginx: [error] failed to run init_by_lua*: error loading module 'cjson.safe' from file '/export/servers/openresty/lualib/cjson.so':
        /export/servers/openresty/lualib/cjson.so: undefined symbol: lua_pcallk
stack traceback:
        [C]: at 0x7f8b75176740
        [C]: in function 'require'
        /export/servers/openresty/nginx/unify-lua/mercury_init.lua:14: in main chunk`

thank you for any suggestion!

**Comment by agentzh** [comment]
@wangyinsheng It should work. Your error message indicates that your cjson.so was built against an incompatible Lua ABI (like Lua 5.2 or 5.3). Note that only the Lua 5.1 ABI is supported in OpenResty.
