### ISSUE TITLE
run the build-win32.sh in win7 with MinGW toolchain, but got an error.

### ISSUE THREAD

**Issue by warmchang** [openresty/openresty#159]
Hello!

According the "README-win32.txt", I have download the "openresty-1.9.7.4.tar.gz" and the necessary dependency library, setup the building tools, then run the "build-win32.sh".

But got an error, It look like the "cjson.so" could not be found, I check the directory, and can't found this file.

What's wrong with my operation? Here are some output infos:

    checking for OS
     + MINGW32_NT-6.1 1.0.18(0.48/3/2) i686
     + using GNU C compiler
     + gcc version: 4.8.1 (GCC)
    checking for gcc -pipe switch ... found
    checking for gcc builtin atomic operations ... found
    checking for C99 variadic macros ... found
    checking for gcc variadic macros ... found
    checking for MINGW32_NT-6.1 specific features
    configuring additional modules
    adding module in ../ngx_devel_kit-0.2.19
     + ngx_devel_kit was configured
    adding module in ../echo-nginx-module-0.58
     + ngx_http_echo_module was configured
    adding module in ../xss-nginx-module-0.05
     + ngx_http_xss_filter_module was configured
    adding module in ../ngx_coolkit-0.2rc3
     + ngx_coolkit_module was configured
    adding module in ../set-misc-nginx-module-0.30
    found ngx_devel_kit for ngx_set_misc; looks good.
     + ngx_http_set_misc_module was configured
    adding module in ../form-input-nginx-module-0.11
    found ngx_devel_kit for ngx_form_input; looks good.
     + ngx_http_form_input_module was configured
    adding module in ../encrypted-session-nginx-module-0.04
     + ngx_http_encrypted_session_module was configured
    adding module in ../srcache-nginx-module-0.30
     + ngx_http_srcache_filter_module was configured
    adding module in ../ngx_lua-0.10.2
    checking for LuaJIT library in /c/openresty/openresty-1.9.7.4/build/luajit-root and /c/openresty/openresty-1.9.7.4/build/luajit-root/include/luajit-2.1 (win32) ... found
    checking for export symbols by default (-E) ... found
    checking for export symbols by default (--export-all-symbols) ... found
    checking for SO_PASSCRED ... not found
     + ngx_http_lua_module was configured
    adding module in ../ngx_lua_upstream-0.05
     + ngx_http_lua_upstream_module was configured
    adding module in ../headers-more-nginx-module-0.29
     + ngx_http_headers_more_filter_module was configured
    adding module in ../array-var-nginx-module-0.05
    found ngx_devel_kit for ngx_array_var; looks good.
     + ngx_http_array_var_module was configured
    adding module in ../memc-nginx-module-0.16
     + ngx_http_memc_module was configured
    adding module in ../redis2-nginx-module-0.12
     + ngx_http_redis2_module was configured
    adding module in ../redis-nginx-module-0.3.7
     + ngx_http_redis_module was configured
    adding module in ../rds-json-nginx-module-0.14
     + ngx_http_rds_json_filter_module was configured
    adding module in ../rds-csv-nginx-module-0.07
     + ngx_http_rds_csv_filter_module was configured
    creating objs/Makefile
    
    Configuration summary
      + using PCRE library: /c/openresty/openresty-1.9.7.4/objs/lib/pcre-8.38
      + using OpenSSL library: /c/openresty/openresty-1.9.7.4/objs/lib/openssl-OpenSSL_1_0_2e
      + md5: using OpenSSL library
      + sha1: using OpenSSL library
      + using zlib library: /c/openresty/openresty-1.9.7.4/objs/lib/zlib-1.2.8
    
      nginx path prefix: "."
      nginx binary file: "./nginx.exe"
      nginx configuration prefix: "./conf"
      nginx configuration file: "./conf/nginx.conf"
      nginx pid file: "./logs/nginx.pid"
      nginx error log file: "./logs/error.log"
      nginx http access log file: "./logs/access.log"
      nginx http client request body temporary files: "client_body_temp"
      nginx http proxy temporary files: "proxy_temp"
      nginx http fastcgi temporary files: "fastcgi_temp"
      nginx http uwsgi temporary files: "uwsgi_temp"
      nginx http scgi temporary files: "scgi_temp"
    
    cd ../..
    Type the following commands to build and install:
        make
        make install
    cd /c/openresty/openresty-1.9.7.4/build/LuaJIT-2.1-20160108 && c:/MinGW/bin/make TARGET_STRIP=@: CCDEBUG=-g XCFLAGS='-DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT' CC='gcc' PREFIX=./luajit
    make[1]: Entering directory 'c:/openresty/openresty-1.9.7.4/build/LuaJIT-2.1-20160108'
    ==== Building LuaJIT 2.1.0-beta1 ====
    c:/MinGW/bin/make -C src
    make[2]: Entering directory 'c:/openresty/openresty-1.9.7.4/build/LuaJIT-2.1-20160108/src'
    make[2]: Nothing to be done for 'default'.
    make[2]: Leaving directory 'c:/openresty/openresty-1.9.7.4/build/LuaJIT-2.1-20160108/src'
    ==== Successfully built LuaJIT 2.1.0-beta1 ====
    make[1]: Leaving directory 'c:/openresty/openresty-1.9.7.4/build/LuaJIT-2.1-20160108'
    cd /c/openresty/openresty-1.9.7.4/build/lua-cjson-2.1.0.3 && c:/MinGW/bin/make DESTDIR=/c/openresty/openresty-1.9.7.4/ LUA_INCLUDE_DIR=/c/openresty/openresty-1.9.7.4/build/luajit-root/include/luajit-2.1 LUA_CMODULE_DIR=./lualib LUA_MODULE_DIR=./lualib CJSON_LDFLAGS="-shared -L/c/openresty/openresty-1.9.7.4/build/luajit-root -llua51" CJSON_CFLAGS="-g -fpic" CC='gcc'
    make[1]: Entering directory 'c:/openresty/openresty-1.9.7.4/build/lua-cjson-2.1.0.3'
    gcc -c -O3 -Wall -pedantic -DNDEBUG  -Ic:/openresty/openresty-1.9.7.4/build/luajit-root/include/luajit-2.1 -g -fpic -o lua_cjson.o lua_cjson.c
    lua_cjson.c:1:0: warning: -fpic ignored for target (all code is position independent) [enabled by default]  /* Lua CJSON - JSON support for Lua
     ^
    gcc -c -O3 -Wall -pedantic -DNDEBUG  -Ic:/openresty/openresty-1.9.7.4/build/luajit-root/include/luajit-2.1 -g -fpic -o strbuf.o strbuf.c
    strbuf.c:1:0: warning: -fpic ignored for target (all code is position independent) [enabled by default]
     /* strbuf - String buffer routines
     ^
    gcc -c -O3 -Wall -pedantic -DNDEBUG  -Ic:/openresty/openresty-1.9.7.4/build/luajit-root/include/luajit-2.1 -g -fpic -o fpconv.o fpconv.c
    fpconv.c:1:0: warning: -fpic ignored for target (all code is position independent) [enabled by default]
     /* fpconv - Floating point conversion routines
     ^
    gcc  -shared -L/c/openresty/openresty-1.9.7.4/build/luajit-root -llua51 -o cjson.so lua_cjson.o strbuf.o fpconv.o
    c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: cannot find -llua51
    collect2.exe: error: ld returned 1 exit status
    Makefile:100: recipe for target 'cjson.so' failed
    make[1]: *** [cjson.so] Error 1
    make[1]: Leaving directory 'c:/openresty/openresty-1.9.7.4/build/lua-cjson-2.1.0.3'
    Makefile:6: recipe for target 'all' failed
    make: *** [all] Error 2

Thank you!

**Comment by agentzh** [comment]
@warmchang What's in your directory `/c/openresty/openresty-1.9.7.4/build/luajit-root`? Seems like your LuaJIT build was incomplete. Ensure you have run `make clean` before running `build-win32.sh` for another time.

**Comment by warmchang** [comment]
Hi @agentzh ,

The "luajit-root" directory make by script. I run the "make clean" then "build-win32.sh" again, and got the same result.

"luajit-root" directory is as follow after build:

    sh-3.1$ pwd
    /c/openresty/openresty-1.9.7.4/build/luajit-root
    sh-3.1$ ls -l
    total 2694
    drwxr-xr-x 3 china Administrators       0 Mar 21 19:37 include
    drwxr-xr-x 3 china Administrators       0 Mar 21 19:37 lua
    -rwxr-xr-x 1 china Administrators 2654883 Mar 21 19:37 lua51.dll
    -rwxr-xr-x 1 china Administrators  103121 Mar 21 19:37 luajit.exe
    sh-3.1$

The "cjson.so" can't be made, and now I have no idea about this...

**Comment by warmchang** [comment]
I have tried the "openresty-1.9.7.3" and "ngx_openresty-1.9.7.2", and got the same result.

    C:\openresty\openresty-1.9.7.4\build\luajit-root>tree /f /a
    文件夹 PATH 列表
    卷序列号为 00000200 662B:8D2B
    C:.
    |   lua51.dll
    |   luajit.exe
    |
    +---include
    |   \---luajit-2.1
    |           lauxlib.h
    |           lua.h
    |           lua.hpp
    |           luaconf.h
    |           luajit.h
    |           lualib.h
    |
    \---lua
        \---jit
                bc.lua
                bcsave.lua
                dis_arm.lua
                dis_mips.lua
                dis_mipsel.lua
                dis_ppc.lua
                dis_x64.lua
                dis_x86.lua
                dump.lua
                p.lua
                v.lua
                vmdef.lua
                zone.lua

**Comment by agentzh** [comment]
@warmchang The error was "ld.exe: cannot find -llua51". But the command triggering that does have the correct library search path set, that is, `-L/c/openresty/openresty-1.9.7.4/build/luajit-root`. And there is indeed a `lua51.dll` file in that `luajit-root` directory. Weird. There seems to be some reason that ld refuses to accept that lua51.dll there.

Because I never see this on my Windows boxes when building the Win32 binary, it's a bit tough for me to reproduce and debug this for you. Maybe you can try digging in that direction yourself?

Failing that, you can use the official Win32 binary distributed on the openresty.org site:

https://openresty.org/en/download.html

**Comment by warmchang** [comment]
Good news,

I have changed to use the MSYS2 environment and mingw-w64-i686-gcc toolchain, and can compile correctly.
    C:\msys32\home\china\openresty\openresty-1.9.7.4>nginx.exe -V
    nginx version: openresty/1.9.7.4
    built by gcc 5.3.0 (Rev2, Built by MSYS2 project)
    built with OpenSSL 1.0.2e 3 Dec 2015
    TLS SNI support enabled
    configure arguments: --prefix=. --with-cc-opt='-O2 -DFD_SETSIZE=1024' --add-module=../ngx_devel_kit-0.2.19
    --add-module=../echo-nginx-module-0.58 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.
    2rc3 --add-module=../set-misc-nginx-module-0.30 --add-module=../form-input-nginx-module-0.11 --add-module=.
    ./encrypted-session-nginx-module-0.04 --add-module=../srcache-nginx-module-0.30 --add-module=../ngx_lua-0.1
    0.2 --add-module=../ngx_lua_upstream-0.05 --add-module=../headers-more-nginx-module-0.29 --add-module=../ar
    ray-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.16 --add-module=../redis2-nginx-module-0.12 -
    -add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-
    nginx-module-0.07 --with-cc=gcc --with-ipv6 --sbin-path=nginx.exe --with-ipv6 --with-pcre-jit --with-http_s
    tub_status_module --with-http_realip_module --with-stream --with-stream_ssl_module --with-http_addition_mod
    ule --with-http_sub_module --with-pcre=/home/china/openresty/openresty-1.9.7.4/objs/lib/pcre-8.38 --with-zl
    ib=/home/china/openresty/openresty-1.9.7.4/objs/lib/zlib-1.2.8 --with-openssl=/home/china/openresty/openres
    ty-1.9.7.4/objs/lib/openssl-1.0.2e --with-select_module --with-http_ssl_module
    
    C:\msys32\home\china\openresty\openresty-1.9.7.4>

So I think the error before was caused by the build environment.

Anyway, thank you for your attention!
