### ISSUE TITLE
how to distinguish real backend err/timeout and backend returned err in upstream

### ISSUE THREAD

**Issue by xbsura** [openresty/openresty#161]
hi:
When using updtream, if upstream_status is [502, 200], I dont know whether the 502 mean backend can not connect or just the backend return 502
and another bug, upstream_addr always print the last upstream such as:
server=127.0.0.1 upstream_addr=[10.57.48.61:8021, 10.57.48.61:8021] upstream_status=[502, 200]
in fact the first upstream addr shoud other addr

openresty 1.9.7.2, with balancer lua module

**Comment by xbsura** [comment]
I tried to use nginx upstream, upstream_addr is ok, but after using set_current_peer, it always print the last ip and port
Maybe it's a bug of balancer module

@agentzh 
thanks.

**Comment by agentzh** [comment]
@xbsura I'm not sure what you're talking about here. Will you give a standalone and complete example to demonstrate the problem?
