### ISSUE TITLE
How to find the latest version in a shell script?

### ISSUE THREAD

**Issue by da99** [openresty/openresty#163]
So far I've been using the following to get the version number. Is there an official, recommended way to getting the latest version in code?

```bash
  git ls-remote -t https://github.com/openresty/openresty |  \
          cut -d'/' -f 3 |           \
          sort -r        |            \
          grep -P '^v[0-9\.]+$' |      \
          head -n 1      |              \
          cut -d'v' -f1

**Comment by agentzh** [comment]
@da99 Will you elaborate your real-world use case for fetching the latest version number of OpenResty?

**Comment by da99** [comment]
This is for dev and testing purposes and not staging/production purposes.
I write Bash/Zsh shell scripts that download and test the app against the latest stable version of OpenResty. I've given up on OS package managers because the versions might be out-of-date or contain customizations I don't want. I've seen popular Node.js code that use curl/wget to download HTML (https://nodejs.org/dist/) and "sed" it to get the latest node.js. I wasn't sure how OpenResty does it.

It's not an important feature. I was curious how other people partially automate the process during dev and testing.

**Comment by agentzh** [comment]
@da99 Well, I'm indeed going to add a /download/openresty-latest.tar.gz resource on the openresty.org site. Hopefully it'll make your life easier.

On the other hand, you can surely download the HTML page of http://openresty.org/en/download.html and scan the HTML source locally if you want to :)

**Comment by da99** [comment]
@agentzh Thanks very much.
