### ISSUE TITLE
./configure: error: ngx_http_lua_module requires the Lua library.

### ISSUE THREAD

**Issue by SilenceCarrot** [openresty/openresty#164]
春哥您好，向您请教一个问题；
我的nginx安装在/usr/local/nginx-1.9.7
我将luajit2-2.1-20160108  lua-nginx-module-0.10.2  ngx_devel_kit-0.2.19放在/path/to/下，
然后进入到luajit2-2.1-20160108中执行make install 
然后进入/usr/local/nginx-1.9.7，配置：
export LUAJIT_LIB=/usr/local/lib
export LUAJIT_INC=/usr/local/include/luajit-2.1

sudo ./configure \
         --with-ld-opt="-Wl,-rpath,/path/to/luajit-or-lua/lib" \
           --add-module=/path/to/ngx_devel_kit-0.2.19 \
           --add-module=/path/to/lua-nginx-module-0.10.2

然后出错了，提示 ./configure: error: ngx_http_lua_module requires the Lua library.
这是什么问题呢？该怎么解决呢？
在这之前我成功安装了echo_nginx_module,测试可以正常使用。谢谢春哥

**Comment by agentzh** [comment]
@SilenceCarrot Please do not use Chinese here. This place is considered English only. Thanks for your cooperation.

Regarding your question, you may try out the OpenResty bundle directly: https://openresty.org/

**Comment by SilenceCarrot** [comment]
Thanks;

**Comment by coeus-lei** [comment]
I saw people using English, Russian, Hindi, Spanish on github, so why can't we use Chinese?

**Comment by maikelvl** [comment]
You can work around it by setting this environmental variables:

```bash
export LUAJIT_LIB=/usr/lib64;
export LUAJIT_INC=/usr/include/luajit-2.1;
```

From https://github.com/openresty/lua-nginx-module/issues/1606#issuecomment-603881588

**Comment by agentzh** [comment]
@coeus-lei It's the project policy. Chinese texts should go to the OpenResty Chinese forum or the OpenResty Chinese mailing list:

https://forum.openresty.us/

https://groups.google.com/forum/#!forum/openresty
