### ISSUE TITLE
cdef call makes lua entry thread aborted

### ISSUE THREAD

**Issue by xu4wang** [openresty/openresty#166]
Hello Openresty/Luajit Gurus，

I wrote a lua script for openresty and called it by 
```
	location /v1/tms {  
	    default_type "text/html";  
	    content_by_lua_file "lua/tms.lua";
	}
```

The script tms.lua use FFI, like below:

```
local ffi = require("ffi")
ffi.cdef[[
	int string_xor(uint8_t *dest, unsigned long *destLen,
		const uint8_t *source1, unsigned long sourceLen1,
		const uint8_t *source2, unsigned long sourceLen2);
	int string_xor_checksum(const uint8_t *source1, unsigned long sourceLen1);
	int des_crypt(uint8_t *dest, unsigned long *destLen,
		const uint8_t *source, unsigned long sourceLen,
		const uint8_t *key, unsigned long keylen);
	int des_decrypt(uint8_t *dest, unsigned long *destLen,
		const uint8_t *source, unsigned long sourceLen,
		const uint8_t *key, unsigned long keylen);
]]

local tmslib = ffi.load("/usr/local/lib/libtms.so")
```

The script works as expected for several days, but after some time, it cannot work.
If I restart nginx, the script works again.  as a result I need to restart nginx every 2 or 3 days ...

I check the error.log and found:

```
2016/04/14 06:37:37 [error] 19203#0: *6210 lua entry thread aborted: runtime error: table overflow
stack traceback:
coroutine 0:
        [C]: in function 'cdef'
        /home/ubuntu/tms/lua/tms.lua:25: in function </home/ubuntu/tms/lua/tms.lua:1>, client: 59.173.204.84, server: , request: "POST /v1/tms?p=811829C715110784F6DC0C878F5672314F4414A533C906096CC96B0AF58B HTTP/1.1", host: "api.xxxxxxxx.com"
```

Looks like the function call to ffi.cdef makes the lua entry thread aborted.
I don't know why it's aborted? I notice the above error message generated for each incoming HTTP request to /v1/tms...
  
Is there anything wrong with my code?

Thanks a lot.
Xu

**Comment by agentzh** [comment]
@xu4wang It is a very bad idea to call `ffi.cdef` and alike for multiple times (here you call them upon every request). You should define a proper Lua module instead. See `lua-resty-string` and `lua-resty-core` for such examples.

**Comment by xu4wang** [comment]
@agentzh  thanks for the quick response. I'm fixing it.

**Comment by xu4wang** [comment]
@agentzh after moving most of the logic (including ffi) into a module, there is no lua entry thread abort for several days. Thanks for the help.
