### ISSUE TITLE
同一个处理阶段只有一个by_lua脚本能执行

### ISSUE THREAD

**Issue by onlonely** [openresty/openresty#167]
`rewrite_by_lua 'ngx.log(ngx.ERR,"root,lua")';`
`location /test {rewrite_by_lua 'ngx.log(ngx.ERR,"location,lua")';}`

假如我nginx.conf里面写入这两行,同样使用rewrite_by_lua在相同的执行阶段执行一段脚本

结果访问/test入口的时候,只有一个脚本执行了
`2016/04/15 09:32:26 [error] 177852#0: *227 [lua] rewrite_by_lua(nginx.conf:130):1: location,lua, client: 10.180.150.65, server`

这样造成同一个阶段在nginx.conf里面最多只能配置一个脚本执行,造成很大的不便和设计难题

**Comment by agentzh** [comment]
@onlonely Please do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see https://openresty.org/en/community.html Thanks for your cooperation.

Regarding your question, I think you should really use custom Lua modules to compose different processing handlers on the Lua land instead. Well, it's Lua.
