### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by alubbe** [openresty/openresty#170]
Sorry to open an issue here, I wasn't sure where the proper place for this question would be.

I've started updating my openresty bundle to nginx 1.9.15 because of improved HTTP2 support and the fix for the openssl 1.0.2f init error messages, and was wondering which nginx version is next for the official bundle and what the rough timeline for its release are?

**Comment by warmchang** [comment]
I think the nginx core of next or's version is 1.9.15:
https://github.com/openresty/openresty/commit/86be514b1c14233d48a5b01e9e74517ee5eee3ac

**Comment by alubbe** [comment]
You're right, that's looking good. I think there was also a luajit bug on hacker news this weekend that was just fixed, maybe that could make it as well?
Regarding the next release, I'm just interested in a rough timelime, nothing concrete, so anything vague is already helpful.

**Comment by agentzh** [comment]
@alubbe Hopefully in the next few weeks. I'm still busy working on the new OR release.

**Comment by agentzh** [comment]
@alubbe Yes, we'll move on the latest LuaJIT v2.1 once my tests show all green :)

**Comment by alubbe** [comment]
That sounds like around 3 weeks, so I'll pull in some patches manually ;)
Thanks for your quick response and your hard work on the next release
