### ISSUE TITLE
Why `os.getenv` doesn't work?

### ISSUE THREAD

**Issue by veficos** [openresty/openresty#171]
```
location /getPath {
    content_by_lua 'ngx.say(os.getenv("PATH"))';
    # set_by_lua $PATH 'return os.getenv("PATH")';
    # echo $PATH;
}
```

result:
```
$ curl http://127.0.0.1/getPath
$ nil
```

but in the init_by_lua, it works well:

```
init_by_lua 'path = os.getenv("PATH")'
...
server {
    set_by_lua $PATH 'return path';
    location /getPath {
        echo $PATH;
    }
}
```

**Comment by RocFang** [comment]
env directive should be used in your nginx.conf.

for reference:
https://github.com/openresty/lua-nginx-module#system-environment-variable-support

**Comment by veficos** [comment]
Thank you. I know this.
But I want to know why : )

**Comment by agentzh** [comment]
@veficos Because nginx only passes a very limited set of system environments to its worker processes due to security considerations (you can find similar constraints in `sudo` configurations too, for example).

**Comment by veficos** [comment]
@agentzh Thanks, I found the answer in the http://nginx.org/en/docs/ngx_core_module.html#env
