### ISSUE TITLE
lua_shared_dict  可以存储LUA table么

### ISSUE THREAD

**Issue by cellcb** [openresty/openresty#174]
lua_shared_dict reqcache 1m;
...

        location /test{
            default_type text/html;
          
            content_by_lua_block {
                local reqcache = ngx.shared.reqcache;
                local tbl= {"alpha", "beta", "gamma"}
                ngx.say(tbl)
                ngx.say('<BR/>')  
                reqcache:set('a',tbl)
                ngx.say(reqcache:get('a'))
            }
        }
 
      "ngx.say(tbl)"   output  alphabetagamma
      but 
      ngx.say(reqcache:get('a'))   output  nil
      
      why ?

**Comment by agentzh** [comment]
@cellcb You need to serialize Lua tables yourself, like using JSON or something.
