### ISSUE TITLE
Markdown::Pod

### ISSUE THREAD

**Issue by Zenexer** [openresty/openresty#175]
Is markdown2pod really necessary?  It looks like it converts from Markdown to POD, then from POD to plaintext.  That's hardly ideal.  The whole point of Markdown is that it's supposed to be human-readable as plaintext.  Markdown::Pod is a pretty hefty dependency for a seemingly trivial task.  It usually takes > 5 minutes to build that and all its dependencies.

**Comment by agentzh** [comment]
@Zenexer We'll eventually use our own markdown -> pod converter here:

https://github.com/openresty/resty-cli/blob/master/bin/md2pod.pl

**Comment by agentzh** [comment]
@Zenexer Fixed in git master by switching to resty-cli's md2pod.pl tool.
