### ISSUE TITLE
Dynamic Log on the fly for specific http hits

### ISSUE THREAD

**Issue by khannavidur** [openresty/openresty#179]
Is it possible to dynamically change the log format on the fly?

My use case being that i don't log the request body in my one custom log format (say `main`) but I do it in my other custom log format (say `main_in`)

So, I am I using `main` in my service's conf file but suppose for some time I wish to capture the logs in `main_in` format in a different file as well without disturbing the earlier logs for some APIs of my service not all of them. 

So essentially for that moment the logs are written in 2 files with different log formats but only for specific api hits and not all.

Can this be done?

**Comment by agentzh** [comment]
@khannavidur Maybe you'll find this library useful:

https://github.com/cloudflare/lua-resty-logger-socket
