### ISSUE TITLE
body_filter_by_lua would hang sometimes

### ISSUE THREAD

**Issue by chenyin** [openresty/openresty#18]
environ:
ubuntu 12.04
ngx_openresty-1.2.4.13

body_filter_by_lua 'ngx.arg[1] = string.upper(ngx.arg[1])';  in the HttpLuaModule docs works.
string.gsub works fine sometimes, when it does not work, the curl would get the correct content and then hang for a long time

I think the below configure would reproduce the bug.

<pre>
        location / {
            root   html;
            body_filter_by_lua      'ngx.arg[1] = string.gsub(ngx.arg[1], "nginx", "x")';
        }
</pre>

**Comment by lgcmmail** [comment]
thanks！

**Comment by aaronkingdom** [comment]
thanks very much， 我也遇到一个这样的问题，百度，谷歌无果， 最后还是找到这里解决了，哈哈哈。 这几天饭都吃的香了。  膜拜大神中！！！！！！！！！！！！！！！！！！！！
