### ISSUE TITLE
cannot stat `/openresty/openresty-1.9.15.2rc0/build/resty.index': No such file or directory

### ISSUE THREAD

**Issue by yitony** [openresty/openresty#181]
run make  success,but when to run  make install, I got an error

**Comment by agentzh** [comment]
@yitony Please do not use Chinese here. This place is considered English only.

Regarding your problem, it seems that you are using a weird path in your `--prefix=PATH` option of `./configure`. Please provide the *exact* copy of the commands you used for building, as well as the detailed information about your operating system. Thanks!

**Comment by yitony** [comment]
os : centos 6.5   gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
GNU Make 4.1
I checkout openresty to my home dir /home/tony ,  the last commit is 7c274e056efcdcfbe6954e0442e280ce4ff13c8b
then got /home/tony/openresty
then run make  ,after download many tar file
I go to /home/tony/openresty/openresty-1.9.15.2rc0,
run ./configure --prefix=/opt/openresty
make 
make run 
the make run has some error as blow

cp /home/tony/openresty/openresty-1.9.15.2rc0/build/resty.index /opt/openresty/
cp: cannot stat `/home/tony/openresty/openresty-1.9.15.2rc0/build/resty.index': No such file or directory
Makefile:11: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by agentzh** [comment]
@yitony I cannot reproduce it on my side on Linux.

```
cd ~/
wget https://openresty.org/download/openresty-1.9.15.2rc0.tar.gz
tar -xvzf openresty-1.9.15.2rc0.tar.gz
cd openresty-1.9.15.2rc0/
./configure --prefix=/opt/openresty -j8
gmake -j9
sudo gmake install
```

**Comment by agentzh** [comment]
@yitony Also, please ensure your tarball file is not corrupted or incomplete. Check the MD5 checksum of the tarball like this:

```
$ md5sum openresty-1.9.15.2rc0.tar.gz
53bb6c6fbc856869adce9c0b018fb830  openresty-1.9.15.2rc0.tar.gz
```

Ensure the output is exactly the same as mine given above.

**Comment by agentzh** [comment]
Consider it resolved.

**Comment by fffonion** [comment]
Sorry to comment in a closed issue but in case someone has the same error, this is may caused by the lack of `hg` binary. For ubuntu example, installing `mercurial` solves the problem.
That's because `util/mirror-tarballs` script will [exit](https://github.com/openresty/openresty/blob/master/util/mirror-tarballs#L828) if it can't hg clone nginx.org repository, which is before generating index.

**Comment by agentzh** [comment]
@fffonion Maybe you just want to use the release tarballs or prebuilt packages? See

https://openresty.org/en/download.html

and also

https://openresty.org/en/linux-packages.html

**Comment by agentzh** [comment]
@fffonion This repository is only meant to be used by the OpenResty development team themselves when packaging the OpenResty source releases.

**Comment by fffonion** [comment]
@agentzh Thanks for the info : )
In fact I just came into another build sse4.2 related issue (253) today and the patch is not released in tarballs yet. So I tested the rc version in a container (which has no hg 😄 ).
Anyways I'll definitely use release versions for general purposes.
