### ISSUE TITLE
nginx-1.9.15 + spdy.patch  cause coredump

### ISSUE THREAD

**Issue by cjhust** [openresty/openresty#182]
nginx-1.9.15
patch:https://github.com/felixbuenemann/sslconfig/blob/7c23d2791857f0b07e3008ba745bcf48d8d6b170/patches/nginx_1_9_15_http2_spdy.patch

sometimes causes coredump.
backtrace as the following:
                                                '.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004800e3 in ngx_write_chain_to_file (file=0x7fb271e94020, cl=0x0, offset=0, pool=0x7fb2744bfcd0) at src/os/unix/ngx_files.c:302
302     src/os/unix/ngx_files.c: No such file or directory.
        in src/os/unix/ngx_files.c
(gdb) bt
#0  0x00000000004800e3 in ngx_write_chain_to_file (file=0x7fb271e94020, cl=0x0, offset=0, pool=0x7fb2744bfcd0) at src/os/unix/ngx_files.c:302
#1  0x000000000045a01c in ngx_write_chain_to_temp_file (tf=0x7fb271e94020, chain=0x0) at src/core/ngx_file.c:136
#2  0x00000000004fd1d4 in ngx_http_spdy_state_read_data (sc=0x7fb274421590, pos=0x7fb2a0f36298 "ps://cell.wacai.com/bill/7252210/index.htm?uid=86308532&aid=7252210&kuaidaiBackUrl=https%3A%2F%2Fmicroservice.wacai.com%2Floan%2Frapid%2F7252210%2Fmaterial%2F2.0.0%2Findex&backUrl=https%3A%2F%2Fmicros"..., end=0x7fb2a0f36298 "ps://cell.wacai.com/bill/7252210/index.htm?uid=86308532&aid=7252210&kuaidaiBackUrl=https%3A%2F%2Fmicroservice.wacai.com%2Floan%2Frapid%2F7252210%2Fmaterial%2F2.0.0%2Findex&backUrl=https%3A%2F%2Fmicros"...) at src/http/ngx_http_spdy.c:1664
#3  0x00000000004fce7e in ngx_http_spdy_state_data (sc=0x7fb274421590, pos=0x7fb2a0f35298 "\r\n--UpYunSDKFormBoundary2016v39CC981D325836BAD\r\nContent-Disposition: form-data; name=\"policy\"\r\n\r\newogICJidWNrZXQiIDogImxpbmtlZC1ydW5uZXIiLAogICJzYXZlLWtleSIgOiAiXC9saW5rZWQtcnVubmVyXC91XzBfaGVhZGVyXzI"..., end=0x7fb2a0f36298 "ps://cell.wacai.com/bill/7252210/index.htm?uid=86308532&aid=7252210&kuaidaiBackUrl=https%3A%2F%2Fmicroservice.wacai.com%2Floan%2Frapid%2F7252210%2Fmaterial%2F2.0.0%2Findex&backUrl=https%3A%2F%2Fmicros"...) at src/http/ngx_http_spdy.c:1569
#4  0x00000000004fb515 in ngx_http_spdy_state_head (sc=0x7fb274421590, pos=0x7fb2a0f35298 "\r\n--UpYunSDKFormBoundary2016v39CC981D325836BAD\r\nContent-Disposition: form-data; name=\"policy\"\r\n\r\newogICJidWNrZXQiIDogImxpbmtlZC1ydW5uZXIiLAogICJzYXZlLWtleSIgOiAiXC9saW5rZWQtcnVubmVyXC91XzBfaGVhZGVyXzI"..., end=0x7fb2a0f36298 "ps://cell.wacai.com/bill/7252210/index.htm?uid=86308532&aid=7252210&kuaidaiBackUrl=https%3A%2F%2Fmicroservice.wacai.com%2Floan%2Frapid%2F7252210%2Fmaterial%2F2.0.0%2Findex&backUrl=https%3A%2F%2Fmicros"...) at src/http/ngx_http_spdy.c:950
#5  0x00000000004fa700 in ngx_http_spdy_read_handler (rev=0x7fb279cd38f0) at src/http/ngx_http_spdy.c:573
#6  0x000000000048875e in ngx_epoll_process_events (cycle=0x7fb2a25602a0, timer=60, flags=1) at src/event/modules/ngx_epoll_module.c:822

**Comment by agentzh** [comment]
@cjhust SPDY is dead: https://zoompf.com/blog/2015/02/spdy-dead-long-live-http2 And we won't support such 3rd-party nginx core patches at all. It's their fault anyway, not us.

You should switch to HTTP/2 instead which is the part of the nginx 1.9.15 core you are using.

**Comment by cjhust** [comment]
thank you for you reply, we will also remove spdy.

**Comment by alubbe** [comment]
It's actually a cloudflare patch https://github.com/cloudflare/sslconfig/tree/master/patches
Don't you use this on your own production servers?

**Comment by agentzh** [comment]
@alubbe I am not sure about that github repo. AFAIK, CloudFlare maintains nginx cite branches instead of nginx core patches internally for many years and the details are complicated and classified. As OpenResty maintainers, we won't support such random patches exposed by some CloudFlare employees.

**Comment by alubbe** [comment]
I completely respect that and agree with separating your openresty interests from your cloudflare job. I just wanted to point out that those patches are not as random as they might seem. cloudflare released them because a lot of windows and mobile users lag behind and support only spdy, with no clear upgrade path in sight - at least until their management upgrades to newer version of windows or they buy a new phone. Therefore, a good number of openresty users who need to support these clients (think b2b or emerging markets) might have a strong use case for needing this patch for another year or so. Personally, I run it in production and it works, and I am curious as to how @cjhust encountered those crashes.
https://blog.cloudflare.com/open-sourcing-our-nginx-http-2-spdy-code/
https://blog.cloudflare.com/introducing-http2
