### ISSUE TITLE
Dynamic server blocks for TCP Proxy without nginx reload

### ISSUE THREAD

**Issue by rshriram** [openresty/openresty#183]
I have a use case where I need to dynamically add new server blocks (not upstream, but server blocks). For example, as new service clusters come up, I would like to create a server block and a corresponding upstream block. I can use `balance_by_lua` to manage TCP upstreams (right?). But I cannot find a way to dynamically create a server block itself. Any idea how to go about this?

```
stream {
 server {
        listen     8888;
        server_name service1;
        proxy_pass stream_backend;
    }
server {
        listen     9999;
        server_name service2;
        proxy_pass stream_backend;
    }

 upstream stream_backend {
        server 127.0.0.1:1;
        balancer_by_lua_block {
            ##Identify LB pool based on server_name field and pick one instance
        }
   }
}
```

My problem is that I do not know the set of services apriori. The service clusters appear dynamically. So, effectively I need to add new server blocks to nginx. Is there a way to do this without config reload?

**Comment by rshriram** [comment]
I apologize if this issue should be posted in a different Git repo. Please let me know.

**Comment by agentzh** [comment]
@rshriram I think it's more relevant to the stream-lua-nginx-module github repository.

Regarding your question, yes, you can manage your own balancer's state via lua-resty-lrucache or lua_shared_dict, depending on your requirements. With the help of balancer_by_lua* (which is still a PR for stream-lua-nginx-module BTW), you can handle unlimited number of upstream servers on the fly, without nginx reloads, of course. I know some CDN vendors are already taking this approach in production, though for the HTTP subsystem.

**Comment by rshriram** [comment]
I can manage upstreamserver downstream server dynamically. The question is how to dynamically add listen directives ie downstreams, to make nginx listen on additional ports. Each service has several upstreams that come and go. They can be managed dynamically using balance by lua. But services also come and go. For each service, a new listen directive is needed. 

Any suggestions for this? Or do I have to statically declare all listen ports during nginx start and just manage my upstreams dynamically?

**Comment by agentzh** [comment]
@rshriram Oh yeah, just configure all the possible listening ports in that single generic `server {}` configuration block in your `nginx.conf`. Hopefully there are just not too many :)
