### ISSUE TITLE
2016/07/15 11:19:51 [error] 4188#0: *267 lua entry thread aborted: runtime error: /data/test.lua:9: no memory

### ISSUE THREAD

**Issue by 0312birdzhang** [openresty/openresty#184]
进行压力测试的时候内存耗尽了
Openresty version 1.9.15.1
test.lua
```
function readAll(file)
    local f = io.open(file, "rb")
    local content = f:read("*all")
    f:close()
    return content
end
local data = readAll("/tmp/jdk-7u79-linux-x64.tar.gz")
ngx.header["Content-disposition"] = "filename=jdk-7u79-linux-x64.tar.gz"
ngx.say(data)
```
nginx.conf

```
server
{
        listen       9092;
        server_name  192.168.1.203;
        index index.html index.htm index.php;
        include deny_files.conf;

        location /test
        {
                content_by_lua_file "/data/script/test.lua";
        }
}
```
I use http_load to test,on the other host
```
cat test.txt
http://192.168.1.203:9092/test
http://192.168.1.203:9092/test
http://192.168.1.203:9092/test
http://192.168.1.203:9092/test
http://192.168.1.203:9092/test
http_load -r 5 -s 60 test.txt
```

192.168.1.203 has 16G mem

**Comment by agentzh** [comment]
@0312birdzhang It's a bad idea to buffer large file contents on the Lua land. Use streaming processing wherever possible. In your case, you can rely on nginx's static content module to serve your content directly without going through Lua (you can still use access_by_lua* for example to add response headers, and etc).

There is a 2GB memory limit in each worker process for GC-managed memory in LuaJIT on x86_64.

**Comment by 0312birdzhang** [comment]
这是我测试的，主要场景是跟fastdfs结合下载文件，如下
https://groups.google.com/forum/#!searchin/openresty/fastdfs/openresty/YMgV-tnZV90/8Tfb9D6dCwAJ

看来需要换一种实现方式了

**Comment by agentzh** [comment]
@0312birdzhang Please, no Chinese here. This place is considered English only. Thanks for your cooperation.
