### ISSUE TITLE
Build prerequisits

### ISSUE THREAD

**Issue by shmul** [openresty/openresty#185]
Hi,

It is worth detailing the prerequisites for the build process. I encountered (on my Mac) the need for `wget`, `dos2unix` (which is indeed mentioned in the readme file) and `mercurial` (i.e. `hg`). 

Cheers,
Shmul

**Comment by agentzh** [comment]
Maybe you should use the release tarballs on openresty.org directly? This GitHub repo is for OpenResty core developers only.
