### ISSUE TITLE
A problem of using "serivce openresty reload"

### ISSUE THREAD

**Issue by Jet-Yuen** [openresty/openresty#186]
Hi, I'm using yum to install the newest OpenResty,but i have got a problem of using "service openresty reload", everytime I use this command, there comes one more process, and when I using "service openresty stop", nginx can not stop completely.  Does anyone know the reason ? please help me out. here is the details:

> [root@devhost10 nginx]# cat /etc/issue 
CentOS release 6.5 (Final)
[root@devhost10 nginx]# cat /proc/version
Linux version 2.6.32-573.8.1.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Tue Nov 10 18:01:38 UTC 2015
[root@devhost10 nginx]# openresty -v
nginx version: openresty/1.9.15.1
[root@devhost10 nginx]# service openresty start
Starting nginx:                                            [  OK  ]
[root@devhost10 nginx]# ps -ef | grep nginx
root     29800     1  0 15:31 pts/0    00:00:00 /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
root     29802     1  0 15:31 ?        00:00:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
nobody   29803 29802  0 15:31 ?        00:00:00 nginx: worker process                                                              
root     29806 29765  0 15:31 pts/0    00:00:00 grep nginx
[root@devhost10 nginx]# service openresty reload
Reloading nginx:                                           [  OK  ]
[root@devhost10 nginx]# ps -ef | grep nginx
root     29802     1  0 15:31 ?        00:00:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
root     29823 29802  0 15:31 ?        00:00:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
nobody   29825 29802  0 15:31 ?        00:00:00 nginx: worker process                                                              
root     29827 29765  0 15:31 pts/0    00:00:00 grep nginx
[root@devhost10 nginx]# service openresty reload
Reloading nginx:                                           [  OK  ]
[root@devhost10 nginx]# ps -ef | grep nginx
root     29802     1  0 15:31 ?        00:00:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
root     29823 29802  0 15:31 ?        00:00:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
root     29844 29802  0 15:31 ?        00:00:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
nobody   29846 29802  0 15:31 ?        00:00:00 nginx: worker process                                                              
root     29848 29765  0 15:32 pts/0    00:00:00 grep nginx
[root@devhost10 nginx]# service openresty stop
Stopping nginx:                                            [  OK  ]
[root@devhost10 nginx]# ps -ef | grep nginx
root     29823     1  0 15:31 ?        00:00:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
root     29844     1  0 15:31 ?        00:00:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
root     29865 29765  0 15:32 pts/0    00:00:00 grep nginx
[root@devhost10 nginx]# service openresty stop
Stopping nginx:                                            [  OK  ]
[root@devhost10 nginx]# ps -ef | grep nginx
root     29823     1  0 15:31 ?        00:00:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
root     29844     1  0 15:31 ?        00:00:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
root     29881 29765  0 15:32 pts/0    00:00:00 grep nginx
[root@devhost10 nginx]# service openresty stop
Stopping nginx:                                            [  OK  ]
[root@devhost10 nginx]# service openresty stop
Stopping nginx:                                            [  OK  ]
[root@devhost10 nginx]# ps -ef | grep nginx
root     29823     1  0 15:31 ?        00:00:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
root     29844     1  0 15:31 ?        00:00:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
root     29919 29765  0 15:32 pts/0    00:00:00 grep nginx

**Comment by agentzh** [comment]
@Jet-Yuen Which yum repository of OpenResty are you using?

**Comment by agentzh** [comment]
@Jet-Yuen And also, what's in your `/usr/local/openresty/nginx/conf/nginx.conf` file?

**Comment by agentzh** [comment]
@Jet-Yuen I've tested the official OpenResty yum repo on CentOS 7 x64 and the reload thing works correctly on my side (using the default nginx.conf installed).

```
[agentzh@centos7 ~]$ ps aux|grep nginx
root       2870  0.0  0.1  32664  1132 ?        Ss   06:10   0:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
nobody     2872  0.0  0.1  32668  1884 ?        S    06:10   0:00 nginx: worker process
agentzh    2874  0.0  0.0 112648   972 pts/0    R+   06:10   0:00 grep --color=auto nginx

[agentzh@centos7 ~]$ sudo service openresty reload
Reloading openresty configuration (via systemctl):         [  OK  ]

[agentzh@centos7 ~]$ ps aux|grep nginx
root       2870  0.0  0.2  32664  2616 ?        Ss   06:10   0:00 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
nobody     2904  0.0  0.2  32668  2020 ?        S    06:10   0:00 nginx: worker process
agentzh    2907  0.0  0.0 112648   976 pts/0    R+   06:10   0:00 grep --color=auto nginx

[agentzh@centos7 ~]$ sudo service openresty stop
Stopping openresty (via systemctl):                        [  OK  ]

[agentzh@centos7 ~]$ ps aux|grep nginx
agentzh    2939  0.0  0.0 112648   976 pts/0    S+   06:10   0:00 grep --color=auto nginx
```

**Comment by agentzh** [comment]
@Jet-Yuen I guess you have turned off the `daemon` directive in your `nginx.conf` yourself, which could lead to the issue you are having. Just always turn on the `daemon`.

**Comment by Jet-Yuen** [comment]
@agentzh Thanks, I really appreciate it. 
It turns out, it's the lua code in my nginx.conf cause this problem. In my lua code , I fork one process in init_by_lua_block{}.  and this function invoked every time I use "reload".  ths again.

**Comment by agentzh** [comment]
Oh that's very bad. Do not fork master!
