### ISSUE TITLE
并发上传，出现生成的文件名重复,导致文件被覆盖

### ISSUE THREAD

**Issue by nick-william** [openresty/openresty#188]
为方便排查问题，整个lua脚本都贴上来

local upload = require "resty.upload"
local cjson = require "cjson"

local chunk_size = 4096
local form = upload:new(chunk_size)
local conf = {max_size=1000000, allow_exts={'jpg', 'png', 'gif'}}
local file
local file_name

--获取文件扩展名
function get_ext(res)
    local ext = 'jpg'
    if res == 'image/png' then
        ext = 'png'
    elseif res == 'image/jpg' or res == 'image/jpeg' then
        ext = 'jpg'
    elseif res == 'image/gif' then
        ext = 'gif'
    end
    return ext
end

--判断某个值是否在数组中
function in_array(v, tab)
    local i = false
    for _, val in ipairs(tab) do
        if val == v then
            i = true
            break
        end
    end
    return i
end
function gen_new_file()
    math.randomseed(tostring(os.time()):reverse():sub(1, 6))
    local newName = string.format("%s%03d%03d",os.date("%Y%m%d%H%M%S", os.time()),math.random(999),math.random(999));
    return newName
end
while true do
    local typ, res, err = form:read()
    if typ == "header" then
        if res[1] ~= "Content-Disposition" then
            math.randomseed(os.time())
            local file_id = ngx.md5('upload'..math.random()) .. gen_new_file()
            local extension = get_ext(res[2])

            if not extension then
                ngx.say(cjson.encode({code=501, msg='未获取文件后缀', data=res}))
                return
            end

            if not in_array(extension, conf.allow_exts) then
                ngx.say(cjson.encode({code=501, msg='不支持这种文件格式', data=res}))
                return
            end

            local dir = '/data/www/public/uploads/'..os.date('%Y')..'-'..os.date('%m')..'-'..os.date('%d')..'/'
            local status = os.execute('mkdir -p '..dir)
            if status ~= 0 then
                ngx.say(cjson.encode({code=501, msg='创建目录失败'}))
                return
            end
            local realName = dir..file_id.."."..extension
            if realName then
                file = io.open(realName, "w+")
                if not file then
                    ngx.say(cjson.encode({code=500, msg='failed to open file',imgurl=''}))
                    return
                end
                file_name = realName
            end
        end
    elseif typ == "body" then
        if type(tonumber(res)) == 'number' and tonumber(res) > conf.max_size then
            ngx.say(cjson.encode({code=501, msg='文件超过规定大小', data=res}))
            return
        end
        if file then
            file:write(res)
        end
    elseif typ == "part_end" then
        if file then
            file:close()
            file = nil
        end
    elseif typ == "eof" then
        file_name = string.gsub(file_name, '/data/www/app.weipaitang.com/public/uploads/', '')
        ngx.say(cjson.encode({code=200, msg='上传成功！',imgurl= file_name}))
        break
    else

    end
end

**Comment by agentzh** [comment]
Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

Please also read the following doc for how to report a problem in the *right* way:

http://openresty.org/en/faq.html#how-should-i-report-a-problem
