### ISSUE TITLE
Issues with POST and upstream failover on error with OpenResty 1.9.15.1

### ISSUE THREAD

**Issue by roland-pope** [openresty/openresty#190]
I recently updated to OpenResty 1.9.15.1 from OpenResty 1.9.7.5 and observed the following issue:

When I POST to an upstream that has several servers declared and the first server in the upstream list returns a '500' error, no fail-over occurs and an Nginx 'Bad Gateway' page is displayed on the client.
This does NOT happen if I do a PUT or a GET or even a DELETE, as these operations fail over across all the upstream servers until the JSON formatted error page that was generated by the server is displayed.
If I POST to an upstream that has only a single server configured, I get the JSON error returned that the upstream server generated rather than the Nginx 'Bad Gateway' that I get on a POST to a multi-server upstream, which is the correct behaviour.

This only happens on 1.9.15.1 and reverting to 1.9.7.5 restores the correct behaviour, which is to fail the POST across all the upstreams and return the server error generated by the final upstream in the list.

let me know if you require any further information with regards this issue.

**Comment by agentzh** [comment]
@roland-pope This is a change introduced since the official nginx core 1.9.13. To quote that release's relevant change log entry:

> Change: non-idempotent requests (POST, LOCK, PATCH) are no longer
>       passed to the next server by default if a request has been sent to a
>       backend; the "non_idempotent" parameter of the "proxy_next_upstream"
>       directive explicitly allows retrying such requests.

So you can see that you can also configure it to restore to the original behavior.
