### ISSUE TITLE
require "ngx.ssl" error

### ISSUE THREAD

**Issue by goudiao** [openresty/openresty#191]
nginx: [emerg] at least OpenSSL 1.0.2e required but found LibreSSL 2.4.2

not support LibreSSL ?

**Comment by agentzh** [comment]
@goudiao You must be using the features that require the new features in recent versions of OpenSSL while those are missing in LibreSSL. They just won't work at all with LibreSSL due to the lack of the equivalent features there (feel free to prove me wrong).

**Comment by agentzh** [comment]
Consider it resolved.
