### ISSUE TITLE
openresty/lua-cjson issue (can not add elsewhere since it's a fork)

### ISSUE THREAD

**Issue by ruslantalpa** [openresty/openresty#193]
the following code

```
local cjson = require 'cjson'
print(cjson.encode(cjson.decode('[]')))
```

prints `{}` but the result should be `[]`

lua-cjson
   2.1devel-1 (installed) - /usr/local/lib/luarocks/rocks-5.2
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio

```
~/Downloads/openresty-1.11.2.1/bundle/lua-cjson-2.1.0.4$ luarocks make
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c lua_cjson.c -o lua_cjson.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c strbuf.c -o strbuf.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c fpconv.c -o fpconv.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load -o cjson.so -L/usr/local/lib lua_cjson.o strbuf.o fpconv.o
Updating manifest for /usr/local/lib/luarocks/rocks-5.2
lua-cjson 2.1devel-1 is now built and installed in /usr/local (license: MIT)

~/Downloads/openresty-1.11.2.1/bundle/lua-cjson-2.1.0.4$ lua test.lua        
{}

```

**Comment by ruslantalpa** [comment]
this patch seems to works
```diff
~$ git diff
diff --git a/lua_cjson.c b/lua_cjson.c
index 5f4faf2..3f26595 100644
--- a/lua_cjson.c
+++ b/lua_cjson.c
@@ -1232,6 +1232,8 @@ static void json_parse_array_context(lua_State *l, json_parse_t *json)
 
     /* Handle empty arrays */
     if (token.type == T_ARR_END) {
+        lua_pop(l, 1);
+        lua_pushlightuserdata(l, &json_empty_array);
         json_decode_ascend(json);
         return;
     }

```

**Comment by bungle** [comment]
I think this is the correct place:
https://github.com/openresty/lua-cjson

**Comment by bungle** [comment]
But I'm pretty sure this is expected behavior with Lua cJSON. When you decode, you get Lua `table`. In Lua we don't have separate arrays and objects. And I'm pretty sure Lua cJSON didn't add metatable or some field to this `table` so that it can look it up and decide if it should be encoded as array or object.

**Comment by bungle** [comment]
This commit, though, seems to have something to do with this:
https://github.com/openresty/lua-cjson/commit/7a9c25ee69f38974e99322971eace37ba1753074

(But with non-fork Lua cJSON I think my statement is still correct).

**Comment by bungle** [comment]
Also check this out:
https://github.com/openresty/lua-cjson#encode_empty_table_as_object

**Comment by ruslantalpa** [comment]
@bungle 
i can not add the issue there since that is a fork
i looked a bit over the code and i get a sense of how things work.
However i do not agree with your statement "it's expected behaviour", decoding then encoding a json string should output the same result.
it's exactly the same case as `{"a":null}`, you do not get a `{"a" = nil}` but a `{"a" = cjson.null}`

There is one small downside to my patch i think, once you decode an array and it's empty, if you later want to insert in the new array/table you need to check if it's a `cjson.empty_array` and turn it into a normal table.

Now that i come to think of it, settings like `encode_empty_table_as_array` should not exist at all, it introduces ambiguity and a potential for bugs, all normal tables should be encoded as objects and if you want empty arrays as output, the property should be `cjson.empty_array`

**Comment by ruslantalpa** [comment]
about the downside, maybe i could use `setmetatable({}, cjson.empty_array_mt)` in the patch to tag the table as being an array then things would work as expected

**Comment by ruslantalpa** [comment]
what would be the C equivalent of `setmetatable(table, cjson.empty_array_mt)`?
in place of these lines

```
lua_pop(l, 1);
lua_pushlightuserdata(l, &json_empty_array);
```

**Comment by bungle** [comment]
@ruslantalpa,

I agree with you, but there is no way to do this properly without some kind of side effects. I don't agree with some of the design choices made with original Lua cJSON, for example I would like it to behave similarly to this (it is my version that binds to cJSON C library that is a totally different than Lua cJSON):

https://github.com/bungle/lua-resty-libcjson

You may try that exactly same code I present these with Lua cJSON or this OpenResty forked one. I bet that you will get different results. Is my way of doing it more correct that the other ways, I'm not sure.

How I do this is that I do add metatable on decode on Lua tables, either `json.object` or `json.array`. Now I can later on use this information to encode as an object or as an array. But this has a lot of side effects as well.

There is clear impedance mitch match, and there is no real solution, only work-arounds.

Now, think this a minute:

```lua
local tbl = cjson.decode('[]') 
-- let's pretend that this tbl now has a magic field or metatable attached
-- that tells it that it is an array
tbl.key = "dog"
-- what the fuck is the tbl now? is it still an array, so we just throw away
-- the key on encode, or has it magically switched it's metatable to object?
-- But then again, there is no equivalent in JSON to what this table structure
-- is in Lua

**Comment by ruslantalpa** [comment]
@bungle i get your point, however i would say the error here is the user using tbl which is marked as array, as if it is an object.
I would say the correct way, if the table has a metatable of array, it should be encoded as array and ignore the keys.

Come to think of it, whenever a table is decoded, it should be marked with "array" metatable, regardless if it's empty or not (there is no ambiguity here since this is know in json). This will ensure that when you decode then encode back, you get the same thing. It's the lib's user responsibility not to use tables that are arrays as if they are objects and if he really want's to do that, he can just remove the metatable after the decode and treat it as a object.

**Comment by bungle** [comment]
Of course, but does this warrant a breaking change, and warrant to make it incompatible with Lua cJSON. Maybe we need a config switch also by which we can control the behavior?

**Comment by bungle** [comment]
Why do you think `object` should be default here:

```lua
json.encode{}
```

If you ask me, this looks more like an array. In object you have at least one key.

**Comment by ruslantalpa** [comment]
I would not say it's a breaking change because i think (the way it is right now) it's a bug, and it would only break code that relies on a buggy behaviour to properly function.

For example i do not understand why (conceptually) you (developer) would decode a json like this `[1,2]` then use it as if it was a `{"1":1, "2":2}` ... this is just bad code :)

about encoding empty tables, i am not sure about that, i was jsut thinking about removing ambiguity, i.e. every lua table is a object unless tagged by a metatable but i guess that can be configured.

**Comment by bungle** [comment]
> For example i do not understand why (conceptually) you (developer) would decode a json like this [1,2] then use it as if it was a {"1":1, "2":2} ... this is just bad code :)

But this is not what is happening, is it?

**Comment by ruslantalpa** [comment]
I am not sure what you mean, by developer i did not mean you specifically, i meant the person using the lib.
What i wanted to say is that if you decode a json array, you should use it as an array and not be surprised that things break when you use it as a object/map.

**Comment by ruslantalpa** [comment]
hence i view this as a bugfix and not a breaking change in the interface

**Comment by bungle** [comment]
Well, If you decode `"[1,2]"` you will get `{ 1, 2 }` on Lua side. The only thing that is confusing is what to do with empty ones by default. You say:

On decoding:

1. if it is an array attach array metatable to it
2. if it is an object attach object metatable to it
3. otherwise just encode the value and map it to a proper Lua type

On encoding:

1. if it has metatable, use what metatable says
2. if it has no metatable use it as object

Now, someone would say, `Why my decoded Lua structures contain all this metadata crap. I want clean Lua structures?`, So we could:

On decoding:

1. If it is an array return { a, b, c }
2. If it is an object return { a = 1, b = 2, c = 3}
3. otherwise just encode the value and map it to a proper Lua type

Now on encoding:

1. Check if { a, b, c } has keys? If not encode it as an array [ a, b, c ], otherwise encode it as object. If it has both, encode it as an object, e.g. { a, b, c, d = 2 } => { "1": a, "2": b, "3": c, d = 2 }

Clean and simple. No need to have any metatable crap and it always works predictable. Now if you really want to force something to object instead of array on encoding, you have to tell it:

```lua
json.encode(setmetatable({}, json.object)) -- now we get {} instead of []
```

Array as default is clearly the best way to do this. Then you could have option for decoding to whether or not to apply metatables or not, so that you can be sure this works:

```lua
json.encode(json.decode"{}")
```

This works always without even metatables then:


```lua
json.encode(json.decode"[]")
```

**Comment by bungle** [comment]
I can say that this looks strange at first:

```lua
json.encode(json.decode"[]") -- output "{}"
```

Or with my approach this looks strange at first:

```lua
json.encode(json.decode"{}") -- output "[]"
```

But without metatables or extra fields, you cannot get this to work, what happens here is just:

```lua
json.encode{}
```

What should come out of it is a decision. Should this be configurable is a decision (something can go wrong because of different configs). What should be a default is a decision. To strictly follow what attached metatable or field says or first try to dynamically check if it is array or object, is again a decision. I say there is clearly no "right" answer.

**Comment by ruslantalpa** [comment]
If the current approach would work in all cases i would agree with you about the metadata, however it does not work reliably, and reliability is much more important then a slightly more complicated data structure. Consider these scenarios

```
-- empty array
encode(decode('[]')) -- should output []

-- empty object
encode(decode('{}')) -- should output {}

-- object that becomes empty
local a = decode({"a":1})
a.a = nil
encode(a) -- should output {}

-- array that becomes empty
local b = decode('[1]')
table.remove(b, 1)
encode(b) -- should output []
```

Think of it in the context of me trying to have a config file in json and i want to be able to decode, manipulate the table structure then encode back.

saying `if you really want to ... you can force the metatable` means that you turn a simple task of decoding, changing one value, encoding into a very complicated process, i.e.
after decoding, i have to walk the entire structure and force the metatable on entities that might be a problem.

**Comment by bungle** [comment]
Read the above: https://github.com/openresty/openresty/issues/193#issuecomment-242707042

What would you decide? Is what you decided the approach everyone agrees? Hardly.

**Comment by ruslantalpa** [comment]
I just read the comment and i am not arguing for or against the metadata approach.
I am simply saying that above all else, correctness should the the deciding factor.
Now how to exactly go about doing that is another topic.
Sure it would be ideal to not need the metatables, but if this is the only way to have reliable results, i would go for that. 
What exactly would be the problem with metatables? Is it just a style thing or are there big performance implications?

**Comment by bungle** [comment]
> saying if you really want to ... you can force the metatable means that you turn a simple task of decoding

Not at all. As there is now other way to say that `{}` is array or object. But my lib has some defaults:

- json.encode(json.decode"[]")
- json.decode(json.decode"{}")

Both of these work always. Only thing is that when you modify and add a key to array, is that we will encode it as an object. But that is clearly a mistake in your code.

**Comment by ruslantalpa** [comment]
Well i am not sure how things work in your lib but it definitely does not work in this one,

are you saying that all these case work with your lib?

```
-- empty array
encode(decode('[]')) -- should output []

-- empty object
encode(decode('{}')) -- should output {}

-- object that becomes empty
local a = decode({"a":1})
a.a = nil
encode(a) -- should output {}

-- array that becomes empty
local b = decode('[1]')
table.remove(b, 1)
encode(b) -- should output []
```

if so, how exactly are you managing objects and arrays that become empty?

**Comment by bungle** [comment]
Yes, I'm saying all that works.

**Comment by ruslantalpa** [comment]
Ok then, let's make this one behave the same :) (though i'll probably just switch to your lib :) )
So how exactly are you managing arrays/objects that become empty. I don't see how you can decide on what the output of the encode should be without a metatable tag

**Comment by ruslantalpa** [comment]
I don't have anything agains manually setting the metatable when i create the data structure in lua, that i reasonable, but when the data structure is the output of decode, i should not have to deal with that.

**Comment by bungle** [comment]
With my lib:

This code:

```lua
local encode = require "resty.libcjson".encode
local decode = require "resty.libcjson".decode

-- empty array
print(encode(decode"[]")) -- should output []

-- empty object
print(encode(decode"{}")) -- should output {}

-- object that becomes empty
local a = decode '{"a":1}'
a.a = nil
print(encode(a)) -- should output {}

-- array that becomes empty
local b = decode "[1]"
table.remove(b, 1)
print(encode(b)) -- should output []
```

Outputs:

```json
[]
{
}
{
}
[]
```

**Comment by ruslantalpa** [comment]
That is exactly what i would like this lib to do, i don't care about the metadata or not, i only care about the correctness of the output

**Comment by bungle** [comment]
But if you do this:

```lua
-- array is going to have keys
local b = decode "[1]"
table.remove(b, 1)
b.a = 1
print(encode(b)) -- will output { "a": 1}
```

And that was a one thing that you didn't agree.

**Comment by ruslantalpa** [comment]
Actually i don't have anything agains how your lib behaves in this case, it's reasonable default and the problem here is the user code (your example), not the lib.
When i said if it decodes an array, it should output an array, that was me taking a shortcut to a solution.
the above behaviour is fine (it's the same in javascript i think).

**Comment by bungle** [comment]
One thing though, I you have huge structures (multiple megabytes in size), my lib does not perform particularly well on `encoding`. Decoding is just fine though.

**Comment by bungle** [comment]
I wish OpenResty has it's own FFI optimized JSON library. For decoding there is:
https://github.com/cloudflare/lua-resty-json

But it is not much updated since, and has no encoder. Also, I'm pretty sure that without encoder, you cannot really rely that with some other encoder you end up with same structure.

**Comment by agentzh** [comment]
FWIW, I've enabled the "issues" board of the openresty/lua-cjson repo.

**Comment by agentzh** [comment]
@bungle Yes, lua-resty-json will be the future. The encoder is also on its roadmap and it will eventually get included in the OpenResty bundle (soon).

**Comment by thibaultcha** [comment]
I have just opened openresty/lua-cjson#28 to address such behaviors in our lua-cjson fork, reviews appreciated!
