### ISSUE TITLE
openresty prefix should be /opt/openresty

### ISSUE THREAD

**Issue by dholth** [openresty/openresty#194]
It would be nice if the openresty prefix in the RPM spec was /opt/openresty instead of /usr/local/openresty. See http://www.pathname.com/fhs/pub/fhs-2.3.html

**Comment by agentzh** [comment]
@dholth nginx defaults to `/usr/local/nginx/`. And I don't see why we cannot use `/usr/local/openresty/` at least for the sake of consistency.

**Comment by dholth** [comment]
That's fine, it would clearly break all examples if it was moved. Traditionally packages install themselves into /usr/local with 'make install' but the RPM version does not. I have never seen nginx installed into /usr/local because I always install it from RPM.

**Comment by agentzh** [comment]
@dholth The decision has been made to make the RPM installation paths consistent with the source distribution.
