### ISSUE TITLE
Not using sbin-path configuration when creating symlink

### ISSUE THREAD

**Issue by davidgaleano** [openresty/openresty#196]
Should the symlink be created using whatever path was set with "--sbin-path" instead of assuming "sbin/nginx"?
https://github.com/openresty/openresty/blob/fd667d63695c640791791e86997778e9b081786d/util/configure#L347

**Comment by agentzh** [comment]
Yes. Pull requests welcome. Thanks!

**Comment by davidgaleano** [comment]
Is the pull requests ok? would you like me to change anything.
