### ISSUE TITLE
建议支持 	openssl-1.1.0 以上版本

### ISSUE THREAD

**Issue by goudiao** [openresty/openresty#198]
建议支持 	openssl-1.1.0 以上版本，一直想在 openresty 下使用 chacha20 加密套件。

**Comment by agentzh** [comment]
Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

Regarding your question, it is already being worked on. See openresty/lua-nginx-module#761 (and also openssl/openssl#1588 )
