### ISSUE TITLE
Incorrectly compiling on Raspberry Pi 3

### ISSUE THREAD

**Issue by ben-walters** [openresty/openresty#199]
When I compile using the instructions here:

https://openresty.org/en/installation.html

Nginx is compiled without lua support:

nginx: [emerg] unknown directive "content_by_lua_block" in /usr/local/openresty/nginx/conf/nginx.conf:40

**Comment by agentzh** [comment]
@ben-walters I think you are invoking the wrong nginx executable? Ensure that you have set your PATH environment correctly. And you can verify which nginx you are invoking via the following command:

```
which nginx
```

When using OpenResty, you're recommended to use the `openresty` command instead of `nginx`.

**Comment by ben-walters** [comment]
@agentzh Is there an openresty bin which exists independently of nginx?

`/usr/local/openresty/nginx/sbin/nginx`

is the bin i have been using to init, and that is complaining.

**Comment by ben-walters** [comment]
Seems to have been fixed in a later version. The version described in the post is legacy.
