### ISSUE TITLE
the proxy_cache doesn't work on openresty/1.11.2.1 

### ISSUE THREAD

**Issue by ieworks** [openresty/openresty#202]
Today I try to use openresty as a front cache for many times, but it does't work. Then I try these on nginx/1.10.2, it works well. The configure almost the same. 

Here is the result picture:

![selection_038](https://cloud.githubusercontent.com/assets/8401057/19687614/c49c6756-9a8b-11e6-940e-c3b451dfcc2b.png)

configure for openresty:
`proxy_cache_path /tmp/nginx/cache levels=1:2 keys_zone=one:512m;`
`server {
	listen       80;
	server_name  doit.cache.garywon.com;
	resolver 192.168.1.1;
	proxy_cache one;
	#charset koi8-r;

	access_log  /var/log/nginx/doit.cache.garywon.com.access.log  main;
	error_log  /var/log/nginx/doit.cache.garywon.com.error.log;

location / {
	proxy_set_header Host doit.garywon.com;
	proxy_set_header X-Forwarded-For $remote_addr;
	proxy_set_header X-Real-IP $remote_addr;

	#proxy_temp_path /dev/shm/nginx/tmp 1 2;

	proxy_buffers 256 4k;
	proxy_connect_timeout 30;
	proxy_cache_key $uri;

	proxy_cache_valid 200 302 10m;
	proxy_cache_valid 301 1h;
	proxy_cache_valid any 1m;
	add_header X-Cache $upstream_cache_status;
	proxy_pass http://127.0.0.1$request_uri;
}

}
`

configure for nginx 

`proxy_cache_path /tmp/nginx/cache levels=1:2 keys_zone=nginx:512m;
`
`server {
	listen       8022;
	server_name  nginx.cache.garywon.com;
	resolver 192.168.1.1;
	proxy_cache nginx;
	#charset koi8-r;

	access_log  /var/log/nginx/nginx.cache.garywon.com.access.log  main;
	error_log  /var/log/nginx/nginx.cache.garywon.com.error.log;

location / {
	proxy_set_header Host doit.garywon.com;
	proxy_set_header X-Forwarded-For $remote_addr;
	proxy_set_header X-Real-IP $remote_addr;

	#proxy_temp_path /dev/shm/nginx/tmp 1 2;

	proxy_buffers 256 4k;
	proxy_connect_timeout 30;
	proxy_cache_key $uri;

	proxy_cache_valid 200 302 10m;
	proxy_cache_valid 301 1h;
	proxy_cache_valid any 1m;
	add_header X-Cache $upstream_cache_status;
	proxy_pass http://127.0.0.1$request_uri;
}

}
`

**Comment by agentzh** [comment]
@ieworks What do you mean by "not work"? Please provide detailed analyses and explanation. Simply dumping your configurations and screen shots may not be sufficient.

BTW, OpenResty 1.11.2.1 just includes the NGINX 1.11.2 core and we never touch the proxy_cache part at all.

**Comment by agentzh** [comment]
@ieworks You should temporarily enable the nginx debugging logs to see why cache misses happen.

**Comment by ieworks** [comment]
@agentzh What I mean "not work" is that I can't find the cached file under the proxy_cache_path.

**Comment by ieworks** [comment]
@agentzh  I enable the debugging log, It saying 
`2016/10/26 21:23:36 [debug] 7334#0: *72 http header: "Host: doit.cache.garywon.com"
2016/10/26 21:23:36 [debug] 7334#0: *72 http header: "User-Agent: curl/7.47.1"
2016/10/26 21:23:36 [debug] 7334#0: *72 http header: "Accept: */*"
2016/10/26 21:23:36 [debug] 7334#0: *72 http header done
2016/10/26 21:23:36 [debug] 7334#0: *72 event timer del: 44: 1477488276444
2016/10/26 21:23:36 [debug] 7334#0: *72 rewrite phase: 0
2016/10/26 21:23:36 [debug] 7334#0: *72 rewrite phase: 1
2016/10/26 21:23:36 [debug] 7334#0: *72 test location: "/"
2016/10/26 21:23:36 [debug] 7334#0: *72 using configuration "/"
2016/10/26 21:23:36 [debug] 7334#0: *72 http cl:-1 max:1048576000
2016/10/26 21:23:36 [debug] 7334#0: *72 rewrite phase: 3
2016/10/26 21:23:36 [debug] 7334#0: *72 rewrite phase: 4
2016/10/26 21:23:36 [debug] 7334#0: *72 rewrite phase: 5
2016/10/26 21:23:36 [debug] 7334#0: *72 lua rewrite handler, uri:"/web/man/python-2.7.12-docs-html/_static/pygments.css" c:1
2016/10/26 21:23:36 [debug] 7334#0: *72 post rewrite phase: 6
2016/10/26 21:23:36 [debug] 7334#0: *72 generic phase: 7
2016/10/26 21:23:36 [debug] 7334#0: *72 generic phase: 8
2016/10/26 21:23:36 [debug] 7334#0: *72 access phase: 9
2016/10/26 21:23:36 [debug] 7334#0: *72 access phase: 10
2016/10/26 21:23:36 [debug] 7334#0: *72 post access phase: 11
2016/10/26 21:23:36 [debug] 7334#0: *72 try files phase: 12
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: "http://127.0.0.1"
2016/10/26 21:23:36 [debug] 7334#0: *72 http script var: "/web/man/python-2.7.12-docs-html/_static/pygments.css"
2016/10/26 21:23:36 [debug] 7334#0: *72 http init upstream, client timer: 0
2016/10/26 21:23:36 [debug] 7334#0: *72 epoll add event: fd:44 op:3 ev:80002005
2016/10/26 21:23:36 [debug] 7334#0: *72 http script var: "/web/man/python-2.7.12-docs-html/_static/pygments.css"
2016/10/26 21:23:36 [debug] 7334#0: *72 http cache key: "/web/man/python-2.7.12-docs-html/_static/pygments.css"
2016/10/26 21:23:36 [debug] 7334#0: *72 add cleanup: 00007F01EBE91830
2016/10/26 21:23:36 [debug] 7334#0: *72 http file cache exists: -5 e:0
2016/10/26 21:23:36 [debug] 7334#0: *72 cache file: "/tmp/nginx/cache/4/18/2102b294e9a4ebe50cba01f8e2e05184"
2016/10/26 21:23:36 [debug] 7334#0: *72 http upstream cache: -5
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: "Host: doit.garywon.com
"
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: "X-Forwarded-For: "
2016/10/26 21:23:36 [debug] 7334#0: *72 http script var: "127.0.0.1"
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: "
"
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: "X-Real-IP: "
2016/10/26 21:23:36 [debug] 7334#0: *72 http script var: "127.0.0.1"
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: "
"
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: "Connection: close
"
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: ""
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: ""
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: ""
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: ""
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: ""
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: ""
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: ""
2016/10/26 21:23:36 [debug] 7334#0: *72 http script copy: ""
2016/10/26 21:23:36 [debug] 7334#0: *72 http proxy header: "User-Agent: curl/7.47.1"
2016/10/26 21:23:36 [debug] 7334#0: *72 http proxy header: "Accept: */*"
2016/10/26 21:23:36 [debug] 7334#0: *72 http proxy header:
"GET /web/man/python-2.7.12-docs-html/_static/pygments.css HTTP/1.0
`
It says cached, but I can't find the file /tmp/nginx/cache/4/18/2102b294e9a4ebe50cba01f8e2e05184. Maybe the key issue is here. But I'm not farmiliar with source code of nginx.  ^`-`

**Comment by agentzh** [comment]
No, it does not say "cached" at all. It says it cannot find a hit in the cache during the cache fetch phase, which is expected. Your debugging log quote is incomplete. What's really interesting comes after the logs your quote above, i.e., the logs for the later "cache store" operation.

BTW, please paste the logs somewhere else (like on gist) and just share the link here. Better avoid flooding this place with too many logs.

**Comment by ieworks** [comment]
[nginx-debug.txt](https://github.com/openresty/openresty/files/554850/nginx-debug.txt)

Ok, I will take care  next time.  That is complete log for the testing, and I couldn't find the key word like "cache store"

**Comment by agentzh** [comment]
@ieworks I've noted the following line in your nginx-debug.txt:

```
2016/10/26 21:23:36 [debug] 7334#0: *72 http upstream process non buffered downstream
```

This means that your proxy uses non buffered mode while updating the cache requires *buffered* mode.

Have you configured `proxy_buffering off` in your `nginx.conf`? If yes, please remove it.

**Comment by ieworks** [comment]
@agentzh :+1:  the directive is  really in nginx.conf. Yeah, this is not a bug,Thank you for your help very much!
