### ISSUE TITLE
how work with ngx.var?

### ISSUE THREAD

**Issue by iamnotaprogrammer** [openresty/openresty#205]
i read documentation.
what is ngx.var?
```lua
type(ngx.var) <=> table 
```
but i cannot get all nginx varibles  use loop:
```lua
for key, value in ipairs(ngx.var) do
             ngx.say(key)
             ngx.say(value)
end
```
if i set my variables
            set $my_proxy_cache_key 'start value';
            set $my_proxy_pass '';
            set $my_proxy_ignore_client_abort '';
            set $my_proxy_read_timeout '' ;
            set $my_proxy_send_timeout '';
            set $my_proxy_hide_header '';
            set $my_proxy_cache_min_uses '';
            set $my_proxy_cache_lock_timeout '';
            set $my_proxy_cache_lock '';
            set $my_proxy_cache '';

how can i set the value from lua ?

i want to do this
 rewrite_by_lua_block{
```lua
                local data = ngx.shared.data
                local my_empty_data = {}

                local my_data = {'my_proxy_cache_key', 'my_proxy_pass', 'my_proxy_ignore_client_abort',  'my_proxy_read_timeout', 'my_proxy_send_timeout', 'my_proxy_hide_header', 'my_proxy_cache_min_uses', 'my_proxy_cache_lock_timeout', 'my_proxy_cache_lock',
 'my_proxy_cache'}
          -- check  my_data in data (it is ngx.shared.data)
          for i, name in ipairs(my_data) do
               if data:get(name) == nil then
                   table.insert(my_empty_data, name)
               end
           end
           -- then i want get my_empty_data from redis 
             if table.getn(my_empty_data) > 0 then
                    local redis = require "resty.redis"
                    red = redis:new()
                    red:set_timeout(100)
                    local ok, err = red:connect("127.0.0.1", 6379)
                    if not ok then
                        ngx.log("failed to connect: ", err)
                        return
                    end
                end
            -- and then set these  values to ngx.var.var_name 
            -- but i don't know how to do this
                ngx.var[''my_proxy_cache_key''] = value_from redis
```
Can i get a list of ngx.var attributes?
Thanks for your answer)
sorry for my english skills)

**Comment by bungle** [comment]
You cannot loop the indexes or keys using `ipairs`, `pairs` or `next` on `ngx.var`. This is by design.

You can set `ngx.var` fields though:

```lua
ngx.var.my_proxy_read_timeout = 1000
```

Everything is documented here:
https://github.com/openresty/lua-nginx-module#ngxvarvariable

**Comment by iamnotaprogrammer** [comment]
Thanks for you explanation)

**Comment by agentzh** [comment]
Consider it resolved.

**Comment by rulatir** [comment]
Is there ANY way, no matter how convoluted, to dump the contents of these objects for debugging purposes?
