### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by punit07** [openresty/openresty#209]
I have tried to install the CentOS package as mentioned here... http://openresty.org/en/linux-packages.html

but its returning a 404 error 

sudo yum-config-manager --add-repo https://openresty.org/yum/centos/OpenResty.repo

Please fix. Thanks

**Comment by detailyang** [comment]
@punit07 you can create the OpenResty.repo manually, @agentzh will fix it as soon as possible:)

**Comment by agentzh** [comment]
Just fixed the 404 error. Please try again on your side. Thanks!

**Comment by contherad** [comment]
I'm getting a 404 when trying to install openresty from repo on centos 7. Any tips for getting it to work?

Thanks!

**Comment by agentzh** [comment]
@contherad What the exact repo URL are you using?

**Comment by agentzh** [comment]
@contherad Please do not hijack existing closed issues to report new issues. Thank you for your cooperation.

**Comment by contherad** [comment]
My apologies.
