### ISSUE TITLE
调用redis_iresty.lua代码报错

### ISSUE THREAD

**Issue by JarvisZhu** [openresty/openresty#210]
我学习《OpenResty最佳实践》时，将redis_iresty.lua的代码原封不动的拷贝到redis_iresty.lua文件中，并将该文件放在/lualib/resty/目录下，然后在conf目录下新建一个conf文件：

worker_processes 1;
error_log logs/error.log;
events {
	worker_connections 1024;
}
http {
	server {
		listen 6699;
		location /set {
			content_by_lua_block {
				local redis = require "resty.redis_iresty"
				local red = redis:new()

				local ok, err = red:set("dog", "an animal")
				if not ok then
					ngx.say("failed to set dog: ", err)
					return
				end

				ngx.say("set result: ", ok)
			}
		}
		
		location /get {
			content_by_lua_block {
				local redis = require "resty.redis_iresty"
				local red = redis:new()
				local r = red:get("dog")
				ngx.say(r)
			}
		}
	}
}
使用nginx.exe -c conf/..conf命令启动，浏览器访问http://localhost:6699/set报错：
2016/12/05 21:38:08 [error] 4156#3580: *21 lua entry thread aborted: runtime error: ./lualib/resty\redis_iresty.lua:77: attempt to call global 'do_command' (a nil value)
stack traceback:
coroutine 0:
	./lualib/resty\redis_iresty.lua: in function 'set'
	content_by_lua(nginx_redis.conf:21):5: in function <content_by_lua(nginx_redis.conf:21):1>, client: 127.0.0.1, server: , request: "GET /set HTTP/1.1", host: "localhost:6699"

请问怎么解决？谢谢！

**Comment by detailyang** [comment]
Hello.

Please use Chinese only or you can post this question on [openresty](https://groups.google.com/forum/#!forum/openresty).

Many thanks :)

**Comment by agentzh** [comment]
@JarvisZhu redis_iresty.lua is not a standard OpenResty component. I'm afraid you are reporting your problem to the wrong place. BTW, as @detailyang mentions, this place is considered English only. Please join the openresty (Chinese) mailing list instead if you really want to use Chinese. Thank you.
