### ISSUE TITLE
About openresty static compile

### ISSUE THREAD

**Issue by xxoxx** [openresty/openresty#218]
I get the code  

wget https://github.com/openresty/openresty/releases/download/v1.11.2.2/openresty-1.11.2.2.tar.gz

build str: ./configure --with-ld-opt="-static" && make && make install

ldd  check the sbin/nginx  is statically linked 
 
./nginx -t  work well

The test code work well 

        location / {
            default_type text/html;
            content_by_lua '
                ngx.say("<p>hello, world</p>")
            ';
        }

And I test other project code

init_by_lua_file  /opt/project/init.lua;
The 1 line:
local cjson_ = require "cjson.safe"

And start the nginx  found error

nginx: [error] init_by_lua_file error: error loading module 'cjson.safe' from file '/usr/local/openresty/lualib/cjson.so':
	Dynamic loading not supported
stack traceback:
	[C]: at 0x55dfd5d61080
	[C]: in function 'require'
	/opt/project/init.lua:3: in main chunk

and  the file   /usr/local/openresty/lualib/cjson.so   is exist

I want worked in static mode,  but load the module error, how can get the right way.

thanks.

**Comment by agentzh** [comment]
@xxoxx Apparently, loading an external Lua C module requires dynamic linking support. A pure static linked binary cannot load DSO.
