### ISSUE TITLE
如何向使用SSL证书（使用密码加载）的网站发送https请求？

### ISSUE THREAD

**Issue by walterdev** [openresty/openresty#221]
使用openresty做正向代理服务器
发送http请求及无证书的https请求时，使用resty.http模块发送请求，但发送不了带SSL证书的请求。
调查lua_ssl_trusted_certificate接口，可以加载SSL证书，但貌似加载不了带密码的SSL证书。
请问我的应用场景应该通过何种方式发送请求？谢谢

**Comment by moonbingbing** [comment]
Please, do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see https://openresty.org/en/community.html Thanks for your cooperation.
