### ISSUE TITLE
Create a TodoBackend implementation using OpenResty

### ISSUE THREAD

**Issue by moredip** [openresty/openresty#224]
Hi,

I'm a curator for [todobackend.com](http://todobackend.com), a community resource showing examples of how to build the same simple HTTP API using different frameworks. We'd love to get a OpenResty implementation contributed - in fact we have an [issue filed](https://github.com/TodoBackend/todo-backend-site/issues/104) for it!

Creating a todobackend implementation usually only takes a hour or two for someone experienced in the framework they're using. There's lots more information about how to do it on the todobackend site [here](http://todobackend.com/contribute.html).

**Comment by agentzh** [comment]
@moredip Check out those existing `lua-resty-*` libraries for examples. It doesn't be in the standard OpenResty distribution, especially when we already have OPM:

http://opm.openresty.org/
