### ISSUE TITLE
Discussion/Insight seeking: Generate Alioss Authorization header before Nginx proxy pass the request 

### ISSUE THREAD

**Issue by fangqiao** [openresty/openresty#226]
Hi all,

My apologies first for using this issue forum to ask this kind of questions if it is not entirely appropriate. I found this might the most likely place for me to get an answer.

I am a tech guy from a start up from China. We are using Aliyun OSS for image storage. We need to have fine control of the image access rights that Ali's existing bucket and object control can't provide.

So I am thinking about using Nginx as reverse proxy. Before the image access request is passed to Aliyun, the request is passed to an inhouse build authentication server with auth_request. If it is authorized, then some module ( I need to develop) write an authorization head required by Aliyun to the proxy request to upstream. 

Aliyun requires following head for authorization:

Authorization = "OSS " + AccessKeyId + ":" + Signature

Signature = base64(hmac-sha1(AccessKeySecret,
            VERB + "\n"
            + Content-MD5 + "\n" 
            + Content-Type + "\n" 
            + Date + "\n" 
            + CanonicalizedOSSHeaders
            + CanonicalizedResource))

My questions : 
1. Is this architecture a good idea in general? Any risks? Any similar set up you know about?
2. I think Lua script is needed to generate the string. Is there library for generating hmac-sha1 and base64?

**Comment by detailyang** [comment]
>Is this architecture a good idea in general? Any risks? Any similar set up you know about?

OpenResty is very good at as a authentication server. Any risks you should be consider about is up to your experience of openresty:). OpenResty have run successfully  on many companies.

>I think Lua script is needed to generate the string. Is there library for generating hmac-sha1 and base64?

[base64](https://github.com/openresty/lua-nginx-module#ngxencode_base64) and [hmac-sha1](https://github.com/openresty/lua-nginx-module#ngxhmac_sha1) have been builtin

**Comment by fangqiao** [comment]
Thanks. I just started to learn OpenResty. So if to use openresty and lua for authentication before proxy pass, auth_request is entirely not needed?

**Comment by detailyang** [comment]
What's the auth_request? You can use the lua to implement authentication:)

**Comment by fangqiao** [comment]
Just found following example from lua-nginx-module documentation:

Note that the ngx_auth_request module can be approximated by using access_by_lua:
```
 location / {
     auth_request /auth;

     # proxy_pass/fastcgi_pass/postgres_pass/...
 }
```
can be implemented in ngx_lua as:
```
 location / {
     access_by_lua '
         local res = ngx.location.capture("/auth")

         if res.status == ngx.HTTP_OK then
             return
         end

         if res.status == ngx.HTTP_FORBIDDEN then
             ngx.exit(res.status)
         end

         ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
     ';

     # proxy_pass/fastcgi_pass/postgres_pass/...
 }
```

I guess this meets my needs, except one final question: 

say I generate the Ali authorization string inside the Lua code block. How can I pass it to 
nginx directive to set the Authorization header?

**Comment by agentzh** [comment]
@fangqiao Such beginner questions should really post to the openresty-en mailing list. This place is for real "issues". Thank you for your cooperation. Please see http://openresty.org/en/community.html

**Comment by fangqiao** [comment]
No problem.

I have got the answers and built up a prototype. It works very well. I might use openresty in production. Do you have a page for who uses openresty? 

Thanks.
