### ISSUE TITLE
Error occurring when running busted tests scripts

### ISSUE THREAD

**Issue by tcho16** [openresty/openresty#227]
I am trying to run a lua test script using busted. My test uses the the ffi library in order to compile C code. This is the following error I'm getting:
`/usr/local/openresty/lualib/resty/aes.lua:106: /opt/zbstudio/bin/linux/x64/lua: undefined symbol: EVP_md5
stack traceback:
	[C]: in function '__index'
	/usr/local/openresty/lualib/resty/aes.lua:106: in main chunk
`
I am unsure how to overcome this problem. I tried debugging aes.lua and realised it fails when it tries to execute the hash table containing sha1, md5, etc. I have the usual files (i.e. `aes.lua   lock.lua      memcached.lua  sha1.lua    sha512.lua  upstream
core      lrucache      mysql.lua      sha224.lua  sha.lua     websocket
core.lua  lrucache.lua  random.lua     sha256.lua  string.lua
dns       md5.lua       redis.lua      sha384.lua  upload.lua`) in the following directory: `/usr/local/openresty/lualib/resty`

**Comment by agentzh** [comment]
@tcho16 You should not use the `lua` interpreter to run your test code since it definitely lacks OpenSSL and all those OpenResty Lua APIs. You should use the `resty` command-line utility shipped with OpenResty instead.

**Comment by thibaultcha** [comment]
@tcho16 Here is an example of how to busted with the `resty` interpreter if that can be of any help: https://github.com/thibaultcha/lua-resty-busted

**Comment by tcho16** [comment]
@agentzh @thibaultcha . Managed to fix my problem. Can successfully lua tests on my KONG plugins.
