### ISSUE TITLE
problem with ngx.location.capture and rate_limit - get stuck forever

### ISSUE THREAD

**Issue by yarix** [openresty/openresty#229]
Hi 
i have a problem with `ngx.location.capture` and rate limits. basically i want to have different rate limits zone per tenants. i came up with the following configuration. The problem that i see is that when a client  (Jmeter) is hitting the `/api` method too fast, and the `rate_limit` starts to delay connections, the client is getting stuck. 

```bash
     limit_req_zone t2Limit zone=t2Zone:40k rate=30r/s;
     limit_req_zone t1Limit zone=t1Zone:40k rate=3r/s;
     location /t1/doApi {
		internal; #this is not accessible from outside.		
		# Proxy all requests to the AReqUpStream server group
		proxy_pass http://ReqUpStream/api;
		limit_req zone=t1Zone burst=1;			
	}

	location /t2/doApi {
		internal; #this is not accessible from outside.		
		# Proxy all requests to the AReqUpStream server group
		proxy_pass http://ReqUpStream/api;
		limit_req zone=t2Zone burst=1 ;			
	}		

	location /api {
			content_by_lua_block {
			ngx.req.read_body();
			local areqBody = ngx.req.get_body_data()
                        --here i have logic that select t1 or t2 locations. for the example i use t1.
                        ngx.log(ngx.ERR, "msg-1");
			local res2 = ngx.location.capture("/t1/doApi", {method=ngx.HTTP_POST, body=areqBody});
                        ngx.log(ngx.ERR, "msg-2");
			if res2.status == ngx.HTTP_OK then
                                ngx.log(ngx.ERR, "msg-3");
				ngx.say(res2.body);
				ngx.exit(res2.status);
			else 
				ngx.log(ngx.ERR, "msg-4");
                                ngx.status = res2.status;
				ngx.exit(res2.status);
			end;
		}
```

the log shows that:
```
2017/02/15 15:26:37 [error] 95196#79972: *57 [lua] content_by_lua: msg-1, client: xxxxxxx, server: me.com, request: "POST /api HTTP/1.1", host: "me.com"
2017/02/15 15:26:37 [error] 95196#79972: *57 [lua] content_by_lua: msg-2 while sending to client, client: xxxxxxx, server: me.com, request: "POST /api HTTP/1.1", host: "me.com"
2017/02/15 15:26:37 [error] 95196#79972: *57 [lua] content_by_lua: msg-3 while sending to client, client: xxxxxxx, server: me.com, request: "POST /api HTTP/1.1", host: "me.com"
2017/02/15 15:26:37 [error] 95196#79972: *57 [lua] content_by_lua: msg-1, client: xxxxxxx, server: me.com, request: "POST /api HTTP/1.1", host: "me.com"
2017/02/15 15:26:37 [info] 95196#79972: *57 delaying request, excess: 0.379, by zone "bofaZone", client: xxxxxxx, server: me.com, request: "POST /api HTTP/1.1", subrequest: "/bofa/auth", host: "me.com"
```

when Jmeter (with 1 thread) sends requests to `api` i can see that the 1st request pass successfully but then the Jmeter get stuck (*forever!*) because of the delay.

is it a bug? 
is there a workaround?

**Comment by yarix** [comment]
It looks related to: https://github.com/openresty/lua-nginx-module/issues/218

**Comment by agentzh** [comment]
@yarix Are you trying to rate-limit subrequests? It looks wrong to me. You should only rate-limit your main requests. Rate-limiting internal requests just make no sense. Also be careful with the benchmark tools that send requests as fast as possible. When such tools get rate limited, it would just take too long to complete all those requests. You should do the maths yourself.

**Comment by yarix** [comment]
thank you @agentzh.
So in case that rate limits are problematic with subrequests, I will really appreciate your advice for the following scenario:
- i need to rate limit my service (`me.com/api`) per tenant.
- all tenants access the same url (`me.com/api`) which is a POST request with JSON body. they can't add headers.
- to figure out the tenant i have to extract something from the JSON Body and then check the DB ( I have a service for that `getTenant`)
- once i know the tenant, i need to FW the request to the to the `api` service, which should be rate-limited.

BTW - i think the limitation (rate-limits for main requests only) should be mention in the documentation

**Comment by yarix** [comment]
@agentzh, could you explain why rate-limiting internal requests are wrong? when adding the `nodelay` option to `limit_req` in the above, then Nginx/Openresty works as expected. but, it get stuck if delay is used.

**Comment by agentzh** [comment]
@yarix You should rate limit your main requests instead of subrequests. Subrequests are for internal use only.
