### ISSUE TITLE
请问window版本的发布中如何配置 类似 nginx-upstream-fair 的负载均衡

### ISSUE THREAD

**Issue by gang929** [openresty/openresty#230]
请问window版本的发布中如何配置 类似 nginx-upstream-fair 的负载均衡，以实现根据后端服务器响应时间来进行分发

**Comment by agentzh** [comment]
@gang929 Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.
