### ISSUE TITLE
openresty hooking on the wrong lua / luarocks module path

### ISSUE THREAD

**Issue by PatHuman** [openresty/openresty#231]
Hi,

Sorry to bring this up again, I'm new to this. Could you please provide clear instructions, as it does not work out of the box for me: I'm struggling to make openresty aware of luarocks module ....
with this line, require('stormpath-nginx') , i'm getting the bellow error:

2017/03/02 10:11:12 [error] 8735#8735: *9 lua entry thread aborted: runtime error: content_by_lua(portal.conf:32):2: module 'stormpath-nginx' not found:
no field package.preload['stormpath-nginx']
no file '/usr/local/openresty/site/lualib/stormpath-nginx.lua'
no file '/usr/local/openresty/site/lualib/stormpath-nginx/init.lua'
no file '/usr/local/openresty/lualib/stormpath-nginx.lua'
no file '/usr/local/openresty/lualib/stormpath-nginx/init.lua'
no file './stormpath-nginx.lua'
no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/stormpath-nginx.lua'
no file '/usr/local/share/lua/5.1/stormpath-nginx.lua'
no file '/usr/local/share/lua/5.1/stormpath-nginx/init.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/stormpath-nginx.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/stormpath-nginx/init.lua'
no file '/usr/local/openresty/site/lualib/stormpath-nginx.so'
no file '/usr/local/openresty/lualib/stormpath-nginx.so'
no file './stormpath-nginx.so'
no file '/usr/local/lib/lua/5.1/stormpath-nginx.so'
no file '/usr/local/openresty/luajit/lib/lua/5.1/stormpath-nginx.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:

Both lua and luarocks installed via rpm on fedora-24, but the installed lua version is 5.3 not 5.1.
Could you please guide me.

Cheers

**Comment by detailyang** [comment]
Hello.
@PatHuman 
The error is obvious that the [stormpath-nginx](https://github.com/stormpath/stormpath-nginx) is not in the [lua_package_path](https://github.com/openresty/lua-nginx-module#lua_package_path) 
>no field package.preload['stormpath-nginx']
no file '/usr/local/openresty/site/lualib/stormpath-nginx.lua'
no file '/usr/local/openresty/site/lualib/stormpath-nginx/init.lua'
no file '/usr/local/openresty/lualib/stormpath-nginx.lua'
no file '/usr/local/openresty/lualib/stormpath-nginx/init.lua'
no file './stormpath-nginx.lua'
no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/stormpath-nginx.lua'
no file '/usr/local/share/lua/5.1/stormpath-nginx.lua'
no file '/usr/local/share/lua/5.1/stormpath-nginx/init.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/stormpath-nginx.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/stormpath-nginx/init.lua'
no file '/usr/local/openresty/site/lualib/stormpath-nginx.so'
no file '/usr/local/openresty/lualib/stormpath-nginx.so'
no file './stormpath-nginx.so'
no file '/usr/local/lib/lua/5.1/stormpath-nginx.so'
no file '/usr/local/openresty/luajit/lib/lua/5.1/stormpath-nginx.so'
no file '/usr/local/lib/lua/5.1/loadall.so'

And you should make sure the [lua_package_path](https://github.com/openresty/lua-nginx-module#lua_package_path) include the [stormpath-nginx](https://github.com/stormpath/stormpath-nginx)

**Comment by PatHuman** [comment]
Hi  detailyang,
Yes, Thanks. I was expecting luarocks to make stormpath-nginx available in openresty, since luarocks installed that module. 
The sentence "make sure the lua_package_path include the stormpath-nginx" is/was misleading for me. It looked like lua_package_path must include luarocks, but I ended up exporting LUA_PATH, and LUA_CPATH given from the command :  luarocks  path --bin.

That fixed my issue.
Many Thanks.
