### ISSUE TITLE
how to add component to openresty after i've finished install openresty

### ISSUE THREAD

**Issue by houfan** [openresty/openresty#232]
eeee.....I forgot to add this option "--with-luajit"  when compiling openresty. but  I found it  also work well with lua scripts .... I worried about it ,Do I need to recompile openresty  with this optioin?  or  how to add this component to the installed openresty?
really  really thanks

**Comment by detailyang** [comment]
Hello. @houfan 
If you want to use LuaJIT, you should recompile the openresty :D

**Comment by houfan** [comment]
hello, @detailyang   thanks for your reply
but  by far ,  it  worked well with lua scripts ...................eeeee how to expain this .........

**Comment by detailyang** [comment]
OpenResty now use LuaJIT 2.1 as the default.
```bash
 --with-luajit                      enable and build the bundled LuaJIT 2.1 (the default)
```

So you havent need to recompile OpenResty.

**Comment by houfan** [comment]
.............you make me soooooo confused..........in the end, do I need to recompile it or nor ?

**Comment by detailyang** [comment]
@houfan 

I'm so sorry that I do misunderstand what you have said. The OpenResty use LuaJIT now as the default which is the reason why you can run lua sciprts and you can check it by `./configure --help`. 

> --with-luajit                      enable and build the bundled LuaJIT 2.1 (the default)

**Comment by houfan** [comment]
eee....it's ok   i am a rookie here .... and  thank you very much   : P

**Comment by detailyang** [comment]
welcome to the OpenResty ：D

BTW, you should close this issues if it's solved.
