### ISSUE TITLE
which one of luajit the openresty is using

### ISSUE THREAD

**Issue by houfan** [openresty/openresty#233]
openresty enable luajit-2.1 by default . I installed another luajit-2.0 (this was a mistake)
now ,I want to know which one of luajit  the openresty is using ????

**Comment by detailyang** [comment]
Hello.

Now the LuaJIT is loaded  by dynamic linker (ld.so) at nginx, the OpenResty set the search path on linker by `--with-ld-opt='-Wl,-rpath,/opt/openresty/luajit/lib`. 
You have two ways to check the search path on linux as the following:

1. `/opt/openresty/bin/openresty -V 2>&1 |grep rpath`
2. check the elf dynamic section by `readelf -d /opt/openresty/bin/openresty |grep RPATH`

AFAK -: , you can use `ldd` to print all shared library by `ldd /opt/openresty/bin/openresty`.

**Comment by houfan** [comment]
so ..... the rpath decide which luajit the openresty is using.and by default  it's using the built-in luajit    

thank you!!! @detailyang
