### ISSUE TITLE
content_by_lua_block 提问

### ISSUE THREAD

**Issue by liuwenru** [openresty/openresty#236]
请教前辈，刚接触openresty，对所有的教程中content_by_lua_block东西不能理解，看样子它是一个函数，一个代码点，但是我如何可以查询到所有的这种东西的资料，就是我在那里可以一览这个东西的列表。方便我在做应用的时候可以查询，还是说我的这个理解就是错的，请赐教，谢谢！

**Comment by agentzh** [comment]
@liuwenru Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

**Comment by liuwenru** [comment]
@agentzh  sorry,  can you give some information about what i asked!

**Comment by detailyang** [comment]
Hello

@liuwenru If you want to use Chinese, you can join the [Chinese Google Group](https://groups.google.com/forum/#!forum/openresty)  (你可以在这个中文社区提问，会有热心的人回答你:))
