### ISSUE TITLE
build-win32.sh  compile nginx will error with  client_max_body_size

### ISSUE THREAD

**Issue by gang929** [openresty/openresty#237]
I use build-win32.sh  to compile the openresty,  the compile is OK!

but, when set   client_max_body_size 30m , the nginx will report a error!!!
nginx: [emerg] "client_max_body_size" directive invalid value!!!!

and , with the same nginx.conf and  the prebuild win32 release zip, It has no the error

why?   the config option is below
-------------------------------------------------
configure arguments: 
--prefix=. 
--with-cc-opt='-O2 -O2 -DFD_SETSIZE=10240' 
--add-module=../ngx_devel_kit-0.3.0 
--add-module=../echo-nginx-module-0.60 
--add-module=../xss-nginx-module-0.05 
--add-module=../ngx_coolkit-0.2rc3 
--add-module=../set-misc-nginx-module-0.31 
--add-module=../form-input-nginx-module-0.12 
--add-module=../encrypted-session-nginx-module-0.06 
--add-module=../srcache-nginx-module-0.31 
--add-module=../ngx_lua-0.10.7 
--add-module=../ngx_lua_upstream-0.06 
--add-module=../headers-more-nginx-module-0.32 
--add-module=../array-var-nginx-module-0.05 
--add-module=../memc-nginx-module-0.17 
--add-module=../redis2-nginx-module-0.13 
--add-module=../redis-nginx-module-0.3.7 
--add-module=../rds-json-nginx-module-0.14 
--add-module=../rds-csv-nginx-module-0.07 
--with-cc=gcc 
--with-cc=gcc 
--with-ipv6 
--sbin-path=nginx.exe 
--with-pcre-jit 
--with-ipv6 
--with-stream 
--with-stream_ssl_module 
--with-http_v2_module 
--without-mail_pop3_module 
--without-mail_imap_module 
--without-mail_smtp_module 
--with-http_stub_status_module 
--with-http_realip_module 
--with-http_addition_module 
--with-http_auth_request_module
--with-http_secure_link_module 
--with-http_random_index_module 
--with-http_gzip_static_module 
--with-http_sub_module 
--with-http_dav_module 
--with-http_flv_module 
--with-http_mp4_module 
--with-http_gunzip_module 
--with-select_module 
--with-pcre=/D/download/bbbb/openresty-1.11.2.2/objs/lib/pcre-8.39 
--with-zlib=/D/download/bbbb/openresty-1.11.2.2/objs/lib/zlib-1.2.8 
--with-openssl=/D/download/bbbb/openresty-1.11.2.2/objs/lib/openssl-1.0.2j 
--with-http_ssl_module

**Comment by agentzh** [comment]
@gang929 Have you tried the official Win32 build of OpenResty here?

http://openresty.org/en/download.html#win32

**Comment by gang929** [comment]
@agentzh   with the same nginx.conf and the official Win32 build prebuild  release zip, It has no the error

but,  the official Win32 build is limited max opened file handle with **1024**!!!  when concurrent connection is more than 1024, the nginx will report error as below
` maximum number of descriptors s upported by select 1024`

I want unlimit the 1024 to 65536, so , to recompile, but it seems not OK!!

**Comment by agentzh** [comment]
@gang929 You should not use so many exclamation marks in your text, which is quite rude. We do not deserve that.

The Win32 version of nginx uses the `select` call to do events, which is limited to 1024 (unless dirty hacks are introduced into your system).

**Comment by gang929** [comment]
@agentzh  so the win32 build can only support 1024 opened file handle?  
when the concurrent connection is more than 1024, how to sovle the problem?

**Comment by gang929** [comment]
@agentzh   Can you give me the win32 compile script,  to solve the client_max_body_size problem?

**Comment by agentzh** [comment]
Won't fix.
