### ISSUE TITLE
Use ® on the OpenResty words in prominent places for the CN site

### ISSUE THREAD

**Issue by agentzh** [openresty/openresty#238]
I've already done this to the EN site below:

https://github.com/openresty/openresty.org/commit/0fab17947

Need to do the same to our Chinese (CN) site as well.

**Comment by detailyang** [comment]
Good to see this :D and can I do this work fro Chinese (CN) site?

**Comment by agentzh** [comment]
@ingydotnet Are you already working on this? If not, then we should definitely use @detailyang's help here :)

**Comment by ingydotnet** [comment]
I was joking about editing Chinese. I'll have to make less jokes!

**Comment by agentzh** [comment]
@ingydotnet Heh.

@detailyang Please go ahead. Thank you!

**Comment by detailyang** [comment]
Haha. It's a joke about editing Chinese :smile:

**Comment by agentzh** [comment]
@detailyang Thanks!
