### ISSUE TITLE
OpenResty TCP communication

### ISSUE THREAD

**Issue by nginxsantos** [openresty/openresty#239]
Not sure if there is any group to discuss about this. Please let me know if you are aware of one. I will restrict raising a question here and my aplogies upfront.

I have few tasks/processes (called worker bees) which needs a HTTP communication towards outside. I want to use OpenResty as a frontend webserver for my few tasks.  So OpenResty receives the messages (and if required authenticates etc..) and then send a message to my tasks (worker bees) using google protobufs over TCP. It does not need to hold up the HTTP transaction till it received a reply. It can just send the 200 OK and then send a message over TCP to the backend tasks.

Can this be done? Is it a good design? Any other alternatives? Any opensource solution for this?

Please let me know.

Thanks, Santos

**Comment by agentzh** [comment]
@nginxsantos See http://openresty.org/en/community.html for such discussions.
