### ISSUE TITLE
 Execute  .configure error when I install the last version openresty on my mac 

### ISSUE THREAD

**Issue by hanmenghui** [openresty/openresty#242]
openresty version:1.11.2.2
command:
./configure \
   --with-cc-opt="-I/usr/local/opt/openssl/include/ -I/usr/local/opt/pcre/include/" \
   --with-ld-opt="-L/usr/local/opt/openssl/lib/ -L/usr/local/opt/pcre/lib/"

ERROR:
  "_lua_type", referenced from:
      _main in luajit.o
      _pmain in luajit.o
      _dotty in luajit.o
      _traceback in luajit.o
      _loadjitmodule in luajit.o
      _runcmdopt in luajit.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [luajit] Error 1
make: *** [default] Error 2
ERROR: failed to run command: make TARGET_STRIP=@: CCDEBUG=-g XCFLAGS='-DLUAJIT_ENABLE_LUA52COMPAT' CC=cc PREFIX=/usr/local/openresty/luajit

**Comment by agentzh** [comment]
@hanmenghui Just try the command `brew install homebrew/nginx/openresty` to install openresty on OS X.

**Comment by hanmenghui** [comment]
@agentzh It works,Thanks!

**Comment by alexhe** [comment]
> @hanmenghui Just try the command `brew install homebrew/nginx/openresty` to install openresty on OS X.

您好，如果还是想在mac上编译不行么？需要跨平台？
