### ISSUE TITLE
There should be  a way to access Nginx map variable from lua

### ISSUE THREAD

**Issue by svrsreeraj** [openresty/openresty#246]
http {
         map $host $my_application_path {
               default "/home/sreeraj/EKAM/CollaborationSuitePHP/";
          }

 init_by_lua_block {
      //access the map variable here
    }
}

**Comment by agentzh** [comment]
@svrsreeraj NGINX variables do not even exist at the point of `init_by_lua_block`. NGINX variables only exist when NGINX serve each individual request while `init_by_lua*` is run upon the nginx configuration loading phase. So it just does not make any sense at all.

**Comment by svrsreeraj** [comment]
ok, but how the map variable can be accessed in content_by_lua ?

**Comment by Mystic-Mirage** [comment]
I need access to map variable in content_by_lua_block. Is it possible?

**Comment by agentzh** [comment]
@svrsreeraj Why don't you try it out yourself? BTW, please do not hijack closed and unrelated issues like this. It's rude.
