### ISSUE TITLE
openresty shows GeoIP dependency error via yum

### ISSUE THREAD

**Issue by ajsaini007** [openresty/openresty#251]
Hello Friends,

I am trying to install openresty 1.11.2 via yum tool on RHEL6.
It shows GeoIP dependency error (below are error logs).

[root@localhost ~]# yum list openresty
Loaded plugins: product-id, refresh-packagekit, search-disabled-repos, security, subscription-manager
Available Packages
openresty.x86_64                                                           1.11.2.2-8.el6                                                           openresty
[root@localhost ~]# yum install openresty
Loaded plugins: product-id, refresh-packagekit, search-disabled-repos, security, subscription-manager
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package openresty.x86_64 0:1.11.2.2-8.el6 will be installed
--> Processing Dependency: openresty-zlib >= 1.2.8-1 for package: openresty-1.11.2.2-8.el6.x86_64
--> Processing Dependency: openresty-openssl >= 1.0.2h-5 for package: openresty-1.11.2.2-8.el6.x86_64
--> Processing Dependency: openresty-pcre >= 8.39-3 for package: openresty-1.11.2.2-8.el6.x86_64
--> Processing Dependency: GeoIP for package: openresty-1.11.2.2-8.el6.x86_64
--> Running transaction check
---> Package openresty.x86_64 0:1.11.2.2-8.el6 will be installed
--> Processing Dependency: GeoIP for package: openresty-1.11.2.2-8.el6.x86_64
---> Package openresty-openssl.x86_64 0:1.0.2k-1.el6 will be installed
---> Package openresty-pcre.x86_64 0:8.40-1.el6 will be installed
---> Package openresty-zlib.x86_64 0:1.2.11-1.el6 will be installed
--> Finished Dependency Resolution
Error: Package: openresty-1.11.2.2-8.el6.x86_64 (openresty)
           Requires: GeoIP
**********************************************************************
yum can be configured to try to resolve such errors by temporarily enabling
disabled repos and searching for missing dependencies.
To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

Error: Package: openresty-1.11.2.2-8.el6.x86_64 (openresty)
           Requires: GeoIP
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@localhost ~]# 

NOTE: I couldn't find GeoIP package yet and still looking, please suggest me a solution for this.

Regards
Ajay

**Comment by agentzh** [comment]
Try sudo yum install epel-release

BTW, please do not cross post.

**Comment by agentzh** [comment]
Considered it resolved. We'll consider removing the GeoIP package dependency in future package releases.

**Comment by taf2** [comment]
Looks like this is now missing from openresty amazon rpm's?

**Comment by agentzh** [comment]
@taf2 This nonstandard GeoIP dependency has been removed from the official binary packages to avoid such installation headache.

**Comment by agentzh** [comment]
One can always use a Lua binding to libmaxminddb or other IP geolocation libraries anyway.

**Comment by taf2** [comment]
Ah okay - it appears to still be included in the homebrew packages which maybe causes confusion when going from a developer environment to production?

**Comment by agentzh** [comment]
@taf2 Different operating systems may have different policies, which is natural :)
