### ISSUE TITLE
mysql error,please help

### ISSUE THREAD

**Issue by taorui2017** [openresty/openresty#254]
version:openresty-1.11.2.2,openssl-1.0.2.k
configure:./configure  --prefix=/home/taorui/cloudfare/openresty --with-debug --with-openssl=/home/taorui/cloudfare/required/openssl-1.0.2k --with-openssl-opt="-d" --with-cc-opt="-O0 -g"&&make 
use mysql:
        mysql = require "resty.mysql"
        local db = mysql:new()
        db:set_timeout(g.db_timeout)
error occurs:2017/05/03 10:03:49 [error] 22925#0: init_by_lua_file error: /home/taorui/cloudfare/openresty/lualib/resty/mysql.lua:471: no request found
stack traceback:
        [C]: in function 'tcp'
        /home/taorui/cloudfare/openresty/lualib/resty/mysql.lua:471: in function 'new'
        /home/taorui/init.lua:43: in main chunk

the mysql.lua:471 is:function _M.new(self)
 471line:   local sock, err = tcp()
    if not sock then
        return nil, err
    end
    return setmetatable({ sock = sock }, mt)
end

**Comment by agentzh** [comment]
@taorui2017 This limitation is officially documented: https://github.com/openresty/lua-resty-mysql/blob/master/README.markdown#limitations

**Comment by taorui2017** [comment]
thank you ,but when i move the code to content_by_lua,this error happen:

2017/05/03 11:31:10 [debug] 8142#0: *4 lua tcp socket pool get keepalive peer
2017/05/03 11:31:10 [debug] 8142#0: *4 lua tcp socket keepalive connection pool not found
2017/05/03 11:31:10 [debug] 8142#0: posix_memalign: 00007FC2207B8390:128 @16
2017/05/03 11:31:10 [debug] 8142#0: *4 lua tcp socket connect timeout: 20000
2017/05/03 11:31:10 [debug] 8142#0: malloc: 00007FC2207B9360:72
2017/05/03 11:31:10 [debug] 8142#0: *4 lua tcp socket network address given directly
2017/05/03 11:31:10 [debug] 8142#0: *4 lua tcp socket resolve retval handler
2017/05/03 11:31:10 [debug] 8142#0: *4 stream socket 11
2017/05/03 11:31:10 [debug] 8142#0: *4 epoll add connection: fd:11 ev:80002005
2017/05/03 11:31:10 [debug] 8142#0: *4 connect to 127.0.0.1:5518, fd:11 #5
2017/05/03 11:31:10 [debug] 8142#0: *4 http cleanup add: 00007FC2207B83E0
2017/05/03 11:31:10 [debug] 8142#0: *4 lua tcp socket connect: -2
2017/05/03 11:31:10 [debug] 8142#0: *4 posix_memalign: 00007FC2207B80C0:128 @16
2017/05/03 11:31:10 [debug] 8142#0: *4 event timer add: 11: 20000:1493782290221
2017/05/03 11:31:10 [debug] 8142#0: *4 lua resume returned 1
2017/05/03 11:31:10 [debug] 8142#0: *4 lua thread yielded
2017/05/03 11:31:10 [debug] 8142#0: *4 http lua finalize fake request: -4, a:1, c:2
2017/05/03 11:31:10 [debug] 8142#0: *4 http lua fake request count:2
2017/05/03 11:31:10 [debug] 8142#0: add cleanup: 00007FC2207B83F8


and,i also test http module,this error also happen

**Comment by agentzh** [comment]
@taorui2017 None of those are errors. Not even warnings. Note the `[debug]` log level. They are completely harmless. They are just debugging output.
