### ISSUE TITLE
Add support to build without sse4 instrunction

### ISSUE THREAD

**Issue by spacewander** [openresty/openresty#256]
Although sse4 is widely used, some outdate cpus don't support it.

There is a feature test for `sse4` in `configure`. However, the build machine supports `sse4` doesn't mean all running machines support `sse4`. So it would be great to support disabling `sse4` option.

At the first glance, it seems I could pass `--with-luajit-xcflags='-mno-sse4.2'` to disable `sse4`.
It doesn't work. Because the `luajit-xcflags` is put ahead of the default one. What I got was `XCFLAGS='-mno-sse4.2 -DLUAJIT_ENABLE_LUA52COMPAT -msse4.2'`.

Maybe we could put the `luajit-xcflags` after the default one, making it possible to override the default cflags?
Or we could just add another `configure` option to remove `sse4` flag?

**Comment by agentzh** [comment]
@spacewander I suggest you build openresty on one of those boxes with old CPU directly. I strongly discourage turning off `-msse4.2` on those boxes *with* SSE 4.2 support. There is a very good reason why we turn it on by default.

**Comment by agentzh** [comment]
@spacewander BTW, there is a bug in the current `-msse4.2` feature test. You'll need the following patch for OpenResty's `./configure` script to make it actually work:

https://github.com/openresty/openresty/commit/eb8fc777

**Comment by agentzh** [comment]
@spacewander BTW, I've made `--with-luajit-xcflags=FLAGS` appended instead of prepended to the default flags. But again, I'm strong against abusing this to disable `-msse4.2` on those boxes actually with SSE 4.2 support.

**Comment by alex-mashin** [comment]
The binary openresty package for Ubuntu artful wouldn't install on by box because of this. Can I do anything about this short of compiling from source?

**Comment by agentzh** [comment]
@alex-mashin Building the latest openresty formal release's source code on your box without SSE 4.2 support should detect this automatically.

**Comment by nelsonmora48** [comment]
Anybidy has a Docker Image of kong without sse4 ? I Have tried to bliud openresty from sources inside a dockler container but fails...

**Comment by neomantra** [comment]
If you have a Docker container based on either `alpine:3.8`, `ubuntu:bionic`, or `ubuntu:xenial`, then you should be able to build OpenResty from source using the commands in the `RUN` stanzas of the Dockerfiles here:

https://github.com/openresty/docker-openresty

If that doesn't work, I can try to help diagnose.
