### ISSUE TITLE
Why rotated openresty(in Docker) log file not release in filesystem?

### ISSUE THREAD

**Issue by StayTherapy** [openresty/openresty#257]
I deploy openresty in Docker and use some cron job to rotate access log, the log file increase quickly, log file rotate is success , but host system disk space didn't release .

I try to use 'lsof | grep delete' check what is going on , The rotated log file is still tag as 'deleted' . When I restarted docker deamon, disk space released.

why this happend whith openresty in docker ?

**Comment by neomantra** [comment]
This is probably an aspect of the Docker storage driver you are using. Which one are you using? Use `docker info` to find out. 

Perhaps you can try using Docker volumes to map the logs to local storage. 

The "official" OpenResty Docker images take a different approach, mapping the access and error files to stdout/stderr so they go through the Docker logging system. This is the same approach the official Nginx images use.

**Comment by StayTherapy** [comment]
it's overlay:
"""
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
"""

I try to adjust the volumes setting ✍️

**Comment by anjia0532** [comment]
@StayTherapy  can you try `kill -USR1 $( cat /path/to/nginx.pid )` ? [Stopping or Restarting NGINX](https://www.nginx.com/resources/wiki/start/topics/tutorials/commandline/#stopping-or-restarting-nginx)

**Comment by agentzh** [comment]
This is more about docker than OpenResty. It's off topic. I'm closing it.

General discussions should go to the openresty-en mailing list instead: http://openresty.org/en/community.html
