### ISSUE TITLE
Error in redis-nginx-module-0.3.7 when compiling.

### ISSUE THREAD

**Issue by concatime** [openresty/openresty#259]
Hi. When I try to compile, I get the same error as [this](https://github.com/openresty/redis2-nginx-module/pull/42).
A quick fix: https://github.com/openresty/redis2-nginx-module/pull/42/commits/73475b8c0cca48f6fb6bc99080e1adbbca1447b8

**Comment by agentzh** [comment]
@concatime Are you changing the nginx core in the OpenResty bundle yourself? If yes, that would be a very bad idea.

**Comment by concatime** [comment]
I just tried to update nginx in openresty to use the latest version 1.13.

**Comment by agentzh** [comment]
@concatime That's not compatible with the rest of the components. Never officially tested and subject to problems. That's the whole point of OpenResty of ensuring everything works nicely and reliably together. We'll try upgrading the nginx core when we are at it.
