### ISSUE TITLE
the access_log off has no effect

### ISSUE THREAD

**Issue by wtiancai** [openresty/openresty#260]
nginx version: openresty/1.11.2.3

ps：when use content_by_lua_file,the access_log off has no effect

if set access_log  off in http,there is no any output in the access.log files，it's right

but if set access_log off in location,it still output access in the access.log files,no effect

my nginx.conf follows:
http {
....
	access_log  logs/access.log main;
...
	server {
			listen       80;
			server_name  localhost;
..
			location ~* .*\.(gif|jpg|jpeg|png|bmp|swf|js|css)$ {
					access_log off;
					proxy_cache pscms;
					proxy_cache_valid 200 304 1h;
					proxy_cache_valid 301 302 5m;
					proxy_cache_valid any 1m;
					proxy_set_header Accept-Encoding "";            
					proxy_ignore_headers "Cache-Control" "Expires";  
					content_by_lua_file ./conf/my.lua;
					expires  15m;
					break;
			} 

			location / {
					proxy_redirect     off;
					proxy_set_header   Host             $host;
					content_by_lua_file ./conf/my.lua;
			}
...

**Comment by agentzh** [comment]
@wtiancai This should be standard nginx core behavior when internal redirects happen. That is, the control flow leaves the current location and enters another location which does the actual access logging and does not have `access_log off`. You can temporarily enable the nginx debugging logs to be sure.

**Comment by wtiancai** [comment]
@agentzh 
when use content_by_lua_file,has the problem. I turn on debugging logs mode,but there is nothing to help.

nginx.conf：
	server {
		listen       80;
		server_name  localhost;

		charset utf-8;
		lua_code_cache on;

		location ~ .*\.(jsp|do|shtml)?$ { 
			proxy_redirect     off; 
			content_by_lua_file ./conf/mytest.lua;
		} 

		location ~* .*\.(gif|jpg|jpeg|png|bmp|swf|js|css)$ { 
			access_log off;
			proxy_cache pscms;                       
			proxy_cache_valid 200 304 1h;           
			proxy_cache_valid 301 302 5m; 
			proxy_cache_valid any 1m; 
			proxy_set_header Accept-Encoding "";            
			proxy_ignore_headers "Cache-Control" "Expires"; 
			content_by_lua_file ./conf/mytest.lua;
			expires  15m; 
			break;  
		} 
     
		location / {
			proxy_redirect     off; 
			content_by_lua_file ./conf/mytest.lua;			
		}

		location @proxy_A {
			proxy_pass http://app_server;
		}

		#error_page  404              /404.html;

		# redirect server error pages to the static page /50x.html
		#
		error_page   502 503 504  /50x.html;
		location = /50x.html {
			root   html;
		}

	}

mytest.lua：
ngx.exec("@proxy_A")

**Comment by agentzh** [comment]
@wtiancai You should put `access_log off;` in side your `location @proxy_A` since that is the location which does the logging. As I've said, internal redirects are happening here due to your use of the `ngx.exec()` API function. Apparently you were not listening :)
