### ISSUE TITLE
Update LuaJIT

### ISSUE THREAD

**Issue by concatime** [openresty/openresty#261]
Hi. A new beta (3) is [released](https://luajit.org/download.html). Could you migrate to it?

**Comment by agentzh** [comment]
@concatime We are already using the latest LuaJIT v2.1 in our master, even newer than beta3. You can try out the following pre-release:

https://openresty.org/download/openresty-1.11.2.4rc0.8.tar.gz

**Comment by concatime** [comment]
Wow, good to know! Sure I will try it! Thx for the awesome job.
