### ISSUE TITLE
Compile openresty with different version of nginx.

### ISSUE THREAD

**Issue by taosx** [openresty/openresty#263]
I would like to try to compile openresty manually with different nginx versions, but I'm not sure where I should change the version of nginx when compiling. I would be interested in special about version 1.12 of nginx which support fastcgi_cache_background_update.

My server is underpowered and I would not like any user requests or bots to hit the php app.

**Comment by agentzh** [comment]
@taosx It's strongly discouraged to change the nginx core in any openresty release tarballs or packages since your own nginx core may not  becompatible and is very likely to be slower in performance and even buggy in behavior.

We'll upgrade the nginx core to the 1.13.x series in OpenResty in the near future.

**Comment by agentzh** [comment]
The nginx core upgrade will happen in the next couple of months.

**Comment by taosx** [comment]
Thank you for all the work, I think I'll wait then.

**Comment by wjessop** [comment]
I'd be really interested in a 1.12, we really need max_conns and it seems this was removed between Nginx v1.5.9 and v1.11.5.

**Comment by wjessop** [comment]
I see you've upgraded Nginx core to 1.11.2, any idea when you will be able to upgrade to 1.11.5? We're blocked still on the max_conns feature of the [server](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#server) directive  only being available in 1.11.5 and upwards.

**Comment by agentzh** [comment]
@wjessop See my reply in the openresty-en mailing list: https://groups.google.com/d/msg/openresty-en/DrhNC0Mbb2A/6nUTpOBmAwAJ

**Comment by wjessop** [comment]
Thanks!
