### ISSUE TITLE
ngx.time() is not correct ,lead to socket timeout

### ISSUE THREAD

**Issue by redcloser** [openresty/openresty#264]
i did a test like below use bin/resty

```lua
print("start time " .. ngx.time())
for i = 1, 5000000000 do end  --or use io.read() and wait 10 seconds
print("end time " .. ngx.time())

Output:
start time 1496995209
end time   1496995209
```
```lua
print("start time " .. ngx.time())
for i = 1, 5000000000 do end --or use io.read() and wait 10 seconds
ngx.update_time() -- or  ngx.sleep(0.001)
print("end time " .. ngx.time())

Output:
start time 1496995133
end time   1496995142
```

this probleam can cause socket timeout if some redis operations after the first code,like someone asked in google group  [cpu满时出现奇怪的lua tcp socket read timed out问题](https://groups.google.com/forum/#!searchin/openresty/timeout%7Csort:relevance/openresty/Pira0yBs0do/2ylZnbSrcAAJ) ,

**Comment by agentzh** [comment]
@redcloser `ngx.time()` is using the cached time of nginx. It's officially documented. If you want accurate times, you should call `ngx.update_time()` yourself. See

https://github.com/openresty/lua-nginx-module/#ngxtime

**Comment by agentzh** [comment]
@redcloser Also, you should never block the nginx event loop with too much CPU computations in the first place. It is a single-threaded application. That's also why we provide `ngx.sleep(0)` to make  it possible for CPU-bound code to periodically yield the control of the CPU:

https://github.com/openresty/lua-nginx-module/#ngxsleep
