### ISSUE TITLE
centos openresty-1.11.2.3-15 rpm package not found 404

### ISSUE THREAD

**Issue by jybleau** [openresty/openresty#265]
Hi, 
on centos7 when installing using the openresty repo:
`https://openresty.org/package/centos/openresty.repo`

Installation fails with 404 error:
`https://openresty.org/package/centos/7/x86_64/00559824-openresty/openresty-1.11.2.3-15.el7.centos.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found`

Should the url be like?
`https://openresty.org/package/centos/7/x86_64/openresty-1.11.2.3-15.el7.centos.x86_64.rpm`

If I should post the issue elsewhere please tell me.
Thanks.

**Comment by agentzh** [comment]
This is strange. Did you strictly follow the instructions here? http://openresty.org/en/linux-packages.html#centos

**Comment by jybleau** [comment]
Testing with a clean install works fine. yum got broken during the latest yum update. Sorry about that.

**Comment by agentzh** [comment]
@jybleau Good to know it gets resolved.
