### ISSUE TITLE
Illegal instruction     $nginx -t -c $NGINX_CONF_FILE

### ISSUE THREAD

**Issue by cnlangzi** [openresty/openresty#267]
It throws "Illegal instruction" when we try to run /usr/local/openresty/nginx/sbin/nginx .  The CPU is Q9550 2.83Ghz .  Does anyone know how to fix it?

**Comment by cnlangzi** [comment]
cpuinfo:

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad CPU    Q9550  @ 2.83GHz
stepping	: 10
microcode	: 2567
cpu MHz		: 2826.505
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm dts tpr_shadow vnmi flexpriority
bogomips	: 5653.01
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad CPU    Q9550  @ 2.83GHz
stepping	: 10
microcode	: 2567
cpu MHz		: 2826.505
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm dts tpr_shadow vnmi flexpriority
bogomips	: 5653.01
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad CPU    Q9550  @ 2.83GHz
stepping	: 10
microcode	: 2567
cpu MHz		: 2826.505
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm dts tpr_shadow vnmi flexpriority
bogomips	: 5653.01
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad CPU    Q9550  @ 2.83GHz
stepping	: 10
microcode	: 2567
cpu MHz		: 2826.505
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm dts tpr_shadow vnmi flexpriority
bogomips	: 5653.01
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

**Comment by cnlangzi** [comment]
openresty is installed from Official OpenResty Repository

**Comment by agentzh** [comment]
@cnlangzi The official OpenResty binary packages require SSE 4.2 support in your CPU. According to the Intel data sheet, your CPU model was released in the year 2008 (9 years ago) and only supports SSE versions up to 4.1. You need to build openresty from source on your old CPU yourself:

https://openresty.org/download/openresty-1.11.2.4rc0.8.tar.gz

I'll add a note to the web site.

**Comment by cnlangzi** [comment]
I have compiled openresty from source code on this server.  
./configure --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include' --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl/lib' --with-pcre-jit --with-ipv6 --with-stream --with-stream_ssl_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-file-aio --with-dtrace-probes --with-http_ssl_module 
gmake
gmake install

it says:
gmake[2]: Leaving directory `/home/devops/openresty-1.11.2.3/build/nginx-1.11.2'
gmake[1]: Leaving directory `/home/devops/openresty-1.11.2.3/build/nginx-1.11.2'
mkdir -p /usr/local/openresty/nginx/site/lualib /usr/local/openresty/nginx/site/pod /usr/local/openresty/nginx/site/manifest
ln -sf /usr/local/openresty/nginx/nginx/sbin/nginx /usr/local/openresty/nginx/bin/openresty

it throws same error  "Illegal instruction" when we try to run "/usr/local/openresty/nginx/nginx/sbin/nginx -V".

Is anything missing on compiling it? thanks.

**Comment by agentzh** [comment]
@cnlangzi I think I asked you to try the following source tarball instead:

https://openresty.org/download/openresty-1.11.2.4rc0.8.tar.gz

I didn't ask you to try the last formal release 1.11.2.3 because its sse 4.2 feature test does not really work.

**Comment by cnlangzi** [comment]
@agentzh sorry, I did not realize they are different.   It works based on openresty-1.11.2.4rc0.8.tar.gz. thanks a lot.

**Comment by cnlangzi** [comment]
@agentzh there is conflict on openssl 

nginx: [emerg] at least OpenSSL 1.0.2e required but found OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by agentzh** [comment]
@cnlangzi It's not a conflict but your openssl is not new enough. You should really use the `openresty-openssl-dev` or `openresty-openssl-devel` packages (depending on your OS) from the official OpenResty pre-built package repositories when building your openresty. The command should be like

```
SSL_PREFIX=/usr/local/openresty/openssl
PCRE_PREFIX=/usr/local/openresty/pcre

cd  /path/to/openresty-xxx/ || exit 1
./configure --with-cc-opt="-I$SSL_PREFIX/include -I$PCRE_PREFIX/include" \
    --with-ld-opt="-Wl,-rpath,$SSL_PREFIX/lib:$PCRE_PREFIX/lib -L$SSL_PREFIX/lib -L$PCRE_PREFIX/lib" \
    -j8 || exit 1

make -j8 || exit 1
sudo make install || exit 1
```

**Comment by agentzh** [comment]
@cnlangzi BTW, it's always recommended to provide your OS info. Otherwise I have to guess.

**Comment by agentzh** [comment]
@cnlangzi BTW, the performance can be bad on old CPU chips without SSE 4.2 support in special cases.

**Comment by cnlangzi** [comment]
@agentzh  thanks. it is fixed.  We are asking the guy to upgrade the server asap. 
I have rebuilt latest openssl on server by https://www.digitalocean.com/community/questions/how-to-get-already-installed-nginx-to-use-openssl-1-0-2-for-alpn  .  the issue can be fixed too.

**Comment by agentzh** [comment]
@cnlangzi You need to apply some of our own OpenSSL patches, otherwise some OpenResty SSL features would be disabled. That's why I suggest you use OpenResty's prebuilt openssl packages.

**Comment by VaiN474** [comment]
I've run into this issue while trying to install OpenResty on an Ubuntu 16.0.4 VM on a local Dell PowerEdge 1950. The CPUs don't support SSE 4.2, but when compiling from source it's still trying to add it for LuaJIT:

```
make TARGET_STRIP=@: CCDEBUG=-g XCFLAGS='-DLUAJIT_ENABLE_LUA52COMPAT -msse4.2' CC=cc PREFIX=/usr/local/openresty/luajit
```

```
$ cat /proc/cpuinfo
processor : 0
vendor_id : GenuineIntel
cpu family  : 6
model   : 23
model name  : Intel(R) Xeon(R) CPU           E5430  @ 2.66GHz
stepping  : 6
microcode : 0x60f
cpu MHz   : 2660.027
cache size  : 6144 KB
physical id : 0
siblings  : 1
core id   : 0
cpu cores : 1
apicid    : 0
initial apicid  : 0
fpu   : yes
fpu_exception : yes
cpuid level : 10
wp    : yes
flags   : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl tsc_reliable nonstop_tsc aperfmperf pni ssse3 cx16 sse4_1 tsc_deadline_timer hypervisor lahf_lm tsc_adjust dtherm
bugs    :
bogomips  : 5320.05
clflush size  : 64
cache_alignment : 64
address sizes : 43 bits physical, 48 bits virtual
power management:
```

I had to manually comment out the line that adds that flag to prevent the `Illegal Instruction` error. I then tried to follow the suggestion to compile against OpenResty's OpenSSL and PCRE, but I ran into a strange issue with it refusing to find the libpq library for the http_postgres_module.

If I compile with the system's versions it works fine:

```
adding module in ../ngx_postgres-1.0rc7
checking for libpq library in directories specified by LIBPQ_INC (/usr/include/postgresql) and LIBPQ_LIB (/usr/lib/x86_64-linux-gnu) ... found
checking for libpq library version 9.1 ... found
```

But when using the suggested method:

```
adding module in ../ngx_postgres-1.0rc7
checking for libpq library in directories specified by LIBPQ_INC (/usr/include/postgresql) and LIBPQ_LIB (/usr/lib/x86_64-linux-gnu) ... not found
 ./configure: error: ngx_postgres addon was unable to find the libpq library.
```

It's failing to find it in the same place. What am I missing here? Do I need a different version of libpq to use OpenResty's OpenSSL/PCRE?

**Comment by agentzh** [comment]
@VaiN474 The sse 4.2 detection logic has a bug in the formal releases but it has already fixed in the git repository. Or you can try the following preview release instead:

https://openresty.org/download/openresty-1.11.2.5rc0.1.tar.gz

BTW, it's strongly recommended to run OpenResty on an Intel chip with SSE 4.2 instruction set otherwise the Lua string creations may incur unbelievable large overhead in special cases.

Regarding the postgres thing, you can check out the `build/nginx-1.11.2/objs/autoconf.err` file for the details of the feature test failure. BTW, it's recommended to use a Lua client based on OpenResty cosocket API, like pgmoon. The libpq library has known bugs when dealing with edge-triggered events (like epoll). Anyway, the Pg thing is already off topic; we should not hijack this issue for such discussions.

**Comment by agentzh** [comment]
@VaiN474 Please, do not reply to a closed issue unless you have a very good reason. Thank you for your cooperation.
