### ISSUE TITLE
dtrace: Command not found

### ISSUE THREAD

**Issue by cnlangzi** [openresty/openresty#268]
We want to compile openresty from source code.  The compile options are copied from official pre-built package.  But it throws an error like below
cat src/dtrace/nginx_provider.d \
	../ngx_lua-0.10.8/dtrace/ngx_lua_provider.d \
	/home/devops/openresty-1.11.2.3/bundle/ngx_lua-0.10.8/dtrace/ngx_lua_provider.d > objs/dtrace_providers.d
dtrace -h -o objs/ngx_dtrace_provider.h -s objs/dtrace_providers.d
gmake[2]: dtrace: Command not found
gmake[2]: *** [objs/ngx_dtrace_provider.h] Error 127
gmake[2]: Leaving directory `/home/devops/openresty-1.11.2.3/build/nginx-1.11.2'
gmake[1]: *** [build] Error 2
gmake[1]: Leaving directory `/home/devops/openresty-1.11.2.3/build/nginx-1.11.2'
gmake: *** [all] Error 2

which dtrace should be installed?  is it https://github.com/dtrace4linux/linux.git or  https://oss.oracle.com/projects/DTrace/?

thanks.

**Comment by cnlangzi** [comment]
Linux  2.6.32-696.3.1.el6.x86_64 #1 SMP Tue May 30 19:52:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by agentzh** [comment]
@cnlangzi It is provided by the `systemtap-sdt-devel` package on RedHat-style distributions. See

https://github.com/openresty/openresty-packaging/blob/master/rpm/SPECS/openresty.spec#L21

**Comment by tanaydin** [comment]
also check https://docs.python.org/3/howto/instrumentation.html
