### ISSUE TITLE
OPM api/pkg/fetch returns redirect for another package

### ISSUE THREAD

**Issue by iseckkeller** [openresty/openresty#269]
bew-net-2015777:isp-openresty kkeller$ curl -v https://opm.openresty.org/api/pkg/fetch?account=openresty&name=lua-resty-lock
[1] 26298
bew-net-2015777:isp-openresty kkeller$ *   Trying 138.68.231.133...
* TCP_NODELAY set
* Connected to opm.openresty.org (138.68.231.133) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: openresty.org
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> GET /api/pkg/fetch?account=openresty HTTP/1.1
> Host: opm.openresty.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 302 Moved Temporarily
< Server: openresty+
< Date: Wed, 21 Jun 2017 14:18:21 GMT
< Content-Type: text/html
< Content-Length: 154
< Connection: keep-alive
< X-File-Checksum: 6c013cd4-2db2-9de2-0fff-b61885e1467c
< Location: /api/pkg/tarball/pintsized/lua-resty-http-0.10.opm.tar.gz
< Expires: Wed, 21 Jun 2017 14:18:27 GMT
< Cache-Control: max-age=180
< Cache-Status: HIT
< 
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Curl_http_done: called premature == 0
* Connection #0 to host opm.openresty.org left intact

[1]+  Done                    curl -v https://opm.openresty.org/api/pkg/fetch?account=openresty

This seems to be a sporadic issue and the results vary(sometimes even work)

bew-net-2015777:isp-openresty kkeller$ curl -v https://opm.openresty.org/api/pkg/fetch?account=openresty&name=lua-resty-lock
[1] 26307
bew-net-2015777:isp-openresty kkeller$ *   Trying 138.68.231.133...
* TCP_NODELAY set
* Connected to opm.openresty.org (138.68.231.133) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: openresty.org
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> GET /api/pkg/fetch?account=openresty HTTP/1.1
> Host: opm.openresty.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 302 Moved Temporarily
< Server: openresty+
< Date: Wed, 21 Jun 2017 14:24:53 GMT
< Content-Type: text/html
< Content-Length: 154
< Connection: keep-alive
< X-File-Checksum: 2b9dfc20-56fe-1885-322b-5fd016aa7057
< Location: /api/pkg/tarball/pintsized/lua-resty-redis-connector-0.03.opm.tar.gz
< Expires: Wed, 21 Jun 2017 14:26:24 GMT
< Cache-Control: max-age=180
< Cache-Status: HIT
< 
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Curl_http_done: called premature == 0
* Connection #0 to host opm.openresty.org left intact

I got here because i was trying to run the following:
> opm get SkyLothar/lua-resty-jwt
and get the following output
root@d453227d53f8:/# opm get SkyLothar/lua-resty-jwt
* Fetching SkyLothar/lua-resty-jwt  
ERROR: bad 302 redirect target in the server response: /api/pkg/tarball/jkeys089/lua-resty-hmac-0.01.opm.tar.gz

i'm running this within the official openresty docker container.

**Comment by iseckkeller** [comment]
... as a follow up.  it was working just fine for me yesterday.

**Comment by eyezak** [comment]
also seeing this issue this morning as of less than 2 hours ago

**Comment by iseckkeller** [comment]
Seems that the origin server is returning from cache which is not considering URL query parameters as part of the cache key.

< Cache-Control: max-age=180
< Cache-Status: HIT
Those are the response headers i see when it fails and the Location header is always the previous package requested.  I tried to add Cache-Control: no cache in request but the server seems to ignore it.

**Comment by agentzh** [comment]
This is indeed a regression. I've disabled the CDN cache for now. Will fix the cache key later. Thank you all for the report!

**Comment by iseckkeller** [comment]
Thank you.  I'm back to working now.  Appreciate the quick turn around.
