### ISSUE TITLE
Provide builtin support for streaming media download speed limiting

### ISSUE THREAD

**Issue by chenzx** [openresty/openresty#276]
The use scene is：

We have a wireless box for accessing streaming music, and it uses 3G/4G connection or WiFi.
Maybe its CPU is not very high-performance,
When the music download speed reaches 1MB/s, the CPU seems too high, and UI(browser kernel with gstreamer) stucks.
Normally if the music download is below 100KB/s, then everything is ok.

So, i guess if nginx can provide builtin support for stream download speed limiting?

I know openresty is used on CDN maily for its high IO performance, but in 3G/4G wireless, if the speed is too high, that means if user is surveying streaming media, he will consume a lot of bytes IO, which will waste a lot of money, since 3G/4G cost is very high....

**Comment by chenzx** [comment]
Sorry, i just found that, Nginx/OpenResty seems to have already support stream speed limit:

http://wiki.jikexueyuan.com/project/openresty-best-practice/lua-limit.html

**Comment by agentzh** [comment]
Consider it resolved.
