### ISSUE TITLE
How can i do a script-controlled file download in OpenResty? i can do it easily in Node.js/Express

### ISSUE THREAD

**Issue by chenzx** [openresty/openresty#277]
How can i do a script-controlled file download in OpenResty? i can do it easily in Node.js/Express.
I'm a newer of OpenResty, but I've found that there isn't any ebook about OpenResty, or any Quick Start guide, or any sample code in distribution.

There are 3 requirements a web server need to meet to do a script-controlled file download：
（1）Url route/query arguments mapping
（2）Basic database access(assume it's mysql, because i think XAMPP on Windows is very convenient, :-) )
（3）script-controlled file download （Usually Apache or Nginx both require to configure local file system path mapping with url path, but that's not very flexible)

The sample code in Node.js/Express:

```
app.get("/cdn/staticfiles/mp3/:songId", function(req, res){
    var songId = req.params.songId;
    pool.query({
        sql: "SELECT absPath FROM `music_info` WHERE id=?",
        timeout: 40*1000,
        values: [songId]
    },
    function(err, results, fields){
        if(err){
            res.status(500).send(err);
            return;
        }
        if(results.length==0){
            res.status(404).send("music with songId "+songId+" not found!");
            return;
        }
        var absPath = results[0].absPath.toString('utf8');
        var dirname = parsePath(absPath).dirname
        var filename = parsePath(absPath).base
        var serve = serveStatic(dirname, options);
        req.url = filename
        serve(req, res, finalhandler(req, res))
    });
})
```

**Comment by agentzh** [comment]
@chenzx You can find many resources on the openresty.org web site, including tutorials, demo web applications, and ebook chapters.

Your JS example can be easily rewritten with rewrite_by_lua*, lua-resty-mysql (or pgmoon for Pg), and ngx.req.set_uri() without using any ugly callback functions.

BTW, please join the openresty-en mailing list for such general usage questions. This place is reserved for real bug reports and patch submissions. Thanks for
your cooperation! Please see https://openresty.org/en/community.html

**Comment by chenzx** [comment]
@agentzh I've read your tutorial ePub book, there are 2 ways to do static files in nginx:

1.  Use ngx_static module, with location & root directives set
2. Use try_files to try multiple dir prefixes

But they are both not flexible. With NodeJS/express's serve-static middleware, I can serve any static file in local file system.

& Also, I have not find the url route mechanism in Nginx or OpenResty, they can be done with manual uri parsing by rewrite_by_lua directive, but the code will be too nasty.

**Comment by chenzx** [comment]
PS: I'm not a Nginx/OpenResty programmer currently, because I'm not doling the web backend work.

I'm just interested in using OpenResty as a scripting/test web server tool.
