### ISSUE TITLE
proxy_cache file post-process with openresty / lua ?

### ISSUE THREAD

**Issue by hohmd** [openresty/openresty#280]
Hello.

Is there any way to post-process an image file which were just cached using proxy_cache in OpenResty / Lua?

Use case:

do bash command (jpegtran) on JPEG cached file

**Comment by agentzh** [comment]
@hohmd No, the standard `ngx_proxy` module does not provide a hook for it and you have to patch the nginx core. Additionally, launching an external shell command requires forking the current nginx worker and will block the current whole process horribly and ruin your openresty's performance.
