### ISSUE TITLE
Broken symlinks when building 1.11.2.4

### ISSUE THREAD

**Issue by polm** [openresty/openresty#281]
I'm trying to build from the OpenResty 1.11.2.4 source bundle on OpenSUSE 13.2 and having trouble.

I run `./configure` with no options and get this error:

    ./configure: error: ngx_http_lua_module requires the Lua or LuaJIT library and LUAJIT_LIB is defined as ...[removed]... and LUAJIT_INC (path for lua.h) ...[removed]..., but we cannot find LuaJIT there.

Checking the `LUAJIT_LIB` path mentioned above I find two broken symlinks:

```
me@myhost:~/code/openresty-1.11.2.4/build/luajit-root/usr/local/openresty/luajit/lib> ls -l                       
total 8                                                                                                                  
lrwxrwxrwx 1 me me   22 Jul 31 19:12 libluajit-5.1.so -> libluajit-5.1.so.2.1.0
lrwxrwxrwx 1 me me   22 Jul 31 19:12 libluajit-5.1.so.2 -> libluajit-5.1.so.2.1.0
drwxr-xr-x 3 me me 4096 Jul 31 19:12 lua
drwxr-xr-x 2 me me 4096 Jul 31 19:12 pkgconfig
```

Using `find` I was able to determine the destination files for the symlinks don't exist anywhere in the directory with the OpenResty bundle.

I tried this with 1.11.2.3 too but had the same error. 

I found a `libluajit.so` file here (relative to the build directory):

    ./build/LuaJIT-2.1-20170405/src/libluajit.so

But copying it to the file pointed to by the symlinks didn't fix anything.

Is there something wrong with my setup, or is this a bug? 

If there's anything I can add please let me know.

**Comment by agentzh** [comment]
@polm This is strange. Maybe you forgot to install the ldconfig utility in your system? Try

```
which ldconfig
```

To debug this problem, we need the following info:

1. the complete shell command history on your side.
2. the complete output of each command you run when building OpenResty.
3. the full content of the file `build/nginx-1.11.2/objs/autoconf.err` in the openresty-1.11.2.4 source directory after the build fails.

Thanks!

BTW, we do have plans to provide official OpenResty pre-built package repositories for OpenSUSE.

**Comment by polm** [comment]
[configure.out.txt](https://github.com/openresty/openresty/files/1189388/configure.out.txt)
[autoconf.err.txt](https://github.com/openresty/openresty/files/1189389/autoconf.err.txt)

`ldconfig` is installed, but it was not in the default `PATH`. The installer told me that so I added `/sbin/` to my path for the install process. After doing that:

    > which ldconfig                                                               
    /sbin/ldconfig  

Shell history is just this:

    export PATH="$PATH":/sbin
    tar xvzf openresty-1.11.2.4.tar.gz 
    cd openresty-1.11.2.4/
    ./configure

`configure.out` is the output of that. There are also some errors in `autoconf.err`.

**Comment by agentzh** [comment]
@polm Hmm, seems like the `install` script in your system is not doing what it is supposed to do. Will you check what is your `install` command in PATH? Maybe you have something nonstandard in PATH?

**Comment by polm** [comment]
Oh, you're right! I had some weird install in my path instead of the standard one. Fixing my path and running it again worked.

Sorry for the false alarm, please feel free to close this.
