### ISSUE TITLE
about nginx 1.13.3

### ISSUE THREAD

**Issue by stspqxl** [openresty/openresty#282]
/etc/init.d/openresty:

nginx="/sbin/nginx"
prog=$(basename $nginx)
pidfile=/usr/local/openresty/nginx/logs/nginx.pid
NGINX_CONF_FILE="/etc/nginx/nginx.conf"

systemctl start openresty.sercice

No response

but nginx started

**Comment by stspqxl** [comment]
nginx.conf:


user  nginx;
worker_processes  1;

error_log  off;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    #access_log  off;
# log_format  main  '$server_name | $remote_addr | $time_local | $request | $uri | $status | "$http_user_agent" | $http_x_forwarded_for | $upstream_addr | $upstream_response_time | $upstream_status | $request_time';

#log_format  main  '$server_name | $remote_addr | $time_local | $request | $uri | $status | "$http_user_agent" | $http_x_forwarded_for';

log_format main '{"server_name":"$server_name","user_proxy_ip":"$http_x_real_ip","lan_ip":"$remote_addr","log_time":"$time_iso8601","user_req":"$request","http_code":"$status","req_time":"$request_time","user_ua":"$http_user_agent","full_url":"$scheme://$server_name$request_uri"}';

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /home/nginx/*.conf;
}
stream {
      upstream mysqltest{
      server 120.25.95.199:23306 weight=1;
      #check interval=3000 rise=2 fall=5 timeout=1000;
      }
      server {
      listen 23306;
      proxy_pass mysqltest;
       }
}

**Comment by stspqxl** [comment]
cp /sbin/nginx /usr/local/openresty/nginx/sbin/nginx

use nginx 1.13.3 to replace nginx openresty/1.11.2.4

/etc/init.d/openresty start
Starting openresty (via systemctl):  

stoped like this,but nginx started

**Comment by spacewander** [comment]
Maybe your `$nginx` is incorrect.
 
The SysVinit script you posted is quite different from the one from the official package.
rpm: https://github.com/openresty/openresty-packaging/blob/master/rpm/SOURCES/openresty.init
deb: https://github.com/openresty/openresty-packaging/blob/master/deb/openresty/debian/openresty.init
If you want to write your own one, please refer to them.

**Comment by stspqxl** [comment]
nginx已经启动，但是systemctl start openresty.service 执行后就卡住了。
系统是 centos 7，openresty是yum 安装的。如果用自带的nginx版本就启动正常，如果把 1.13.3的nginx文件替换nginx/sbin/nginx文件，就卡在这里，恢复原来文件启动正常。

**Comment by spacewander** [comment]
@stspqxl 
The `/etc/init.d/openresty` you posted is different from the one shipped by the yum package.
Have you modified it?

I suggest you to ask the question in the OpenResty Chinese mailing list:
https://groups.google.com/group/openresty

And you should use some measurable details instead of "卡在这里".

**Comment by agentzh** [comment]
@stspqxl OpenResty does not support nginx 1.13.x yet. Do not hack your own way. We won't support your hacks.
