### ISSUE TITLE
As the program running time increases, CPU usage is also increasing

### ISSUE THREAD

**Issue by fc13240** [openresty/openresty#283]
I use Yum install openresty, the program is to request third party resources with lua-resty-http, then edit the contents returned by the third party and return to the client. As the program running time increases, the usage of CPU is also increasing. With strace monitoring, mainly munmap, mremap consumption. Httpc timeout is set to 60s, and no reason has been found yet. After the progam runed 10 hours, the cpu usage is to 90%.

my enviroment:
via `openresty -V`:
nginx version: openresty/1.11.2.4
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 
built with OpenSSL 1.0.2k  26 Jan 2017
TLS SNI support enabled

uname -a:
Linux 2.6.32-696.6.3.el6.centos.plus.x86_64 #1 SMP Thu Jul 13 14:24:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by agentzh** [comment]
@fc13240 See the following page on how to profile and optimize your OpenResty apps:

http://openresty.org/en/profiling.html

Also, performance issues in 3rd-party Lua libraries should be reported to the authors of those Lua libraries instead unless you have enough evidences to suspect it is OpenResty at fault.

**Comment by fc13240** [comment]
the sample bt svg:
<img width="1201" alt="2017-08-07 10 13 15" src="https://user-images.githubusercontent.com/5786628/29010338-2cce4ddc-7b5d-11e7-902b-c3feff691140.png">



the sample bt on/off cpu svg:

<img width="1201" alt="2017-08-07 10 40 03" src="https://user-images.githubusercontent.com/5786628/29010344-3c166c5c-7b5d-11e7-852f-563b7f854f35.png">

**Comment by agentzh** [comment]
@fc13240 Apparently you are doing too many Lua string concatenation operations in either your own Lua code or the lua-resty-http library. Either way, it's your responsibility to reduce that. You can sample a Lua-land on-CPU flame graph to pinpoint the source of such Lua string concatenations. Anyway, it's not OpenResty at fault at all. I'm closing this.
