### ISSUE TITLE
MSYS环境下编译失败

### ISSUE THREAD

**Issue by Corson011** [openresty/openresty#284]
我在msys下编译openresty出现以下的问题，就到这里就不动了，停住了，不知道是什么原因，但该环境下单独编译nginx是可以的，请赐教，谢谢！
![qq 20170807115014](https://user-images.githubusercontent.com/12711733/29013368-31f23fa4-7b75-11e7-8b27-d6f0f80ad843.jpg)

**Comment by agentzh** [comment]
@Corson011 Please, no Chinese here. This place is considered English only. If you really
want to use Chinese, please join the openresty (Chinese) mailing list instead.
Please see https://openresty.org/en/community.html Thanks for your cooperation.

BTW, regarding to you may want to take a look at these:

https://openresty.org/en/download.html#win32

https://github.com/openresty/openresty/blob/master/doc/README-win32.md#readme

**Comment by Corson011** [comment]
I really sorry about that, I will pay attention to later. Thank you for your answer. It worked when I removed the compile paramater '-j$cores' in ‘make -j$cores ...’

**Comment by Corson011** [comment]
@agentzh I really sorry about that, I will pay attention to later. Thank you for your answer. It worked when I removed the compile paramater '-j$cores' in ‘make -j$cores ...’
