### ISSUE TITLE
Issue with LuaJIT version used for last stable OpenResty release

### ISSUE THREAD

**Issue by nilnor** [openresty/openresty#285]
I tried to upgrade our OpenResty version from openresty-1.9.15.1 to openresty-1.11.2.4, which unfortunately failed since [ljsyscall](https://github.com/justincormack/ljsyscall) stopped working. Troubleshooting this I discovered that the reason for this is that the LuaJIT version bundled with this release (LuaJIT-2.1-20170405) appears to report the 64-bit ABI flag incorrectly (false instead of true). The last tagged version from the bundle LJ repo does not appear to have this issue. As it is the last released version is not usable for us, and others might potentially have issues as well.

Quick test script for verification:

```lua
local ffi = require "ffi"
local is64 = ffi.abi("64bit")
local is32 = ffi.abi("32bit")
print("is64: " .. tostring(is64))
print("is32: " .. tostring(is32))
```

[nilnor@cohen:/usr/local/openresty-1.11.2.4]% ./luajit/bin/luajit /tmp/test.lua 
is64: false
is32: false

**Comment by agentzh** [comment]
@nilnor This is a known regression. Will you try out the latest OpenResty 1.11.2.5rc1 release below?

https://groups.google.com/d/msg/openresty-en/Mw5B11AQwqM/qY5MltXmAgAJ
