### ISSUE TITLE
Illegal instruction, configure SSE test passes.

### ISSUE THREAD

**Issue by soverysour** [openresty/openresty#287]
I used the latest source release from the openresty website, openresty-1.11.2.4.tar.gz   4.0MB   11 July 2017.

Output of `uname -a` is: `Linux machine 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux` (Linux mint 18.2)

The problem is that the `./configure` test for msse 4.2 passes when it shouldn't, so `Illegal instruction` warnings are all the binaries get me. Commenting out the `if / else` test regarding sse4.2 in the configure script, letting just the `else` error message print solves this. (commenting out lines 641-646 and 648, aka no `-msse4.2` flag. Used gcc)

**Comment by spacewander** [comment]
@soverysour 
Could you run `gcc -march=native -dM -E - < /dev/null | grep SSE` and `cat /proc/cpuinfo` in your environment?

**Comment by soverysour** [comment]
Output of `gcc -march=native -dM -E - < /dev/null | grep SSE`:
```
#define __SSE2_MATH__ 1
#define __SSE_MATH__ 1
#define __SSE2__ 1
#define __SSE__ 1
#define __SSE3__ 1
```

Output of `cat /proc/cpuinfo`:
```
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 15
model		: 76
model name	: Mobile AMD Sempron(tm) Processor 3500+
stepping	: 2
cpu MHz		: 800.000
cache size	: 512 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 1
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow rep_good nopl extd_apicid pni cx16 lahf_lm extapic cr8_legacy 3dnowprefetch vmmcall
bugs		: fxsave_leak sysret_ss_attrs null_seg swapgs_fence amd_e400
bogomips	: 1596.05
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management: ts fid vid ttp tm stc
```

**Comment by agentzh** [comment]
@soverysour Your CPU lacks SSE 4.2 support and OpenResty 1.11.2.4 (and 1.11.2.3) has a bug in its SSE 4.2 detection.

You can try the latest OpenResty 1.11.2.5 release's source tarball instead:

https://openresty.org/en/download.html

**Comment by agentzh** [comment]
@soverysour Or better, find a box with SSE 4.2 CPU support. Performance can be miserable in special cases on CPUs lacking SSE 4.2.
