### ISSUE TITLE
can not find configure file

### ISSUE THREAD

**Issue by HakChealKim** [openresty/openresty#289]
if i use mac homebrew install all things, 
i use the ./configure but it cannot work ;
and then , i checked the file theres no configure file,

1.i need download a configure file?
2.configure file is a file in some other directory?

**Comment by kuhippo** [comment]
Make sure you have
PATH=/usr/local/opt/openresty/nginx/sbin:$PATH
export PATH

**Comment by agentzh** [comment]
@HakChealKim The `./configure` script is only meant for being used by those want to compile openresty manually from source code. You do not need that for automatic installations via homebrew and other means. I'm closing this.

**Comment by HakChealKim** [comment]
OK，tks
