### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rpatelob** [openresty/openresty#292]
Trying to install "openresty-1.11.2.5.tar.gz"

`src/event/ngx_event_openssl.c: In function ‘ngx_ssl_connection_error’:
 src/event/ngx_event_openssl.c:2048:21: error: ‘SSL_R_NO_CIPHERS_PASSED’ undeclared (first use in 
 this function)
             || n == SSL_R_NO_CIPHERS_PASSED`

Openssl version in my pc is 
`OpenSSL 1.0.2l  25 May 2017`

make command gives an error.

**Comment by agentzh** [comment]
@rpatelob Are you sure you're using the right openssl's C headers?

**Comment by rpatelob** [comment]
@agentzh I don't understand. I tried to install openresty and it showed me this error. So I updated openssl's version but still same error. Is there anything i missed?

**Comment by agentzh** [comment]
@rpatelob I guess your build does not really use the openssl header files you think you are using. You should use `./configure --with-cc-opt="-I/path/to/openssl/include" --with-ld-opt="-L/path/to/openssl/lib -Wl,-rpath,/path/to/openssl/lib` to be sure. Or better, just use the pre-built OpenResty packages on openresty.org.

**Comment by agentzh** [comment]
@rpatelob BTW, you can try the `./configure` option `--with-luajit-xcflags='-mno-sse4.2'` to disable SSE 4.2 in a box *with* SSE 4.2 support. That can help you "cross-compile".
