### ISSUE TITLE
Not support log_format name [escape=default|json]

### ISSUE THREAD

**Issue by anjia0532** [openresty/openresty#294]
openresty
```bash
sudo apt-get -y install libreadline-dev libncurses5-dev libpcre3-dev  libssl-dev perl make build-essential

wget https://openresty.org/download/openresty-1.11.2.5.tar.gz

tar zxf openresty-1.11.2.5.tar.gz

cd openresty-1.11.2.5

./configure --prefix=/tmp/openresty -j4

make -j4 && make install

cd /tmp/openresty

vi nginx/conf/nginx.conf

# add log_format name escape=json

cat nginx/conf/nginx.conf| grep 'json_log'
    log_format json_log escape=json '{"ip":"$remote_addr","@timestamp":"$time_iso8601","host":"$http_host","request":"$request","req_body":"$request_body","status":"$status","size":$body_bytes_sent,"ua":"$http_user_agent","cookie":"$http_cookie","req_time":"$request_time","uri":"$uri","referer":"$http_referer","ups_status":"$upstream_status","ups_addr":"$upstream_addr","ups_time":"$upstream_response_time"}';
    access_log  logs/access.log  json_log;

sudo bin/openresty -t && sudo bin/openresty

curl http://localhost/

cat nginx/logs/access.log 
escape=json{"ip":"172.60.30.14","@timestamp":"2017-08-30T15:23:48+08:00","host":"172.60.30.128","request":"GET / HTTP/1.1","req_body":"-","status":"200","size":562,"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3198.0 Safari/537.36","cookie":"-","req_time":"0.000","uri":"/index.html","referer":"-","ups_status":"-","ups_addr":"-","ups_time":"-"}

```
nginx's doc [Module ngx_http_log_module](http://nginx.org/en/docs/http/ngx_http_log_module.html)

>Syntax:  log_format name [escape=default\|json] string ...; 
>log_format: combined "...";
>content: http

> The escape parameter (1.11.8) allows setting json or default characters escaping in variables, by default, default escaping is used.

escape param since nginx v1.11.8, openresty1.11.2.5 supports nginx 1.13.3+([openresty's twitter](https://twitter.com/OpenResty/status/901547620564221952))

nginx
```bash

wget http://nginx.org/download/nginx-1.13.4.tar.gz

tar zxf nginx-1.13.4.tar.gz

cd nginx-1.13.4

./configure --prefix=/tmp/nginx

make -j4 && make install

cd /tmp/nginx

vi conf/nginx.conf

# add log_format name escape=json

cat conf/nginx.conf| grep 'json_log'
    log_format json_log escape=json '{"ip":"$remote_addr","@timestamp":"$time_iso8601","host":"$http_host","request":"$request","req_body":"$request_body","status":"$status","size":$body_bytes_sent,"ua":"$http_user_agent","cookie":"$http_cookie","req_time":"$request_time","uri":"$uri","referer":"$http_referer","ups_status":"$upstream_status","ups_addr":"$upstream_addr","ups_time":"$upstream_response_time"}';
    access_log  logs/access.log  json_log;

sudo sbin/nginx -t && sudo sbin/nginx

curl http://localhost/

cat logs/access.log  
{"ip":"127.0.0.1","@timestamp":"2017-08-30T15:31:53+08:00","host":"localhost","request":"GET / HTTP/1.1","req_body":"","status":"200","size":612,"ua":"curl/7.47.0","cookie":"","req_time":"0.000","uri":"/index.html","referer":"","ups_status":"","ups_addr":"","ups_time":""}
```

fix nginx  access_log has hex chars write to logstash(elk) failed parse json log.

[stackoverflow#nginx logging $request_body as hexidecimal](https://stackoverflow.com/a/45229274/7001350)

**Comment by agentzh** [comment]
@anjia0532 The nginx docs you referenced above clearly indicates that the json formater was first added to nginx 1.11.8. The OpenResty 1.11.2.5 you are using bundles nginx 1.11.2 (the first 3 numbers in OpenResty's version numbers), which obviously does not have it.

The next OpenResty release will be based on nignx 1.13.x, which will definitely bring this feature in.

**Comment by anjia0532** [comment]
@agentzh sorry about this issues, I thought it was using nginx 1.13.3 `OpenResty's ngx_stream_lua_module now supports nginx 1.13.3+`(ref ([openresty's twitter](https://twitter.com/OpenResty/status/901547620564221952))

Because openresty's doc does not specify this matter. 

```bash
openresty -v
nginx version: openresty/1.11.2.5
```

**Comment by agentzh** [comment]
@anjia0532 You can always get the nginx core version from openresty's version numbers, as officially documented here:

http://openresty.org/en/faq.html

**Comment by anjia0532** [comment]
@agentzh Thank you for your patient reply.   :  )
