### ISSUE TITLE
could not be resolved (3: Host not found)

### ISSUE THREAD

**Issue by Macrame** [openresty/openresty#298]
Thanks for your library first. 
I know that someone reported this "issue" which was not an issue in fact. Today, I tried to resolve this problem but failed.
I had deployed two _service_ in kubernetes.  One is named weedfs-master and another is named feedfs-volume. Those two pod were built from [seaweedfs](https://github.com/chrislusf/seaweedfs). I also built an image based centos 7 and installing **openresty** and **GraphicsMagick**. Let's call it file-server app.
In the file-server, I write upload.lua to handle the file posted by users.
```
function process_upload()
  local weed_master_url = ngx.var.weed_master
  local http = require "resty.http"
  local hc = http.new()
  hc:set_timeout(3000)
  local res, err = hc:request_uri(
    weed_master_url,
    {
      method = 'GET',
      path = '/dir/assign',
      headers = {
        ["Content-Type"] = "application/json"
      }

    })
  if not res then
    ngx.say("failed to request:", err, "<br/>")
    return
  end
  local code = res.status
  ......
end
```
The variable **weed_master** was set to "http://weedfs-master:9333".
I have specified the resolver to 10.0.6.200 in nginx.conf:
```
http {
    ...
    lua_package_path "/usr/local/openresty/lualib/?.lua;;";
    resolver 10.0.6.200;
    server {
        listen       80;
        ...
        location /upload {
          resolver 10.0.6.200;
          default_type "application/json";
          content_by_lua_file conf/upload.lua;
        }
        ...
    }
}
```
Kubernetes provide a component named [kube-dns](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns) which can be used as a DNS server to resolve all the _service_ in the kubernetes cluster. I can see weedfs-master was resolve correctly.

```
#nslookup weedfs-master
Server:		10.0.6.200
Address:	10.0.6.200#53

Name:	weedfs-master.xxxxxx.svc.cluster.local
Address: 10.0.6.102
```

But the hostname could not be resolved  in the lua script: **failed to request:weedfs-master could not be resolved (3: Host not found)<br/>**.
It worked if I set **weed_master** to "http://10.0.6.102:9333".
Would you like to help me about this error? Thank a lot.

**Comment by agentzh** [comment]
@Macrame How do you configure the `resolver` directive in your `nginx.conf`. NGINX's own resolver does not respect `/etc/resolv.conf` file but its own `resolver` directive. See

http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver

**Comment by Macrame** [comment]
@agentzh  Thank you for your reply. I have specified the resolver to 10.0.6.200 in nginx.conf:
```
http {
    ...
    lua_package_path "/usr/local/openresty/lualib/?.lua;;";
    resolver 10.0.6.200;
    server {
        listen       80;
        ...
        location /upload {
          resolver 10.0.6.200;
          default_type "application/json";
          content_by_lua_file conf/upload.lua;
        }
        ...
    }
}
```

**Comment by agentzh** [comment]
@Macrame You can always enable the nginx debugging logs to see the details of the resolver. We also provided the `openresty-debug` pre-built package for this:

https://openresty.org/en/linux-packages.html

Also, it's always a good idea to add `ipv6=off` to the resolver directive when your dns server may return IPv6 addresses and your network does not support it.

**Comment by agentzh** [comment]
@Macrame You need to use `debug` level in your `error_log` directive as well.

**Comment by agentzh** [comment]
@Macrame BTW, what do you get if you run the following command?

```
dig @10.0.6.200 weedfs-master.xxxxxx.svc.cluster.local
```

If dig also cannot get the result, then you shouldn't expect nginx's resolver can.

**Comment by Macrame** [comment]
@agentzh Thank you very much. I tried to use dig and found that there is a little different between the kube-dns and a real named server.
```
dig @10.0.6.200 weedfs-master

; <<>> DiG 9.9.4-RedHat-9.9.4-50.el7_3.1 <<>> @10.0.6.200 weedfs-master
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 31755
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;weedfs-master.			IN	A

;; Query time: 0 msec
;; SERVER: 10.0.6.200#53(10.0.6.200)
;; WHEN: Mon Sep 11 13:37:22 HKT 2017
;; MSG SIZE  rcvd: 42
```
The true address is weedfs-master._xxx_.svc.cluster.local (here, the _xxx_ is my namespace used in kubernetes)
```
dig @10.0.6.200 weedfs-master.xxx.svc.cluster.local

; <<>> DiG 9.9.4-RedHat-9.9.4-50.el7_3.1 <<>> @10.0.6.200 weedfs-master.xxx.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50013
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;weedfs-master.xxx.svc.cluster.local. IN A

;; ANSWER SECTION:
weedfs-master.xxx.svc.cluster.local. 30 IN	A 10.0.6.55

;; Query time: 1 msec
;; SERVER: 10.0.6.200#53(10.0.6.200)
;; WHEN: Mon Sep 11 13:42:14 HKT 2017
;; MSG SIZE  rcvd: 74
```
At last, I used weedfs-master._xxx_.svc.cluster.local in the nginx.conf and it worked nice although I didn't know why the nslookup can resolve the hostname but dig can't. Thanks again!

**Comment by Macrame** [comment]
@agentzh By the way, I found that other apps can connect any service using the service name except the lua script running as content_by_lua_file. It is important that the proxy section can also work for the short service name. Example:
```
location ~ /\d+,.*{
            if ($request_method = 'DELETE' ) {
                return 405;
            }
            if ($request_method = 'PUT' ) {
                return 405;
            }
            proxy_pass http://weedfs-volume$uri;
}
```
Just lua script can resolve the service name.
