### ISSUE TITLE
ngx_openresty-1.10.24 does not build under OSX

### ISSUE THREAD

**Issue by onyxraven** [openresty/openresty#3]
When linking the final objs/nginx, 

Undefined symbols for architecture x86_64:
  "_pcre_free_study", referenced from:
      _ngx_http_lua_ngx_re_match in ngx_http_lua_regex.o
      _ngx_http_lua_ngx_re_gmatch in ngx_http_lua_regex.o
      _ngx_http_lua_ngx_re_sub_helper in ngx_http_lua_regex.o
      _ngx_http_lua_cleanup_pcre_study_data in ngx_http_lua_regex.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
make[2]: **\* [objs/nginx] Error 1

this was configured with a plain './configure' line.

**Comment by Paxa** [comment]
Seems like same error in nginx itself
http://trac.nginx.org/nginx/ticket/94
Reason is it takes headers from `/usr/local/include/`, dylib from `/usr/lib`

**Comment by agentzh** [comment]
Please read the official documentation for instructions of installing OpenResty on Mac OS X:

http://openresty.org/#Installation

Essentially, it's as simple as

```
brew install pcre
./configure \
             --with-cc-opt="-I/usr/local/include" \
             --with-ld-opt="-L/usr/local/lib" \
             -j4
make -j4
sudo make install
```

where we assume that your system has 4 spare CPU cores.

Good luck!

**Comment by grasses** [comment]
I have installed pcre, and configure command is:

> sudo ./configure --with-openssl=bundle/openssl --with-cc-opt="-I/usr/local/Cellar/pcre/8.37/include" --with-ld-opt="-L/usr/local/Cellar/pcre/8.37/lib"

still return error:

![](http://785igi.com1.z0.glb.clouddn.com/private/Screen%20Shot%202015-07-10%20at%2011.15.13%20AM.png)

meanwhile it has a warning:

WARNING! If you wish to build 64-bit library, then you have to
         invoke './Configure darwin64-x86_64-cc' *manually*.
         You have about 5 seconds to press Ctrl-C to abort.

**Comment by grasses** [comment]
then I let nginx build the PCRE source, 
> sudo ./configure --with-openssl=bundle/openssl --with-pcre=bundle/pcre-8.37

return same error.
so sad.

**Comment by agentzh** [comment]
@grasses A quick google search found this solution:

http://forum.nginx.org/read.php?2,256012,256064#msg-256064

**Comment by agentzh** [comment]
@grasses I've tested on my macbook (Mac OS X 10.10.4) the work-around works:

```bash
export KERNEL_BITS=64
./configure --with-cc-opt='-I/usr/local/Cellar/pcre/8.37/include/' \
       --with-ld-opt='-L/usr/local/Cellar/pcre/8.37/lib' \
       --with-openssl=$HOME/work/openssl-1.0.2d -j9
make -j9
sudo make install
```

BTW, only use `sudo` when `make install` otherwise the environments may change.

**Comment by agentzh** [comment]
@grasses It seems that this is a known issue with recent versions of OpenSSL on Mac OS X. And it only happens when you try to use the `--with-openssl=PATH` option to build OpenSSL from source directly via NGINX's build system (yes, it's not specific to OpenResty, but a general NGINX issue).

I'll incorporate the work-around directly into OpenResty's build system so that the users will no longer have to worry about the details.

Thanks for the report!

**Comment by grasses** [comment]
@agentzh 
It works now!! thanks !!

**Comment by agentzh** [comment]
@grasses Glad it works for you now. You're welcome :)

**Comment by Bingnan** [comment]
Check pcre and openssl path by "brew info pcre" and "brew info openssl";

then according to the result, specify the path for both of them in configure command:

./configure  --with-cc-opt="-I/usr/local/Cellar/pcre/8.37/include -I/usr/local/opt/openssl/include" --with-ld-opt="-L/usr/local/Cellar/pcre/8.37/lib -L/usr/local/opt/openssl/lib"

**Comment by bsyk** [comment]
I had to 
```export MACOSX_DEPLOYMENT_TARGET=10.9```
to get the configure script to use the right versions of the libraries.

From the LuaJit project installation [page](http://luajit.org/install.html) :
> Note for OSX: if the MACOSX_DEPLOYMENT_TARGET environment variable is not set, then it's forced to 10.4.

**Comment by agentzh** [comment]
@bsyk Thanks for the info. Maybe we should set the environment automatically in OpenResty's build system.

**Comment by agentzh** [comment]
@bsyk Fixed in git master.

**Comment by lavenkin** [comment]
when I insert ./configure 
-bash: ./configure: No such file or directory

**Comment by agentzh** [comment]
@lavenkin Seems like you are in the wrong current working directory. Try the following commands:

```bash
brew install pcre
wget https://openresty.org/download/ngx_openresty-1.9.7.1rc2.tar.gz
tar -xvf ngx_openresty-1.9.7.1rc2.tar.gz
cd ngx_openresty-1.9.7.1rc2/
./configure --with-cc-opt="-I/usr/local/include" --with-ld-opt="-L/usr/local/lib" -j5
make -j5
sudo make install
```

**Comment by c9n** [comment]
``` bash
./configure --with-cc-opt="-I/usr/local/include" --with-ld-opt="-L/usr/local/lib" --with-openssl=/usr/local/Cellar/openssl/1.0.2e -j5

make
```

output:

```
cd /Users/Lynn/Desktop/ngx_openresty-1.9.7.1/build/LuaJIT-2.1-20151219 && /Applications/Xcode.app/Contents/Developer/usr/bin/make TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/openresty/luajit
==== Building LuaJIT 2.1.0-beta1 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
make[2]: Nothing to be done for `default'.
==== Successfully built LuaJIT 2.1.0-beta1 ====
cd /Users/Lynn/Desktop/ngx_openresty-1.9.7.1/build/lua-cjson-2.1.0.3 && /Applications/Xcode.app/Contents/Developer/usr/bin/make DESTDIR= LUA_INCLUDE_DIR=/Users/Lynn/Desktop/ngx_openresty-1.9.7.1/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 LUA_CMODULE_DIR=/usr/local/openresty/lualib LUA_MODULE_DIR=/usr/local/openresty/lualib CJSON_CFLAGS="-g -fpic" CJSON_LDFLAGS='-bundle -undefined dynamic_lookup' CC=cc
cc -c -O3 -Wall -pedantic -DNDEBUG  -I/Users/Lynn/Desktop/ngx_openresty-1.9.7.1/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 -g -fpic -o lua_cjson.o lua_cjson.c
cc -c -O3 -Wall -pedantic -DNDEBUG  -I/Users/Lynn/Desktop/ngx_openresty-1.9.7.1/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 -g -fpic -o strbuf.o strbuf.c
cc -c -O3 -Wall -pedantic -DNDEBUG  -I/Users/Lynn/Desktop/ngx_openresty-1.9.7.1/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 -g -fpic -o fpconv.o fpconv.c
cc  -bundle -undefined dynamic_lookup -o cjson.so lua_cjson.o strbuf.o fpconv.o
cd /Users/Lynn/Desktop/ngx_openresty-1.9.7.1/build/lua-redis-parser-0.12 && /Applications/Xcode.app/Contents/Developer/usr/bin/make DESTDIR= LUA_INCLUDE_DIR=/Users/Lynn/Desktop/ngx_openresty-1.9.7.1/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 LUA_LIB_DIR=/usr/local/openresty/lualib LDFLAGS='-bundle -undefined dynamic_lookup' CC=cc
cc -c -g -O -Wall -fpic -I/Users/Lynn/Desktop/ngx_openresty-1.9.7.1/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1   -o redis-parser.o redis-parser.c
cc -bundle -undefined dynamic_lookup -o parser.so redis-parser.o
cd /Users/Lynn/Desktop/ngx_openresty-1.9.7.1/build/lua-rds-parser-0.06 && /Applications/Xcode.app/Contents/Developer/usr/bin/make DESTDIR= LUA_INCLUDE_DIR=/Users/Lynn/Desktop/ngx_openresty-1.9.7.1/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 LUA_LIB_DIR=/usr/local/openresty/lualib LDFLAGS='-bundle -undefined dynamic_lookup' CC=cc
cc -c -g -O -Wall -fpic -I/Users/Lynn/Desktop/ngx_openresty-1.9.7.1/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1   -o src/rds_parser.o src/rds_parser.c
cc -bundle -undefined dynamic_lookup -o parser.so src/rds_parser.o
cd /Users/Lynn/Desktop/ngx_openresty-1.9.7.1/build/nginx-1.9.7 && /Applications/Xcode.app/Contents/Developer/usr/bin/make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f objs/Makefile
cd /usr/local/Cellar/openssl/1.0.2e \
    && if [ -f Makefile ]; then /Applications/Xcode.app/Contents/Developer/usr/bin/make clean; fi \
    && ./config --prefix=/usr/local/Cellar/openssl/1.0.2e/.openssl no-shared  \
    && /Applications/Xcode.app/Contents/Developer/usr/bin/make \
    && /Applications/Xcode.app/Contents/Developer/usr/bin/make install LIBDIR=lib
/bin/sh: ./config: No such file or directory
make[2]: *** [/usr/local/Cellar/openssl/1.0.2e/.openssl/include/openssl/ssl.h] Error 127
make[1]: *** [build] Error 2
make: *** [all] Error 2
```

**Comment by wynelu** [comment]
I'm using OX EI Capitan 10.11.2,  use brew install openssl and pcre, then configure generate error, then using brew link --force openssl(don't know it helps), then compile specify path like follows..

./configure  --with-cc-opt='-I/usr/local/Cellar/pcre/8.38/include/ -I/usr/local/Cellar/openssl/1.0.2e_1/include/' --with-ld-opt='-L/usr/local/Cellar/pcre/8.38/lib -L/usr/local/Cellar/openssl/1.0.2e_1/lib' -j2

then make works fine. 
just record this to some newers like me.

**Comment by bungle** [comment]
@wynelu, I use brew and:
--with-cc-opt="-I/usr/local/include -I/usr/local/opt/openssl/include"
--with-ld-opt="-L/usr/local/lib -L/usr/local/opt/openssl/lib"

**Comment by lavenkin** [comment]
@agentzh, Yes It works!

**Comment by LittleShrimp1987** [comment]
$: ln -s /usr/local/Cellar/pcre/8.38 /usr/local/opt/pcre
works for me
