### ISSUE TITLE
您好，关于动态配置nginx.conf中的location 正则表达式

### ISSUE THREAD

**Issue by damon-93** [openresty/openresty#303]
你好，首先非常感谢您贡献的openresty
最近在工作i遇到一个问题，我们想要有选择的去缓存文件的类型，比如有时只想要缓存gif;或者只想缓存jpg.
于是我在nginx.conf中这样设置，想法是在lua中动态设置$proxy_rule
set $proxy_rule  "/";
 location $proxy_rule {
      XXXXXXX
}
但是这样配置是错误的，location 应该是将“$proxy_rule”以正则方式解析了，而并没先将$proxy_rule值取出，然后进行location的正则解析。。。

以上，还往多多指导

**Comment by agentzh** [comment]
@damon-93 Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.
