### ISSUE TITLE
proxy_cache_background_update not supported?

### ISSUE THREAD

**Issue by lavie** [openresty/openresty#305]
I get the following error when trying to use `proxy_cache_background_update` with openresty:

```
nginx: [emerg] unknown directive "proxy_cache_background_update" in /usr/local/openresty/nginx/conf/nginx.conf: 35
```

Here is my `nginx.conf`:

```
events {
    worker_connections  14096;
}

http {
    access_log off;
    proxy_cache_path /data levels=1:2 keys_zone=zuul:10m max_size=10g;
    proxy_http_version 1.1;
    resolver 127.0.0.1;
    upstream zuul {
        server 127.0.0.1:9666;
    }
    server {
        location / {
            proxy_cache zuul;
            proxy_pass http://zuul;
            proxy_cache_use_stale updating;
            proxy_cache_background_update on;
        }
        listen 0.0.0.0:80 default_server;
    }
}

```

Openresty version:

> $ nginx -V
> nginx version: openresty/1.11.2.5
> built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
> built with OpenSSL 1.0.2k  26 Jan 2017
> TLS SNI support enabled
> configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.06 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.10 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.32 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.18 --add-module=../redis2-nginx-module-0.14 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-nginx-module-0.07 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-openssl=/tmp/openssl-1.0.2k --with-pcre=/tmp/pcre-8.40 --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module=dynamic --with-ipv6 --with-mail --with-mail_ssl_module --with-md5-asm --with-pcre-jit --with-sha1-asm --with-stream --with-stream_ssl_module --with-threads

If it matters, the upstream server is just a hello-world Node.js process.

**Comment by spacewander** [comment]
`proxy_cache_background_update` is added since Nginx 1.11.10.
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_background_update
But OpenResty 1.11.2.5 is based on Nginx 1.11.2.

**Comment by lavie** [comment]
Oh, I see! Thanks.
Is there a newer version of openresty that includes this feature?
In general, how can I tell which version of openresty is based on which nginx version?
If not, is it possible to rebuild openresty with an upped nginx version?

**Comment by agentzh** [comment]
@lavie Yes, a new OpenResty based on nginx 1.13.6+ will be out soon.

**Comment by lavie** [comment]
@agentzh fantastic!
Are we talking soon like a few weeks? If you think it might take longer, please let me know, so I can work around the background update issue for now.

**Comment by agentzh** [comment]
@lavie Yes, should be in a few weeks.

**Comment by agentzh** [comment]
OpenResty 1.13.6.1 RC1 was already a few days ago. Closing this.

**Comment by lavie** [comment]
@agentzh nice! Where can I find it, though? I don't see anything in Releases or a tag...

**Comment by agentzh** [comment]
@lavie New releases are always announced in the openresty-en mailing list. See

https://groups.google.com/d/msg/openresty-en/pVPxLB5jfl4/QOnUnXntBgAJ
