### ISSUE TITLE
ngx_http_lua_headers.c  occured "incompatible types" when compiled nginx-1.12.2

### ISSUE THREAD

**Issue by yaoboxu** [openresty/openresty#310]
when i want to add nginx-lua module into nginx,  i hava sucessed configure nginx, and then make nginx,  it occured follow error:

# /usr/local/lua-nginx-module-0.10.2/src/ngx_http_lua_headers.c: In function ‘ngx_http_lua_ngx_req_raw_header’:
/usr/local/lua-nginx-module-0.10.2/src/ngx_http_lua_headers.c:145: error: incompatible types when assigning to type ‘struct ngx_buf_t *’ from type ‘ngx_chain_t’
/usr/local/lua-nginx-module-0.10.2/src/ngx_http_lua_headers.c:221: error: incompatible types when assigning to type ‘struct ngx_buf_t *’ from type ‘ngx_chain_t’
make[1]: *** [objs/addon/src/ngx_http_lua_headers.o] Error 1
make[1]: Leaving directory `/usr/local/nginx-1.12.2'

**Comment by spacewander** [comment]
@yaoboxu 
The ngx_lua module you used is too old. You should upgrade to a newer one.
https://github.com/openresty/lua-nginx-module/releases

**Comment by agentzh** [comment]
Consider it resolved.
