### ISSUE TITLE
Unable to install on CentOS

### ISSUE THREAD

**Issue by ferdinandocarella** [openresty/openresty#312]
I installed the required repo `https://openresty.org/package/centos/openresty.repo`

But when I try to install Openresty I get this message:

`https://openresty.org/package/centos/latest/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`

I guess this is because the directory under `https://openresty.org/package/centos/` should contain a link `latest` pointing to the latest version directory.

I temporarily fixed by manually changing the repo file.

**Comment by agentzh** [comment]
@ferdinandocarella This is strange. What version of CentOS are you using? I've never seen this on CentOS 6.9 or CentOS 7.3 myself. It's weird that the `$releasever` variable is taking the "latest" value on your side (I've only seen this on Amazon Linux).

**Comment by ferdinandocarella** [comment]
That's correct, it's on Amazon Linux.

**Comment by agentzh** [comment]
@ferdinandocarella Then you should use our Amazon Linux package repo instead:

https://openresty.org/en/linux-packages.html#amazon-linux

**Comment by agentzh** [comment]
Amazon Linux is not CentOS, BTW.
