### ISSUE TITLE
: systemctl status openresty command creates warning message that service has changed on disk

### ISSUE THREAD

**Issue by psabhar** [openresty/openresty#313]
When we run systemctl command to check status of openresty we see warning message telling openresty.service has changed and it ask to run systemctl daemon-reload. 
Is this warning message valid because I dont see any change in file content and file size.

When systemctl status openresty command is issued, the following is expected:
[ systemctl status openresty
● openresty.service - SYSV: OpenResty is a scalable web platform by extending
  Loaded: loaded (/etc/rc.d/init.d/openresty; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-10-03 12:31:49 UTC; 1 weeks 1 days ago
     Docs: man:systemd-sysv-generator(8)
  Process: 7503 ExecStop=/etc/rc.d/init.d/openresty stop (code=exited, status=0/SUCCESS)
  Process: 7720 ExecStart=/etc/rc.d/init.d/openresty start (code=exited, status=0/SUCCESS)
Main PID: 7740 (nginx)
   CGroup: /system.slice/openresty.service
           ├─7740 nginx: master process /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/ngin...
           ├─7750 nginx: worker process
           ├─7751 nginx: worker process
           └─7752 nginx: worker process
Warning: openresty.service changed on disk. Run 'systemctl daemon-reload' to reload units.

**Comment by agentzh** [comment]
@psabhar Maybe systemctl simply checks the file modification timestamps. Not sure. Such warning is usually harmless.
