### ISSUE TITLE
openresty-1.13.6.1 bug,Double http request....

### ISSUE THREAD

**Issue by smarttang** [openresty/openresty#314]
- [ ] The exact version of the related software, including but not limited to the OpenResty version
(if any), the NGINX core version, the `ngx_lua` module version(via `openresty -V` or `nginx -V`),
and your operating system version(via `uname -a`).

nginx -v:
`
[root@localhost sbin]# ./nginx -v
nginx version: openresty/1.13.6.1

`
uname -a:
`
Linux localhost.localdomain 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
`

- [ ] **A minimal and standalone test case** that others can easily run on their side and
reproduce the issue you are seeing.

In /usr/local/openresty/nginx/conf/nginx.conf  for " http " insert :

![image](https://user-images.githubusercontent.com/4961402/33227769-2d9ab692-d170-11e7-8e0e-3acacd5c94dc.png)

and request for test website for openresty server.

![image](https://user-images.githubusercontent.com/4961402/33227774-5d44f588-d170-11e7-85cf-1b65a0480413.png)

user one request but openresty double request.

save log code:
`
function ngxLog(itype,msg)
  local logName = os.date("%Y%m%d", os.time())
  local file = assert(io.open(NGX_LUA_LOG_DIR.."/"..logName..".log","ab"))
  local time = os.date("%Y-%m-%d %H:%M:%S", os.time())
  file:write(time.." [msg]".."["..itype.."]"..msg.."\r\n")
  file:flush()
  file:close()
end
`

- [ ] Do not simply say "something is broken" or "something does not work". Always provide
as much details as possible. Always describe **the symptoms and your expected results**.

I think normal requests should not be requested twice, so I think this is a flaw, but not sure if it is OPENRESTY flaw or code issue.

**Comment by spacewander** [comment]
@smarttang 
> user one request but openresty double request.

How do you send the request? Have you captured the packets to see how many requests sent to OpenResty?

**Comment by smarttang** [comment]
@spacewander 

Simple Curl http request;
![image](https://user-images.githubusercontent.com/4961402/33228426-f9185030-d180-11e7-80de-042a4bae1773.png)

**Comment by agentzh** [comment]
@smarttang Such things are usually due to the internal redirects during the processing of a single request, in which case your `access_by_lua*` (and etc) might run multiple times (each time in different location, or the same location for different internal redirects).

The only way to be sure is to check out the nginx debugging logs for the guilty request. Your config above is far from complete to be conclusive.

**Comment by agentzh** [comment]
@smarttang For your sample request `/` above, it indeed initiates an internal redirect to the `/index.html` page triggered by the standard `ngx_index` module:

http://nginx.org/en/docs/http/ngx_http_index_module.html#index

You can check the current request URI, via `ngx.var.uri`, inside your `access_by_lua*` handler, for example.

**Comment by smarttang** [comment]
This problem is not the case, I wrote the code and pictures are very clear,
And redirect does not matter, I have tested the online environment, only this version of the problem.

**Comment by smarttang** [comment]
这就尴尬了，我这在生产环境上测试过原生版Nginx和旧的openresty都ok，特地测试一个新的openresty就出问题，然后提交这个ISSUES，你还给我关了。。。尴尬。。

This embarrassed, I tested in the production environment native version of Nginx and the old openresty are ok, specifically to test a new openresty problems, and then submit the ISSUES, you shut me back. . . awkward. .

**Comment by smarttang** [comment]
➜  ~ curl http://10.211.55.4 -v
* Rebuilt URL to: http://10.211.55.4/
*   Trying 10.211.55.4...
* TCP_NODELAY set
* Connected to 10.211.55.4 (10.211.55.4) port 80 (#0)
> GET / HTTP/1.1
> Host: 10.211.55.4
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sat, 25 Nov 2017 08:37:02 GMT
< Content-Type: text/plain
< Content-Length: 562
< Last-Modified: Fri, 24 Nov 2017 15:48:16 GMT
< Connection: keep-alive
< Fingerprint: ZhiLianWaf
< Server: ZhaopinServer
< ETag: "5a183f40-232"
< Accept-Ranges: bytes
< 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to OpenResty!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to OpenResty!</h1>
<p>If you see this page, the OpenResty web platform is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="https://openresty.org/">openresty.org</a>.<br/></p>

<p><em>Thank you for flying OpenResty.</em></p>
</body>
</html>
* Connection #0 to host 10.211.55.4 left intact

**Comment by spacewander** [comment]
@smarttang 
Could you [enable the debug log](http://nginx.org/en/docs/debugging_log.html), and send the result to the OpenResty (Chinese) mailing list: https://groups.google.com/group/openresty?
It will be great if you also show us the debug log output in normal case.

**Comment by smarttang** [comment]
@spacewander 
thx。i think this version maybe have a bug..
On last version is ok, this version is not work...

**Comment by agentzh** [comment]
@smarttang Apparently you were not really reading my comments but simply keep saying you know everything clearly and it must be a bug in OpenResty. This is not helpful. When you access `/`, it MUST initiate an internal redirect to `/index.html` otherwise you won't be able to see the index page at all. And I already told you that internal redirect MUST enters another location or the same location again for the same client request, thus making your `access_by_lua*` hook run twice.

**Comment by agentzh** [comment]
@smarttang I closed this issue since I was (still am) certain that it MUST be the internal redirect in play here. So it's definitely not a bug in OpenResty or NGINX.

**Comment by agentzh** [comment]
@smarttang Note that "internal redirects" are completely different from HTTP redirects like 301 and 302. You might want to read my nginx tutorials to learn such basics first otherwise you might not understand what I'm saying:

http://openresty.org/en/ebooks.html

**Comment by agentzh** [comment]
@smarttang BTW, you can always use the `ngx.req.is_internal()` Lua API to skip processing requests initiated from internal redirects inside your `access_by_lua*` or `rewrite_by_lua*` Lua handlers. See

https://github.com/openresty/lua-nginx-module/#ngxreqis_internal

**Comment by agentzh** [comment]
@smarttang I've already given you so many suggestions on trouble-shooting and resolving your problem. Please read them and do it.

**Comment by smarttang** [comment]
@agentzh 
First of all, I am very grateful to the author, but also to my dear friends.
First of all, I did not think the author you are right, 302 or 301 redirect may indeed exist this problem, but I have not tried any changes in the configuration, I installed the default openresty-1.13.6.1.tar.gz Have this problem. In the reverse version, openresty-1.11.2.3.tar.gz the same configuration, note: "the same configuration" does not exist in the problem.
So, in a production environment, I returned a version of openresty-1.11.2.3.tar.gz.
I have no objection to what you are saying, and it is also possible that my configuration difference caused the problem to exist, and I accept it alright, although I have not altered any of the configs with the default (nginx.conf).


However, it does not matter, the problem is solved by downgrading,
Thank the author. :)

中文版：
首先，非常感谢作者，也感谢热心的朋友。
其次，我没有认为作者您说得不对，302或者301的重定向确实有可能存在这个问题，但是我并没有尝试过任何的改动配置，我是默认安装了 openresty-1.13.6.1.tar.gz  后才有了这个问题。在倒退版本后，openresty-1.11.2.3.tar.gz 同样的配置下，注意：“同样的配置下”却不存在该问题。
所以，在生产环境下，我退回了openresty-1.11.2.3.tar.gz的版本。
我不反对您说的，也有可能是我配置的不同导致该问题存在，我坦然接受，虽然我没有改动任何的配置，用默认的(nginx.conf).


不过，不重要了，问题通过降级解决了，
感谢作者。：）

**Comment by smarttang** [comment]
@agentzh 

@smarttang BTW, you can always use the ngx.req.is_internal() Lua API to skip processing requests initiated from internal redirects inside your access_by_lua* or rewrite_by_lua* Lua handlers. See

Thanks, I study ~

**Comment by vulntor** [comment]
> @agentzh
> 
> @smarttang BTW, you can always use the ngx.req.is_internal() Lua API to skip processing requests initiated from internal redirects inside your access_by_lua* or rewrite_by_lua* Lua handlers. See
> 
> Thanks, I study ~



> @agentzh
> First of all, I am very grateful to the author, but also to my dear friends.
> First of all, I did not think the author you are right, 302 or 301 redirect may indeed exist this problem, but I have not tried any changes in the configuration, I installed the default openresty-1.13.6.1.tar.gz Have this problem. In the reverse version, openresty-1.11.2.3.tar.gz the same configuration, note: "the same configuration" does not exist in the problem.
> So, in a production environment, I returned a version of openresty-1.11.2.3.tar.gz.
> I have no objection to what you are saying, and it is also possible that my configuration difference caused the problem to exist, and I accept it alright, although I have not altered any of the configs with the default (nginx.conf).
> 
> However, it does not matter, the problem is solved by downgrading,
> Thank the author. :)
> 
> 中文版：
> 首先，非常感谢作者，也感谢热心的朋友。
> 其次，我没有认为作者您说得不对，302或者301的重定向确实有可能存在这个问题，但是我并没有尝试过任何的改动配置，我是默认安装了 openresty-1.13.6.1.tar.gz 后才有了这个问题。在倒退版本后，openresty-1.11.2.3.tar.gz 同样的配置下，注意：“同样的配置下”却不存在该问题。
> 所以，在生产环境下，我退回了openresty-1.11.2.3.tar.gz的版本。
> 我不反对您说的，也有可能是我配置的不同导致该问题存在，我坦然接受，虽然我没有改动任何的配置，用默认的(nginx.conf).
> 
> 不过，不重要了，问题通过降级解决了，
> 感谢作者。：）

老哥，人家说的是内部重定向，不是301这种。。访问/会重定向到index.html 就出现了两次请求。
 我这边也出这个问题，调试代码的时候出错响应500的时候就出现两次请求，因为重定向到了500的错误页面。

so it must be internal redirects。
