### ISSUE TITLE
404 Error while reverse proxying to SSL upstream servers

### ISSUE THREAD

**Issue by Himanshu4** [openresty/openresty#315]
I am using openresty where I am trying to set up nginx as a reverse proxy to an https server.
env PROFILE;

http {
server {
        listen 80 default_server;

        server_name _;

        set_by_lua_block $profile { return os.getenv("PROFILE") }

        location /fg_analytics {
    	    internal;
    	    
    	    resolver 8.8.8.8;
    	    resolver_timeout 5s;
            proxy_pass https://analytics-$profile/fg/api/v3/feature;
            proxy_ignore_client_abort on;
            proxy_read_timeout 50s;
            proxy_connect_timeout 50s;
      		proxy_http_version 1.1;
      		proxy_set_header Host $http_host;
      		# Remove the Connection header if the client sends it,
            # it could be "close" to close a keepalive connection
            proxy_set_header Connection "";
      		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      		proxy_set_header X_FORWARDED_PROTO https;
      		proxy_ssl_session_reuse off;
    	}

upstream analytics-test {
        server p13n-qa.adobe.io:443;
    }

}

Basic Lua code:

ngx.location.capture("/fg_analytics", { method = ngx.HTTP_POST, body = some body })

I am getting the following error:

status = 404 headers = {"Content-Length":564,"Content-Type":"text\/html"} body = <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

If I change the upstream server to some http server listening on a port say 8080, it works fine. Is proxy pass does not work with https?? 

I am not sure whether this is the right place to log this bug, but any help would be really appreciated.

nginx version: openresty/1.9.7.3

**Comment by spacewander** [comment]
@Himanshu4 
Could you enable the debug log to show us the internal behaviors with http proxy and https proxy?
See http://nginx.org/en/docs/debugging_log.html for how to enable the debug log.

**Comment by Himanshu4** [comment]
My bad! This was a configuration issue.

**Comment by nishantrayan** [comment]
@Himanshu4 I am seeing the same. can you share which part of the configuration was the culprit

**Comment by Himanshu4** [comment]
@nishantrayan : My host header was getting set incorrectly and the ALB was redirecting the traffic based on host header. That's why, 404. Setting the correct host header fixes the issue.
