### ISSUE TITLE
Date & time an hour ago

### ISSUE THREAD

**Issue by onlynishant** [openresty/openresty#318]
Hi,

I want date and hour for -1 hour (date & time an hour ago). e.g. 

2017-12-07 06:47:58   => 2017-12-07 05
2017-12-01 00:47:58   => 2017-11-30 23

Basically I want equivalent of 
```
$ date -d'now-1 hour' '+%Y-%m-%d %H'
2017-12-07 05
```

**Comment by RocFang** [comment]
Hi
you can simply use
``` 
os.date("%Y-%m-%d %H", ngx.time()-3600)
```
