### ISSUE TITLE
Install openresty error in centos7 with error SSE 4.2 not found 

### ISSUE THREAD

**Issue by xlingit** [openresty/openresty#319]
# ./configure
platform: linux (linux)
cp -rp bundle/ build
cd build
cd LuaJIT-2.1-20171103
/tmp/resty-config-C4glu7.c: In function ‘main’:
/tmp/resty-config-C4glu7.c:4:5: error: #error SSE 4.2 not found
 #   error SSE 4.2 not found
     ^
WARNING: -msse4.2 not supported in cc.
gmake TARGET_STRIP=@: CCDEBUG=-g XCFLAGS='-DLUAJIT_ENABLE_LUA52COMPAT' CC=cc PREFIX=/usr/local/openresty/luajit

**Comment by xlingit** [comment]
version is openresty-1.13.6.1

**Comment by xlingit** [comment]
old cpu

**Comment by xlingit** [comment]
old cpu

**Comment by khaiphan9x** [comment]
No one cares about this error, but the installation and use of openresty is not affected
