### ISSUE TITLE
attempt to call method 'expire' (a nil value)

### ISSUE THREAD

**Issue by abeljinming** [openresty/openresty#322]
I met the issue: attempt to call method 'expire' (a nil value), the codes below, can anyone help?

		local dict_captcha_access_times = ngx.shared.dict_captcha_access_times
		local newval, err, forcible = dict_captcha_access_times:incr(clientIP, 1, 0)
		if newval == 1 then
			dict_captcha_access_times:expire(clientIP, 10)
		else
			if newval > 5 then
				dict_captcha_black_list:set(clientIP, 1, 30)
				ngx.exit(403)
			end
		end

**Comment by agentzh** [comment]
@abeljinming You should try the latest OpenResty version. Your version must be too hold to have it.

**Comment by abeljinming** [comment]
Many thanks for reply!
The version I am using is: nginx version: openresty/1.13.6.1, is it right?

**Comment by agentzh** [comment]
@abeljinming OK, seems like you forgot to add `require "resty.core.shdict"` or `require "resty.core"` to your `init_by_lua*` handler. To quickly test it:

```
$ resty --shdict 'dogs 1m' -e 'require "resty.core.shdict" dogs = ngx.shared.dogs dogs:set("Tom", 3) print(dogs:expire("Tom", 32))'
true
```

**Comment by abeljinming** [comment]
Yes, I forgot "require resty.core", Many thanks!

BTW, as there is no way to add expired key when using "incr" method, so I have to write below codes:
	if newval == 1 then
		dict_captcha_access_times:expire(clientIP, 10)
	else
Consider the concurrent situation, are the codes right?

**Comment by agentzh** [comment]
@abeljinming It looks good to me as long as there is no one else deletes or decrements the key.
