### ISSUE TITLE
openresty-1.13.6.1  configure

### ISSUE THREAD

**Issue by hy05190134** [openresty/openresty#334]
I find Nginx's configure have "--with-stream_ssl_preread_module" options when openresty's configure have no options when I click "--help", but I find it also can work when I click "--with-stream_ssl_preread_module" and compile successful

**Comment by hy05190134** [comment]
but I find the module doesn't take effect

**Comment by agentzh** [comment]
@hy05190134 OpenResty's `configure` script simply passes any options it does not know directly to the underlying nginx core's `./configure` script. So even though it does not appear in OpenResty's `./configure --help`, it should still work (and also for any nginx's future options).

I agree we should still add this option to OpenResty's configure script's help text. Addressed in the latest master branch.
