### ISSUE TITLE
why the script run by resty and luajit goes differently?

### ISSUE THREAD

**Issue by prime89** [openresty/openresty#335]
Here is my code
```lua
    local c = openssl.cms.read(indata, 'pem')
    local r = openssl.cms.verify(c, 'verify', {cert}, castore, nil, out)
    
    if r then
        print('verified successfully')
    end
```

but the output run by resy and luajit is diffrent
output:
```bash
[portal@ecs-5c2a-0008 userlib]$ /opt/app/openresty/bin/resty test.lua 
0.7.1Lua 5.1OpenSSL 1.0.2k  26 Jan 2017
[portal@ecs-5c2a-0008 userlib]$ /opt/app/openresty/luajit/bin/luajit test.lua 
0.7.1	Lua 5.1	OpenSSL 1.0.2k  26 Jan 2017
verified successfully
```

begging for help~

**Comment by spacewander** [comment]
We could not answer your question because we don't know what `openssl.cms.xxx` means.
Have you checked the error returned from these `openssl.cms.xxx` methods? Maybe the error message could tell you something useful.

**Comment by prime89** [comment]
@spacewander thanks for your reply
I compiled openresty with `--with-cc-opt` instead of `--with-openssl`. it works.

the `test.lua` is:
```lua
local auth = require('auth.main')
auth.login()
```
run test.lua by resty 
```
[portal@ecs-5c2a-0008 userlib]$ /opt/app/openresty/bin/resty test.lua
0.7.1Lua 5.1OpenSSL 1.0.2n  7 Dec 2017
true
verified successfully

```

and luajit
```
[portal@ecs-5c2a-0008 userlib]$ /opt/app/openresty/luajit/bin/luajit test.lua
0.7.1	Lua 5.1	OpenSSL 1.0.2n  7 Dec 2017
true
verified successfully
```

but when exec this scripts by nginx，it doesn't work again.
my nginx config is:
```conf
location ^~  /login {
    content_by_lua_block {
	    local auth = require "auth.main"
            auth.login();
    }
}
```

**Comment by spacewander** [comment]
@prime89 
> We could not answer your question because we don't know what `openssl.cms.xxx` means.
They are not the part of OpenResty.

Your further explanation doesn't tell us what `openssl.cms.xxx` is.
And now I am more confused with the `require "auth.main"`. What is the `auth.main`?

If you consider this is a bug in OpenResty, please submit a minimal reproduce case, so that we are able to reproduce it.

BTW, have you ever checked the error message from the blahblah module? It is neccessary to check the error message first if something doesn't work as expected.

**Comment by prime89** [comment]
Sorry, it has been resolved.
Thanks anyway

**Comment by prime89** [comment]
Sorry, it has been resolved.
Thanks anyway
