### ISSUE TITLE
simpl/ngx_devel_kit has become simplresty/ngx_devel_kit

### ISSUE THREAD

**Issue by giacomini** [openresty/openresty#336]
The `ngx_devel_kit` module is now located at https://github.com/simplresty/ngx_devel_kit (see https://github.com/simplresty/ngx_devel_kit/commit/e90019294c7eda6c5484586a7943bfb800936b14) . This breaks the `util/mirror-tarballs` script at https://github.com/openresty/openresty/blob/master/util/mirror-tarballs#L448, which should become
```
mv simplresty-ngx_devel_kit-* ngx_devel_kit-$ver || exit 1
```

**Comment by spacewander** [comment]
@giacomini 
Would you like to submit a patch to us?
Remember to update `simpl/ngx_devel_kit` to `simplresty/ngx_devel_kit` in the download link as well.
Thanks!

**Comment by giacomini** [comment]
I've changed the download link as well, although in fact it was working correctly, since github redirected to the new project.

As a test, I generated the bundle, built and installed the executable and checked that nginx started properly. Let me know if there is anything else I can do.
