### ISSUE TITLE
对于Openresty防御CC攻击有没有什么比较不错的方案？

### ISSUE THREAD

**Issue by onesez** [openresty/openresty#338]
特别是在使用CDN之后，有没有什么比较优秀的方案？

**Comment by agentzh** [comment]
@onesez Please, no Chinese here. This place is considered English only. If you really
want to use Chinese, please join the openresty (Chinese) mailing list instead.
Please see https://openresty.org/en/community.html Thanks for your cooperation.

Also, this place is reserved for bug reports and patch submissions.

Regarding your question, you may find the lua-resty-limit-traffic library useful (it's already included in OpenResty).
