### ISSUE TITLE
Amazon Linux Yum Repo returns 404

### ISSUE THREAD

**Issue by brunodomenici** [openresty/openresty#346]
Hi,

I'm trying to install OpenResty using https://openresty.org/en/linux-packages.html but it's returning 404 

https://openresty.org/package/amazon/2017.09/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

Thank you

**Comment by brunodomenici** [comment]
Checking now, maybe Amazon Linux release 2017.09 it's not supported by OpenResty, right?

**Comment by agentzh** [comment]
@brunodomenici Interesting. Amazon Linux used to use the value `latest` for the yum variable `$releasever`, but now it changes it to the real release version, `2017.09`. I just created a symlink `2017.09` to point to `latest`. Please try it out again.

A quick test on my side seems to work fine:

```
$ curl -I https://openresty.org/package/amazon/2017.09/x86_64/repodata/repomd.xml
HTTP/1.1 200 OK
Server: openresty+
Date: Wed, 14 Feb 2018 19:53:02 GMT
Content-Type: text/xml; charset=utf-8
Content-Length: 2988
Connection: keep-alive
Last-Modified: Mon, 13 Nov 2017 06:42:50 GMT
...
```

**Comment by vincent-lu** [comment]
Having the same problem as above.

**Comment by vincent-lu** [comment]
Thanks it works now.

BTW for anyone who has trouble getting this installed in the future (e.g. future Amazon Linux version), potentially you can change the releasever to latest to get openresty installed (obviously not idea, @agentzh maybe you can let us know if it is safe at all):

```
yum-config-manager --save --setopt=releasever=latest #switch yum releasever to latest
yum update -y #update
yum install openresty -y #install openresty from latest
yum-config-manager --save --setopt=releasever=2018.03 #switch yum releasever back to 2018.03 (assuming that's your current releasever)
yum-config-manager --save --setopt=openresty.skip_if_unavailable=True #so yum doesn't complain about missing repo
```

**Comment by agentzh** [comment]
@vincent-lu Yes, it should.

**Comment by agentzh** [comment]
@vincent-lu Just for the openresty yum repo, BTW, not globally.

**Comment by pramodbhn** [comment]
@agentzh FYI

Similar issue on Amazon Linux 2
_sudo yum install openresty_

https://openresty.org/package/amazon/2/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
failure: repodata/repomd.xml from openresty: [Errno 256] No more mirrors to try.
https://openresty.org/package/amazon/2/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found


I was able to install by editing the repository url to https://openresty.org/package/amazon/latest/x86_64/repodata/repomd.xml
