### ISSUE TITLE
Openresty build issue

### ISSUE THREAD

**Issue by FireBurn** [openresty/openresty#347]
It looks like Openresty is expecting simpl-ngx_devel_kit-* but downloads ngx_devel_kit-0.3.0.tar.gz

This was working before

+ make
./util/mirror-tarballs
openresty 1.13.6.1

--2018-02-20 12:12:24--  https://openresty.org/download/nginx-1.13.6.tar.gz
Resolving openresty.org (openresty.org)... 178.62.102.153
Connecting to openresty.org (openresty.org)|178.62.102.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1029603 (1005K) [application/x-gzip]
Saving to: ���nginx-1.13.6.tar.gz���

     0K .......... .......... .......... .......... ..........  4% 1.67M 1s
    50K .......... .......... .......... .......... ..........  9% 2.17M 0s
   100K .......... .......... .......... .......... .......... 14%  135M 0s
   150K .......... .......... .......... .......... .......... 19%  156M 0s
   200K .......... .......... .......... .......... .......... 24% 2.14M 0s
   250K .......... .......... .......... .......... .......... 29%  301M 0s
   300K .......... .......... .......... .......... .......... 34%  276M 0s
   350K .......... .......... .......... .......... .......... 39% 2.67M 0s
   400K .......... .......... .......... .......... .......... 44% 11.6M 0s
   450K .......... .......... .......... .......... .......... 49%  331M 0s
   500K .......... .......... .......... .......... .......... 54%  220M 0s
   550K .......... .......... .......... .......... .......... 59%  164M 0s
   600K .......... .......... .......... .......... .......... 64%  328M 0s
   650K .......... .......... .......... .......... .......... 69%  345M 0s
   700K .......... .......... .......... .......... .......... 74%  346M 0s
   750K .......... .......... .......... .......... .......... 79% 2.78M 0s
   800K .......... .......... .......... .......... .......... 84% 12.1M 0s
   850K .......... .......... .......... .......... .......... 89%  211M 0s
   900K .......... .......... .......... .......... .......... 94%  307M 0s
   950K .......... .......... .......... .......... .......... 99%  306M 0s
  1000K .....                                                 100% 10436G=0.1s

2018-02-20 12:12:25 (8.10 MB/s) - ���nginx-1.13.6.tar.gz��� saved [1029603/1029603]

[33m[INFO][0m applying the stream_balancer_export patch for nginx
patching file src/stream/ngx_stream_upstream_round_robin.c
patching file src/stream/ngx_stream_upstream_round_robin.h

[33m[INFO][0m applying the stream_proxy_get_next_upstream_tries patch for nginx
patching file src/stream/ngx_stream.h
patching file src/stream/ngx_stream_proxy_module.c
Hunk #1 succeeded at 2164 (offset 8 lines).

[33m[INFO][0m applying the stream_proxy_timeout_fields patch for nginx
patching file src/stream/ngx_stream.h
patching file src/stream/ngx_stream_proxy_module.c
Hunk #12 succeeded at 1476 (offset 4 lines).
Hunk #13 succeeded at 1670 (offset 4 lines).

[33m[INFO][0m applying the balancer_status_code patch
patching file src/http/ngx_http_upstream.c
Hunk #1 succeeded at 1515 (offset 147 lines).
patching file src/http/ngx_http_upstream.h
Hunk #1 succeeded at 426 (offset 8 lines).

[33m[INFO][0m applying the builtin_error_page_footer patch
patching file src/http/ngx_http_special_response.c
Hunk #1 succeeded at 33 (offset 7 lines).

[33m[INFO][0m applying the delayed-posted-events patch
patching file src/event/ngx_event.c
patching file src/event/ngx_event_posted.c
patching file src/event/ngx_event_posted.h

[33m[INFO][0m applying the privileged-agent-process patch
patching file src/core/nginx.c
Hunk #1 succeeded at 1026 with fuzz 2 (offset 45 lines).
Hunk #2 succeeded at 1056 with fuzz 2 (offset 46 lines).
patching file src/core/ngx_cycle.h
Hunk #2 succeeded at 89 with fuzz 1 (offset 5 lines).
patching file src/os/unix/ngx_process_cycle.c
Hunk #9 succeeded at 861 (offset -3 lines).
Hunk #10 succeeded at 1182 with fuzz 1 (offset -2 lines).
patching file src/os/unix/ngx_process_cycle.h

[33m[INFO][0m applying the single-process-graceful-exit patch
patching file src/os/unix/ngx_process_cycle.c
Hunk #1 succeeded at 313 (offset 9 lines).
Hunk #2 succeeded at 343 (offset 9 lines).

[33m[INFO][0m applying the intercept-error-log patch
patching file src/core/ngx_cycle.h
Hunk #1 succeeded at 25 with fuzz 1 (offset 3 lines).
Hunk #2 succeeded at 88 (offset 8 lines).
patching file src/core/ngx_log.c

[33m[INFO][0m applying the upstream-pipelining patch for nginx
patching file src/http/ngx_http_upstream.c
Hunk #1 succeeded at 2161 (offset 158 lines).

[33m[INFO][0m applying the server_header patch for nginx
patching file src/core/nginx.h
patching file src/http/ngx_http_header_filter_module.c
patching file src/http/v2/ngx_http_v2_filter_module.c
Hunk #1 succeeded at 144 (offset 1 line).

[33m[INFO][0m applying the no_error_pages patch for nginx
patching file src/http/ngx_http_core_module.c

[33m[INFO][0m applying the no_Werror patch for nginx
patching file auto/cc/clang
Hunk #1 succeeded at 88 with fuzz 1 (offset -1 lines).
patching file auto/cc/gcc
Hunk #1 succeeded at 166 (offset -2 lines).
patching file auto/cc/icc
Hunk #1 succeeded at 111 (offset -4 lines).

[33m[INFO][0m applying the log_escape_non_ascii patch for nginx
patching file src/http/modules/ngx_http_log_module.c

[33m[INFO][0m applying the dtrace patch for nginx
patching file README
patching file auto/install
patching file auto/make
patching file auto/modules
patching file auto/options
Hunk #3 succeeded at 196 (offset 1 line).
Hunk #4 succeeded at 350 (offset 2 lines).
Hunk #5 succeeded at 423 (offset 2 lines).
Hunk #6 succeeded at 583 (offset 3 lines).
Hunk #7 succeeded at 603 (offset 3 lines).
patching file auto/os/darwin
patching file auto/os/freebsd
patching file auto/os/linux
patching file auto/sources
patching file auto/summary
patching file configure
patching file src/core/ngx_core_probe.h
patching file src/core/ngx_palloc.c
patching file src/dtrace/nginx.stp
patching file src/dtrace/nginx_provider.d
patching file src/dtrace/stap-nginx
patching file src/event/ngx_event_probe.h
patching file src/event/ngx_event_timer.c
patching file src/event/ngx_event_timer.h
patching file src/http/ngx_http.c
patching file src/http/ngx_http_core_module.c
Hunk #2 succeeded at 2233 (offset -216 lines).
Hunk #3 succeeded at 2383 (offset -216 lines).
patching file src/http/ngx_http_probe.h
patching file src/http/ngx_http_request.c
patching file src/http/ngx_http_request_body.c

[33m[INFO][0m applying patches/nginx-1.13.6-gcc-maybe-uninitialized-warning.patch for nginx
patching file src/http/ngx_http_request.c
Hunk #1 succeeded at 2050 with fuzz 2 (offset 99 lines).

[33m[INFO][0m applying the proxy_host_port_vars patch for nginx 1.13.6
patching file src/http/modules/ngx_http_proxy_module.c
Hunk #1 succeeded at 809 (offset 16 lines).

[33m[INFO][0m applying the cache_manager_exit patch for nginx 1.13.6
patching file src/os/unix/ngx_process_cycle.c
Hunk #1 succeeded at 1196 (offset -139 lines).

[33m[INFO][0m applying the larger_max_error_str patch for nginx 1.13.6
patching file src/core/ngx_log.h
Hunk #1 succeeded at 73 (offset 9 lines).

[33m[INFO][0m applying the pcre_conf_opt patch for nginx 1.13.6
patching file auto/options
Hunk #1 succeeded at 356 (offset 70 lines).
Hunk #2 succeeded at 569 with fuzz 1 (offset 127 lines).

[33m[INFO][0m applying the always_enable_cc_feature_tests patch to nginx
patching file auto/cc/conf
Hunk #1 succeeded at 144 (offset 8 lines).

[33m[INFO][0m applying the ssl_cert_cb_yield.patch patch to nginx
patching file src/event/ngx_event_openssl.c
Hunk #1 succeeded at 1347 (offset 137 lines).

[33m[INFO][0m applying the ssl_pending_session.patch patch to nginx
patching file src/event/ngx_event_openssl.c
Hunk #1 succeeded at 1348 (offset 41 lines).

[33m[INFO][0m applying the upstream_timeout_fields patch for nginx
patching file src/http/ngx_http_upstream.c
Hunk #2 succeeded at 1617 (offset 20 lines).
Hunk #3 succeeded at 1693 (offset 20 lines).
Hunk #4 succeeded at 1987 (offset 20 lines).
Hunk #5 succeeded at 2030 (offset 20 lines).
Hunk #6 succeeded at 2856 (offset 49 lines).
Hunk #7 succeeded at 3187 (offset 51 lines).
Hunk #8 succeeded at 3425 (offset 51 lines).
Hunk #9 succeeded at 3437 (offset 51 lines).
Hunk #10 succeeded at 3631 (offset 51 lines).
patching file src/http/ngx_http_upstream.h

[33m[INFO][0m applying the safe_resolver_ipv6_option patch for nginx
patching file src/core/ngx_resolver.c
Hunk #1 succeeded at 227 (offset 3 lines).
Hunk #2 succeeded at 252 (offset 3 lines).

--2018-02-20 12:12:25--  https://github.com/openresty/echo-nginx-module/tarball/v0.61
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/openresty/echo-nginx-module/legacy.tar.gz/v0.61 [following]
--2018-02-20 12:12:26--  https://codeload.github.com/openresty/echo-nginx-module/legacy.tar.gz/v0.61
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ���echo-nginx-module-0.61.tar.gz���

     0K .......... .......... .......... .......... ..........  153K
    50K .                                                      23.9M=0.3s

2018-02-20 12:12:26 (159 KB/s) - ���echo-nginx-module-0.61.tar.gz��� saved [53157]

--2018-02-20 12:12:26--  https://github.com/openresty/xss-nginx-module/tarball/v0.05
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/openresty/xss-nginx-module/legacy.tar.gz/v0.05 [following]
--2018-02-20 12:12:27--  https://codeload.github.com/openresty/xss-nginx-module/legacy.tar.gz/v0.05
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ���xss-nginx-module-0.05.tar.gz���

     0K .......... .                                           73.8M=0s

2018-02-20 12:12:27 (73.8 MB/s) - ���xss-nginx-module-0.05.tar.gz��� saved [11477]

--2018-02-20 12:12:27--  https://github.com/simpl/ngx_devel_kit/tarball/v0.3.0
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/simplresty/ngx_devel_kit/tarball/v0.3.0 [following]
--2018-02-20 12:12:28--  https://github.com/simplresty/ngx_devel_kit/tarball/v0.3.0
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/simplresty/ngx_devel_kit/legacy.tar.gz/v0.3.0 [following]
--2018-02-20 12:12:28--  https://codeload.github.com/simplresty/ngx_devel_kit/legacy.tar.gz/v0.3.0
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ���ngx_devel_kit-0.3.0.tar.gz���

     0K .......... .......... .......... .......... ..........  167K
    50K .......... ....                                         107K=0.4s

2018-02-20 12:12:29 (148 KB/s) - ���ngx_devel_kit-0.3.0.tar.gz��� saved [66457]

mv: cannot stat ���simpl-ngx_devel_kit-*���: No such file or directory
make: *** [all] Error 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by FireBurn** [comment]
Sorry this is a duplicate of https://github.com/openresty/openresty/issues/336

Will there be a new point release to fix this?

**Comment by agentzh** [comment]
@FireBurn It's already fixed in the master branch.

**Comment by agentzh** [comment]
@FireBurn Why don't you just use the OpenResty releases? See

https://openresty.org/en/download.html

**Comment by FireBurn** [comment]
I wasn't aware of them :S 

Taking a closer look, have you considered using git submodules?

**Comment by agentzh** [comment]
@FireBurn No, git submodules suck and I had too much pain with it. Besides, not everything is managed by git.
