### ISSUE TITLE
Error response while using proxy_next_upstream

### ISSUE THREAD

**Issue by ugolas** [openresty/openresty#351]
Hi all,

I've added the `proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;` config in order to support retries in case of 5xx.

The expected behavior is for nginx to retry idempotent requests X times and if all retries still fail return the upstream response after the X attempt.

The weird behavior is when calling POST (a non idempotent request) and upstream returns a 5xx response. It does not retry the request (which it shouldn't), but I don't get the upstream response, instead I'm getting in response the openresty HTML error, example:
```
<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>openresty/1.11.2.4</center>
</body>
</html>
```

If I remove the `proxy_next_upstream` config, I get the original upstream response. 
If I call an idempotent method (GET etc..), after the retries I get the original upstream response.

Any idea how to get the original upstream error response for POST requests while still using  proxy_next_upstream for 5xx?

Thanks

**Comment by spacewander** [comment]
@ugolas 
I think you need to add the `non_idempotent` option to `proxy_next_upstream`.
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream

**Comment by ugolas** [comment]
@spacewander thanks for the response. but adding `non_idempotent` will cause retries on POST requests, and I don't want that. I only want to get the actual response from upstream instead of the openresty html.

**Comment by spacewander** [comment]
@ugolas 
Sorry for misunderstanding your word.
AFAIK, there is not way to achieve this because Nginx's proxy mechanism doesn't allow it.

**Comment by spacewander** [comment]
@ugolas 
It seems that Nginx fix this "feature" in a recent commit: https://github.com/nginx/nginx/commit/d90a75b7cdc70ddb2aa1880dc09301c5f1a279ae
Build with the latest Nginx, you could get the original upstream error response for POST requests while still using proxy_next_upstream for 5xx.

**Comment by ugolas** [comment]
Thanks! Appreciate the updates
