### ISSUE TITLE
make step failed while building Openresty 1.13.6.1 from source

### ISSUE THREAD

**Issue by svarlitskiy** [openresty/openresty#352]
### Issue ###
fails to make simpl-ngx_devel_kit. Because the wrong package is specified.

--2018-03-19 14:13:04--  https://github.com/simpl/ngx_devel_kit/tarball/v0.3.0
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/simplresty/ngx_devel_kit/tarball/v0.3.0 [following]
--2018-03-19 14:13:05--  https://github.com/simplresty/ngx_devel_kit/tarball/v0.3.0
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/simplresty/ngx_devel_kit/legacy.tar.gz/v0.3.0 [following]
--2018-03-19 14:13:05--  https://codeload.github.com/simplresty/ngx_devel_kit/legacy.tar.gz/v0.3.0
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘ngx_devel_kit-0.3.0.tar.gz’

ngx_devel_kit-0.3.0.tar.gz                       [ <=>                                                                                           ]  64.90K  --.-KB/s    in 0.1s    

2018-03-19 14:13:05 (502 KB/s) - ‘ngx_devel_kit-0.3.0.tar.gz’ saved [66457]

mv: cannot stat 'simpl-ngx_devel_kit-*': No such file or directory
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1

### FIX ###
1. Edit mirror-tarballs
2. Scroll down to line 432 - 435
3. Modify to simpl to simplresty

```
ver=0.3.0
$root/util/get-tarball "https://github.com/simplresty/ngx_devel_kit/tarball/v$ver" -O ngx_devel_kit-$ver.tar.gz
tar -xzf ngx_devel_kit-$ver.tar.gz || exit 1
mv simplresty-ngx_devel_kit-* ngx_devel_kit-$ver || exit 1
```

4. Save and run make again
5. completes

**Comment by agentzh** [comment]
@svarlitskiy You are not really building from source. See

https://openresty.org/en/download.html#source-code-releases

This repo is for OpenResty *DEVELOPERS* use only.

**Comment by agentzh** [comment]
@svarlitskiy BTW, that issue in this repo was already fixed in the master branch quite some time ago.
