### ISSUE TITLE
OpenResty for Nginx 1.13.10

### ISSUE THREAD

**Issue by arcivanov** [openresty/openresty#353]
1.13.10 is getting a GRPC module. Integrating it with Lua/OpenResty would be extremely desirable.

**Comment by agentzh** [comment]
@arcivanov Yes, upgrading to the latest nginx release is always a goal of OpenResty releases. But we need to release a new OpenResty 1.13.6.1.2 version first according to our schedule.

**Comment by feifangit** [comment]
@agentzh where could I find the schedule doc? or do you have an est. time to upgrade nginx core to 1.13.10

**Comment by agentzh** [comment]
@feifangit We don't have a release schedule document. The 1.13.6.1.2 release should happen in the next few weeks while a release with nginx 1.13.10+ would be out in a couple of months after that.

**Comment by zlatangao** [comment]
可以临时出一个吗？

**Comment by zlatangao** [comment]
@agentzh can u help give a temp release just upgrading to 1.13.10?

**Comment by agentzh** [comment]
The next OpenResty version will be based on nginx 1.15.x. Well, it's a moving target :)

Hopefully we can provide a preview version of OpenResty based on nginx 1.15.x in the next few weeks. Too busy with other new OpenResty features and optimizations right now.

Sorry for the delay.

**Comment by rohitjoshi** [comment]
Any update on this?

**Comment by agentzh** [comment]
A new release candidate of OpenResty based on nginx 1.15.x is expected to be out next month. We're busy porting OpenResty to ARM64 with corporate sponsorship right now.

**Comment by sparvu** [comment]
ARM64 port +1. Cool stuff. Cavium's ThunderX ?

**Comment by xkeyideal** [comment]
The next OpenResty version will be based on nginx 1.15.x will be expected to be out August?

**Comment by agentzh** [comment]
@xkeyideal Maybe. Or September.

**Comment by qiqizjl** [comment]
hello,update on this?

**Comment by urifoox** [comment]
Are there any updates on this? We are blocked from using Proxy Protocol Version 2 which only comes out in a newer version of NginX and I can't seem to compile a newer version of NginX  into Openresty

**Comment by fancy-rabbit** [comment]
hello @agentzh , any update on this?

**Comment by agentzh** [comment]
@fancy-rabbit We're busy preparing for the new OpenResty 1.15.5.1 release atm.

**Comment by agentzh** [comment]
@arcivanov Will kick out a quick and dirty OpenResty 1.15.5.1 RC0 preview version for download here later today...Sorry for the delay.

**Comment by arcivanov** [comment]
Awesome, thanks!

**Comment by agentzh** [comment]
Try this: https://openresty.org/download/openresty-1.15.5.1rc0.tar.gz

The ngx_stream_lua module is known to have some compatibility issues. We'll try resolving the remaining issues in the coming days. Also, we're still in the progress of testing (travis ci testing is far from enough).

**Comment by fancy-rabbit** [comment]
awesome!

**Comment by agentzh** [comment]
Just updated that rc0 tarball (same URI) with the latest ngx_lua and ngx_stream_lua tweaks and fixes. The tests of ngx_stream_lua seem to be fully passing now.

The new version of the tarball has the following MD5 checksum:

9cb82eb20b1aec191b6eea5d561138b2

**Comment by feifangit** [comment]
when will a pre-built 1.15.x package ready?

**Comment by agentzh** [comment]
The new OpenResty 1.15.6.1 formal release should be out in the next few weeks. We're still working on it. We'll push out an RC1 first.

**Comment by agentzh** [comment]
The next version will be OpenResty 1.15.8.1. We've already kicked out a preview version for it:

https://openresty.org/download/openresty-1.15.8.1rc0.tar.gz

Please do not hijack this old issue. Thank you. It was about nginx 1.13.10.
