### ISSUE TITLE
how can I update the nginx version?

### ISSUE THREAD

**Issue by lljuser** [openresty/openresty#359]
I want to update the nginx to the 1.13.10 version .  how can I do ?    I want to use the GRPC .

**Comment by agentzh** [comment]
@lljuser NGINX never maintains backward compatibility on the C level so better wait for the new OpenResty releases based on new nginx cores (which will be extensively tested).

**Comment by thibaultcha** [comment]
Hi,

The next release will be 1.15.8.1 and is soon to be published. All branches are in frozen state, and we will spend a few days doing some testing on our side.

Thanks for your patience, 

Thibault

**Comment by stlnkm** [comment]
Hello, is it support cosocket?
