### ISSUE TITLE
Intermittent "nginx: [error] failed to initialize Lua VM in nginx.conf:43004"

### ISSUE THREAD

**Issue by arcivanov** [openresty/openresty#363]
Running OpenResty eccf26672cfc1e740cf3bedd1a0cd960b404c2ca, in docker on Amazon Linux latest.

```
# nginx -V
nginx version: openresty/1.13.6.2rc1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --with-debug --with-cc-opt='-DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC -O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/zlib/include -I/usr/local/pcre/include -I/usr/local/openssl/include' --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.13 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.5 --with-ld-opt='-Wl,-rpath,/usr/local/luajit/lib -L/usr/local/zlib/lib -L/usr/local/pcre/lib -L/usr/local/openssl/lib -Wl,-rpath,/usr/local/zlib/lib:/usr/local/pcre/lib:/usr/local/openssl/lib' --add-module=/tmp/nginx-upstream-dynamic-servers --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_realip_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-file-aio --with-dtrace-probes --with-stream --with-stream_ssl_module --with-http_ssl_module
```

There are >600 individual servers (the max target is about 3000 but really it shouldn't matter as far as the bug is concerned). As the number of servers increases these errors get more and more frequent and are produced both on `nginx -t` and `nginx`. Each server contains a single `access_by_lua_block` and they share a dictionary. 

The subj error is really all that there is. "--with-debug" does literally nothing and no debug logging from Lua occurs as no logging is initialized when Lua VM fails to create. 

See https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_util.c#L3756

```
ngx_log_debug1(NGX_LOG_DEBUG_HTTP, log, 0, "lua initialize the "
                   "global Lua VM %p", L);
```
Since HTTP is not yet created, no logging is available. I will be forking ngx_lua to try to get logging to use core to get more out of it.

Any ideas what may be the cause (I know it's very little to go on).

**Comment by arcivanov** [comment]
So gdb'ing this.

```
(gdb) step
3751        L = ngx_http_lua_new_state(parent_vm, cycle, lmcf, log);
(gdb) next
3753            return NULL;
(gdb) list
3748        }
3749
3750        /* create new Lua VM instance */
3751        L = ngx_http_lua_new_state(parent_vm, cycle, lmcf, log);
3752        if (L == NULL) {
3753            return NULL;
3754        }
3755
3756        ngx_log_debug1(NGX_LOG_DEBUG_HTTP, log, 0, "lua initialize the "
3757                       "global Lua VM %p", L);
```

![Deeper](http://i0.kym-cdn.com/photos/images/original/000/531/557/a88.jpg)

**Comment by arcivanov** [comment]
Ok, here's the answer: `luaL_newstate () at lib_aux.c:347` fails because `mmap_map32 (size=131072) at lj_alloc.c:312` fails and `mmap_probe (size=131072) at lj_alloc.c:284` fails as well.

Thoughts?

**Comment by agentzh** [comment]
@arcivanov The thing is that your nginx has configured too many `server {}` blocks and nginx is bad at handling many virtual servers in its standard `nginx.conf` way since it would allocate a lot of memory upon nginx startup in the C heap (through glibc's allocator), which makes the low 2G address space almost drained out (the LuaJIT VM needs the low 2G address space).

In our commercial[ OpenResty Edge 2 product](https://openresty.com/en/), for example, we use Lua to dispatch virtual servers directly and it's easy to handle tens of thousands, hundreds of thousands, or even millions of virtual servers in the single OpenResty process without using too much memory or draining out the low 2G memory at all.
