### ISSUE TITLE
Errors installing openresty (1.13.6.2-1) on Ubuntu 18.04

### ISSUE THREAD

**Issue by PaulSchulz** [openresty/openresty#368]
After following the instructions from here: 
 https://openresty.org/en/linux-packages.html

I get the following error:

> May 18 18:01:01 elite systemd[1]: Starting full-fledged web platform...
> May 18 18:01:01 elite nginx[10891]: /usr/local/openresty/nginx/sbin/nginx: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
> May 18 18:01:01 elite systemd[1]: openresty.service: Control process exited, code=exited status=127
> May 18 18:01:01 elite systemd[1]: openresty.service: Failed with result 'exit-code'.
> May 18 18:01:01 elite systemd[1]: Failed to start full-fledged web platform.

The package openrusty-pcre is installed.

Other versions..
<pre>
openresty/bionic,now 1.13.6.2-1~bionic1 amd64 [installed] 
openresty-resty/bionic,bionic,now 1.13.6.2-1~bionic1 all [installed,automatic]
openresty-pcre/bionic,now 8.42-1~bionic1 amd64 [installed]
</pre>

**Comment by agentzh** [comment]
@PaulSchulz I cannot reproduce it on my side with a fresh install of Ubuntu 18.04 (with a full system upgrade via `sudo apt dist-upgrade`. Below is the full installation and test process on my side for your reference:

https://gist.github.com/agentzh/90fac17c5e786adb0cd7daaf8d72f8d0

Your error looks weird. Maybe you used to have an old install of some other builds of OpenResty in the same location? Check the following:

```
$ md5sum /usr/local/openresty/nginx/sbin/nginx
773a0ceddb7745429f4bb662b4cc8323  /usr/local/openresty/nginx/sbin/nginx

$ ldd /usr/local/openresty/nginx/sbin/nginx|grep pcre
	libpcre.so.1 => /usr/local/openresty/pcre/lib/libpcre.so.1 (0x00007f09eeaa3000)

$ file /usr/local/openresty/pcre/lib/libpcre.so.1
/usr/local/openresty/pcre/lib/libpcre.so.1: symbolic link to libpcre.so.1.2.10

$ md5sum /usr/local/openresty/pcre/lib/libpcre.so.1
33612241b3153f0d0357c34913993118  /usr/local/openresty/pcre/lib/libpcre.so.1
```

If you are getting different output from any of the commands above, then your installation is indeed broken.

**Comment by PaulSchulz** [comment]
Successfully installed.
Thankyou for your patience. 
The root cause appears to be that I had nginx packages installed (pcre might have been something else, as library files didn't get installed although the package was). 

Fix was as simple as - Completly removing all packages as listed by:
  dpkg -l | grep  nginx
  dpkg -l | grep openresty
with
  apt remove --purge <package> 

and reinstalling with
  apt install openresty
allowed everything to install cleanly. 

Cheers.
