### ISSUE TITLE
can openresty rewrite websocket message while openresty proxy websocket server?

### ISSUE THREAD

**Issue by Tseian** [openresty/openresty#374]
I use openresty to proxy my websocekt server ,the follow code are my nginx.conf
```shell

server {

    listen       443 ssl;
    server_name  xxx.xxx.net;
    root  /usr/share/nginx/html;

    ssl_certificate "/etc/ssl/crt/xxxx.crt";
    ssl_certificate_key "/etc/ssl/crt/xxx.key";

    location / {
            content_by_lua_file lua/test.lua;
            add_header Cache-Control no-cache; 
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host  $host;
            proxy_set_header X-Nginx-Proxy true;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass  http://localhost:30005/;
    }

    error_page 404 /404.html;
        location = /40x.html {
    }

    error_page 500 502 503 504 /50x.html;
        location = /50x.html {
    }
}

```
the question is that the lua/test.lua is not executed when websocket server  accepted  client.
how can i get and rewrite websocket message via my lua script in openresty?

**Comment by zenboss** [comment]
I have the same question.

**Comment by agentzh** [comment]
Not with the `ngx_proxy` module since that module itself does not even bother understanding the websocket frames at all. A Lua-land websocket proxies can definitely do that (using something like the `lua-resty-websocket` library, for example).

BTW, please join the openresty-en mailing list for such general usage questions. This place is reserved for real bug reports and patch submissions. Thanks for
your cooperation! Please see https://openresty.org/en/community.html

**Comment by JazminFlorez** [comment]
> I use openresty to proxy my websocekt server ,the follow code are my nginx.conf
> 
> ```shell
> server {
> 
>     listen       443 ssl;
>     server_name  xxx.xxx.net;
>     root  /usr/share/nginx/html;
> 
>     ssl_certificate "/etc/ssl/crt/xxxx.crt";
>     ssl_certificate_key "/etc/ssl/crt/xxx.key";
> 
>     location / {
>             content_by_lua_file lua/test.lua;
>             add_header Cache-Control no-cache; 
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header X-Forwarded-For $remote_addr;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header Host  $host;
>             proxy_set_header X-Nginx-Proxy true;
>             proxy_http_version 1.1;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection "upgrade";
>             proxy_pass  http://localhost:30005/;
>     }
> 
>     error_page 404 /404.html;
>         location = /40x.html {
>     }
> 
>     error_page 500 502 503 504 /50x.html;
>         location = /50x.html {
>     }
> }
> ```
> 
> the question is that the lua/test.lua is not executed when websocket server accepted client.
> how can i get and rewrite websocket message via my lua script in openresty?


did you solve it?

**Comment by successjian** [comment]
> Not with the `ngx_proxy` module since that module itself does not even bother understanding the websocket frames at all. A Lua-land websocket proxies can definitely do that (using something like the `lua-resty-websocket` library, for example).
> 
> BTW, please join the openresty-en mailing list for such general usage questions. This place is reserved for real bug reports and patch submissions. Thanks for your cooperation! Please see https://openresty.org/en/community.html

dear agentzhang, i have a question, how can i intercept the websocket traffic using openresty?thanks.
