### ISSUE TITLE
I have 403 error on latest   openresty/1.13.6.2

### ISSUE THREAD

**Issue by salamsoliman** [openresty/openresty#376]
hi,
When I finished the nginx configuration, I was always get the 403 error when I tried to install my site program.

error.log shows

`2018/06/08 10:33:18 [error] 12018#12018: *334 directory index of "/usr/local/openresty/nginx/html/install/" is forbidden, `

This is my configuration.

`
user  root;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;
    
    client_max_body_size 8m;    #允许客户端请求的最大单文件字节数
    client_body_buffer_size 2m;  #缓冲区代理缓冲用户端请求的最大字节

   #WAF
    lua_shared_dict limit 50m;  #防cc使用字典，大小50M
    lua_shared_dict guard_dict 100m;
    lua_shared_dict dict_captcha 70m;
    lua_max_running_timers 1;
    lua_package_path "/usr/local/openresty/nginx/conf/waf/?.lua";
    init_by_lua_file "/usr/local/openresty/nginx/conf/waf/init.lua";
    access_by_lua_file "/usr/local/openresty/nginx/conf/waf/access.lua";
   

    #keepalive_timeout  0;
    keepalive_timeout  65;

    gzip  on;

    server {
        listen       80;
        listen       [::]:80 default_server;
        server_name  my.ip.address.here;
        
        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {

            root    html;
            index  index.html index.htm index.php;
        }

        location /phpmyadmin {
            alias /usr/share/phpMyAdmin;
            index index.php;
         }

       location ~ /phpmyadmin/.+\.php$ {
            if ($fastcgi_script_name ~ /phpmyadmin/(.+\.php.*)$) {
             set $valid_fastcgi_script_name $1;
            }
             include fastcgi_params;
             fastcgi_pass 127.0.0.1:9000;
             fastcgi_index index.php;
             fastcgi_param SCRIPT_FILENAME /usr/share/phpMyAdmin/$valid_fastcgi_script_name;
         }

       

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    
        location ~ \.php$ {
          
            fastcgi_pass   127.0.0.1:9000;
            
            fastcgi_index  index.php;

            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
          
            include        fastcgi_params;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /document_root$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }

    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

    # HTTPS server
    
    server {
        listen  443 ssl http2;
        
        server_name  my.ip.adress;
        charset  utf-8;
        ssl on;
        default_type  text/plain;
        
       

       ssl_session_cache    shared:SSL:1m;
       ssl_session_timeout  5m;
       ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

       ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
       ssl_prefer_server_ciphers  on;

       location / {
            root   html;
           index  index.html index.htm index.php;
        }

         location ~ /phpmyadmin/.+\.php$ {
            if ($fastcgi_script_name ~ /phpmyadmin/(.+\.php.*)$) {
             set $valid_fastcgi_script_name $1;
            }
             include fastcgi_params;
             fastcgi_pass 127.0.0.1:9000;
             fastcgi_index index.php;
             fastcgi_param SCRIPT_FILENAME /usr/share/phpMyAdmin/$valid_fastcgi_script_name;
         }

       location ~ \.php$ {
   
            fastcgi_pass   127.0.0.1:9000;
          
            fastcgi_index  index.php;
    
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        
            include        fastcgi_params;
        }

   }

}
`

I already set my directory(/usr/local/openresty/nginx/html/install/  and /usr/local/openresty/nginx/html) authority to 777 and the root.root as owner.

**Comment by salamsoliman** [comment]
ip/index.html   and ip/50x.html is works well.but when I open ip/install ,it would shows "403 forbidden"

**Comment by agentzh** [comment]
@salamsoliman It's a common configuration error in your own nginx.conf file. That error message usually means that you fail to configure a proper content handler for that location. You should reach out to the nginx or openresty-en mailing lists for help instead:

https://openresty.org/en/community.html

BTW, if you really think it's a bug in OpenResty or the Nginx core, you should really provide a minimal example that others can easily run and reproduce the issue (that is, you should keep removing unrelated stuff from your example as long as you can preserve the issue).  In fact, many users can find their own mistakes while doing this. Simply pasting the full `nginx.conf` is just too lazy and is a waste of others' time, usually.

Also, for debugging large nginx.conf, if you really need to, you should really (temporarily) enable the nginx debugging logs to see what's happening under the hood. See

http://nginx.org/en/docs/debugging_log.html

**Comment by salamsoliman** [comment]
Your answer is useful ,thanks.
