### ISSUE TITLE
nginx: [error] init_by_lua_file error: cannot open /usr/local/openresty/nginx/conf/waf/init.lua: No such file or directory

### ISSUE THREAD

**Issue by salamsoliman** [openresty/openresty#377]
Today ,I tried restart my openresty,I typed "/usr/local/openresty/nginx/sbin/nginx -t"
but it shows error

`nginx: the configuration file /usr/local/openresty/nginx/conf/nginx.conf syntax is ok
nginx: [error] init_by_lua_file error: cannot open /usr/local/openresty/nginx/conf/waf/init.lua: No such file or directory
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed`

How can I fix it?

**Comment by agentzh** [comment]
@salamsoliman You should check whether that file exists in the first place? We cannot fix such things for you, apparently ;)

**Comment by salamsoliman** [comment]
I fixed this issue and found that I didn't install waf .
