### ISSUE TITLE
The status of coroutine is wrong?

### ISSUE THREAD

**Issue by snaix** [openresty/openresty#379]
Hi openresty
When I use ngx.thread.spawn(), I found that the status of coroutine was wrong.
For example, I spawn a new user thread A,
and retrieve the self status and the parent thread status in this A.
I expect it should output **"running" & "normal"**.
But the result is **"running" & "running"**.
According to [lua reference](http://www.lua.org/manual/5.1/manual.html#pdf-coroutine.status), the parent thread should be "normal" at that moment.
So I think spawn() just create a specific coroutine, the status should be same as normal lua coroutine?

I have read the code of lua coroutine scheduler, 
it should assign a NGX_HTTP_LUA_CO_NORMAL in ngx_http_lua_uthread_spawn() if it's a bug really?

The following is the code, it can be reproduced in openresty/1.13.6.2

        local yield = coroutine.yield

        g_self = coroutine.running()

        function f()
                local self = coroutine.running()
                ngx.say("f 1", coroutine.status(self), coroutine.status(g_self))
                yield(self)
        end

        ngx.say("1")
        ngx.thread.spawn(f)

        ngx.say("2")

**Comment by agentzh** [comment]
@snaix Our light threads are not identical to plain Lua coroutines. They are automatically scheduled while plain Lua coroutines are always manually scheduled. Better do not confuse those two and expect light threads always strictly follow plain Lua coroutines' semantics. That just does not make sense.

**Comment by agentzh** [comment]
@snaix By definition, all light threads are running at the same time (since they are automatically scheduled).
