### ISSUE TITLE
openresty support grpc

### ISSUE THREAD

**Issue by jworldexpo** [openresty/openresty#380]
hello

I want to support nginx's new grpc module in the latest version of openresty. I don't know if there are any good solutions and suggestions.

**Comment by agentzh** [comment]
The next release of OpenResty will base on more recent NGINX cores, which will definitely have the new GRPC proxy feature.

**Comment by naturallight** [comment]
+1

**Comment by Xuhaomiao** [comment]
@agentzh , the next release of OpenResty that supports gRPC,  when is it released?

**Comment by agentzh** [comment]
@Xuhaomiao Try this forn now:

https://openresty.org/download/openresty-1.15.8.1rc0.tar.gz

**Comment by kelvinkuo** [comment]
@agentzh so the grpc module is stabled?

**Comment by agentzh** [comment]
@kelvinkuo The most recent version with that is here:

https://openresty.org/en/ann-1015008001rc1.html

**Comment by fujiahui** [comment]
How to know if grpc is supported？

**Comment by fujiahui** [comment]
How to know if grpc is supported, there is a demo to test it.

**Comment by agentzh** [comment]
@fujiahui That's a standard nginx feature:

https://www.nginx.com/blog/nginx-1-13-10-grpc/
