### ISSUE TITLE
发现bug，不知道是不是bug，在线等......有人在吗？？？ 急着用！！！

### ISSUE THREAD

**Issue by aaronkingdom** [openresty/openresty#402]
location / {
        这里面的反向代理正常， 图片和html都不会发生重复请求.。。。
}

当请求为js css的时候，使用ngx.re.gsub会出现重复请求.。。。。。
location ~* /(.*)\.(css|js|eot|woff|woff2|ttf|svg|ttc|tif|Webp|BMPPCX|TIF|GIF|JPG|JPEG|TGA|EXIF|FPX|SVG|PSD|CDR|PCD|DXF|UFO|EPS|AI|PNG|HDRI|RAW|ICO|ICON|CUR)(.*) {
    proxy_pass http://www.xxxxxxx.com;

      set $style_needcacheuri"1"
   	set $style_proxy_buffer "";

	body_filter_by_lua_block {
		if ngx.arg[1] ~= '' then
			ngx.var.style_proxy_buffer = ngx.var.style_proxy_buffer..ngx.arg[1]
		end
		if ngx.arg[2] then
    		if ngx.var.style_needcacheuri=="1" then
                local body = ngx.var.style_proxy_buffer
				body, n, err = ngx.re.gsub(body, "(?<=url\\()[^)]+(?=\\))", "", "i") -- 这里添加替换就会发生js css 重复请求， type会和常规的请求不一样， 来源为： xxxx.css, xxxx.js
				ngx.arg[1] = body
            return
		else
			ngx.arg[1] = nil
		end
	}
}

**Comment by aaronkingdom** [comment]
从chrome或者firefox中的network可以查看css js都会重复， 而且很诡异， 内容一样。 大小不一样， 压缩的问题？？？

**Comment by agentzh** [comment]
@aaronkingdom Please, do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see https://openresty.org/en/community.html Thanks for your cooperation.

Regarding to your issue, you are using the body filter in the *wrong* way. A body filter can be invoked for multiple times for all the data chunks in a *single* response body. To quote the relevant official documentation:

> Nginx output filters may be called multiple times for a single request because response body may be delivered in chunks. Thus, the Lua code specified by in this directive may also run multiple times in the lifetime of a single HTTP request.

See https://github.com/orinc/lua-nginx-module-plus#body_filter_by_lua for more details.

**Comment by aaronkingdom** [comment]
ok, thanks

**Comment by aaronkingdom** [comment]
but how to do the replace in this case?????????

**Comment by aaronkingdom** [comment]
yes,   will do the multiple times for all the data chunks, but in the
ngx.arg[2], just onetime, right?????   if i dont use ngx.re.gsub,
everything is ok...       how can i replace the body if not use the
"body_filter_by_lua" ??   the document is no more information let me know
to resolve this problem , thank you


Yichun Zhang <notifications@github.com> 于2018年9月14日周五 上午4:43写道：
