### ISSUE TITLE
[help]  undefined reference to `pthread_atfork'

### ISSUE THREAD

**Issue by minnan0422** [openresty/openresty#408]
I am experiencing a problem. This problem happened when I compiled and installed nginx1.13.10. Now I have encountered openresty. This problem is caused by the use of openssl1.1.1. This is a bug of openssl1.1.1. But on nginx1.13.10, I can temporarily modify Makeflie and modify the pthread, just like this “-ldl -lcrypt -lpcre /usr/local/openssl/lib/libssl.a /usr/local/openssl/lib/libcrypto. a -ldl -lz -lpthread \ ; But on openresty, this part is different, I don't know how to modify it, openresty is like this -L/usr/local/openresty-1.13.6.2/build/luajit-root/ Usr/local/openresty/nginx/luajit/lib -L/usr/local/openresty-1.13.6.2/build/luajit-root/usr/local/openresty/nginx/luajit/lib -L/usr/local/openresty- 1.13.6.2/build/luajit-root/usr/local/openresty/nginx/luajit/lib -L/usr/local/openresty-1.13.6.2/build/luajit-root/usr/local/openresty/nginx/luajit/ Lib -Wl, -rpath, /usr/local/openresty/nginx/luajit/lib -Wl, -E -Wl, -E -Wl, -E -Wl, -E -ldl -lpthread -lcrypt -L/usr/ Local/openres Ty-1.13.6.2/build/luajit-root/usr/local/openresty/nginx/luajit/lib -lluajit-5.1 -lm -ldl -L/usr/local/openresty-1.13.6.2/build/luajit-root/ Usr/local/openresty/nginx/luajit/lib -lluajit-5.1 -lm -ldl -L/usr/local/openresty-1.13.6.2/build/luajit-root/usr/local/openresty/nginx/luajit/lib - Lluajit-5.1 -lm -ldl -L/usr/local/openresty-1.13.6.2/build/luajit-root/usr/local/openresty/nginx/luajit/lib -lluajit-5.1 -lm -ldl -lpcre /usr/ Local/openssl/lib/libssl.a /usr/local/openssl/lib/libcrypto.a -ldl -lz \,” so you can solve openssl's openssl link on this issue https://github.com/openssl/openssl/ Issues/3884

**Comment by agentzh** [comment]
@minnan0422 You can try `./configure --with-ld-opt=-lpthread` while building OpenResty (or the vanilla nginx) or just linking against openssl via dynamic linking instead.

**Comment by minnan0422** [comment]
@agentzh Thank you, but it doesn't solve the problem, which itself is a BUG in openssl1.1.1, complete compilation parameters: ". / configure -- prefix = / usr/local/openresty/nginx - with - cc - opt = - O2 - add - the module = / usr/local/openresty - 1.13.6.2 / bundle/ngx_devel_kit - 0.3.0 - add - the module = / usr/local/openresty - 1.13.6.2 / bundle/echo - nginx - module - 0.61 - the add - the module = / usr/local/openresty - 1.13.6.2 / bundle/XSS - nginx - module - 0.06 - add - the module = / usr/local/openresty - 1.13.6.2 / bundle/ngx_coolkit - 0.2 rc3 - add - the module = / usr/local/openresty 1.13.6.2 / bundle/set - misc - nginx - module - 0.32 - add - the module = / usr/local/openresty - 1.13.6.2 / bundle/form - input - nginx - module - 0.12 - the add - the module = / usr/local/openresty - 1.13.6.2 / bundle/encrypted session - nginx - module - 0.08 - add - the module = / usr/local/openresty - 1.13.6.2 / bundle/srcache - nginx - module - 0.31 - the add - the module = / usr/local/openresty - 1.13.6.2 / bundle/ngx_lua - 0.10.13 - add - the module = / usr/local/openresty - 1.13.6.2 / bundle/ngx_lua_upstream - 0.07 - the add - the module = / usr/local/openresty - 1.13.6.2 / bundle/headers - more - nginx - module - 0.33 - add - the module = / usr/local/openresty - 1.13.6.2 / bundle/array - var - nginx - module - 0.05 - the add - the module = / usr/local/openresty - 1.13.6.2 / bundle/memc - nginx - module - 0.19 - add - the module = / usr/local/openresty - 1.13.6.2 / bundle/redis2 - nginx - module - 0.15 - the add - the module = / usr/local/openresty - 1.13.6.2 / bundle/redis - nginx - module - 0.3.7 - add - the module = / usr/local/openresty - 1.13.6.2 / bundle/RDS - json - nginx - module - 0.15 - the add - the module = / usr/local/openresty - 1.13.6.2 / bundle/RDS - CSV - nginx - module - 0.09 --add-module=/usr/local/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5 --with-openssl=/usr/local/openssl --with-ld-opt=-lpthread --with-ipv6 --with-http_realip_module --with-http_ssl_module - with - http_stub_status_module - with - http_v2_module - with - stream - with - stream_ssl_module"

**Comment by minnan0422** [comment]
> @minnan0422 @agentzh nginx 1.13.11 fix [nginx](https://github.com/nginx/nginx/commit/90ca1071b77b0fbb4373ae052b1242023295513f)

So I need to change the nginx-1.13.6 to 1.13.11?  i  try

**Comment by minnan0422** [comment]
@yyqbuct   I tried nginx's 1.13.10, 1.14.0, and 1.15.5, and now I'm reporting this error, with no clue.

Error message: "ngx_stream_lua_prereadby. C: (. Text + 0 x640) : multiple definition of ` ngx_stream_lua_preread_handler_file '

Objs addon/SRC/ngx_stream_lua_prereadby. O: ngx_stream_lua_prereadby. C: (. The text + 0 x640) : first defined here

Collect2: error: ld returned 1 exit status

Make [2]: *** [objs/nginx] Error 1

Make [2] : brigade directory ` / usr/local/openresty - 1.13.6.2 / build/nginx - 1.13.10 '

Make [1]: *** [build] Error 2

Make [1] : brigade directory ` / usr/local/openresty - 1.13.6.2 / build/nginx - 1.13.10 '

Make: *** [all] Error 2"

**Comment by minnan0422** [comment]
@yyqbuct In version 1.13.6, I can use the same method to skip the first error to the current error, but at this point I really don't know how to solve it, I may need to test on the basis of the compiled 1.13.10
