### ISSUE TITLE
最新版openresty是否可以支持http2_push_preload?

### ISSUE THREAD

**Issue by whitekyo** [openresty/openresty#415]
1.我看了nginx是从1.13.9开始支持，不知道openresty如何支持
2.是否有相关nginx1.14.0 和nginx1.15版本编译lua的成功案例或者其他解决方案。

**Comment by agentzh** [comment]
Read the template:

"This place is for bug reports and development discussions only. For general questions and
discussions, please join the openresty-en mailing list instead: https://groups.google.com/group/openresty-en.
If you want to use Chinese, please join the openresty (Chinese) mailing list instead: https://groups.google.com/group/openresty.
Do not use Chinese in this place."
