### ISSUE TITLE
openresty healthcheck doesn't work

### ISSUE THREAD

**Issue by zhu1q1q1q** [openresty/openresty#419]
my openresty version is openresty-1.13.6.1,
and nginx version is nginx-1.12.2.
now the healthcheck doesn't work, and error log is：“2018/11/12 13:14:53 [error] 30806#30806: *136082499 [lua] healthcheck.lua:53: errlog(): healthcheck: failed to run healthcheck cycle: attempt to yield across metamethod/C-call boundary, context: ngx.timer”

why？

**Comment by agentzh** [comment]
@zhu1q1q1q You should use LuaJIT instead of the standard Lua 5.1 interpreter. That error clearly indicates you are using the latter.

How can you use a different nginx core while using OpenResty 1.13.6.1? And why are you using a different Lua VM while OpenResty already bundles its own LuaJIT and should work out of the box?

I'm very confused.

**Comment by zhu1q1q1q** [comment]
My operation steps：
安装包准备：

nginx-1.12.2.tar.gz

nginx-module-vts-master.zip

openresty-1.13.6.1.tar.gz

解压路径：

/usr/local/src/

nginx-module-vts-master.zip解压到openresty-1.13.6.1下。

编译安装：

cd openresty-1.13.6.1

sudo ./configure

sudo gmake

sudo gmake install

cd /usr/local/src/openresty-1.13.6.1/build/nginx-1.12.2

sudo yum install lua-devel

sudo ./configure --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.07 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.11 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.18 --add-module=../redis2-nginx-module-0.14 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.08 --add-module=../ngx_stream_lua-0.0.3 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --sbin-path=/usr/local/nginx/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/usr/local/nginx/conf/nginx.conf --error-log-path=/usr/local/nginx/logs/error.log --http-log-path=/usr/local/nginx/logs/access.log --pid-path=/usr/local/nginx/logs/nginx.pid --lock-path=/usr/local/nginx/logs/nginx.lock --http-client-body-temp-path=/usr/local/nginx/client_body_temp --http-proxy-temp-path=/usr/local/nginx/proxy_temp --http-fastcgi-temp-path=/usr/local/nginx/fastcgi_temp --http-uwsgi-temp-path=/usr/local/nginx/uwsgi_temp --http-scgi-temp-path=/usr/local/nginx/scgi_temp --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_ssl_module --add-module=/usr/local/src/openresty-1.13.6.1/nginx-module-vts-master --with-stream --with-stream_ssl_module

sudo make

sudo make install 

Becouse，I use the /usr/local/src/openresty-1.13.6.1/build/nginx-1.12.2，when execute  ./configure ... ，there are error message：
adding module in ../ngx_lua-0.10.11
checking for Lua library ... not found
checking for Lua library in /usr/local/ ... not found
checking for Lua library in /usr/local/ ... not found
checking for Lua library in /usr/pkg/ ... not found
checking for Lua library in /opt/local/ ... not found
checking for Lua library in /usr/local/*/lua51/ ... not found
checking for Lua library in /usr/ ... not found
checking for LuaJIT library in /usr/local/ ... not found
checking for LuaJIT library in /usr/ ... not found
checking for LuaJIT library in /usr/ ... not found
 ./configure: error: ngx_http_lua_module requires the Lua library.

before it ，I have to execute “sudo yum install lua-devel” to install the lua。

please，how can I make it well？

**Comment by zhu1q1q1q** [comment]
and，How to retrieve the compiled parameters of old programs

**Comment by agentzh** [comment]
@zhu1q1q1q No, you should always use the `./configure` file at the *top* of the directory. Do not mess with the `build/` directory yourself! Do not replace the nginx core with your own! It may not work at all.

**Comment by agentzh** [comment]
@zhu1q1q1q If you hack the OpenResty tarball and use your own build sequence, then you are on your own. Do not expect getting help from us. The "warranty" was already voided (if there's any).

**Comment by zhu1q1q1q** [comment]
Got it. Thanks for your answer. I've solved this problem. Thank you very much.
