### ISSUE TITLE
ngx.say cant work

### ISSUE THREAD

**Issue by corn1ng** [openresty/openresty#422]
i am new use  openresty . my version is 1.13.6.2
when i use openresty , my nginx.conf is here.
```
worker_processes 1;
events{
  worker_connections 1024;
}
http{
  server{
    listen 6699;
    server_name localhost;
    location / {
      rewrite_by_lua_block{
        ngx.say("1")
      }
      access_by_lua_block{
        ngx.say("2")
      }
      content_by_lua_block{
        ngx.say("3")
      }
    }
  }
}
```

when i run the application  i only see 1 but cant see 2 and 3 .
can you tell me the reason .

**Comment by agentzh** [comment]
@corn1ng You can only generate the response in a *single* nginx phase (be it `rewrite` or `access` or `content`, not across all of them). Once you generate some response body data in the rewrite phase, the subsequent phases won't even run.

**Comment by corn1ng** [comment]
thanks!
