### ISSUE TITLE
source code has wrong?

### ISSUE THREAD

**Issue by zhangwenzhao** [openresty/openresty#425]
centos 7x64
openresty 1.13.6.2

./configure --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include' --add-module=./bundle/ngx_devel_kit-0.3.0 --add-module=./bundle/echo-nginx-module-0.61 --add-module=./bundle/xss-nginx-module-0.06 --add-module=./bundle/ngx_coolkit-0.2rc3 --add-module=./bundle/set-misc-nginx-module-0.32 --add-module=./bundle/form-input-nginx-module-0.12 --add-module=./bundle/encrypted-session-nginx-module-0.08 --add-module=./bundle/srcache-nginx-module-0.31 --add-module=./bundle/ngx_lua-0.10.13 --add-module=./bundle/ngx_lua_upstream-0.07 --add-module=./bundle/headers-more-nginx-module-0.33 --add-module=./bundle/array-var-nginx-module-0.05 --add-module=./bundle/memc-nginx-module-0.19 --add-module=./bundle/redis2-nginx-module-0.15 --add-module=./bundle/redis-nginx-module-0.3.7 --add-module=./bundle/ngx_stream_lua-0.0.5 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl/lib' --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-dtrace-probes --with-stream --with-stream_ssl_module --with-http_ssl_module --with-openssl=/data/apps/openssl-1.0.2q --add-module=/data/apps/ngx_http_substitutions_filter_module

objs/addon/src/ngx_stream_lua_balancer.o:/data/apps/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5/src/ngx_stream_lua_balancer.c:708: first defined here
objs/addon/src/ngx_stream_lua_logby.o: In function `ngx_stream_lua_log_handler':
/data/apps/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5/src/ngx_stream_lua_logby.c:66: multiple definition of `ngx_stream_lua_log_handler'
objs/addon/src/ngx_stream_lua_logby.o:/data/apps/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5/src/ngx_stream_lua_logby.c:66: first defined here
objs/addon/src/ngx_stream_lua_logby.o: In function `ngx_stream_lua_log_handler_inline':
/data/apps/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5/src/ngx_stream_lua_logby.c:134: multiple definition of `ngx_stream_lua_log_handler_inline'
objs/addon/src/ngx_stream_lua_logby.o:/data/apps/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5/src/ngx_stream_lua_logby.c:134: first defined here
objs/addon/src/ngx_stream_lua_logby.o: In function `ngx_stream_lua_log_handler_file':
/data/apps/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5/src/ngx_stream_lua_logby.c:161: multiple definition of `ngx_stream_lua_log_handler_file'
objs/addon/src/ngx_stream_lua_logby.o:/data/apps/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5/src/ngx_stream_lua_logby.c:161: first defined here
objs/addon/src/ngx_stream_lua_prereadby.o: In function `ngx_stream_lua_preread_handler':
/data/apps/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5/src/ngx_stream_lua_prereadby.c:26: multiple definition of `ngx_stream_lua_preread_handler'
objs/addon/src/ngx_stream_lua_prereadby.o:/data/apps/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5/src/ngx_stream_lua_prereadby.c:26: first defined here
objs/addon/src/ngx_stream_lua_prereadby.o: In function `ngx_stream_lua_preread_handler_inline':
/data/apps/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5/src/ngx_stream_lua_prereadby.c:124: multiple definition of `ngx_stream_lua_preread_handler_inline'
objs/addon/src/ngx_stream_lua_prereadby.o:/data/apps/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5/src/ngx_stream_lua_prereadby.c:124: first defined here
objs/addon/src/ngx_stream_lua_prereadby.o: In function `ngx_stream_lua_preread_handler_file':
/data/apps/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5/src/ngx_stream_lua_prereadby.c:151: multiple definition of `ngx_stream_lua_preread_handler_file'
objs/addon/src/ngx_stream_lua_prereadby.o:/data/apps/openresty-1.13.6.2/bundle/ngx_stream_lua-0.0.5/src/ngx_stream_lua_prereadby.c:151: first defined here
collect2: error: ld returned 1 exit status
gmake[2]: *** [objs/nginx] Error 1
gmake[2]: Leaving directory `/data/apps/openresty-1.13.6.2/build/nginx-1.13.6'
gmake[1]: *** [build] Error 2
gmake[1]: Leaving directory `/data/apps/openresty-1.13.6.2/build/nginx-1.13.6'
gmake: *** [all] Error 2

why? source code has wrong?

**Comment by elonmia** [comment]
save issue, any updates?
