### ISSUE TITLE
Consideration with stable version of Nginx

### ISSUE THREAD

**Issue by mehrdadpfg** [openresty/openresty#429]
Hello dear agent zh,

I was wondering why are you using the mainline versions of Nginx instead of stable version?
is there any consideration, architecture matter, or any preference over stable version?
Also do we need to rebuild Openresty with stable Nginx version for production stage instead of 1.15.6? (for ex. we need HTTP push introduced in 1.13.9 so we need versions higher than Openresty 1.13.6)

Thanks a million.

**Comment by agentzh** [comment]
@mehrdadpfg Nginx's stable versions are just stable APIs. It's not that the mainline versions are unstable or anything like that. It's just that the mainline versions' APIs are not considered "stable".

In reality, nginx mainline versions get bug fixes and new features much faster. So we have no intention to stick with the stable series. Period.

This is an FAQ, BTW.
