### ISSUE TITLE
http.lua request_uri() method may have a potential bug while not have keepalive params to call it

### ISSUE THREAD

**Issue by innfuns** [openresty/openresty#430]
when I call request_uri() like
local resp, err = httpc:request_uri(hostUrl, {  
    method = "GET",  
    path = requestBody
})
it throws a exception like this
runtime error: /usr/***/http.lua:909: bad argument #2 to 'set_keepalive' (number expected, got nil)
so I check the source code of http.lua in the line 909
 902     if params.keepalive == false then
 903         local ok, err = self:close()
 904         if not ok then
 905             ngx_log(ngx_ERR, err)
 906         end 
 907         
 908     else
 909         local ok, err = self:set_keepalive(params.keepalive_timeout, params.keepalive_pool)
 910         if not ok then
 911             ngx_log(ngx_ERR, err)
 912         end
 913 

we could see that in line 902,  if(params.keepalive == false)
the expression params.keepalive == false may return false in condition that keepalive is just nil
so I think it may a BUG,hope you can fix it,thanks

**Comment by innfuns** [comment]
now we will have to add additional params like 
httpc:request_uri(hostUrl, {
method = "GET",
path = requestBody,
keepalive=false
}) to fix it temporily

**Comment by innfuns** [comment]
but in the past,if you not have a keepalive param,it will works,so I guess that change the code if params.keepalive == false to if not params.keepalive will fix the problem

**Comment by innfuns** [comment]
but better to judge condition obviously

**Comment by agentzh** [comment]
The lua-resty-http library is not maintained by the official OpenResty team. Maybe you should contact the maintainers/authors of that library instead? We cannot really help.
