### ISSUE TITLE
support proxy_socket_keepalive?

### ISSUE THREAD

**Issue by diluga** [openresty/openresty#432]
https://github.com/nginx/nginx/commit/1305b8414d22610b0820f6df5841418bf98fc370  is that any plan to support this feature？

**Comment by liqlin2015** [comment]
@agentzh Do you know the release plan of v1.15.8?  When the new version will be released?

**Comment by agentzh** [comment]
@liqlin2015 See

https://openresty.org/en/ann-1015008001rc1.html

We're preparing 1.15.8.1 RC1 these days. Once the latest RC versions are good enough, we'll kick out the 1.15.8.1 formal. It should happen this month, if no serious regressions come up.

**Comment by agentzh** [comment]
Consider it resolved.
