### ISSUE TITLE
openresty-1.13.6.2-win64 unable to start, error code 0xc000001d

### ISSUE THREAD

**Issue by sanmaozhao** [openresty/openresty#436]
This problem is not all machines, and two are found:
One is win7 sp1 and the other is win2008r2 sp1.
openresty-1.13.6.2-win32 version on the problem machine can start properly.

All binaries are official builds and downloaded from here:
https://openresty.org/download/openresty-1.13.6.2-win64.zip

The complete error is as follows:

Nginx.exe
The application was unable to start correctly 0xc000001d. click ok to close the application.
OK

Please give pointers about what might be the problem? Thanks!

**Comment by agentzh** [comment]
Are you sure the problematic systems are indeed 64-bit? The binary was tested on Windows 10 only. You could try using the MinGW2 project's gdb to debug the crash. Hopefully we can get some backtraces. We never tested on win7 or win2008 ourselves.

**Comment by sanmaozhao** [comment]
Thank you for your quick reply.
The system is really 64-bit, I will try to install gdb and get backtraces.

![default](https://user-images.githubusercontent.com/6970742/50129806-a6a9e900-02b5-11e9-9e2b-3baeac9a76c7.png)

**Comment by agentzh** [comment]
@sanmaozhao Please beware that 64-bit CPUs are able to run 32-bit Windows systems. I suggest you follow Microsoft's document below to check of your operating system is indeed 64-bit:

https://support.microsoft.com/en-us/help/827218/how-to-determine-whether-a-computer-is-running-a-32-bit-version-or-64

**Comment by sanmaozhao** [comment]
Here is gdb log(I used gdb for the first time, I don't know if the information is correct):

C:\mingw64\bin>gdb C:\openresty-1.13.6.2-win64\nginx.exe
GNU gdb (GDB) 7.1.90.20100730-cvs
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from C:\openresty-1.13.6.2-win64\nginx.exe...done.
(gdb) r
Starting program: C:\openresty-1.13.6.2-win64\nginx.exe
[New Thread 2332.0x204]

Program received signal SIGILL, Illegal instruction.
x64_init_random_constructor () at C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/7.3.0/include/smmintrin.h:841
841     C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/7.3.0/include/smmintrin.h: No such file or directory.
        in C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/7.3.0/include/smmintrin.h
(gdb) bt
#0  x64_init_random_constructor () at C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/7.3.0/include/smmintrin.h:841
#1  0x0000000066dd9e52 in __do_global_ctors () from C:\openresty-1.13.6.2-win64\lua51.dll
#2  0x0000000066d812cf in __DllMainCRTStartup () from C:\openresty-1.13.6.2-win64\lua51.dll
#3  0x0000000077527ace in ntdll!RtlDeleteAce () from C:\Windows\system32\ntdll.dll
#4  0x00000000002d6a50 in ?? ()
#5  0x0000000000000000 in ?? ()
(gdb)

**Comment by agentzh** [comment]
@sanmaozhao Sorry for the late reply. Are you using an AMD CPU?

**Comment by sanmaozhao** [comment]
> 
> 
> @sanmaozhao Sorry for the late reply. Are you using an AMD CPU?

The gdb log is obtained on an **Intel Xeon E7420** computer(virtual machine). The other problematic machine is the **AMD A6-3400M** CPU(physical machine).

**Comment by agentzh** [comment]
Our windows binaries currently require CPUs with the SSE 4.2 instruction set though we will relax this for CPUs without it.

**Comment by sanmaozhao** [comment]
I changed a computer with newer CPU,  and everything is ok.
Thanks.

**Comment by NerdyProjects** [comment]
I think I am also hitting this "bug" in #651
