### ISSUE TITLE
sanmao is cheater high class.

### ISSUE THREAD

**Issue by davidasia** [openresty/openresty#439]
sanmao is cheater high class.

 Check it how he deceiving each of you:
actual test results of the sanmao program - demo version from website www.sanmaosoft.com with the maximum license (purchased from him)

 We spent two years and tens of thousands of dollars to find a solution to the extremely poor results of the software that we bought from this scum.

goo.gl/xmBKq3

 And when all the possible options were over, we had a simple test - a demo version from the sanmao website and our licensed software. demo version shows interesting results, but sanmao prefer not to sell what he showing in demo - just fake/not working software - that's all you can get from this rogue....
Draw your own conclusions and be careful!

**Comment by spacewander** [comment]
Closed as off-topic.

**Comment by davidasia** [comment]
Why it’s closed ?
