### ISSUE TITLE
server_tokens off not working with openresty

### ISSUE THREAD

**Issue by kkmuffme** [openresty/openresty#440]
When using server_tokens off; openresty will still add a "Server: openresty" header.

Why? When I don't want to have server header, why does openresty still add one?

This "feature" was introduced here:
https://openresty.org/en/changelog-1013006.html
since Version 1.13.6.1:
"change: applied a patch to the nginx core to make sure the "server" header in HTTP/2 response shows "openresty" when the server_tokens diretive is turned off."

**Comment by agentzh** [comment]
Just use the `more_clear_headers` directive provided by the ngx_echo module (also enabled by default in OpenResty). See

https://github.com/openresty/headers-more-nginx-module#more_clear_headers
