### ISSUE TITLE
openssl module  not found in windows platform. need help how to add openssl module  in openresty for windows platform 

### ISSUE THREAD

**Issue by gaurav13uniyal** [openresty/openresty#453]
getting below error in openresty in windows platform

In my configuration I required below modules
openssl
sha

If i need to build openresty from source then what are the steps for same.

Error Details
2019/02/06 14:36:44 [error] 5468#1180: *1 failed to run set_by_lua*: set_by_lua:1: module 'openssl' not found:
	no field package.preload['openssl']
	no file './site/lualib/openssl.ljbc'
	no file './site/lualib/openssl/init.ljbc'
	no file './lualib/openssl.ljbc'
	no file './lualib/openssl/init.ljbc'
	no file './site/lualib/openssl.lua'
	no file './site/lualib/openssl/init.lua'
	no file './lualib/openssl.lua'
	no file './lualib/openssl/init.lua'
	no file '.\openssl.lua'
	no file 'C:\openresty\lualib\openssl.lua'
	no file 'C:\openresty\lua\openssl.lua'
	no file 'C:\openresty\lua\openssl\init.lua'
	no file './site/lualib/openssl.so'
	no file './lualib/openssl.so'
	no file '.\openssl.dll'
	no file 'C:\openresty\lualib\openssl.so'
	no file 'C:\openresty\openssl.dll'
	no file 'C:\openresty\loadall.dll'
stack traceback:
	[C]: in function 'require'
	set_by_lua:1: in function <set_by_lua:1>, client: 192.168.9.179, server: vbs-usr-pc179.vserv-it.com, request: "GET / HTTP/2.0", host: "vbs-usr-pc179.vserv-it.com"

**Comment by agentzh** [comment]
@gaurav13uniyal OpenResty does not provide the `openssl` Lua module. Maybe you should install and configure it yourself? Not sure what the `openssl` Lua module really is. Never used any Lua modules of that name myself.

**Comment by gaurav13uniyal** [comment]
@agentzh 
I am using below code in nginx config file
set_by_lua $couchdb_username 'if ngx.var.https == "on" then return string.match(require("openssl").x509.read(ngx.var.ssl_client_raw_cert):subject():oneline(),"/CN=([^/]+)") end return nil';
           set_by_lua $couchdb_token 'if ngx.var.couchdb_username ~= nil and ngx.var.couchdb_username ~= "" then return require("sha1").hmac("secretkey",ngx.var.couchdb_username) end return nil';
can you please share if there is any aletrnative or same.

can you please share what steps I need to follow install and configure required module in windows environment
