### ISSUE TITLE
Openresty 1.13.6.2, Docker releases, OpenSSL 1.1.1 and TLS 1.3 

### ISSUE THREAD

**Issue by Soulou** [openresty/openresty#454]
Hello good morning,

Last version of Openresty is shipped with nginx **1.13** which is TLSv1.3 compatible. However all the docker images released are using OpenSSL **1.1.0i** which is not compatible with TLSv1.3. (The first version being compatible is **1.1.1**. As a result none of the images are compatible with TLSv1.3

Any specific reason it has not been bundled with this version of OpenSSL or can I try to do it for my needs without expecting the whole thing to explode?

Thanks a lot!

**Comment by Soulou** [comment]
For info, appart the following build error https://github.com/openssl/openssl/issues/3884#issuecomment-313857555 requiring a fix of the nginx 1.13.6 Makefile, the build went well.

TLS 1.3 is now correctly enabled with my openresty 1.13.6.2 / OpenSSL 1.1.1, it seems to work as expected.

**Comment by thibaultcha** [comment]
As stated in #456, we'll upgrade OpenSSL to 1.1.1 when we get to update our patches.
