### ISSUE TITLE
vrf support ?

### ISSUE THREAD

**Issue by pkking** [openresty/openresty#457]
dear team,
  I have a openresty running on a box with 2 different vrf, is it possible to change socketopts of each requests so that i can ensure openresty can connect to the service in a different vrf successfully?
  Be more specific, i want openresty run on a vrf as a proxy to serve requests from outside and can also connect to another service behind it in a different vrf.

**Comment by agentzh** [comment]
@pkking There are many ways we could do this. The simplest way is to expose the fd number from cosocket objects (by a new method, for example) and then call the C API function `setsockopt()` or alike via LuaJIT FFI upon this fd. This also ensures the maximum flexibility. You are welcome to submit a pull request to add a `fd()` method to the cosocket objects (we need to be careful about exotic operating systems like Windows here though).

**Comment by pkking** [comment]
Thanks for your reply.
Does that means we need **a piece of patch** to let openresty expose the request socket fd that use to connect to the backend in another vrf?
We also need to add some config vars to specific the vrf device name passed to the `setsockopt()` as well, is that correct?

**Comment by agentzh** [comment]
@pkking Depending on whether you are using Lua to talk to the backend or the proxy module. For the former, yes.

**Comment by pkking** [comment]
Got it, thanks
