### ISSUE TITLE
would you please add ngx_http_proxy_connect_module into openresty?

### ISSUE THREAD

**Issue by sanholy** [openresty/openresty#459]
有一个需求，想用nginx做正向代理并基于内网的源ip和目的域名做访问控制，redis的key值为源ip，目的域名是1个list。但是内网较多都是商业软件，访问的都是https也有http，原生nginx不支持connect，只能用ngx_http_proxy_connect_module。目前是自己在nginx+ngx_http_proxy_connect_module+openresty里面的几个模块自己搞定了，如果openresty加进来就更好了。

https://github.com/chobits/ngx_http_proxy_connect_module#proxy_connect_allow

感觉这个需求还是比较多的，建议下哈。

**Comment by agentzh** [comment]
Please, no Chinese here. This place is considered English only. If you really
want to use Chinese, please join the openresty (Chinese) mailing list instead.
Please see https://openresty.org/en/community.html Thanks for your cooperation.

Regarding to your request, you can always add new modules to OpenResty in the same way as with NGINX. See

https://openresty.org/en/installation.html#building-from-source
