### ISSUE TITLE
TLS does not work for TCP proxy

### ISSUE THREAD

**Issue by drasko** [openresty/openresty#463]
Ensure you have provided the following details while reporting a problem:

- [x] The exact version of the related software, including but not limited to the OpenResty version
(if any), the NGINX core version, the `ngx_lua` module version(via `openresty -V` or `nginx -V`),
and your operating system version(via `uname -a`).

`alpine` docker from DockerHub

- [x] **A minimal and standalone test case** that others can easily run on their side and
reproduce the issue you are seeing.

This works for mainstream NginX, but not for OpenResty:
```
# MQTT
stream {
    # MQTT
    server {
        listen 8883 ssl;
        listen [::]:8883 ssl;

        # Certificates
        ssl_certificate /etc/ssl/certs/mainflux-server.crt;
        ssl_certificate_key /etc/ssl/private/mainflux-server.key;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;

        # from https://cipherli.st/
        # and https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
        ssl_ecdh_curve secp384r1;
        ssl_session_tickets off;
        resolver 8.8.8.8 8.8.4.4 valid=300s;
        resolver_timeout 5s;

        proxy_pass mqtt-adapter:1883;
    }
}
```

- [x] Do not simply say "something is broken" or "something does not work". Always provide
as much details as possible. Always describe **the symptoms and your expected results**.

This hangs:
```
mosquitto_pub -h localhost -d  -t test -m "hello again" -p 8883 --cafile ./ca.crt 
```

**Comment by drasko** [comment]
Related to https://github.com/openresty/docker-openresty/issues/90

**Comment by neomantra** [comment]
Can you include how you are running this, especially since you are including other service dependencies.  From the other issues, you seem to be using `docker-compose`, which is great for sharing.  Maybe post a  version of that with the config files and how you are running it so it's easier for us to help you by reproducing or inspecting

**Comment by alexjames98** [comment]
> 
> 
> Ensure you have provided the following details while reporting a problem:
> 
>     * [x]  The exact version of the related software, including but not limited to the OpenResty version
>       (if any), the NGINX core version, the `ngx_lua` module version(via `openresty -V` or `nginx -V`),
>       and your operating system version(via `uname -a`).
> 
> 
> `alpine` docker from DockerHub
> 
>     * [x]  **A minimal and standalone test case** that others can easily run on their side and
>       reproduce the issue you are seeing.
> 
> 
> This works for mainstream NginX, but not for OpenResty:
> 
> ```
> # MQTT
> stream {
>     # MQTT
>     server {
>         listen 8883 ssl;
>         listen [::]:8883 ssl;
> 
>         # Certificates
>         ssl_certificate /etc/ssl/certs/mainflux-server.crt;
>         ssl_certificate_key /etc/ssl/private/mainflux-server.key;
>         ssl_dhparam /etc/ssl/certs/dhparam.pem;
> 
>         # from https://cipherli.st/
>         # and https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
> 
>         ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
>         ssl_prefer_server_ciphers on;
>         ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
>         ssl_ecdh_curve secp384r1;
>         ssl_session_tickets off;
>         resolver 8.8.8.8 8.8.4.4 valid=300s;
>         resolver_timeout 5s;
> 
>         proxy_pass mqtt-adapter:1883;
>     }
> }
> ```
> 
>     * [x]  Do not simply say "something is broken" or "something does not work". Always provide
>       as much details as possible. Always describe **the symptoms and your expected results**.
> 
> 
> This hangs:
> 
> ```
> mosquitto_pub -h localhost -d  -t test -m "hello again" -p 8883 --cafile ./ca.crt 
> ```

Get into the same problem.

**Comment by neomantra** [comment]
@drasko So was this resolved by mounting the config file to the correct path?  It was that the service wasn't up at all?   

Or is there a separate TLS issue?

**Comment by drasko** [comment]
@neomantra no, this is the one that was resolved by mounting config file where it should be.

@alexjames98 this one should help you: https://github.com/openresty/docker-openresty/issues/90

Closing this one now.
