### ISSUE TITLE
Still get xpcall when use the newest version openresty-1.15.8.1rc1 on ARM64

### ISSUE THREAD

**Issue by david-holonet** [openresty/openresty#464]
When using openresty-1.13.6.2 on ARM64(aarch64), there is cjson error message when process inits.  
And when I upgrade it to the newest version 1.15.8.1rc1, the error message disappeared.  
And another xpcall occurs when the process called ngx.re.match, and the error message is:
```
bad light userdata pointer
```
Who will tell me what's the reason? Thanks a lot.

**Comment by agentzh** [comment]
@david-holonet Because OpenResty 1.15.8.1 RC1 is the first version with proper AArch64 support. Older versions just do not work.

**Comment by agentzh** [comment]
@david-holonet Read the change log of OpenResty 1.15.8.1 RC1:

https://openresty.org/en/ann-1015008001rc1.html

**Comment by david-holonet** [comment]
My question is for 1.15.8.1rc1, coredump at ngx.re.match.
the code here is:
```
local m,err = ngx.re.match(host,"([^.]+)","jio")
```

**Comment by agentzh** [comment]
@david-holonet You must put the following to the `http {}` block of your nginx.conf:

```nginx
init_by_lua_block { require "resty.core" }
```

The default CFunction-based ngx.re API implementation just does not support AArch64. We're retiring the current CFunction-based implementation very soon.

**Comment by agentzh** [comment]
@thibaultcha Seems like we should enable lua-resty-core by default in this 1.15.8.1 release? The old CFunction-based implementation is too troublesome (not just this issue, but also potential deadlock issues when using lua-resty-lock).

**Comment by david-holonet** [comment]
Good job.  
I put `require "resty.core"` in init_by_lua_file, and it works now.  
Thanks a lot.
