### ISSUE TITLE
Still get xpcall when use the newest version openresty-1.15.8.1rc1 on ARM64

### ISSUE THREAD

**Issue by david-holonet** [openresty/openresty#465]
My question is for 1.15.8.1rc1, coredump at ngx.re.match. The original issue is closed, so I have to create this issue.  
the code here is:  
```
local m,err = ngx.re.match(host,"([^.]+)","jio")
```

_Originally posted by @david-holonet in https://github.com/openresty/openresty/issues/464#issuecomment-473737187_

**Comment by thibaultcha** [comment]
Thanks for reporting, we’ll look into it very soon.

**Comment by agentzh** [comment]
@david-holonet We can re-open the original issue. Closing this now as duplicate.
