### ISSUE TITLE
difference of minilua.c `f_parser` against  lj_load.c `cpparser` when initializing closure's `env`

### ISSUE THREAD

**Issue by socoding** [openresty/openresty#467]
As you see the following code which was marked as bold and italic, there is some difference of initializing closure's `env`. f_parser in minilua.c initializes the closure's env as gt(L) while cpparser in lj_load.c initializes it as L->env. 
If  f_parser in minilua.c was used to parse a lua file, _G is always the global G lua state which all services in one prossess shares. 

**minilua.c**
static void f_parser(lua_State*L,void*ud){
int i;
Proto*tf;
Closure*cl;
struct SParser*p=cast(struct SParser*,ud);
luaC_checkGC(L);
tf=luaY_parser(L,p->z,
&p->buff,p->name);
**_cl=luaF_newLclosure(L,tf->nups,hvalue(gt(L)));_**
cl->l.p=tf;
for(i=0;i<tf->nups;i++)
cl->l.upvals[i]=luaF_newupval(L);
setclvalue(L,L->top,cl);
incr_top(L);
}
static int luaD_protectedparser(lua_State*L,ZIO*z,const char*name){
struct SParser p;
int status;
p.z=z;p.name=name;
luaZ_initbuffer(L,&p.buff);
status=luaD_pcall(L,f_parser,&p,savestack(L,L->top),L->errfunc);
luaZ_freebuffer(L,&p.buff);
return status;
}

**VS**

**lj_load.c**
static TValue *cpparser(lua_State *L, lua_CFunction dummy, void *ud)
{
  LexState *ls = (LexState *)ud;
  GCproto *pt;
  GCfunc *fn;
  int bc;
  UNUSED(dummy);
  cframe_errfunc(L->cframe) = -1;  /* Inherit error function. */
  bc = lj_lex_setup(L, ls);
  if (ls->mode && !strchr(ls->mode, bc ? 'b' : 't')) {
    setstrV(L, L->top++, lj_err_str(L, LJ_ERR_XMODE));
    lj_err_throw(L, LUA_ERRSYNTAX);
  }
  pt = bc ? lj_bcread(ls) : lj_parse(ls);
  **_fn = lj_func_newL_empty(L, pt, tabref(L->env));_**
  /* Don't combine above/below into one statement. */
  setfuncV(L, L->top++, fn);
  return NULL;
}

LUA_API int lua_loadx(lua_State *L, lua_Reader reader, void *data,
		      const char *chunkname, const char *mode)
{
  LexState ls;
  int status;
  ls.rfunc = reader;
  ls.rdata = data;
  ls.chunkarg = chunkname ? chunkname : "?";
  ls.mode = mode;
  lj_buf_init(L, &ls.sb);
  status = lj_vm_cpcall(L, NULL, &ls, cpparser);
  lj_lex_cleanup(L, &ls);
  lj_gc_check(L);
  return status;
}

**Comment by agentzh** [comment]
minilua is never used by LuaJIT, nor the OpenResty. It's only used to build the LuaJIT itself. It's a pity that you are looking at the code which is never used by your OpenResty nor LuaJIT installations.
