### ISSUE TITLE
redis set_keepalive function seems have bug on MIPS platform

### ISSUE THREAD

**Issue by ayrtonLiu** [openresty/openresty#477]
code like this 
 local ok, err = red:set_keepalive(10000, 20)
  if not ok then
    ngx.log(ngx.ERR, "Set redis keepalive error: "..err)
  end
log: Set redis keepalive error: unread data in buffer
the first time call is ok, next may have this problem

**Comment by agentzh** [comment]
@ayrtonLiu This is your own usage mistake. You can never reuse any connections with unread data in the read buffer. Read them all. It has nothing to do with MIPS anyway. And the error message is very clear about your usage mistake.

**Comment by ayrtonLiu** [comment]
Thank you very much, i get it.



At 2019-04-18 14:44:01, "Yichun Zhang" <notifications@github.com> wrote:


@ayrtonLiu This is your own usage mistake. You can never reuse any connections with unread data in the read buffer. Read them all. It has nothing to do with MIPS anyway. And the error message is very clear about your usage mistake.
