### ISSUE TITLE
openresty 1.13 版本配置反向代理https

### ISSUE THREAD

**Issue by yaoshenshen** [openresty/openresty#482]
openresty 1.13 版本配置反向代理https

配置
  proxy_pass https://www.test.cn;

会提示no resolver defined to resolve www.test.cn ，我尝试在配置文件中在http 中加入
resolver 114.114.114.114；还是会提示

配置proxy_pass https://192.168.100.1;   这样就会没有问题，请问这是什么原因

**Comment by agentzh** [comment]
Please, do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see https://openresty.org/en/community.html Thanks for your cooperation
