### ISSUE TITLE
Does openstry have http header range bug?

### ISSUE THREAD

**Issue by ricardo-ml** [openresty/openresty#486]
Does openstry have http header range bug?

**Comment by agentzh** [comment]
@ricardo-ml It's too vague. What range bug are you referring to?

**Comment by ricardo-ml** [comment]
like apache range dos attack. i didn't test for it. just hear of it.

**Comment by ricardo-ml** [comment]
Quote: https://www.cnblogs.com/princessd8251/articles/3853421.html

**Comment by agentzh** [comment]
We're not interested in such imaginary bugs that you haven't even tried yourself.
