### ISSUE TITLE
attempt to call field 'decode' (a nil value)

### ISSUE THREAD

**Issue by jobs-git** [openresty/openresty#493]
Error from latest centos 7 installer, cjson is not working

**Comment by agentzh** [comment]
@jobs-git What's your configuration and code? I just tried the official OpenResty rpm packages on CentOS 7 and cjson works well:

```shell
[agentzh@centos7 ~]$ which resty
/usr/local/openresty-plus/bin/resty

[agentzh@centos7 ~]$ resty -V |& head -n2
resty 0.25
nginx version: openresty+/1.15.8.1.2

[agentzh@centos7 ~]$ resty -e 'local cjson = require "cjson" print(cjson.encode(cjson.decode([[{"foo":5}]])))'
{"foo":5}
```

**Comment by jobs-git** [comment]
I am using nginx, used these local cjson = require "cjson", when I call cjson.decode it says field not found nil

**Comment by agentzh** [comment]
@jobs-git The cjson library is shipped with OpenResty, not NGINX. Better switch to OpenResty to avoid such troubles on both sides (your side and our side).
