### ISSUE TITLE
Missing SSL_ERROR_WANT_CLIENT_HELLO_CB in nginx-1.15.8-ssl_cert_cb_yield.patch

### ISSUE THREAD

**Issue by crasyangel** [openresty/openresty#494]
[feature: added OpenSSL 1.1.1 support to ssl_session_fetch_by_lua*.](https://github.com/openresty/lua-nginx-module/commit/a38d9066787f6fe311135fc512004b1bc19ba1ac)

https://raw.githubusercontent.com/openresty/openresty/master/patches/nginx-1.15.8-ssl_cert_cb_yield.patch

SHOULD return NGX_AGAIN when SSL_get_error return **SSL_ERROR_WANT_CLIENT_HELLO_CB**

**Comment by crasyangel** [comment]
https://raw.githubusercontent.com/openresty/openresty/master/patches/nginx-1.15.8-ssl_pending_session.patch

This patch is not found, but it appears in https://openresty.org/en/nginx-ssl-patches.html

**Comment by crasyangel** [comment]
Another question, where is the definition of HAVE_SSL_CLIENT_HELLO_CB_SUPPORT?

**Comment by thibaultcha** [comment]
@crasyangel Hi,

Have a look at this patch: https://raw.githubusercontent.com/openresty/openresty/master/patches/nginx-1.15.8-ssl_sess_cb_yield.patch (notice the name change).

We renamed the `ssl_pending_session.patch` to `ssl_sess_cb_yield.patch` for the 1.15.8 version of this patch. You will find there that we return `NGX_AGAIN` on `SSL_ERROR_WANT_CLIENT_HELLO_CB`, and you will also find the definition of `HAVE_SSL_CLIENT_HELLO_CB_SUPPORT` there.

An easy way to realize you might be missing something is to look at the CI build: you will see that it is passing without any issues with OpenSSL 1.0.2, 1.1.0, and 1.1.1: https://travis-ci.org/openresty/lua-nginx-module/builds/541530664

The website documentation you pointed to hasn't been updated yet, the PR is pending here: https://github.com/openresty/openresty.org/pull/99

Best,
