### ISSUE TITLE
add nginx module Nginx-limit-traffic-rate-module to ngx_openresty-1.9.7.1-win32

### ISSUE THREAD

**Issue by luliloveshe** [openresty/openresty#495]
There is currently a need, I need to use the Nginx-limit-traffic-rate-module. I downloaded the ngx_openresty-1.9.7.1 source code and Nginx-limit-traffic-rate-module source code. Because I have not been exposed to C  development, there is no way to start. Can you give a specific operation document?

**Comment by gjongenelen** [comment]
Openresty install is very similar to nginx. So you can just follow regular openresty installation guides. 

At configure-step add the argument ` --add-module=path/to/nginx/limit/module ` and install.

**Comment by thibaultcha** [comment]
Indeed! Considering this answered, thanks!
