### ISSUE TITLE
unknown directive "content_by_lua_file" in /etc/nginx/sites-enabled/my_site.com

### ISSUE THREAD

**Issue by GildedHonour** [openresty/openresty#501]
After installing everything -- nginx, Lua, LuaJit,  openresty, etc -- and starting nginx, I get this:

`    unknown directive "content_by_lua_file" in /etc/nginx/sites-enabled/my_site.com`

What did I forget? Should have been enabled Lua support somehow when I was installing nginx? How?

It's Arch Linux, my script will run on **LuaJit**

**Comment by gjongenelen** [comment]
The fact that you installed nginx is not correct. OpenResty replaces nginx.
You are probably starting the 'regular' nginx which has no support for Lua out of the box.
Please read the install instructions carefully: https://openresty.org/en/installation.html

**Comment by dndx** [comment]
Your Nginx does not have OpenResty properly built into. Please use our [pre-packaged source](https://openresty.org/en/download.html) to install OpenResty instead of doing it on your own.
