### ISSUE TITLE
Openresty do not support the master branch of  nginx_upstream_check_module

### ISSUE THREAD

**Issue by ox123** [openresty/openresty#504]
## openresty version
- 1.15.8.1
## nginx_upstream_check_module(https://github.com/yaoweibin/nginx_upstream_check_module)
- use the master branch 

## issues
1.  we found that the configuration which using the method of nginx_upstream_check_module did not work. is there any way to resolve this issues? or what shoud we to change if we want to use this upstream health check module?
2. We use the version 1.13.6.1 of the openresty, and compile with the  the nginx_upstream_check_module methioned above is ok, it works fine.

**Comment by agentzh** [comment]
@ox123 I think that 3rd-party module just fails to be compatible with newer nginx cores. You can try the standard nginx 1.15.8 core downloaded from https://nginx.org.

Please note that we only make sure our open source OpenResty is compatible with standard nginx core, standard nginx modules and our own 3rd-party modules. Any other 3rd-party nginx modules are not officially supported. You should really contact the maintainers of those 3rd-party modules, not us.
