### ISSUE TITLE
subrequest access.log not working correctly when using ngx.location.capture()

### ISSUE THREAD

**Issue by ex3yop** [openresty/openresty#505]
version: openresty/1.15.8.1,  OS:wsl-ubuntu18.04

when using "log_subrequest on" in subrequest, the subrequest not appear in access.log, instead, the main request log twice.  i made a minimal test as bellow:

```
#nginx.conf
worker_processes  4;
events {worker_connections  1024;}
http {
    lua_code_cache off;
    server {
        listen 81;
        error_log logs/error.log;
        access_log  logs/access.log;
        location =/main {
            content_by_lua_block {
                local res = ngx.location.capture("/sub")
                ngx.say(res.body)
             }
        }
        location =/sub {
            log_subrequest on;
            content_by_lua_block {
                ngx.say("hello")
             }
        }
    }
}
```

when visit /main, the access.log looks something like this, there's no /sub in it:
127.0.0.1 - - [10/Jul/2019:21:11:20 +0800] "GET /main HTTP/1.1" 200 0 "-" "Mozilla/5.0..."
127.0.0.1 - - [10/Jul/2019:21:11:20 +0800] "GET /main HTTP/1.1" 200 17 "-" "Mozilla/5.0..."

**Comment by ex3yop** [comment]
it seems $request always log the main request, this is not a bug.

**Comment by madalion** [comment]
hello ,how do you resolve this issue,I meet this problem too.

**Comment by zhuizhuhaomeng** [comment]
> it seems $request always log the main request, this is not a bug.
Yes， that's right
