### ISSUE TITLE
how to solve the problem"ld returned 1 exit status" when I upgrade openrestry to 1.15.8.1 on the Centos7.6.1810

### ISSUE THREAD

**Issue by hepyu** [openresty/openresty#507]
The error occurs when gmake.

![image](https://user-images.githubusercontent.com/3917749/61205162-eb99df00-a721-11e9-8475-74920a34b26e.png)

**Comment by hepyu** [comment]
I'm so confused that no useful information.

**Comment by hepyu** [comment]
this is my configure command:

./configure --prefix=/app/3rd/nginx/openresty --with-cc-opt=-O2 --add-module=build/ngx_devel_kit-0.3.1rc1 --add-module=build/iconv-nginx-module-0.14 --add-module=build/echo-nginx-module-0.61 --add-module=build/xss-nginx-module-0.06 --add-module=build/ngx_coolkit-0.2 --add-module=build/set-misc-nginx-module-0.32 --add-module=build/form-input-nginx-module-0.12 --add-module=build/encrypted-session-nginx-module-0.08 --add-module=build/srcache-nginx-module-0.31 --add-module=build/ngx_lua-0.10.15 --add-module=build/ngx_lua_upstream-0.07 --add-module=build/headers-more-nginx-module-0.33 --add-module=build/array-var-nginx-module-0.05 --add-module=build/memc-nginx-module-0.19 --add-module=build/redis-nginx-module-0.3.7 --add-module=build/rds-json-nginx-module-0.15 --add-module=build/rds-csv-nginx-module-0.09 --add-module=build/ngx_stream_lua-0.0.7 --with-ld-opt=-Wl,-rpath,/app/3rd/nginx/openresty/luajit/lib --add-module=/app/3rd/src-install/ngx_http_consistent_hash --with-http_stub_status_module --with-pcre-jit --with-stream_ssl_preread_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_v2_module --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-openssl=/opt/openresty/openssl-1.1.0i --with-dtrace-probes --with-stream --with-stream_ssl_module

**Comment by agentzh** [comment]
@hepyu ngx_stream_lua_module is already enabled in OpenResty by default. Your linker errors clearly indicate that. You should remove the option `--add-module=build/ngx_stream_lua-0.0.7`.

**Comment by hepyu** [comment]
3Q, it works~
