### ISSUE TITLE
Hello, why copy the directory  of bundle to the directory  of build, if the c file is modified, re-copy and compile again?

### ISSUE THREAD

**Issue by ygm521** [openresty/openresty#509]
Hello, ask why copy the bundle directory to the build, if the c file is modified, re-copy and compile again?For example, modified a simple function, re-copy, re-compile openssl?

**Comment by ygm521** [comment]
For example, modified a simple function, re-copy, re-compile openssl?

**Comment by agentzh** [comment]
@ygm521 Well, you could just edit the source code in the `build/` directory and then run `make -jN` to do an incremental compilation as long as you do *not* run the `./configure` command line again.

**Comment by ygm521** [comment]
such Generate ngx_auto_config.h，i should add   build directory to my project？Why not compile directly like the official nginx? Do you have to copy the source code to compile? i think This method is stupid.

**Comment by agentzh** [comment]
@ygm521 Well, the idea is to avoid polluting the original source directory (`bundle/`) with `.o` files, `.so` files and etc. So a clean rebuild is guaranteed. Please do not assume we are stupid ;)
