### ISSUE TITLE
misc/unwind-generic.h unused, potential license issue?

### ISSUE THREAD

**Issue by chewi** [openresty/openresty#513]
I'd like to clarify the situation around misc/unwind-generic.h. It was added 8 years ago in 1276fbdf4858d8a644a0dd4c70e7b28cd8990b14 to fix builds on BSD. It is not clear whether it was also used over system versions on other platforms. The only line explicitly referencing it was commented out a year later in e8990b7d030304e4fc6a4c782370dbb6739746a8. Is it therefore no longer used?

If it is still used then I believe there is a licensing issue, at least on FreeBSD. The GPL-2 license extends to the executable being built unless it is being built with GCC. That was the default compiler on FreeBSD at the time but it has long since switched to LLVM's Clang.

**Comment by agentzh** [comment]
@chewi Yeah, it should be removed I believe.

**Comment by agentzh** [comment]
Pull requests welcome!
