### ISSUE TITLE
set cookie by Lua will change html MIME-TYPE 

### ISSUE THREAD

**Issue by skytsai3321** [openresty/openresty#52]
when I set nginx config like this
server {
    ......
    set_by_lua $xyz "
        ngx.header['Set-Cookie'] = {'___obj=123'}
        return '123'
    ";
    ......
}

but I browse my html file by google chrome, it will be a download file not show on the browser. I check the html mime-type is application/octet-stream.

when I comment the set cookie, everything will be fine. Could you tell me why?

**Comment by dersimn** [comment]
Did you implement the `ngx.resp.add_header()` thing, or?
