### ISSUE TITLE
Issue in build and test case execution 

### ISSUE THREAD

**Issue by SantoshMagdum** [openresty/openresty#521]
Hi,
I am trying to build the openresty on RHEL 7.6 ppc64le platform. I had patched the LuaJIT2 code for ppc64le specific changes and I could build then openresty which created nginx binary.
I am still looking at the few build issues while running nginx but I have some queries on running the test suits for openresty - https://github.com/openresty/openresty

I notice, two of the test suits can be used to run openresty library tests –

1)	https://github.com/openresty/openresty/tree/master/t
	2)	https://github.com/openresty/test-nginx -
			The document indicates this is the test platform for testing openresty nginx.
			Document excerpt -
					"Test::Nginx - Data-driven test scaffold for Nginx C module and Nginx/OpenResty-based libraries and applications"
			And below test modules could be used to test the openresty nginx.
				https://github.com/openresty/echo-nginx-module
				https://github.com/openresty/headers-more-nginx-module
				https://github.com/openresty/drizzle-nginx-module
				https://github.com/openresty/rds-json-nginx-module
				https://github.com/openresty/rds-csv-nginx-module
				https://github.com/openresty/srcache-nginx-module
				https://github.com/openresty/xss-nginx-module
				https://github.com/openresty/lua-nginx-module
				https://github.com/openresty/set-misc-nginx-module
				https://github.com/openresty/array-var-nginx-module
				https://github.com/calio/form-input-nginx-module
				https://github.com/calio/iconv-nginx-module
				https://github.com/liseen/set-cconv-nginx-module
				https://github.com/FRiCKLE/ngx_coolkit
				https://github.com/nbs-system/naxsi
				https://github.com/nginx-shib/nginx-http-shibboleth

I see few test cases failures in both approches.

Kindly please help suggest,
		After successful build of openresty (https://github.com/openresty/openresty), which test suit I should be running? Should I refer #1 or #2 test suit or both?

Thanks in advance.
Santosh

**Comment by agentzh** [comment]
@SantoshMagdum See here for all the test suites we run before each release: https://qa.openresty.org/
