### ISSUE TITLE
Difference between openresty and tengine

### ISSUE THREAD

**Issue by CMCDragonkai** [openresty/openresty#54]
I saw that Taobao originally sponsored the development of openresty but now they focus on tengine. What's the relationship between openresty and tengine? Is there a place that compares the 2?

**Comment by bwalia** [comment]
Thanks @agentzh as always for your valiant efforts to keep things on track. However if I was building a web router service for 1000s of sites which one should I use openresty or tengine? Regards / Balinder

**Comment by agentzh** [comment]
@bwalia I would definitely recommend OpenResty, or even better, our commercial OpenResty Edge product: https://openresty.com

**Comment by bwalia** [comment]
This is really interesting. I have started building Web UI too for ops guys and 2nd level engineers. I should have known about openresty edge. Well I spend a lot time now. However just ignoring that side of things what we also require is real time bot mitigation, redirect services for example any non technical user can can add https://www.sun.com/sports redirect to http//www.thesunsports.com and immediately it purges caches etc and starts to redirect traffic micro site. Also auto https provisioning and renewals. Perhaps from letsencrypt. Also Edge side caching with real time purging and caching with business rules. I am really impressed with your edge offering so far. It seems you are on the right track going to PAAS model and big players like akamai and Fastly. Well now I know I will keep an eye on it. By the way is edge also open source? Or can I get involved in any way or form?

**Comment by agentzh** [comment]
@bwalia The OpenResty Edge product already supports real-time global cache purges, and also purging by tags and any custom conditions. And the automatic https provisioning and renewals support with Letsencrypt in the OpenResty Edge product is well under way (we can speed this up if real customers request this) though it's already possible with our RESTful API to automate the global SSL certificate updates. The real time bot mitigation and redirect services are already very easy to do with web forms in our OpenResty Edge Admin system, a centralized web console, even for nontechnical persons.

We do sell software licenses of OpenResty Edge, not really doing the PAAS model. Our customers deploy the whole OpenResty Edge software in their own machines.

The OpenResty Edge product is not an open source project. It's a commercial product we're selling. The best way to get involved is to become one of our paid customers and we can closely work with you to make Edge fit your needs best and to support you to customize and extend the Edge platform in your own way.
