### ISSUE TITLE
can't build  openresty-1.15.8.2.tar.gz on openbsd-6.6

### ISSUE THREAD

**Issue by zhaiyuzhen** [openresty/openresty#549]
Hi team,
      I can't build  openresty-1.15.8.2.tar.gz on openbsd-6.6, the same errors like described at https://github.com/openresty/openresty/issues/487.
I can build openresty-1.15.8.2rc0.tar.gz --with-ld-opt='-lc++abi -lpthread'  --with-luajit-ldflags='-lc++abi -lpthread' on openbsd-6.6.Please merge the specific for openbsd in the openresty-1.15.8.2rc0.tar.gz to the trunk,Thnk you!

**Comment by agentzh** [comment]
@zhaiyuzhen Not sure if we want to do that since it would be tricky to detect particular compiler versions and operating systems automatically in the `./configure` script. Or do you have a good enough patch to propose?

**Comment by agentzh** [comment]
@zhaiyuzhen We don't have OpenBSD around so we cannot really prepare such patches even if we want to.

**Comment by zhaiyuzhen** [comment]
@agentzh Considering that there are many scenarios using OpenBSD, I think it would be beneficial to do some work of adapting OpenBSD. I am not a development engineer, I'm afraid I can provide patches. I can provide a laptop with OpenBSD for you if you need.

**Comment by zhaiyuzhen** [comment]
I can build on FreeBSD 12.1 without any errors.So this issues can be closed.
