### ISSUE TITLE
cannot find resty.so ,core.so... files

### ISSUE THREAD

**Issue by arrow2012** [openresty/openresty#563]
openresty-1.15.8.2   source install

./configure --prefix=/data/app/openresty 

![image](https://user-images.githubusercontent.com/46478986/70404578-88fd0300-1a75-11ea-9118-c807755565e0.png)

the core.lua file in    /data/app/openresty/lualib/resty/core.lua 

#1533    https://github.com/openresty/lua-nginx-module/issues/1533
init_by_lua_block {
    -- 注释下面一行来禁用 lua-resty-core
    require 'resty.core'
}

 but . I cannot find resty.core file

**Comment by agentzh** [comment]
You seem to have permission problems in your path. Try assigning executable permission to your /data and /data/app directories for everyone, for example.

**Comment by agentzh** [comment]
Also you seem to configure lua_package_path directive incorrectly in your nginx.conf?

**Comment by arrow2012** [comment]
lua_package_path "/data/app/openresty/lualib/lua-resty-core/?.lua;data/app/openresty/lualib/resty/?.lua;/data/app/openresty/lualib/ngx/?.lua";

/data and /data/app directories are all 755

**Comment by agentzh** [comment]
Just remove that whole directive and it should work. Your configuration is indeed wrong.

**Comment by arrow2012** [comment]
the right path should be
lua_package_path “ /data/app/openresty/lualib/?.lua;/data/app/openresty/lualib/resty/?.lua;/data/app/openresty/lualib/ngx/?.lua “;

**Comment by agentzh** [comment]
You should never repeat the standard search paths in your own directive value. Just use ;; to indicate the std paths. Read the docs for the lua_package_path directive.

**Comment by agentzh** [comment]
Your latest directive value is still incorrect BTW. That's also why you should never repeat the std search paths yourself.

**Comment by arrow2012** [comment]
1
lua_package_path“ /data/app/openresty/lualib/?.lua;;“ ;

or

2
lua_package_path“ /data/app/openresty/lualib/?.lua;/data/app/openresty/lualib/resty/?.lua;/data/app/openresty/lualib/ngx/?.lua;;“ ;

or

3
lua_package_path“ /data/app/openresty/lualib/?.lua;;/data/app/openresty/lualib/resty/?.lua;;/data/app/openresty/lualib/ngx/?.lua;;“ ;



which one is the right?

**Comment by agentzh** [comment]
@arrow2012 Unless you have your own search paths, otherwise I don't see a reason you should configure `lua_package_path` yourself at all.

Say, you have your own search paths like `/foo/?.lua;/bar/baz/?.lua`, then you can just write

```nginx
lua_package_path "/foo/?.lua;/bar/baz/?.lua;;";
```

Otherwise you can just avoid configuring `lua_pacakge_path`.
