### ISSUE TITLE
 lua entry thread aborted: runtime error: content_by_lua(default.conf:35):2: no request found stack traceback:

### ISSUE THREAD

**Issue by YazaiHu** [openresty/openresty#564]
config:
location /test {
		set $a 12;
		content_by_lua_block {
			ngx.say("ngx var变量:", ngx.var.a)
		}
	}

execute cmd:
curl 127.0.0.1:8080/test

then notice error:
2019/12/09 19:42:21 [error] 1181#1181: *1 lua entry thread aborted: runtime error: content_by_lua(default.conf:35):2: no request found
stack traceback:
coroutine 0:
	[C]: in function '__index'
	content_by_lua(default.conf:35):2: in main chunk, client: 127.0.0.1, server: localhost, request: "GET /test HTTP/1.1", host: "127.0.0.1:8080"

What causes it,and how to solve it? thanks.

**Comment by YazaiHu** [comment]
[root@10-9-46-65 utils]# openresty -v
nginx version: openresty/1.15.8.2

openresty version

**Comment by agentzh** [comment]
That looks weird. You may have some incorrect `lua_package_path` and/or `lua_package_cpath` directives in your `nginx.conf` (or manual `package.path` or `package.cpath` assignments), which pick up some wrong `resty.core.*` modules I guess.

**Comment by YazaiHu** [comment]
> That looks weird. You may have some incorrect `lua_package_path` and/or `lua_package_cpath` directives in your `nginx.conf` (or manual `package.path` or `package.cpath` assignments), which pick up some wrong `resty.core.*` modules I guess.

thanks,You guess right.

I use this project:
https://github.com/CNSRE/ABTestingGateway/blob/master/doc/nginx_conf_%E9%85%8D%E7%BD%AE%E8%BF%87%E7%A8%8B.md

it set lua_package_path like this:
#lua代码的路径
lua_package_path "/usr/local/dygateway/luacode/ab/?.lua;/usr/local/dygateway/luacode/ab/lib/?.lua;/usr/local/dygateway/luacode/ab/lib/lua-resty-core/lib/?.lua;;";

and i grep the error message in this project:
Geikiy-MacBook:ABTestingGateway Geikiy$ grep -rni "no request found" *
lib/lua-resty-core/lib/ngx/semaphore.lua:84:        return error("no request found")
lib/lua-resty-core/lib/ngx/balancer.lua:45:        return error("no request found")
lib/lua-resty-core/lib/ngx/balancer.lua:67:        return error("no request found")
lib/lua-resty-core/lib/ngx/balancer.lua:85:        return error("no request found")
lib/lua-resty-core/lib/ngx/ocsp.lua:127:        return error("no request found")
lib/lua-resty-core/lib/ngx/ssl.lua:59:        return error("no request found")
lib/lua-resty-core/lib/ngx/ssl.lua:74:        return error("no request found")
lib/lua-resty-core/lib/ngx/ssl.lua:90:        return error("no request found")
lib/lua-resty-core/lib/ngx/ssl.lua:113:        return error("no request found")
lib/lua-resty-core/lib/ngx/ssl.lua:135:        return error("no request found")
lib/lua-resty-core/lib/ngx/ssl.lua:156:        return error("no request found")
lib/lua-resty-core/lib/ngx/ssl.lua:173:        return error("no request found")
lib/lua-resty-core/lib/ngx/ssl.lua:191:        return error("no request found")
lib/lua-resty-core/lib/resty/core/response.lua:46:        return error("no request found")
lib/lua-resty-core/lib/resty/core/response.lua:113:        return error("no request found")
lib/lua-resty-core/lib/resty/core/var.lua:39:        return error("no request found")
lib/lua-resty-core/lib/resty/core/var.lua:79:        return error("no request found")
lib/lua-resty-core/lib/resty/core/ctx.lua:37:        return error("no request found")
lib/lua-resty-core/lib/resty/core/ctx.lua:63:        return error("no request found")
lib/lua-resty-core/lib/resty/core/request.lua:76:        return error("no request found")
lib/lua-resty-core/lib/resty/core/request.lua:138:        return error("no request found")
lib/lua-resty-core/lib/resty/core/request.lua:195:        return error("no request found")
lib/lua-resty-core/lib/resty/core/request.lua:224:            return error("no request found")
lib/lua-resty-core/lib/resty/core/request.lua:256:        return error("no request found")
lib/lua-resty-core/lib/resty/core/request.lua:290:            return error("no request found")
lib/lua-resty-core/lib/resty/core/request.lua:327:        return error("no request found")
lib/lua-resty-core/lib/resty/core/exit.lua:32:        return error("no request found")
lib/lua-resty-core/lib/resty/core/misc.lua:75:        return error("no request found")
lib/lua-resty-core/lib/resty/core/misc.lua:93:        return error("no request found")
lib/lua-resty-core/lib/resty/core/misc.lua:117:        return error("no request found")
lib/lua-resty-core/lib/resty/core/misc.lua:137:        return error("no request found")

notice this error "no request found" all in lib/lua-resty-core/lib,
so I remove  this path: "/usr/local/dygateway/luacode/ab/lib/lua-resty-core/lib/?.lua"

it works well.

Thanks,brother chun.

**Comment by agentzh** [comment]
@YazaiHu Good to know you sorted it out. I'm closing this.

**Comment by YazaiHu** [comment]
> Good to know you sorted it out. I'm closing this.

ok,thanks.
