### ISSUE TITLE
nginx: [emerg] unknown "bytes_received" variable

### ISSUE THREAD

**Issue by louishot** [openresty/openresty#566]
nginx: [emerg] unknown "bytes_received" variable
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed

I build included
stream
stream_ssl_preread_module

why bytes_received variable can't use in logs

nginx: [emerg] unknown "bytes_received" variable

[root@centos7 html]# nginx -V
nginx version: openresty/1.15.8.2
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.1rc1 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.15 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.7 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-stream --with-stream_ssl_module --with-http_v2_module --with-stream --with-stream_ssl_preread_module --with-http_ssl_module
[root@centos7 html]#

**Comment by louishot** [comment]
I also see nginx: [emerg] unknown "upstream_queue_time" variable
nginx: [emerg] unknown "upstream_first_byte_time" variable
there is any problem with stream module?

**Comment by agentzh** [comment]
@louishot Those variables are ONLY available in the ngx_http_upstream facility, not in the ngx_stream_upstream one you're using. They're separate subsystems. Better lookup the documentation for the right subsystem ("http" vs "stream").

**Comment by louishot** [comment]
> @louishot Those variables are ONLY available in the ngx_http_upstream facility, not in the ngx_stream_upstream one you're using. They're separate subsystems. Better lookup the documentation for the right subsystem ("http" vs "stream").

So $bytes_received,  $upstream_queue_time $upstream_first_byte_time only available in the ngx_http_upstream?

there is another way to get bytes received from client? this is used for statistics traffic

**Comment by agentzh** [comment]
@louishot Seems like they are available in the stream upstream module as well:

http://nginx.org/en/docs/stream/ngx_stream_upstream_module.html#var_upstream_first_byte_time

Make sure you are using the right nginx. OpenResty 1.15.8.2 includes nginx 1.15.8 so those variables are definitely there.

**Comment by louishot** [comment]
> @louishot Seems like they are available in the stream upstream module as well:
> 
> http://nginx.org/en/docs/stream/ngx_stream_upstream_module.html#var_upstream_first_byte_time
> 
> Make sure you are using the right nginx. OpenResty 1.15.8.2 includes nginx 1.15.8 so those variables are definitely there.

Thanks @agentzh 

```
    '"bytes_received":$bytes_received,'
    '"bytes_sent":$bytes_sent,'

    '"upstream_bytes_sent":$upstream_bytes_sent,'
    '"upstream_bytes_received":$upstream_bytes_received,'
```

But I can't use it in log_format(in http block, not stream)
nginx: [emerg] unknown "bytes_received" variable
[root@centos7 html]# nginx -V
nginx version: openresty/1.15.8.2

I tested these
$upstream_bytes_sent working
$upstream_bytes_received working
$bytes_received a unknown "bytes_received" variable
$bytes_sent working

**Comment by louishot** [comment]
@agentzh 
I checked variable bytes_sent available in the ngx_stream and ngx_http both, but bytes_received variable only see in file ngx_stream_variables.c, so in http subsystems I can't see how many bytes received from a client.

**Comment by louishot** [comment]
$request_length
request length (including request line, header, and request body) (1.3.12, 1.2.7)
I think this is what variable I need. I think $request_length = $bytes_received in http subsystems.
If I can use $bytes_received in http subsystems is perfect, this way I don't need to define one more field

**Comment by agentzh** [comment]
They are two separate subsystems and you cannot cross reference the variables across the subsystem boundary. This is more related to the std nginx core btw.

**Comment by charescape** [comment]
@louishot @agentzh This problem is not related to openresty.

The reason is that the variable `$bytes_received` is missing in `ngx_http_log_module.c`

https://github.com/nginx/nginx/blob/master/src/http/modules/ngx_http_log_module.c

I think nginx will solve this problem in future releases.

**Comment by ygm521** [comment]
@charescape did you solved it?

**Comment by zengqingfu1442** [comment]
> @louishot Those variables are ONLY available in the ngx_http_upstream facility, not in the ngx_stream_upstream one you're using. They're separate subsystems. Better lookup the documentation for the right subsystem ("http" vs "stream").

I tried to use the `$upstream_queue_time` in http block, but it is not working:
```
worker_processes 1;

events {
  worker_connections 1024;
}

http {
  log_format  upstreamlog  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"'
                      '$request_time $upstream_response_time $upstream_header_time $upstream_queue_time '
                      '$upstream_addr $upstream_status';
  proxy_connect_timeout 600;
  proxy_read_timeout 3600;
  proxy_send_timeout 3600;
  upstream llm {
    server llm1:8000;
    server llm2:8000;
    server llm3:8000;
    server llm4:8000;
  }
  server {
    listen 80;

    #server_name service1.example.com;

    location / {
      proxy_pass http://llm;
    }
    access_log /var/log/nginx/access.log upstreamlog;
  }
}
```
