### ISSUE TITLE
Cannot add dynamic module into openresty - nginx

### ISSUE THREAD

**Issue by satscreate** [openresty/openresty#587]
**I installed a latest version:**
`https://openresty.org/download/openresty-1.15.8.2.tar.gz`

**nginx -V**
```
nginx version: openresty/1.15.8.2
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.1rc1 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.15 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.7 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_ssl_module
```

Happily nginx starts with below command,
`sudo systemctl restart nginx.service`

now  when i try to add some modules, like https://nginx.org/en/docs/njs/install.html#install_sources

i tried,
```
 [openresty-1.15.8.2]# ./configure --with-compat --add-dynamic-module=../njs-0173143d7b15/nginx
.....................
make & make install
```

Then,
make results in below error, adding few lines.. 

```
gmake[1]: Entering directory `/tmp/openresty/openresty-1.15.8.2/build/nginx-1.15.8'
gmake -f objs/Makefile
gmake[2]: Entering directory `/tmp/openresty/openresty-1.15.8.2/build/nginx-1.15.8'
cd /tmp/openresty/openresty-1.15.8.2/../njs-0173143d7b15/nginx/.. \
&& if [ -f build/Makefile ]; then gmake clean; fi \
&& CFLAGS="-I/tmp/openresty/openresty-1.15.8.2/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 -I/tmp/openresty/openresty-1.15.8.2/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -g -O2 -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DLUA_DEFAULT_PATH='"/usr/local/openresty/site/lualib/?.ljbc;/usr/local/openresty/site/lualib/?/init.ljbc;/usr/local/openresty/lualib/?.ljbc;/usr/local/openresty/lualib/?/init.ljbc;/usr/local/openresty/site/lualib/?.lua;/usr/local/openresty/site/lualib/?/init.lua;/usr/local/openresty/lualib/?.lua;/usr/local/openresty/lualib/?/init.lua"' -DLUA_DEFAULT_CPATH='"/usr/local/openresty/site/lualib/?.so;/usr/local/openresty/lualib/?.so"' -DNDK_SET_VAR" CC="cc" ./configure \
&& gmake
/bin/sh: line 2: /usr/local/openresty/site/lualib/?/init.ljbc: No such file or directory
/bin/sh: line 2: /usr/local/openresty/lualib/?.ljbc: No such file or directory
/bin/sh: line 2: /usr/local/openresty/lualib/?/init.ljbc: No such file or directory
/bin/sh: line 2: /usr/local/openresty/site/lualib/?.lua: No such file or directory
/bin/sh: line 2: /usr/local/openresty/site/lualib/?/init.lua: No such file or directory
/bin/sh: line 2: /usr/local/openresty/lualib/?.lua: No such file or directory
/bin/sh: line 2: /usr/local/openresty/lualib/?/init.lua' -DLUA_DEFAULT_CPATH='/usr/local/openresty/site/lualib/?.so: No such file or directory
/bin/sh: line 2: /usr/local/openresty/lualib/?.so' -DNDK_SET_VAR: No such file or directory
gmake[2]: *** [/tmp/openresty/openresty-1.15.8.2/../njs-0173143d7b15/nginx/../build/libnjs.a] Error 127
gmake[2]: Leaving directory `/tmp/openresty/openresty-1.15.8.2/build/nginx-1.15.8'
gmake[1]: *** [build] Error 2
gmake[1]: Leaving directory `/tmp/openresty/openresty-1.15.8.2/build/nginx-1.15.8'
gmake: *** [all] Error 2
```

Please help!!

**Comment by agentzh** [comment]
Hmm, this is a bug in nginx's build system that does not escape special characters in the value for the `CFLAGS` shell variable assignment. We need to work out a patch for it (cc @doujiang24 ). Thanks for the report.

**Comment by satscreate** [comment]
> Hmm, this is a bug in nginx's build system that does not escape special characters in the value for the `CFLAGS` shell variable assignment. We need to work out a patch for it (cc @doujiang24 ). Thanks for the report.

Is this fixed? should i need to update to latest openresty?

**Comment by agentzh** [comment]
This issue will get fixed in the next OpenResty release. I can reproduce the problem and already got a patch working fully on my side. Will commit it tomorrow.

**Comment by agentzh** [comment]
Hey guys, please try this OpenResty 1.17.8.1 RC1 version on your side:

https://openresty.org/download/openresty-1.17.8.1rc1.tar.gz

This issue should already be fixed in this version.

**Comment by lianhuazi** [comment]
> Hey guys, please try this OpenResty 1.17.8.1 RC1 version on your side:
> 
> https://openresty.org/download/openresty-1.17.8.1rc1.tar.gz
> 
> This issue should already be fixed in this version.
➜  openresty-1.17.8.1rc1 ./configure  --with-compat    --add-dynamic-module=/root/incubator-pagespeed-ngx-master
➜  openresty-1.17.8.1rc1 make modules                                               
make: *** 没有规则可以创建目标“modules”。 停止。
我用make吧，结果全部编译。编译完成了后 

➜  openresty-1.17.8.1rc1 ll ./build/nginx-1.15.8/objs/ngx_pagespeed.so 
ls: 无法访问./build/nginx-1.15.8/objs/ngx_pagespeed.so: 没有那个文件或目录
➜  openresty-1.17.8.1rc1 ll ./build/nginx-1.17.8/objs/ngx_pagespeed.so
-rwxr-xr-x 1 root root 20M 4月  30 12:25 ./build/nginx-1.17.8/objs/ngx_pagespeed.so
➜  openresty-1.17.8.1rc1 cp ./build/nginx-1.17.8/objs/ngx_pagespeed.so /usr/lib64   
➜  openresty-1.17.8.1rc1  ll /usr/lib64/ngx_pagespeed.so;
-rwxr-xr-x 1 root root 20M 4月  30 12:32 /usr/lib64/ngx_pagespeed.so
➜  openresty-1.17.8.1rc1  /usr/local/openresty/nginx/sbin/nginx -t
nginx: [emerg] module "/usr/lib64/ngx_pagespeed.so" is not binary compatible in /usr/local/openresty/nginx/conf/nginx.conf:1
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed
➜  openresty-1.17.8.1rc1  /usr/local/openresty/nginx/sbin/nginx -v
nginx version: openresty/1.17.8.1rc1
➜  openresty-1.17.8.1rc1 

并没有什么用
