### ISSUE TITLE
Variables are shared between modules ？

### ISSUE THREAD

**Issue by wuchencm** [openresty/openresty#589]
![image](https://user-images.githubusercontent.com/14210543/75112694-259c6d80-5681-11ea-815c-f6e2d2002712.png)

why the count ariable is 0 forever ?

test2.lua
`local mod2 = require("module2")

if mod2.count == 0 then
        ngx.say("count_in :",mod2.hello())
        ngx.say("count :",mod2.count)
else
        ngx.say("hello world")
end
`

module2.lua
`local count = 0
local function hello()
        count = count + 1
        return count
end

local _M ={
        hello = hello,
        count = count
}
return _M
`

**Comment by agentzh** [comment]
@wuchencm Because you never update the `count` field in the Lua module table (`_M`). You only upvalue the upvalue `count` (declared by `local`) for function `hello`. You seem to assume the line `count = count` establishes a reference relationship between these two `count` values, but it doesn't.

**Comment by wuchencm** [comment]
> @wuchencm Because you never update the `count` field in the Lua module table (`_M`). You only upvalue the upvalue `count` (declared by `local`) for function `hello`. You seem to assume the line `count = count` establishes a reference relationship between these two `count` values, but it doesn't.

能提示出正确的代码吗？困扰好久了
