### ISSUE TITLE
Unreasonable settings in systemd service

### ISSUE THREAD

**Issue by Mint-M** [openresty/openresty#590]
The pre-built binary package of openresty 1.15.8.2 for RHEL8 is installed on CentOS 8.1.
The network of the system is configured using NetworkManager.

Current systemd file settings is 'After=syslog.target **network.target** remote-fs.target nss-lookup.target'.

If proxy_pass is set to a domain which requires to be resolved(For example, proxy_pass http://abc.com;) ,the enabled service will fail after a reboot because of the unreasonable settings in systemd service.
The log shows "[emerg] host not found in upstream "abc.com".
When network.target is replace with network-online.target, the service starts as normal.

According to the document of systemd, network-online.target means that the network is configured and applications which need network is ready to be started.
https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
Therefore, the network is not necessarily available after network.target and abc.com was failed to be resolved which prevented openresty to be started.

**Comment by nielsek** [comment]
Same issue with the Ubuntu package.

**Comment by doujiang24** [comment]
@nielsek thanks for your report, can you help to create a PR?
