### ISSUE TITLE
OpenSSL打了patch，只能用于编译nginx时使用么

### ISSUE THREAD

**Issue by pmkol** [openresty/openresty#615]
为了yield打了提供的patch，请问打了这个patch的openssl源码包，只能用于编译nginx时使用么？

如果编译安装替换系统(Centos7)的openssl，又或是编译其它需要openssl的程序(如PHP)，会不会出什么问题？

另外 https://openresty.org/en/openssl-patches.html 这个页面建议更新一下，最新的openssl补丁已经是 1.1.1f 了，和 1.1.1c 补丁有不同，容易误导使用补丁的人。

**Comment by doujiang24** [comment]
> 只能用于编译nginx时使用么

打了 patch 的 openssl 是保持向后兼容的，不影响 patch 之前的 openssl 兼容性

> 会不会出什么问题

不会的

> 这个页面建议更新一下

多谢提醒，也欢迎你提交 PR，openresty.org 本身也是开源的
https://github.com/openresty/openresty.org

另外，github 通常建议使用英文交流，习惯用中文的话，欢迎来 [OpenResty 官方论坛](https://forum.openresty.us/) 交流
