### ISSUE TITLE
Server missing on install for Ubuntu

### ISSUE THREAD

**Issue by scrumit** [openresty/openresty#619]
I'm trying to install openresty onto a Linux Mint machine. Here's the output of the Echo command:

> echo "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
> deb http://openresty.org/package/ubuntu tricia main

Here's the error on sudo apt-get update:

>Hit:9 http://packages.linuxmint.com tricia Release                      
> Err:10 http://openresty.org/package/ubuntu tricia Release
>   404  Not Found [IP: 178.62.102.153 80]

**Comment by doujiang24** [comment]
there are no pre-built packages for ubuntu tricia, you need to install it from source then.
see: http://openresty.org/en/linux-packages.html
