### ISSUE TITLE
Enable IPv6 and PCRE JIT support by default?

### ISSUE THREAD

**Issue by jiahuif** [openresty/openresty#62]
By default `configure` comes with `--with-http_ssl_module`, probably because ssl is commonly needed. However there are another two modules that are also widely used and adopted by nginx packages in all modern Linux distributions, namely `ipv6` and `pcre-jit`.

Without `--with-ipv6` switch while configuring, nginx cannot listen on any IPv6 address. This is definitely not a good idea since IPv6 has already widely used around the Internet.

`--with-pcre-jit` enables PCRE JIT, which can speed up processing of regular expressions significantly according to the official document.

> ```
> Syntax: pcre_jit on | off;
> Default:    pcre_jit off;
> Context:    main
> This directive appeared in version 1.1.12.
> ```
> 
> Enables or disables the use of “just-in-time compilation” (PCRE JIT) for the regular expressions known by the time of configuration parsing.
> 
> PCRE JIT can speed up processing of regular expressions significantly.
> 
> The JIT is available in PCRE libraries starting from version 8.20 built with the `--enable-jit` configuration parameter. When the PCRE library is built with nginx (`--with-pcre=`), the JIT support is enabled via the `--with-pcre-jit` configuration parameter.

The following configure flags are used by current Debian stable release.

```
# configure flags
common_configure_flags := \
            --with-cc-opt="$(debian_cflags)" \
            --with-ld-opt="$(debian_ldflags)" \
            --prefix=/usr/share/nginx \
            --conf-path=/etc/nginx/nginx.conf \
            --http-log-path=/var/log/nginx/access.log \
            --error-log-path=/var/log/nginx/error.log \
            --lock-path=/var/lock/nginx.lock \
            --pid-path=/run/nginx.pid \
            --http-client-body-temp-path=/var/lib/nginx/body \
            --http-fastcgi-temp-path=/var/lib/nginx/fastcgi \
            --http-proxy-temp-path=/var/lib/nginx/proxy \
            --http-scgi-temp-path=/var/lib/nginx/scgi \
            --http-uwsgi-temp-path=/var/lib/nginx/uwsgi \
            --with-debug \
            --with-pcre-jit \
            --with-ipv6 \
            --with-http_ssl_module \
            --with-http_stub_status_module \
            --with-http_realip_module \
```

for `nginx-1.0.15-5.el6.i686.rpm` (which is a rather old one)

```
--prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/var/run/nginx.pid --lock-path=/var/lock/subsys/nginx --user=nginx --group=nginx --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_perl_module --with-mail --with-mail_ssl_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables' --with-ld-opt=-Wl,-E
```

**Comment by dvershinin** [comment]
For anyone wondering about `--with-pcre-jit` - just found that even **if you don't pass it**, the NGINX configure scripts are smart enough to detect and enable it automatically. See [here](http://hg.nginx.org/nginx/file/abd40ce603fa/auto/lib/pcre/conf#l179).

So if your PCRE library is recent enough, a simple `./configure` with no switches will compile NGINX with PCRE_JIT enabled.

**Comment by agentzh** [comment]
@dvershinin Thanks for sharing :)
