### ISSUE TITLE
OpenResty1.17.8.1RC1:  Error while setting ngx.req.set_uri while path params has encoded space

### ISSUE THREAD

**Issue by satishnaidu** [openresty/openresty#627]
nginx version: openresty/1.17.8.1rc1
built by gcc 9.3.0 (Ubuntu 9.3.0-10ubuntu2)
built with OpenSSL 1.1.0k 28 May 2019

lua-resty-core: 0.1.18
OS: Linux ea01851460a5 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Hi All,

While using OpenResty1.17.8.1 version, if the path parameters contain any encoded space, then while setting the ngx.req.set_uri(url, false), we are getting the following error.

2020/06/15 23:50:49 [error] 6#6: *337 unsafe byte "0x20" in uri 
**_"/v1/route/path/bcd1cb044a4dd95  /managed"_** while sending to client, client: 172.17.0.1, server: *.test.com: "GET /prefix/v1/route/path/bcd1cb044a4dd95%20%20/managed HTTP/1.1", host: "localhost:8083"

2020/06/15 23:50:49 [error] 6#6: *337 lua entry thread aborted: runtime error: access_by_lua(config.conf:35):19: attempt to use unsafe uri
coroutine 0:
	[C]: in function 'set_uri'
	access_by_lua(config.conf:35):19: in main chunk while sending to client, client: 172.17.0.1, server: *.apis.spectrum.net, request: "GET /prefix/v1/route/path/bcd1cb044a4dd95%20%20/managed HTTP/1.1", host: "localhost:8083"

Steps to reproduce:
1. Add a encoded space to path param, for instance  prefix/v1/a/b%20%20/c
2. In the location block, try to remove the "prefix" path and setting to Nginx request URI.
    local url = util.remove(ngx.var.uri, "/prefix")
    ngx.req.set_uri(url, false)

In OpenResty1.15.18.3 we are not observing this behavior, please let me know how to proceed on this.

**Comment by jongiddy** [comment]
I see the same problem, but the version details differ:
- In 1.15.8.1 passing a space character to `set_uri` works.
- In 1.15.8.3 passing a space character fails as described at https://github.com/openresty/lua-nginx-module/issues/1676
- Using the [latest commit](https://github.com/openresty/openresty/commit/99ec14bfb2bdd95f71f75067620927d19d3f9a80) of branch `1.15.8.x` passing a space character works.
- Using 1.17.8.1rc1 passing a space character fails as described above and in the linked issue.

**Comment by jongiddy** [comment]
I've tested and can confirm that this is fixed in 1.17.8.1. It accepts a space character correctly.

**Comment by doujiang24** [comment]
@jongiddy Thanks for your feedback, closing this issue.
