### ISSUE TITLE
original request headers and body are not passed to the proxied server when a lua script with io is executed

### ISSUE THREAD

**Issue by gizem969** [openresty/openresty#629]
Running the [openresty/openresty:1.15.8.3-bionic](https://hub.docker.com/layers/openresty/openresty/1.15.8.3-bionic/images/sha256-dfe63bfb9569ae92c45bee23a06cd8db78d6161991fd9b4bbe427d2d18e54e07?context=explore) image.

I'm trying to set up a proxy that executes a command for every request, reads the output of that command and put that value in a header, then pass the request to the proxied server.

Here's my configuration:
```
                    daemon off;
                    error_log /dev/stdout debug;
                    events {
                      worker_connections  4096;
                    }
                    http {
                        access_log /dev/stdout;
                        server {
                            listen 8080;
                            server_name  localhost;
                            location / {
                                set_by_lua_block $res {
                                     local handle = io.popen('my-command')
                                     local result = handle:read('*a')
                                     handle:close()
                                     return result
                                }
                                proxy_pass http://server_host:server_port;
                                proxy_set_header MyHeader $res;
                            }
                        }
                    }
```

When I run the proxy with this configuration, my new header is passed to the proxied server correctly. However, the original request headers and body are not passed. I tried `adding proxy_pass_request_body on;` and `proxy_pass_request_headers on;` to no avail.

When I replace the `return result` with something like `return 'some-static-value'` it works as intended, ie passes the request with original body, original headers and the additional header.

**Comment by gizem969** [comment]
Turns out the problem was caused by the trailing newline in the command's output, changing the configuration as the following to delete whitespaces solved the issue.
```
                    daemon off;
                    error_log /dev/stdout debug;
                    events {
                      worker_connections  4096;
                    }
                    http {
                        access_log /dev/stdout;
                        server {
                            listen 8080;
                            server_name  localhost;
                            location / {
                                set_by_lua_block $res {
                                     local handle = io.popen('my-command')
                                     local result = handle:read('*a')
                                     handle:close()
                                     return string.gsub(result, '%s+', '')
                                }
                                proxy_pass http://server_host:server_port;
                                proxy_set_header MyHeader $res;
                            }
                        }
                    }
```

**Comment by TsSerV** [comment]
> Turns out the problem was caused by the trailing newline in the command's output, changing the configuration as the following to delete whitespaces solved the issue.

You are a lifesaver! Thank you!
