### ISSUE TITLE
32bit windows  OpenResty prebuild version was compiled without PCRE support

### ISSUE THREAD

**Issue by witkeysa** [openresty/openresty#641]
runtime error: ./lualib/resty\http.lua:16: no support for 'ngx.re.match' OpenResty was compiled without PCRE support.
but when i use window 64bit version,it get success result,Is this a bug or right?

**Comment by staudenmayerc** [comment]
I'm observing the same problem, using 1.17.8.2.
When I use the prebuilt 64 bit binaries, my module (which requires resty.http) works fine. When I use the prebuilt 32 bit ones, I get this:
```
2020/09/25 15:51:21 [error] 4844#4136: *1 lua entry thread aborted: runtime error: ./lualib/resty\http.lua:16: no support for 'ngx.re.match': OpenResty was compiled without PCRE support
```

**Comment by agentzh** [comment]
Thanks for the report! We will look into this. @thibaultcha will you please have a look at this? It is related to your earlier change? Thanks!

**Comment by agentzh** [comment]
We must fix this serious regression before the next OpenResty version is out.

**Comment by agentzh** [comment]
I can confirm this regression on my Windows 10 VM.

**Comment by agentzh** [comment]
@thibaultcha we should avoid calling C API in such 3rd-party C libraries like pcre and zlib in our lua-resty-core library. They are very problematic.

**Comment by agentzh** [comment]
Guys, I just built a new Win32 version: https://openresty.org/download/openresty-1.19.3.1rc0-win32.zip

My local tests with `ngx.re.*` API pass on Windows 10. Will you try it out please?

**Comment by staudenmayerc** [comment]
> Guys, I just built a new Win32 version: https://openresty.org/download/openresty-1.19.3.1rc0-win32.zip
> 
> My local tests with `ngx.re.*` API pass on Windows 10. Will you try it out please?

Tried it out and the problem is fixed. Thanks!

**Comment by agentzh** [comment]
@staudenmayerc Great. Thanks for your feedback!
