### ISSUE TITLE
compile source on centos6 failed

### ISSUE THREAD

**Issue by elderbig** [openresty/openresty#648]
compile source on centos6  failed

- openresty version: 1.15.8 & 1.17.2

- os version :CentOS release 6.10 (Final)

- gcc versoin:gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)

- gmake version:GNU Make 3.81

compile arguments:

```
./configure --prefix=/home/test/openresty \
--with-luajit --with-pcre=/home/test/temp/pcre-8.44 \
--with-openssl=/home/test/temp/openssl-1.1.1-stable-SNAP-20200809  \
--with-zlib=/home/test/temp/zlib-1.2.11 \
--with-cc-opt="-I/home/test/temp/openssl-1.1.1-stable-SNAP-20200809/include/ -I/home/test/temp/pcre-8.44/" \
--with-ld-opt="-L/home/test/temp/openssl-1.1.1-stable-SNAP-20200809/lib/ -L/home/test/temp/pcre-8.44/lib/" \
-j8

make -j4
```

configue success,but make got fail,error message:
```
...
........
install libcrypto.pc -> /home/test/temp/openssl-1.1.1-stable-SNAP-20200809/.openssl/lib/pkgconfig/libcrypto.pc
install libssl.pc -> /home/test/temp/openssl-1.1.1-stable-SNAP-20200809/.openssl/lib/pkgconfig/libssl.pc
install openssl.pc -> /home/test/temp/openssl-1.1.1-stable-SNAP-20200809/.openssl/lib/pkgconfig/openssl.pc
make[3]: Leaving directory `/home/test/temp/openssl-1.1.1-stable-SNAP-20200809'
make[2]: Leaving directory `/home/test/temp/openresty-1.15.8.3/build/nginx-1.15.8'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/home/test/temp/openresty-1.15.8.3/build/nginx-1.15.8'
make: *** [all] Error 2
[test@localhost openresty-1.15.8.3]$ 
```

when I compile on manjaro 20.0.3 with the same method,none error appeared,is openresty not support centos6 ?

**Comment by agentzh** [comment]
I believe openssl 1.1.1's build system does require modern gcc toolchain. You can install the devtoolset repo's toolset which is much newer. We used it to build our official CentOS 6 pre-built packages:

https://openresty.org/cn/linux-packages.html

**Comment by elderbig** [comment]
I  update devtoolset by：

```
sudo yum -y install centos-release-scl
sudo yum -y install devtoolset-9-gcc devtoolset-9-gcc-c++ devtoolset-9-binutils
```
then use the same build command,it does work,but I never change to new toolset like this

```
scl enable devtoolset-9 bash
```
it is to say,gcc 4.4.7 is  in using:
```
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
I will copy it to another centos6 server & test.
THX!

**Comment by elderbig** [comment]
> I believe openssl 1.1.1's build system does require modern gcc toolchain. You can install the devtoolset repo's toolset which is much newer. We used it to build our official CentOS 6 pre-built packages:
> 
> https://openresty.org/cn/linux-packages.html

I have not root priviliege in product server,so ,I must compile them,and then move it to product envirment.

**Comment by agentzh** [comment]
@elderbig You didn't set up the devtoolset properly. It provides gcc 8 or even newer.
