### ISSUE TITLE
在windows安装了openresty,报错'perl' 不是内部或外部命令

### ISSUE THREAD

**Issue by wangkezheng1234** [openresty/openresty#649]
E:\app\openresty>tasklist /fi "imagename eq nginx.exe"                                                                                                                                                                                          映像名称                       PID 会话名              会话#       内存使用                                             ========================= ======== ================ =========== ============                                            nginx.exe                     9372 Console                    4      8,464 K                                            
nginx.exe                      548 Console                     4      8,996 K                                                                                                                                                                    E:\app\openresty>resty -e "ngx.say('Hello, OpenResty!')"                                                                
'perl' 不是内部或外部命令，也不是可运行的程序                                                                           或批处理文件。                                                                                                          You do not have Perl in your PATH.

**Comment by agentzh** [comment]
@wangkezheng1234 Yeah, you need to install perl separately, like strawberry perl or activeperl are available for free download for windows. The `resty` utility depends on perl.
