### ISSUE TITLE
'configure' missing, but mentioned in 'Building from Source' at https://openresty.org/en/installation.html

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [openresty/openresty#682]

**Comment by sparvu** [comment]
yes, thats correct latest openresty distro is missing configure. Previous distribution, openresty-1.17.8.2.tar.gz had everything properly inside. Any ideas whats going on ?

**Comment by sparvu** [comment]
anyone any ideas whats going on with configure script ?

**Comment by xiaocang** [comment]
I downloaded the source package of openresty-1.19.3.1.tar.gz from offical download page (https://openresty.org/en/download.html), and found that the `configure` file is there.

**Comment by sparvu** [comment]
ok. will try again. something was wrong.

**Comment by sparvu** [comment]
correct. not sure what has happened. case closed.
