### ISSUE TITLE
Release tag for 1.19.3.1 is missing

### ISSUE THREAD

**Issue by cbhp** [openresty/openresty#685]
This GitHub project misses the release tag for 1.19.3.1.
There is only a pre-release for v1.19.3.1rc1 and the latest release is 1.15.8.3

But on https://openresty.org/en/ann-1019003001.html, OpenResty 1.19.3.1 is announced as released.

**Comment by agentzh** [comment]
It is tagged:

https://github.com/openresty/openresty/tags

We no longer create new releases on github though. The only official place is here:

https://openresty.org/en/download.html
