### ISSUE TITLE
如何解决access.log日志不能显示中文的问题

### ISSUE THREAD

**Issue by charlesqing** [openresty/openresty#689]
如何解决access.log日志不能显示中文的问题，中文字符都变成16进制编码\xE6\xB5\x8B\xE8\xAF\x95，有和方法让access.log输出日志中保留中文字符

**Comment by agentzh** [comment]
See http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format

Use `escape=none` for your `log_format` directive.

BTW, this place is considered English only. You can join the forum here if you want to use Chinese: https://forum.openresty.us/
