### ISSUE TITLE
performance of version 1.19.3.1 with luajit

### ISSUE THREAD

**Issue by reyncr** [openresty/openresty#690]
**The QPS of version 1.19.3.1 is reduced by about 20% compared to version 1.17.8.2:**

Test environment：
* test OS:  docker in MacOS 
* test tool:  wrk
* test target: nginx + lua --> `content_by_lua_file`

topo:
++++++++++++-----++++++++++++++
| MacOS: 8880| <--->| docker | nginx:80|
++++++++++++-----++++++++++++++

## test openresty-1.19.3.1

1. compile openresty and start nginx
```bash
git checkout v1.19.3.1
make
cd openresty-1.19.3.1
./configure --with-luajit
make
make install
## start openresty
/usr/local/openresty/nginx/sbin/nginx -c /etc/openresty/nginx.conf
```
2. QPS test

```bash
# ./wrk -t10 -c200 -d20s http://localhost:8880/luatest --latency
  10 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    50.60ms   22.47ms 355.40ms   75.13%
    Req/Sec   401.74     93.31   787.00     71.05%
  Latency Distribution
     50%   47.34ms
     75%   61.60ms
     90%   77.06ms
     99%  121.51ms
  80277 requests in 20.10s, 16.15MB read
Requests/sec:   3993.62
Transfer/sec:    822.74KB
```

## test openresty-1.17.8.2

1. compile openresty and start nginx
```bash
make clean
git checkout v1.17.8.2
make
cd openresty-1.17.8.2
./configure --with-luajit
make
make install
## start openresty
/usr/local/openresty/nginx/sbin/nginx -c /etc/openresty/nginx.conf
```

2. QPS test

```bash
$ ./wrk -t10 -c200 -d20s http://localhost:8880/luatest --latency
Running 20s test @ http://localhost:8880/luatest
  10 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    41.17ms   24.85ms 416.85ms   85.71%
    Req/Sec   508.20    114.93   820.00     66.35%
  Latency Distribution
     50%   37.27ms
     75%   49.65ms
     90%   63.87ms
     99%  131.58ms
  101207 requests in 20.06s, 20.36MB read
  Socket errors: connect 0, read 14, write 0, timeout 0
Requests/sec:   5045.25
Transfer/sec:      1.02MB
```

## openresty config 
* openresty config: /etc/openresty/nginx.conf
```
worker_processes  2;
worker_cpu_affinity 00000001 00000010;

error_log  logs/error.log;
error_log  logs/error.log  notice;
error_log  logs/error.log  info;

pid        logs/nginx.pid;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;

    client_body_temp_path /var/run/openresty/nginx-client-body;
    proxy_temp_path       /var/run/openresty/nginx-proxy;
    fastcgi_temp_path     /var/run/openresty/nginx-fastcgi;
    uwsgi_temp_path       /var/run/openresty/nginx-uwsgi;
    scgi_temp_path        /var/run/openresty/nginx-scgi;
    sendfile        on;
    keepalive_timeout  65;
    include /etc/nginx/conf.d/*.conf;
}
```
/etc/nginx/conf.d/default.conf
```
server {
    listen       80;
    server_name  localhost;
    location /luatest {
        default_type text/html;
        content_by_lua_file /tmp/testlua.lua;
    }
    location / {
        root   /usr/local/openresty/nginx/html;
        index  index.html index.htm;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/local/openresty/nginx/html;
    }
    location = /error {
        content_by_lua_block {
            ngx.status = 500
            ngx.print("error here!")
            return ngx.exit(500)
        }
    }
}
```

Through other test, I think this problem is caused by the commit of [e9af1abec542e6f9851ff2368e7f196b6382a44c](https://github.com/openresty/luajit2/commit/e9af1abec542e6f9851ff2368e7f196b6382a44c).

Has anyone encountered this problem before? Or does anyone know how to solve this problem?

**Comment by yong0706** [comment]
I also got big performance drop in 1.19.3.1 and went back to 1.17.8.2.
Due to the complexity of my code I was not able to narrow down the
root cause.  If you revert e9af1abec542e6f9851ff2368e7f196b6382a44c,
do you get back good performance numbers?

**Comment by reyncr** [comment]
> I also got big performance drop in 1.19.3.1 and went back to 1.17.8.2.
> Due to the complexity of my code I was not able to narrow down the
> root cause. If you revert e9af1abec542e6f9851ff2368e7f196b6382a44c,
> do you get back good performance numbers?

Yes, using the commit before e9af1abec542e6f9851ff2368e7f196b6382a44c, the performance is normal; but using the code after the commit, the performance drops by about 20%;

**Comment by doujiang24** [comment]
@reyncr 
Could you provide the `testlua.lua` file for testing?

I did a benchmark on my side, 1.19.3.1 is a bit faster than 1.17.8.2.

nginx.conf:
```
worker_processes  1;
worker_cpu_affinity auto;

error_log  logs/error.log  error;
pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       9090;
        server_name  localhost;

        access_log off;

        location /luatest {
            default_type text/html;
            content_by_lua_block {
                ngx.say("hello")
            }
        }
    }
}
```

1.19.3.1
```
$ wrk -t 2 -c 40 -d 10 http://127.0.0.1:9090/luatest
Running 10s test @ http://127.0.0.1:9090/luatest
  2 threads and 40 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.65ms  310.66us  29.35ms   92.67%
    Req/Sec    11.87k   465.81    12.55k    77.00%
  236107 requests in 10.00s, 39.84MB read
Requests/sec:  23604.92
Transfer/sec:      3.98MB
```

1.17.8.2
```
$ wrk -t 2 -c 40 -d 10 http://127.0.0.1:9090/luatest
Running 10s test @ http://127.0.0.1:9090/luatest
  2 threads and 40 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.74ms  333.80us  22.43ms   92.68%
    Req/Sec    11.27k   482.41    12.25k    76.00%
  224271 requests in 10.00s, 37.85MB read
Requests/sec:  22420.82
Transfer/sec:      3.78MB
```

**Comment by reyncr** [comment]
> @reyncr
> Could you provide the `testlua.lua` file for testing?
> 
> I did a benchmark on my side, 1.19.3.1 is a bit faster than 1.17.8.2.
> 
> nginx.conf:
> 
> ```
> worker_processes  1;
> worker_cpu_affinity auto;
> 
> error_log  logs/error.log  error;
> pid        logs/nginx.pid;
> 
> events {
>     worker_connections  1024;
> }
> 
> http {
>     sendfile        on;
>     keepalive_timeout  65;
> 
>     server {
>         listen       9090;
>         server_name  localhost;
> 
>         access_log off;
> 
>         location /luatest {
>             default_type text/html;
>             content_by_lua_block {
>                 ngx.say("hello")
>             }
>         }
>     }
> }
> ```
> 
> 1.19.3.1
> 
> ```
> $ wrk -t 2 -c 40 -d 10 http://127.0.0.1:9090/luatest
> Running 10s test @ http://127.0.0.1:9090/luatest
>   2 threads and 40 connections
>   Thread Stats   Avg      Stdev     Max   +/- Stdev
>     Latency     1.65ms  310.66us  29.35ms   92.67%
>     Req/Sec    11.87k   465.81    12.55k    77.00%
>   236107 requests in 10.00s, 39.84MB read
> Requests/sec:  23604.92
> Transfer/sec:      3.98MB
> ```
> 
> 1.17.8.2
> 
> ```
> $ wrk -t 2 -c 40 -d 10 http://127.0.0.1:9090/luatest
> Running 10s test @ http://127.0.0.1:9090/luatest
>   2 threads and 40 connections
>   Thread Stats   Avg      Stdev     Max   +/- Stdev
>     Latency     1.74ms  333.80us  22.43ms   92.68%
>     Req/Sec    11.27k   482.41    12.25k    76.00%
>   224271 requests in 10.00s, 37.85MB read
> Requests/sec:  22420.82
> Transfer/sec:      3.78MB
> ```

The code of testlua.lua:
```
local args=nil
local headers = nil
local request_method = ngx.var.request_method
if"GET" == request_method then
        --args = ngx.req.get_uri_args()

	headers = ngx.req.get_headers()
elseif "POST" == request_method then
        ngx.req.read_body()
        args = ngx.req.get_post_args()
        if (args == nil or args.data == null) then
                args = ngx.req.get_uri_args()
        end
	headers = ngx.req.get_headers()
end

--local name = args.name
local req_headers = ""

if headers ~= nil then
	for hdrs , value  in pairs(headers) do
		req_headers = req_headers .. hdrs .. "=" .. value .. "\n"
	end
	ngx.say("request headers: \n".. req_headers)
end

--ngx.say("linux hello:"..name)
```

**Comment by doujiang24** [comment]
1.19.3.1 is still bit faster than 1.17.8.2 when using the testlua.lua that you provided.

1.17.8.2

```
$ wrk -t 2 -c 40 -d 30 http://127.0.0.1:80/luatest
Running 30s test @ http://127.0.0.1:80/luatest
  2 threads and 40 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   694.60us    0.93ms 135.23ms   99.74%
    Req/Sec    28.92k     2.81k   57.68k    91.32%
  1726681 requests in 30.09s, 344.08MB read
Requests/sec:  57379.63
Transfer/sec:     11.43MB
```

1.19.3.1
```
wrk -t 2 -c 40 -d 30 http://127.0.0.1:80/luatest
Running 30s test @ http://127.0.0.1:80/luatest
  2 threads and 40 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   655.90us    1.00ms 126.91ms   99.76%
    Req/Sec    30.57k     3.11k   42.51k    93.02%
  1831048 requests in 30.10s, 364.87MB read
Requests/sec:  60832.81
Transfer/sec:     12.12MB
```

I built openresty in this way:

```
./configure  \
    --with-pcre-jit \
    --with-pcre-conf-opt="--enable-utf8" \
    --with-cc-opt="-I /usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include -O2 -g3" \
    --with-ld-opt="-L /usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/openssl/lib" \
    --with-luajit-xcflags="-DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT -O2 -g3 -DLUAJIT_ENABLE_GC64" \
    --with-stream \
    --with-stream_ssl_module \
    --with-stream_ssl_preread_module \
    --with-http_realip_module \
    --with-http_v2_module \
    --with-http_stub_status_module
```

**Comment by reyncr** [comment]
> 1.19.3.1 is still bit faster than 1.17.8.2 when using the testlua.lua that you provided.
> 
> 1.17.8.2
> 
> ```
> $ wrk -t 2 -c 40 -d 30 http://127.0.0.1:80/luatest
> Running 30s test @ http://127.0.0.1:80/luatest
>   2 threads and 40 connections
>   Thread Stats   Avg      Stdev     Max   +/- Stdev
>     Latency   694.60us    0.93ms 135.23ms   99.74%
>     Req/Sec    28.92k     2.81k   57.68k    91.32%
>   1726681 requests in 30.09s, 344.08MB read
> Requests/sec:  57379.63
> Transfer/sec:     11.43MB
> ```
> 
> 1.19.3.1
> 
> ```
> wrk -t 2 -c 40 -d 30 http://127.0.0.1:80/luatest
> Running 30s test @ http://127.0.0.1:80/luatest
>   2 threads and 40 connections
>   Thread Stats   Avg      Stdev     Max   +/- Stdev
>     Latency   655.90us    1.00ms 126.91ms   99.76%
>     Req/Sec    30.57k     3.11k   42.51k    93.02%
>   1831048 requests in 30.10s, 364.87MB read
> Requests/sec:  60832.81
> Transfer/sec:     12.12MB
> ```
> 
> I built openresty in this way:
> 
> ```
> ./configure  \
>     --with-pcre-jit \
>     --with-pcre-conf-opt="--enable-utf8" \
>     --with-cc-opt="-I /usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include -O2 -g3" \
>     --with-ld-opt="-L /usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/openssl/lib" \
>     --with-luajit-xcflags="-DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT -O2 -g3 -DLUAJIT_ENABLE_GC64" \
>     --with-stream \
>     --with-stream_ssl_module \
>     --with-stream_ssl_preread_module \
>     --with-http_realip_module \
>     --with-http_v2_module \
>     --with-http_stub_status_module
> ```
> 
> nginx.conf
> 
> ```
> worker_processes  1;
> worker_cpu_affinity 00000001;
> 
> error_log  logs/error.log;
> error_log  logs/error.log  notice;
> error_log  logs/error.log  info;
> 
> pid        logs/nginx.pid;
> events {
>     worker_connections  1024;
> }
> http {
>     default_type  application/octet-stream;
>     sendfile        on;
>     keepalive_timeout  65;
> 
> server {
>     listen       80;
>     server_name  localhost;
>     location /luatest {
>         default_type text/html;
>         content_by_lua_file /tmp/testlua.lua;
>     }
>     location / {
>         root   /usr/local/openresty/nginx/html;
>         index  index.html index.htm;
>     }
>     error_page   500 502 503 504  /50x.html;
>     location = /50x.html {
>         root   /usr/local/openresty/nginx/html;
>     }
>     location = /error {
>         content_by_lua_block {
>             ngx.status = 500
>             ngx.print("error here!")
>             return ngx.exit(500)
>         }
>     }
> }
> }
> ```

OK，my test environment is destroyed, I will rebuild the environment and test it to confirm whether the problem exists. Thanks!

**Comment by reyncr** [comment]
> 1.19.3.1 is still bit faster than 1.17.8.2 when using the testlua.lua that you provided.
> 
> 1.17.8.2
> 
> ```
> $ wrk -t 2 -c 40 -d 30 http://127.0.0.1:80/luatest
> Running 30s test @ http://127.0.0.1:80/luatest
>   2 threads and 40 connections
>   Thread Stats   Avg      Stdev     Max   +/- Stdev
>     Latency   694.60us    0.93ms 135.23ms   99.74%
>     Req/Sec    28.92k     2.81k   57.68k    91.32%
>   1726681 requests in 30.09s, 344.08MB read
> Requests/sec:  57379.63
> Transfer/sec:     11.43MB
> ```
> 
> 1.19.3.1
> 
> ```
> wrk -t 2 -c 40 -d 30 http://127.0.0.1:80/luatest
> Running 30s test @ http://127.0.0.1:80/luatest
>   2 threads and 40 connections
>   Thread Stats   Avg      Stdev     Max   +/- Stdev
>     Latency   655.90us    1.00ms 126.91ms   99.76%
>     Req/Sec    30.57k     3.11k   42.51k    93.02%
>   1831048 requests in 30.10s, 364.87MB read
> Requests/sec:  60832.81
> Transfer/sec:     12.12MB
> ```
> 
> I built openresty in this way:
> 
> ```
> ./configure  \
>     --with-pcre-jit \
>     --with-pcre-conf-opt="--enable-utf8" \
>     --with-cc-opt="-I /usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include -O2 -g3" \
>     --with-ld-opt="-L /usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/openssl/lib" \
>     --with-luajit-xcflags="-DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT -O2 -g3 -DLUAJIT_ENABLE_GC64" \
>     --with-stream \
>     --with-stream_ssl_module \
>     --with-stream_ssl_preread_module \
>     --with-http_realip_module \
>     --with-http_v2_module \
>     --with-http_stub_status_module
> ```
> 
> nginx.conf
> 
> ```
> worker_processes  1;
> worker_cpu_affinity 00000001;
> 
> error_log  logs/error.log;
> error_log  logs/error.log  notice;
> error_log  logs/error.log  info;
> 
> pid        logs/nginx.pid;
> events {
>     worker_connections  1024;
> }
> http {
>     default_type  application/octet-stream;
>     sendfile        on;
>     keepalive_timeout  65;
> 
> server {
>     listen       80;
>     server_name  localhost;
>     location /luatest {
>         default_type text/html;
>         content_by_lua_file /tmp/testlua.lua;
>     }
>     location / {
>         root   /usr/local/openresty/nginx/html;
>         index  index.html index.htm;
>     }
>     error_page   500 502 503 504  /50x.html;
>     location = /50x.html {
>         root   /usr/local/openresty/nginx/html;
>     }
>     location = /error {
>         content_by_lua_block {
>             ngx.status = 500
>             ngx.print("error here!")
>             return ngx.exit(500)
>         }
>     }
> }
> }
> ```

Thank you very much for your reply. The performance of 1.19.3.1 is indeed better than that of 1.17.8.2. In my previous test, when compiling the version of 1.19.3.1, the official luajit was used instead of luajit2. If I want to use the latest luajit2, v2.1-20201229 and v2.1-20201027, which one should I choose?
