### ISSUE TITLE
When the number of requests is high, openresty reload will cause 502

### ISSUE THREAD

**Issue by W-BC0001** [openresty/openresty#695]
## Problem description

My architecture looked like this when I was using the ALB reverse proxy OpenResty

```shell
Client <----> ALB <-----> Openresty*1 <------> Real Servers*3
```

Very frequent requests from the client cause openResty to report an error of 502 when reload, and OpenResty will not generate any logs about 502, generally 502 is recorded on the downstream ALB

The Client uses up to 20 connections to send 1,000,000 requests via Apache Bench, and keeps Alive to send multiple requests on the same connection:

```shell
$ ab -n 1000000 -c 20 -k -r http://frontNginx-79879.ap-nortst-1.elb.amazonaws.com/ 
```

Run `nginx -s reload` during the test to replicate the problem.

The experimental results show that ELB 502 does appear at the moment of Reload

To investigate this problem, I am in the present experiment also in nginx caught package, and filter out the error corresponding tcp flow, found that propagated after receipt of `FIN`, because of the propagated to the tcp connection of the send buffer still has the data, so must will send buffer request sent to return to `FIN`, but nginx has close connection, is not able to send data, therefore returns the `RST`.

Since ALB is forced to close the connection before receiving the HTTP Response, it returns HTTP 502 to the client. This phenomenon is easier to repeat in high-volume environments, and you can also see from this package that each request is only about 1 ms apart.

It is worth mentioning that I think there is another possibility to cause this phenomenon. If nginx closes the idle connection when reload, but receives the request just sent by ALB when it closes, it will also cause a Race Condition:
- Nginx sends `FIN` to idle connection under reload
- Since the FIN has not been sent to ALB, ALB uses this connection to send a request before receiving the `FIN`
- ALB receives the FIN and returns the FIN/ACK (at this point 502 has been generated, because for ALB, nginx closes the connection first)
- Nginx receives HTTP request and FIN and returns `RST` directly

## Version

openresty
```shell
$ openresty -V
nginx version: openresty/1.19.3.1
built by gcc 7.3.1 20180712 (Red Hat 7.3.1-12) (GCC)
built with OpenSSL 1.1.1g  21 Apr 2020
TLS SNI support enabled
```

nginx
```shell
$ nginx -v
nginx version: openresty/1.19.3.1
```

operating system version
```shell
$ uname -a
Linux ip-xxx-xxx-xxx-xxx.ap-xxxxxx-1.compute.internal 4.14.209-160.339.amzn2.x86_64 #1 SMP Wed Dec 16 22:44:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

##  **A minimal and standalone test case** that others can easily run on their side and reproduce the issue you are seeing.

```shell
Client <----> ALB <-----> Openresty*1 <------> Real Servers*3
```

The Client uses up to 20 connections to send 1,000,000 requests via Apache Bench, and keeps Alive to send multiple requests on the same connection:

```shell
$ ab -n 1000000 -c 20 -k -r http://frontNginx-79879.ap-nortst-1.elb.amazonaws.com/ 
```

Run nginx -s reload during the test to replicate the problem.

## The result I expected

OpenResty's configuration parameters can be set to solve the problem of 502 caused by reloading Nginx during heavy traffic

**Comment by ssalinas** [comment]
@W-BC0001 I know this is a fairly old open issue at this point, but did you ever find more detail or a workaround for this? I believe our team is experiencing the same issue under high load behind an ALB and are currently digging for fixes

**Comment by ensean** [comment]
+1, we encountered similar issue with the traffic path `client ---> CloudFront ---> NLB ---> openresty --> SpringBoot App`. Although setting `keepalive_timeout` to zero can resolve this, but this is not a good idea for production env...
