### ISSUE TITLE
compile openresty-1.19.3.1 failed with some warnings

### ISSUE THREAD

**Issue by oule** [openresty/openresty#708]
hello!

I just want to add a module nginx-dav-ext-module-3.0.0 when I compile openresty. Configure outputs normally. However, make reported a lot of warning errors and ended in failure. I don't know why. Please help me to have a look.

Here are the steps：
./configure \
--prefix=/usr/local/openresty-1.19.3.1 \
--with-cc-opt='-O2' \
--add-module=bundle/ngx_devel_kit-0.3.1 \
--add-module=bundle/echo-nginx-module-0.62 \
--add-module=bundle/xss-nginx-module-0.06 \
--add-module=bundle/ngx_coolkit-0.2 \
--add-module=bundle/set-misc-nginx-module-0.32 \
--add-module=bundle/form-input-nginx-module-0.12 \
--add-module=bundle/encrypted-session-nginx-module-0.08 \
--add-module=bundle/srcache-nginx-module-0.32 \
--add-module=bundle/ngx_lua-0.10.19 \
--add-module=bundle/ngx_lua_upstream-0.07 \
--add-module=bundle/headers-more-nginx-module-0.33 \
--add-module=bundle/array-var-nginx-module-0.05 \
--add-module=bundle/memc-nginx-module-0.19 \
--add-module=bundle/redis2-nginx-module-0.15 \
--add-module=bundle/redis-nginx-module-0.3.7 \
--add-module=bundle/ngx_stream_lua-0.0.9 \
--add-module=bundle/nginx-dav-ext-module-3.0.0 \
--with-pcre-jit \
--with-stream \
--with-stream_ssl_module \
--with-stream_ssl_preread_module \
--with-http_v2_module \
--without-mail_pop3_module \
--without-mail_imap_module \
--without-mail_smtp_module \
--with-http_stub_status_module \
--with-http_realip_module \
--with-http_addition_module \
--with-http_auth_request_module \
--with-http_secure_link_module \
--with-http_random_index_module \
--with-http_gzip_static_module \
--with-http_sub_module \
--with-http_dav_module \
--with-http_flv_module \
--with-http_mp4_module \
--with-http_gunzip_module \
--with-threads \
--with-stream \
--with-http_ssl_module

make -j2
 CC=cc PREFIX=/usr/local/openresty-1.19.3.1/luajit
make[1]: Entering directory '/root/install/openresty-1.19.3.1/build/LuaJIT-2.1-20201027'
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[2]: Entering directory '/root/install/openresty-1.19.3.1/build/LuaJIT-2.1-20201027/src'
make[2]: Nothing to be done for 'default'.
make[2]: Leaving directory '/root/install/openresty-1.19.3.1/build/LuaJIT-2.1-20201027/src'
==== Successfully built LuaJIT 2.1.0-beta3 ====
make[1]: Leaving directory '/root/install/openresty-1.19.3.1/build/LuaJIT-2.1-20201027'
usr/local/openresty-1.19.3.1/lualib CJSON_CFLAGS="-g -fpic" CC=cc
make[1]: Entering directory '/root/install/openresty-1.19.3.1/build/lua-cjson-2.1.0.8'
uajit-2.1 -g -fpic -o lua_cjson.o lua_cjson.c
uajit-2.1 -g -fpic -o strbuf.o strbuf.c
uajit-2.1 -g -fpic -o fpconv.o fpconv.c
cc  -shared -o cjson.so lua_cjson.o strbuf.o fpconv.o
make[1]: Leaving directory '/root/install/openresty-1.19.3.1/build/lua-cjson-2.1.0.8'
d/luajit-root/usr/local/openresty-1.19.3.1/luajit/include/luajit-2.1 LUA_LIB_DIR=/usr/local/openresty-1.19.3.1/lualib CC=cc
make[1]: Entering directory '/root/install/openresty-1.19.3.1/build/lua-resty-signal-0.02'
cc -O3 -g -Wall -fpic -c resty_signal.c
cc -shared -fvisibility=hidden resty_signal.o -o librestysignal.so
make[1]: Leaving directory '/root/install/openresty-1.19.3.1/build/lua-resty-signal-0.02'
d/luajit-root/usr/local/openresty-1.19.3.1/luajit/include/luajit-2.1 LUA_LIB_DIR=/usr/local/openresty-1.19.3.1/lualib CC=cc
make[1]: Entering directory '/root/install/openresty-1.19.3.1/build/lua-redis-parser-0.13'
-o redis-parser.o redis-parser.c
cc -shared -o parser.so redis-parser.o
make[1]: Leaving directory '/root/install/openresty-1.19.3.1/build/lua-redis-parser-0.13'
luajit-root/usr/local/openresty-1.19.3.1/luajit/include/luajit-2.1 LUA_LIB_DIR=/usr/local/openresty-1.19.3.1/lualib CC=cc
make[1]: Entering directory '/root/install/openresty-1.19.3.1/build/lua-rds-parser-0.06'
-o src/rds_parser.o src/rds_parser.c
cc -shared -o parser.so src/rds_parser.o
make[1]: Leaving directory '/root/install/openresty-1.19.3.1/build/lua-rds-parser-0.06'
cd /root/install/openresty-1.19.3.1/build/nginx-1.19.3 && make
make[1]: Entering directory '/root/install/openresty-1.19.3.1/build/nginx-1.19.3'
make -f objs/Makefile
make[2]: Entering directory '/root/install/openresty-1.19.3.1/build/nginx-1.19.3'
objs/Makefile:3588: warning: overriding recipe for target 'objs/addon/src/ndk.o'
objs/Makefile:2384: warning: ignoring old recipe for target 'objs/addon/src/ndk.o'
objs/Makefile:3595: warning: overriding recipe for target 'objs/addon/src/ngx_http_echo_module.o'
objs/Makefile:2391: warning: ignoring old recipe for target 'objs/addon/src/ngx_http_echo_module.o'
...
...
-0.0.9/src/api -I /usr/include/libxml2 -I objs \
	-o objs/src/core/nginx.o \
	src/core/nginx.c
-0.0.9/src/api -I /usr/include/libxml2 -I objs \
	-o objs/src/core/ngx_log.o \
	src/core/ngx_log.c
...
...
-0.0.9/src/api -I /usr/include/libxml2 -I objs \
	-o objs/src/core/ngx_regex.o \
	src/core/ngx_regex.c
root/install/openresty-1.19.3.1/build/luajit-root/usr/local/openresty-1.19.3.1/luajit/include/luajit-2.1 \
	-o objs/src/http/ngx_http.o \
	src/http/ngx_http.c
root/install/openresty-1.19.3.1/build/luajit-root/usr/local/openresty-1.19.3.1/luajit/include/luajit-2.1 \
	-o objs/src/http/ngx_http_core_module.o \
	src/http/ngx_http_core_module.c
...
...
root/install/openresty-1.19.3.1/build/luajit-root/usr/local/openresty-1.19.3.1/luajit/include/luajit-2.1 \
	-o objs/src/http/modules/ngx_http_stub_status_module.o \
	src/http/modules/ngx_http_stub_status_module.c
luajit-2.1 \
	-o objs/src/stream/ngx_stream.o \
	src/stream/ngx_stream.c
luajit-2.1 \
	-o objs/src/stream/ngx_stream_variables.o \
	src/stream/ngx_stream_variables.c
...
...
ld/luajit-root/usr/local/openresty-1.19.3.1/luajit/include/luajit-2.1 \
	-o objs/addon/nginx-dav-ext-module-3.0.0/ngx_http_dav_ext_module.o \
	/root/install/openresty-1.19.3.1/bundle/nginx-dav-ext-module-3.0.0/ngx_http_dav_ext_module.c
-0.0.9/src/api -I /usr/include/libxml2 -I objs \
	-o objs/ngx_modules.o \
	objs/ngx_modules.c
sed -e "s|%%PREFIX%%|/usr/local/openresty-1.19.3.1/nginx|" \
	-e "s|%%PID_PATH%%|/usr/local/openresty-1.19.3.1/nginx/logs/nginx.pid|" \
	-e "s|%%CONF_PATH%%|/usr/local/openresty-1.19.3.1/nginx/conf/nginx.conf|" \
	-e "s|%%ERROR_LOG_PATH%%|/usr/local/openresty-1.19.3.1/nginx/logs/error.log|" \
	< docs/man/nginx.8 > objs/nginx.8
cc -o objs/nginx \
objs/src/core/nginx.o \
objs/src/core/ngx_log.o \
objs/src/core/ngx_palloc.o \
...
...
objs/addon/nginx-dav-ext-module-3.0.0/ngx_http_dav_ext_module.o \
objs/ngx_modules.o \
exslt \
-Wl,-E
st defined here
al+0x0): first defined here
/usr/bin/ld: objs/addon/src/ndk.o: in function `ndk_http_rewrite_var':
defined here
/usr/bin/ld: objs/addon/src/ndk.o: in function `ndk_http_rewrite_value':
t defined here
/usr/bin/ld: objs/addon/src/ndk.o: in function `ndk_set_var_core':
...
...
.62/src/ngx_http_echo_request_info.c:515: first defined here
nstall/openresty-1.19.3.1/bundle/echo-nginx-module-0.62/src/ngx_http_echo_subrequest.c:22: first defined here
nresty-1.19.3.1/bundle/echo-nginx-module-0.62/src/ngx_http_echo_subrequest.c:37: first defined here
resty-1.19.3.1/bundle/echo-nginx-module-0.62/src/ngx_http_echo_subrequest.c:36: first defined here
esty-1.19.3.1/bundle/echo-nginx-module-0.62/src/ngx_http_echo_subrequest.c:35: first defined here
sty-1.19.3.1/bundle/echo-nginx-module-0.62/src/ngx_http_echo_subrequest.c:33: first defined here
ty-1.19.3.1/bundle/echo-nginx-module-0.62/src/ngx_http_echo_subrequest.c:31: first defined here
enresty-1.19.3.1/bundle/echo-nginx-module-0.62/src/ngx_http_echo_subrequest.c:39: first defined here
...
...
/usr/bin/ld: objs/addon/src/ngx_stream_lua_input_filters.o: in function `ngx_stream_lua_read_any':
eam_lua_input_filters.c:70: first defined here
/usr/bin/ld: objs/addon/src/ngx_stream_lua_input_filters.o: in function `ngx_stream_lua_read_line':
ream_lua_input_filters.c:99: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [objs/Makefile:678: objs/nginx] Error 1
make[2]: Leaving directory '/root/install/openresty-1.19.3.1/build/nginx-1.19.3'
make[1]: *** [Makefile:8: build] Error 2
make[1]: Leaving directory '/root/install/openresty-1.19.3.1/build/nginx-1.19.3'
make: *** [Makefile:9: all] Error 2

**Comment by ING-XIAOJIAN** [comment]
how to solve it
