### ISSUE TITLE
patch for openssl-1.1.1j

### ISSUE THREAD

**Issue by louishot** [openresty/openresty#714]
Hello all,

Does anyone know the openssl 1.1.1 patch works?
 patches/openssl-1.1.1c-sess_set_get_cb_yield.patch
 patches/openssl-1.1.1e-sess_set_get_cb_yield.patch
 patches/openssl-1.1.1f-sess_set_get_cb_yield.patch

I want to build with openssl-1.1.1j 
What is the difference between c e f patch, can I apply any of the above patches on 1.1.1j

**Comment by neomantra** [comment]
I just pushed tags for Docker images that use this `1.1.1j`.   [I didn't know it existed until I saw the recent issue about wanting unreleased `1.1.1k`.   So if you want to try those, it will be images tagged with `1.19.3.1-5` once Travis is done building. 

You can look at how the Dockerfiles work to do it yourself:
https://github.com/openresty/docker-openresty/blob/master/focal/Dockerfile#L106

But basically, for `j`, apply patch `f`.

That said, I do not QA this at all -- it builds fine, so I release it.  There are multiple tags so users can choose the one that is best for them, including highly quality-controlled built-from-upstream-packages images.

**Comment by louishot** [comment]
Exactly I see this so I using openssl-1.1.1f-sess_set_get_cb_yield.patch looks work pretty build success
https://github.com/openresty/docker-openresty/blob/master/alpine/Dockerfile
I just want to know if there are any adverse reactions when using openssl-1.1.1f-sess_set_get_cb_yield.patch on openssl-1.1.1j

**Comment by zhuizhuhaomeng** [comment]
just using openssl-1.1.1f-sess_set_get_cb_yield.patch, that is right.
