### ISSUE TITLE
Does openresty support running on photon OS?

### ISSUE THREAD

**Issue by xiaozhi747** [openresty/openresty#737]
Does openresty support running on photon OS?  thanks.

**Comment by xiaocang** [comment]
Yes, but you need to compile it manually, because there are no pre-compiled packages yet

**Comment by xiaozhi747** [comment]
> Yes, but you need to compile it manually, because there are no pre-compiled packages yet

Can you provide a pre-compiled package? I tried to compile manually, but it failed.
The following are my steps
`tdnf install -y pcre-devel openssl-devel gcc curl perl make readline-devel wge

cd /home

wget https://openresty.org/download/openresty-1.19.3.1.tar.gz

tar -zxvf openresty-1.19.3.1.tar.gz

cd openresty-1.19.3.1

./configure`
Then it reported an error:
`root [ /home/openresty-1.19.3.1 ]# ./configure
platform: linux (linux)
cp -rp bundle/ build
cd build
cd LuaJIT-2.1-20201027
make TARGET_STRIP=@: CCDEBUG=-g XCFLAGS='-DLUAJIT_ENABLE_LUA52COMPAT' CC=cc PREFIX=/usr/local/openresty/luajit
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: Entering directory '/home/openresty-1.19.3.1/build/LuaJIT-2.1-20201027/src'
In file included from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:34,
                 from luaconf.h:12,
                 from lua.h:16,
                 from lj_arch.h:9:
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:195:15: fatal error: limits.h: No such file or directory
  195 | #include_next <limits.h>  /* recurse down to the real one */
      |               ^~~~~~~~~~
compilation terminated.
In file included from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:34,
                 from luaconf.h:12,
                 from lua.h:16,
                 from lj_arch.h:9:
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:195:15: fatal error: limits.h: No such file or directory
  195 | #include_next <limits.h>  /* recurse down to the real one */
      |               ^~~~~~~~~~
compilation terminated.
In file included from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:34,
                 from luaconf.h:12,
                 from lua.h:16,
                 from lj_arch.h:9:
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:195:15: fatal error: limits.h: No such file or directory
  195 | #include_next <limits.h>  /* recurse down to the real one */
      |               ^~~~~~~~~~
compilation terminated.
In file included from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:34,
                 from luaconf.h:12,
                 from lua.h:16,
                 from lj_arch.h:9:
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:195:15: fatal error: limits.h: No such file or directory
  195 | #include_next <limits.h>  /* recurse down to the real one */
      |               ^~~~~~~~~~
compilation terminated.
In file included from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:34,
                 from luaconf.h:12,
                 from lua.h:16,
                 from lj_arch.h:9:
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:195:15: fatal error: limits.h: No such file or directory
  195 | #include_next <limits.h>  /* recurse down to the real one */
      |               ^~~~~~~~~~
compilation terminated.
In file included from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:34,
                 from luaconf.h:12,
                 from lua.h:16,
                 from lj_arch.h:9:
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:195:15: fatal error: limits.h: No such file or directory
  195 | #include_next <limits.h>  /* recurse down to the real one */
      |               ^~~~~~~~~~
compilation terminated.
In file included from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:34,
                 from luaconf.h:12,
                 from lua.h:16,
                 from lj_arch.h:9:
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed/limits.h:195:15: fatal error: limits.h: No such file or directory
  195 | #include_next <limits.h>  /* recurse down to the real one */
      |               ^~~~~~~~~~
compilation terminated.
Makefile:274: *** Unsupported target architecture.  Stop.
make[1]: Leaving directory '/home/openresty-1.19.3.1/build/LuaJIT-2.1-20201027/src'
make: *** [Makefile:113: default] Error 2
ERROR: failed to run command: make TARGET_STRIP=@: CCDEBUG=-g XCFLAGS='-DLUAJIT_ENABLE_LUA52COMPAT' CC=cc PREFIX=/usr/local/openresty/luajit
`
Can you help me, thanks!

**Comment by xiaocang** [comment]
You can try this on your build machine:
```
sudo tdnf install -y pcre-devel openssl-devel gcc curl perl make glibc-devel linux-api-headers binutils zlib-devel
```

then re-compile it.

**Comment by xiaozhi747** [comment]
> You can try this on your build machine:
> 
> ```
> sudo tdnf install -y pcre-devel openssl-devel gcc curl perl make glibc-devel linux-api-headers binutils zlib-devel
> ```
> 
> then re-compile it.

@xiaocang  Thank you very much. After following your instructions, the above problems have been solved, but new problems have appeared, as follows:
![image](https://user-images.githubusercontent.com/19251872/119778533-3bd75000-befa-11eb-8a3a-fa7a6a65d5ad.png)

**Comment by xiaocang** [comment]
It looks like you are missing `tr` command, just install it with `sudo tdnf install -y coreutils`, and if it still reports an error next missing other commands, use `sudo tdnf provides *bin/tr` to find the packages.

good luck.

**Comment by xiaozhi747** [comment]
> It looks like you are missing `tr` command, just install it with `sudo tdnf install -y coreutils`, and if it still reports an error next missing other commands, use `sudo tdnf provides *bin/tr` to find the packages.
> 
> good luck.

Thank you very much for your help, now I have successfully compiled openresty, if I complete the openresty dockerfile of photon, I will also share it
