### ISSUE TITLE
Blocked Builds on Travis

### ISSUE THREAD

**Issue by srajmane** [openresty/openresty#749]
It is observed that the builds for Openresty are blocked on [Travis ](https://travis-ci.com/github/openresty/openresty)due to negative credit balance.
As per the Travis [blog](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), Travis fully supports the OSS teams and allocates them more credits after they apply for the same.
Could you please open a request with Travis CI support stating that you'd like to be considered for the OSS allotment?
Please refer the Travis [blog ](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)for more details on how to open support request with Travis.

**Comment by neomantra** [comment]
Travis has been really weird for me.   I use it for the [docker-openresty](https://travis-ci.com/github/openresty/docker-openresty) builds.   I had 10,000 build minutes as an individual, but I am also part of the OpenResty organization.    I had enabled `Consume paid credits for OSS`. There is no way I used more than 500 minutes for my own projects and `docker-openresty`, but it shows that I've used in excess of 10,000.

I also thought it was weird that the travis.com builds started working and stopped working and started working and stopped working...  Does Travis slurp these minutes from all organization participants and now that it's been exhausted from everybody, it has stopped working again? 

If this isn't resolved by the next OpenResty release, I'll probably move the Docker builds to GitLab CI.

**Comment by cwsolee** [comment]
@neomantra My team have been working with Travis since s390x is supported, I pass your comment to them, will keep u posted if I hear anything.

**Comment by neomantra** [comment]
@cwsolee Thanks!   To be clear, my issue isn't the depletion of my build minutes (I only use Travis for OpenResty and am happy to donate them).   I'm just giving data so we can understand what's going on.

**Comment by xiaocang** [comment]
Thanks for reporting, I have sent an email to the travis support team to request OSS credits

**Comment by cwsolee** [comment]
@xiaocang I did the same and credit should be higher now, take a look and ok to request more if needed.

**Comment by xiaocang** [comment]
> @xiaocang I did the same and credit should be higher now, take a look and ok to request more if needed.

Cool, credits have increased!

**Comment by srajmane** [comment]
Thank you very much for your help.
