### ISSUE TITLE
want to trace stream reverse proxy on acesslog,but miss some variable

### ISSUE THREAD

**Issue by luyaotang** [openresty/openresty#750]
I have configue a steam reverse proxy in nginx.conf。 the routing is: client -> openresty   -> tcpserver。
The problem is when I want to know a connection's original client ip info from tcpserver side, I can' get full info by openresty access log。

clinet($remote_addr:$remote_port)  …  openresty listen ($server_addr:$server_port) …  forward(  ???? )  … tcpserver listen ($upstream_addr)

I search nginx log module's variables , cant' find that. Can some one help?

**Comment by zhuizhuhaomeng** [comment]
http://nginx.org/en/docs/http/ngx_http_core_module.html#var_remote_addr
is it what you need?

is your tcpserver nginx/openresty? 
when do you want to search accesslog, openresty or tcpserver?

**Comment by luyaotang** [comment]
tcpserver is not nginx/openresty, developed by third comany,and not support proxy protocal. 
when we want to debug from the tcpserver side ,run the comman "netstat -anp|grep '$tcpserverlistenport‘“，wen can find the connected tcp info ,such as "tcp        0      0 127.0.0.1:19222         127.0.0.1:7100          ESTABLISHED 6725/nginx: worker", we want to know how can we get the "127.0.0.1:19222 " info in nginx log to nginx's access_log?

**Comment by zhuizhuhaomeng** [comment]
there are not nginx variables about the local address/port of the upstream connection.
