### ISSUE TITLE
Downloads page/pub key/entire openresty.org site is down, bad SSL CIPHER 

### ISSUE THREAD

**Issue by ahungry** [openresty/openresty#752]
Downloads page/pub key/entire openresty.org site is down, bad SSL CIPHER 

Please try to go to your own page and see if you can fix the SSL problem so it's usable for downloads/CI pipelines.

**Comment by xiaocang** [comment]
Hi, thanks for report, we had some troubles on cdn and now it is recovered.

**Comment by ahungry** [comment]
Thanks for the fast fix!
