### ISSUE TITLE
how to install lua-resty-core

### ISSUE THREAD

**Issue by buithevuong** [openresty/openresty#771]
After installing according to the instructions, I started nginx and got an error, I tried the methods of other questions but failed. give me the solution.
------------------------------------------------------------
**nginx**: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file '/home/AppCode/install-nginx/lua-resty-core-0.1.22/lib/resty/core.lua'
	no file './resty/core.lua'
	no file '/usr/local/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so') in /home/javadev/AppCode/nginx-new/conf/nginx.conf:118

-------------------------------------------------------
**my nginx** : 
nginx version: nginx/1.21.1
built by gcc 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled
configure arguments: --prefix=/home/javadev/AppCode/nginx-new --with-http_ssl_module --with-stream --with-mail=dynamic --add-module=../nginx-rtmp-module --with-ld-opt=-Wl,-rpath,/usr/local/lib --add-module=../ngx_devel_kit-0.3.1 --add-module=../lua-nginx-module-0.10.20
-------------------------------------------------------
**my LuaJIT** :
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2021 Mike Pall. https://luajit.org/

**Comment by lwx2615** [comment]
how to resolve it?It,s sad that shipped with the OpenResty bundle by default.But I also with the same issue

**Comment by lwx2615** [comment]
I have found it, though the Resty core is build in ,it also need to include the resty core lib.Just like ua_package_path "./?.lua;../../lualib/resty/?.lua;;";
