### ISSUE TITLE
API disabled in the context of access_by_lua*

### ISSUE THREAD

**Issue by endison1986** [openresty/openresty#787]
call `ngx.req.set_uri` in **_M.rewirte** failure, get error message "API disabled in the context of access_by_lua*"?

**Comment by zhuizhuhaomeng** [comment]
ngx.req.set_uri(uri, jump?, binary?)
when jump is true, it is only allowed in rewrite phase

**Comment by endison1986** [comment]
I understand, but _M.rewrite is not in rewrite phase? 
I write ngx.re.set_uri in _M.rewrite, but also get this error.

**Comment by zhuizhuhaomeng** [comment]
since _M.rewrite is not in the rewrite phase, you can not set the second arg of ngx.req.set_uri to true.

**Comment by endison1986** [comment]
It means _M_rewrite is in the rewrite phase at one time, why not now?
In that case, where should i write `ngx.req.set_uri('/abc', true);`
`_M.set` is blocked, I must do http request before rewrite uri.
