### ISSUE TITLE
ERROR  'ngx_http_lua_ffi_exec_regex'

### ISSUE THREAD

**Issue by smallbirdwy** [openresty/openresty#790]
when i require   xxx.lua , lua entry thread aborted: runtime error /nginx/lualib/ngx/re.lua:47 missing declaration for symbol 'ngx_http_lua_ffi_exec_regex'
nginx version: openresty/1.15.8.1
built by gcc 4.8.5 20150623
built with Openssl 1.1.1c
this my install "./configure --prefix=/nginx --with-pcre=/pcre-8.39 --with-openssl=/openssl-1.1.1c --with-zlib=/zlib-1.2.8 --with-http_sub_module"

**Comment by zhuizhuhaomeng** [comment]
it is better to use the newer version openresty.

**Comment by smallbirdwy** [comment]
thank you

**Comment by zhaoshoucheng** [comment]
> thank you

i have the same problem
How to solve the problem finally?
what version to use?
