### ISSUE TITLE
ngx.shared can not get the value when set it in another listen port by browser get? 

### ISSUE THREAD

**Issue by douxiaofeng99** [openresty/openresty#794]
This place is for bug reports and development discussions only. For general questions and
discussions, please join the openresty-en mailing list instead: https://groups.google.com/group/openresty-en.
If you want to use Chinese, please join the openresty (Chinese) mailing list instead: https://groups.google.com/group/openresty.
Do not use Chinese in this place.

Before you open a new issue, please search the internet and make sure it is not duplicate.

Ensure you have provided the following details while reporting a problem:

- [ ] The exact version of the related software, including but not limited to the OpenResty version
(if any), the NGINX core version, the `ngx_lua` module version(via `openresty -V` or `nginx -V`),
and your operating system version(via `uname -a`).
nginx version: nginx/1.9.9
Linux nzb01 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- [ ] **A minimal and standalone test case** that others can easily run on their side and
reproduce the issue you are seeing.
config openresty listen two http port: 18080, 19000

server {
        listen       18080;
        server_name  localhost;
        error_page   404 https://cnr.asiainfo.com/404.html;
        error_page   500 502 503 504 405 403 404 https://cnr.asiainfo.com/403.html;
            
        location / {
                default_type 'text/plain';
                content_by_lua_file conf/vhost/gray_lua.lua;
        }
        location /set_rule {
                content_by_lua '
                ngx.header["Content-Type"] = "text/html"
                local mode = ngx.var.arg_mode
                local sdata = ngx.shared.sdata
                sdata:set("RUN_MODE",mode)
                ngx.say(sdata:get("RUN_MODE"))
                ';
        }
        location /get_rule {
                content_by_lua '
                ngx.header["Content-Type"] = "text/html"
                local sdata = ngx.shared.sdata
                ngx.say(sdata:get("RUN_MODE"))
                ';
        }

server {
        listen       19000;
        server_name  localhost;

        location / {
                default_type 'text/plain';
                content_by_lua_file conf/vhost/rule_set.lua;
        }
}

 rule_set.lua 
ngx.header['Content-Type'] = 'text/html'
local mode = ngx.var.arg_mode
local sdata = ngx.shared.sdata
sdata:set("RUN_MODE",mode)
local run_mode = sdata:get("RUN_MODE")
local outprint = string.format("PARAM MODE IS:%s, MODE IS:%s",mode,run_mode)
ngx.say(outprint)

if i use curl access 19000 port: curl http://10.19.10.42:19000/?mode=SINGLE_A
console print : PARAM MODE IS:SINGLE_A, MODE IS:SINGLE_A
and i use curl or browser access 18080: curl http://10.19.10.42:18080/get_rule
all show： SINGLE_A

but, if i access 19000 by chrome browser:  http://10.19.10.42:19000/?mode=SINGLE_A
browser will display:  PARAM MODE IS:SINGLE_A, MODE IS:SINGLE_A

then i access the 18080 port to get ngx.shared value: it will display nil.
curl http://10.19.10.42:18080/get_rule
nil

- [ ] Do not simply say "something is broken" or "something does not work". Always provide
as much details as possible. Always describe **the symptoms and your expected results**.

the curl command is ok, but the chrome browser is not expected.
the chrome browser set the ngx.shared value can not be accessed.

 the ngx.shared value should be same as  curl command

You can (temporarily) enable the nginx debugging logs to see the internal workings
of NGINX in your nginx''s `error.log` file. See http://nginx.org/en/docs/debugging_log.html
The same instructions apply equally well to OpenResty.

If you are seeing crashes, please provide the full backtrace for the crash. See
https://www.nginx.com/resources/wiki/start/topics/tutorials/debugging/#core-dump
for more details.

Thanks for your cooperation.

**Comment by zhuizhuhaomeng** [comment]
you forgot the uri
should be  http://10.19.10.42:19000/get_rule?mode=SINGLE_A

**Comment by douxiaofeng99** [comment]
no, the uris get_rule and set_rule are in 18080 port.  the 19000 is write by lua.  
ngx.header['Content-Type'] = 'text/html'
local mode = ngx.var.arg_mode
local sdata = ngx.shared.sdata
sdata:set("RUN_MODE",mode)
local run_mode = sdata:get("RUN_MODE")
local outprint = string.format("PARAM MODE IS:%s, MODE IS:%s",mode,run_mode)
ngx.say(outprint)

**Comment by douxiaofeng99** [comment]
Thx.  need help

**Comment by zhuizhuhaomeng** [comment]
can not reproduce your result.

**Comment by zhuizhuhaomeng** [comment]
content_by_lua_file conf/vhost/gray_lua.lua;   

what does this script do ?

**Comment by douxiaofeng99** [comment]
ngx.header['Content-Type'] = 'text/html'
local mode = ngx.var.arg_mode
local sdata = ngx.shared.sdata
sdata:set("RUN_MODE",mode)
local run_mode = sdata:get("RUN_MODE")
local outprint = string.format("PARAM MODE IS:%s, MODE IS:%s",mode,run_mode)
ngx.say(outprint)

it will set the ngx.dict value

**Comment by xiaocang** [comment]
> but, if i access 19000 by chrome browser: http://10.19.10.42:19000/?mode=SINGLE_A
> browser will display: PARAM MODE IS:SINGLE_A, MODE IS:SINGLE_A

> then i access the 18080 port to get ngx.shared value: it will display nil.
> curl http://10.19.10.42:18080/get_rule
> nil

Hi @douxiaofeng99, When you access this address using chrome, chrome will try to access the favicon (http://10.19.10.42:19000/favicon.ico)
and the request will set your shared dict to nil.

**Comment by douxiaofeng99** [comment]
got it. Thx  a lot.
