### ISSUE TITLE
socket connect timed out

### ISSUE THREAD

**Issue by gfreezy** [openresty/openresty#80]
我用 siege 压力测试服务器的时候，刚开始的时候没有问题。但是时间长一些 nginx 会报这个错误：

```
2015/01/21 21:51:20 [error] 24312#0: *25731 lua tcp socket connect timed out, client: 127.0.0.1, server: api.xiachufang.com, request: "GET /v2/goods/fresh.json?origin=android&limit=1&sk=KtAdMhg3TSSqzv6QQ0keAA&api_sign=9be862870ccaab400c4bc274d5880a91&offset=0&api_key=07e72bef932537c71f9cafbe4c94df1c&version=97& HTTP/1.1", host: "api.almond.xiachufang.com"
2015/01/21 21:51:20 [error] 24312#0: *25731 [lua] test2.lua:17: failed to connect to redis: timeout, client: 127.0.0.1, server: api.xiachufang.com, request: "GET /v2/goods/fresh.json?origin=android&limit=1&sk=KtAdMhg3TSSqzv6QQ0keAA&api_sign=9be862870ccaab400c4bc274d5880a91&offset=0&api_key=07e72bef932537c71f9cafbe4c94df1c&version=97& HTTP/1.1", host: "api.almond.xiachufang.com"
```

nginx 配置：

```
location /v2/ {
        access_by_lua_file /etc/nginx/test2.lua;
        proxy_pass xxx;
}
```

/etc/nginx/test2.lua:

```lua
local redis = require "resty.redis"

local redis_host = "127.0.0.1"
local red = redis:new()
red:set_timeout(1000)
local ok, err = red:connect(redis_host, 6379)
if not ok then
        ngx.log(ngx.ERR, "failed to connect to redis: ", err)
        return
end

local v, err = red:get('a')
if err then
        ngx.log(ngx.ERR, "keepalive ", err)
end
local ok, err = red:set_keepalive(100000, 1)
if not ok then
        ngx.log(ngx.ERR, "keepalive ", err)
end
```

用的是最新版本的 openresty , ubuntu 14.04.1 ，运行 /ngx-req-distr -c -m `cat /var/run/nginx.pid` 会报:

 ```
Tracing 21527 21528 21529 21530 21531 21532 21533 21534 21535 21536 21537 21538 21539 21540 21541 21542 21543 21544 21545 21546 21547 21548 21549 21550 (/usr/local/openresty/nginx/sbin/nginx)...
Hit Ctrl-C to end.
^C
worker 21527:	9616 reqs,	9616 conns
worker 21528:	7330 reqs,	7330 conns
worker 21529:	5369 reqs,	5369 conns
worker 21530:	7012 reqs,	7012 conns
worker 21531:	5614 reqs,	5609 conns
worker 21532:	8338 reqs,	8338 conns
worker 21533:	4372 reqs,	4372 conns
worker 21534:	7626 reqs,	7626 conns
worker 21535:	9925 reqs,	9925 conns
worker 21536:	7418 reqs,	7418 conns
worker 21537:	5068 reqs,	5068 conns
worker 21538:	5967 reqs,	5967 conns
worker 21539:	4787 reqs,	4782 conns
worker 21540:	6661 reqs,	6661 conns
worker 21541:	11094 reqs,	11094 conns
worker 21542:	7813 reqs,	7813 conns
worker 21543:	8315 reqs,	8315 conns
worker 21544:	7236 reqs,	7236 conns
worker 21545:	3645 reqs,	3645 conns
worker 21546:	7478 reqs,	7478 conns
worker 21547:	6859 reqs,	6859 conns
worker 21548:	5168 reqs,	5168 conns
worker 21549:	6253 reqs,	6253 conns
worker 21550:	6778 reqs,	6763 conns
```

**Comment by agentzh** [comment]
@gfreezy Please, no Chinese here. This place is considered English only. If you really want to use Chinese, please join the openresty (Chinese) mailing list instead. See http://openresty.org/#Community Thanks for your cooperation.

Regarding your question, it's obvious that your redis backend is the bottleneck. The redis-server's default backlog queue size is quite small, for example. You can try increasing its `tcp-backlog` setting, see http://download.redis.io/redis-stable/redis.conf

Also, ensure your connection pool is large enough for your client concurrency level to save `connect()` and `close()` system calls.

**Comment by agentzh** [comment]
@gfreezy BTW, properly configuring your nginx worker processes can improve performance considerably as well (when the redis backend is not the bottleneck):

1. make the number of workers match the *available* logical CPU cores in your machine. note that your redis-server is also running locally, so you should spare one CPU core to it. Otherwise you're just wasting resources on context switches. If you run siege on the same box, you should account for the CPU resources used by this busy client as well.
2. properly set the CPU affinity for your nginx worker processes to avoid meaningless context switches between your nginx worker processes:

http://nginx.org/en/docs/ngx_core_module.html#worker_cpu_affinity

Well, benchmarking is an art :) And it can easily be got wrong :)

**Comment by gfreezy** [comment]
Sorry.

My nignx configuration has the following config:

```
worker_processes 24;
events {
    worker_connections 10000;
    use epoll;
}
```

If all nginx connections need to get something from redis,  does it mean that there might be 24 * 10000 connections to redis at most. So depending on my real traffic, i need to tune the redis server.

**Comment by JLLNANA** [comment]
I have the same problem.lua tcp socket connect timed out, client: x.x.x.x, server: xxx.cn, request: "POST test.lua?t=1&m=3HTTP/1.1", host: "xxx.cn"
There are lua script and php script running on this server. Only lua script has this problem, if this is the problem of nginx configuration, php script should have the same problem.

**Comment by agentzh** [comment]
Consider it resolved.
