### ISSUE TITLE
OpenResty packages for Alpine 3.15 

### ISSUE THREAD

**Issue by wkruse** [openresty/openresty#804]
[Alpine 3.15.0 was released](https://alpinelinux.org/posts/Alpine-3.15.0-released.html), would it be possible to release OpenResty packages for Alpine 3.15?

`openresty/openresty:1.19.9.1-4-alpine-fat` is also already based on Alpine 3.15

```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.0
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

openresty/docker-openresty#187

But there are no OpenResty packages for Alpine 3.15

https://openresty.org/package/alpine/

Thank you!

**Comment by tgip-work** [comment]
Hi, any updates yet regarding alpine 3.15?

**Comment by tobybellwood** [comment]
Alpine 3.15 packages look to have now been released as of https://github.com/openresty/openresty-packaging/issues/80
https://openresty.org/package/alpine/v3.15/main/
