### ISSUE TITLE
Server(server_name) config never match the requests with header host=''

### ISSUE THREAD

**Issue by HullQin** [openresty/openresty#813]
Openresty location config:
```
    server {
        listen 80 default;
        # server_name '';  # This line is useless, '' is default value.
        return 444;
    }
    server {
        listen 80;
        server_name _;
        return 444;
    }
```

request the server via python3 requests:
```python3
import requests
requests.get('http://1.14.247.221', headers={'host': ''})
```

In my expectation, error should occur (due to `return 444`):
```
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

But, I got 400, with the body:
```
<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>openresty/1.19.9.1</center>\r\n</body>\r\n</html>\r\n
```

**Requests with header host="" are always evil, I hope to return 444 rather then 404 (which leads to waste)**

I am using openresty docker image:
openresty/openresty   centos    163377e35b6c

OS version (in docker container):
```
Linux VM-16-5-centos 4.18.0-305.3.1.el8.x86_64 #1 SMP Tue Jun 1 16:14:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
`ngx_lua` module version:
```
nginx version: openresty/1.19.9.1
built by gcc 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)
built with OpenSSL 1.1.1k  25 Mar 2021 (running with OpenSSL 1.1.1l  24 Aug 2021)
```

**Comment by RocFang** [comment]
I guess requests default use http/1.1, which make sense to return a 400 for request without host header.
You can make you request use http/1.0 and try again.

Generally speaking, it has nothting todo with openresty.

**Comment by HullQin** [comment]
> I guess requests default use http/1.1, which make sense to return a 400 for request without host header. You can make you request use http/1.0 and try again.
> 
> Generally speaking, it has nothting todo with openresty.

Thanks for fast reply, but I tried with http/1.0, still 400.

```
>>> from http import client
>>> client.HTTPConnection._http_vsn=10
>>> client.HTTPConnection._http_vsn_str='HTTP/1.0'
>>> requests.get('http://127.0.0.1', headers={'host': ''}).text
'<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>openresty/1.19.9.1</center>\r\n</body>\r\n</html>\r\n'
>>>
```

And access.log:
```
[2022-02-24T16:11:13+08:00] "" "/" "GET" "http" "HTTP/1.0" 400 163 "-" "python-requests/2.27.1"
```
format:
```
log_format  main  '[$time_iso8601] "$host" "$request_uri" "$request_method" "$scheme" "$server_protocol" '
                      '$status '
                      '$body_bytes_sent "$http_referer" "$http_user_agent"';
```

The request with header host=''(**empty string but not null**) should use(or hit) such server role:
```
server {
        listen 80 default;
        # server_name '';  # This line is useless, '' is default value.
        return 444;
    }
```
But it did not, so I think it should be fixed 😊

**Comment by RocFang** [comment]
@HullQin  yes, it's nginx's behavior. if host length is zero, nginx will give a 400 reply.
you could see it in function ngx_http_validate_host in src/http/nginx_http_request.c :)

**Comment by HullQin** [comment]
> @HullQin yes, it's nginx's behavior. if host length is zero, nginx will give a 400 reply. you could see it in function ngx_http_validate_host in src/http/nginx_http_request.c :)

thanks
