### ISSUE TITLE
lua table iterate terminated early

### ISSUE THREAD

**Issue by dragonorloong** [openresty/openresty#817]
An error is reported when using lua-resty-http to send a request, the error message:  **invalid value (boolean) at index 8 in table for 'concat**,  “for pairs" terminates early， only 1.21.4.1rc2 exist this bug， The test code cannot be reproduced, but it is easy to reproduce when it is released to the production environment, and the reason for the recurrence cannot be determined

nginx version: **openresty/1.21.4.1rc2**

"for pairs" terminates early when calling the following function "_format_request"
funcion log : 
   `_format_request` begin, headers:{"Content-Type":"application\/json","App-Key":"aaa","X-Forwarded-For":"vv","Sign":"cc","Content-Length":137,"Accept-Encoding":"","Host":"dd","User-Agent":"lua-resty-http\/0.09 (Lua) ngx_lua\/10021"}

_format_request after, headers:["POST"," ","\/test",""," HTTP\/1.1\r\n","Content-Type: application\/json\r\n","\r\n",true]
`

`

    local function _format_request(params)
    local version = params.version
    local headers = params.headers or {}
    local cjson = require 'cjson'
    ngx.log(ngx.ERR, "_format_request begin, headers:", cjson.encode(headers))

    local query = params.query or ""
    if query then
        if type(query) == "table" then
            query = "?" .. ngx_encode_args(query)
        end
    end

    -- Initialize request
    local req = {
        str_upper(params.method),
        " ",
        params.path,
        query,
        HTTP[version],
        -- Pre-allocate slots for minimum headers and carriage return.
        true,
        true,
        true,
    }
    local c = 6 -- req table index it's faster to do this inline vs table.insert

    -- Append headers
    for key, values in pairs(headers) do
        if type(values) ~= "table" then
            values = {values}
        end

        key = tostring(key)
        for _, value in pairs(values) do
            req[c] = key .. ": " .. tostring(value) .. "\r\n"
            c = c + 1
        end
    end

    -- Close headers
    req[c] = "\r\n"

    ngx.log(ngx.ERR, "_format_request after, headers:", cjson.encode(req))

    return tbl_concat(req)
   end

**Comment by zhuizhuhaomeng** [comment]
@dragonorloong  would you please print the value of req[8] before tbl_concat

**Comment by dragonorloong** [comment]
> 
_format_request after, headers:["POST"," ","/test",""," HTTP/1.1\r\n","Content-Type: application/json\r\n","\r\n",true]
Because the following loop terminates early, resulting in req[8] = true

-- Append headers
for key, values in pairs(headers) do
    if type(values) ~= "table" then
        values = {values}
    end

    key = tostring(key)
    for _, value in pairs(values) do
        req[c] = key .. ": " .. tostring(value) .. "\r\n"
        c = c + 1
    end
end

**Comment by zhuizhuhaomeng** [comment]
```
Because the following loop terminates early, resulting in req[8] = true
```
Is that expected?

**Comment by dragonorloong** [comment]
> ```
> Because the following loop terminates early, resulting in req[8] = true
> ```
> 
> Is that expected?

No, this function is to copy the headers into req, but if the copy is not completed, the loop ends early

**Comment by zhuizhuhaomeng** [comment]
so what's the data in the table?
maybe you can try cjson to dump the table

**Comment by dragonorloong** [comment]
> so what's the data in the table? maybe you can try cjson to dump the table

Please look carefully at the code above:
`
_format_request begin, headers:{"Content-Type":"application/json","App-Key":"aaa","X-Forwarded-For":"vv","Sign":"cc","Content-Length":137,"Accept-Encoding":"","Host":"dd","User-Agent":"lua-resty-http/0.09 (Lua) ngx_lua/10021"}

_format_request after, headers:["POST"," ","/test",""," HTTP/1.1\r\n","Content-Type: application/json\r\n","\r\n",true]
`

expectation： _format_request after, headers:["POST"," ","/test",""," HTTP/1.1\r\n","Content-Type: application/json\r\n", “App-Key:aaa\r\n”, "X-Forwarded-For: vv", "Sign: cc\r\n", "Content-Length:137\r\n", "Accept-Encoding:\r\n", "Host:dd\r\n", "User-Agent: lua-resty-http/0.09 (Lua) ngx_lua/10021\r\n"]

 **All values need to be copied from headers to req, but only one key is copied, for pairs(headers) is over**

**Comment by dragonorloong** [comment]
> so what's the data in the table? maybe you can try cjson to dump the table


Please look carefully at the code above

`
_format_request begin, headers:{"Content-Type":"application/json","App-Key":"aaa","X-Forwarded-For":"vv","Sign":"cc","Content-Length":137,"Accept-Encoding":"","Host":"dd","User-Agent":"lua-resty-http/0.09 (Lua) ngx_lua/10021"}

_format_request after, headers:["POST"," ","/test",""," HTTP/1.1\r\n","Content-Type: application/json\r\n","\r\n",true]
`

expectation： _format_request after, headers:["POST"," ","/test",""," HTTP/1.1\r\n","Content-Type: application/json\r\n", “App-Key:aaa\r\n”, "X-Forwarded-For: vv", "Sign: cc\r\n", "Content-Length:137\r\n", "Accept-Encoding:\r\n", "Host:dd\r\n", "User-Agent: lua-resty-http/0.09 (Lua) ngx_lua/10021\r\n"]

 **All values need to be copied from headers to req, but only one key is copied, for pairs(headers) is over**

**Comment by zhuizhuhaomeng** [comment]
Is this bug exists in openresty-1.21.4.1rc1 ?

**Comment by dragonorloong** [comment]
> Is this bug exists in openresty-1.21.4.1rc1 ?

This version has not been tested, and it is not convenient to reproduce in the production environment

**Comment by aarcamp** [comment]
We're also using lua-resty-http (version 0.13) and ran into this same issue. I didn't try any of the aforementioned tags, but the v2.1-20201229 sources of luajit2 work.

**Comment by CapsAdmin** [comment]
I come from the LuaJIT issue tracker out of curiosity, so I have no context here.

Can we guarantee that HTTP[version] won't return nil? (default to a version maybe)

Unrelated to the issue: if headers contain 1 entry or is empty then table.concat would error because it contains true at the end. (use "" instead of true maybe)
