### ISSUE TITLE
use regular expression in location doesn't work

### ISSUE THREAD

**Issue by doodle88** [openresty/openresty#82]
objective: redirect https://hostname/(?<prj>\w+).googlecode/(?<path>.*) to https://$prj.googlecode.com/$path
test url: https://hostname/mythbox.googlecode/files/script.mythbox.1.1.0.zip

following code answers me with "502 Bad Gateway" error:
 location ~ '^/(\w+).googlecode/(.*)$' {
        proxy_pass "https://$1.googlecode.com/$2";
 }
I replaced the proxy_pass with echo, the target url is correct and location without re works properly. Any idea???

**Comment by agentzh** [comment]
@doodle88 Try the following:

1. (temporarily) enable the nginx debug logging: http://nginx.org/en/docs/debugging_log.html It will generate a lot of details in the nginx error logs.
2. upgrade to the latest OpenResty release.

If you still have no idea, please provide the complete debugging logs and the exact version number of OpenResty.

**Comment by agnibha** [comment]
Hi @agentzh, I've got this same problem with server_name and proxy_pass. While the same configuration works in base nginx, it doesn't seem to be working for openresty:

`   server {
     resolver 8.8.8.8;
     listen 80;

     server_name ~^(.*)\.example\.com;
     set $upstream_endpoint  https://cdn.example.com/service-workers/$1$request_uri;
     location / {
       proxy_pass $upstream_endpoint;
       proxy_pass_request_headers on;
     }
   }`

**Comment by agentzh** [comment]
@agnibha Maybe you should just try out the latest OpenResty version?

**Comment by agnibha** [comment]
I've updated to latest(nginx version: openresty/1.11.2.4). The Bad Gateway problem still exists.

The configure arguments: 
`--prefix=/usr/local/openresty/nginx --with-debug --with-cc-opt='-DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC -O2' --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.60 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.06 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.8 --add-module=../ngx_lua_upstream-0.06 --add-module=../headers-more-nginx-module-0.32 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.18 --add-module=../redis2-nginx-module-0.14 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-nginx-module-0.07 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-http_realip_module --with-stream --with-http_ssl_module`

**Comment by agnibha** [comment]
Update: I found the errors thanks to the debug logs. It was a timeout error and then, an SSL handshake error. I've had it resolved at my end. Thanks @agentzh for the suggestions.

**Comment by agentzh** [comment]
Consider it resolved.
