### ISSUE TITLE
dnf install - checksum doesn't match

### ISSUE THREAD

**Issue by spcu185** [openresty/openresty#824]
When attempting to 'dnf install openresty' I see a failure re checksum:

[MIRROR] openresty-zlib-1.2.12-1.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: e3039f8f10d6402fc3f48cb5d09593ad545ec3648fddc00ed086b25bd929893e(sha256)  Expected: 4fe80843b6599777ec1e1e1bf2deeaba86946a7d96b2d151a5e33735cf2f1937(sha256)

My openresty repo is configured as below:
[openresty]
name=Official OpenResty Open Source Repository for CentOS
baseurl=https://openresty.org/package/centos/$releasever/$basearch
skip_if_unavailable=False
gpgcheck=1
repo_gpgcheck=0
gpgkey=https://openresty.org/package/pubkey.gpg
enabled=1
enabled_metadata=1

So installation fails. Is this an issue with the checksum in the Repo?

**Comment by spcu185** [comment]
Thankyou. Unfortunately the error remains the same.

**Comment by zhuizhuhaomeng** [comment]
Try it again.  If still fail to installl,  please run `dig openresty.org` and paste the result here.

**Comment by spcu185** [comment]
Looks good now. Thank you very much.
To be clear, was this a temporary issue on my side, or a problem with the openresty repo?
