### ISSUE TITLE
How to get port number in Lua when using port range in nginx config.

### ISSUE THREAD

**Issue by anand-010** [openresty/openresty#830]
I am new to openresty and Lua programming.
This project is the only solution I've found for my dynamic tcp load balancing problem.
My nginx listening on multiple ports using port range operator.
```
server {
    listen 9000-9999;

    proxy_pass http://upstream-host:$server_port;
}
```
i want to know which port is used in current request inside lua to make some redis queries.
I've don't find a way to do that.
I've searched ngx. methods but i've couldn't find any please help me.

**Comment by zhuizhuhaomeng** [comment]
you can use ngx.var.server_port

**Comment by anand-010** [comment]
From [this reference](https://openresty-reference.readthedocs.io/en/latest/Lua_Nginx_API/?q=port&check_keywords=yes&area=default#ngxvarvariable) I've thought that only the variables created in the nginx config variables are accessible by ngx.var.VARIABLE.
After a quick search i've found that nginx already using some variables the server_port is one of them.
The [complete list found here](http://nginx.org/en/docs/varindex.html).
Thank you for helping me.
