### ISSUE TITLE
content_by_lua_block not working with tcp proxy_pass.

### ISSUE THREAD

**Issue by anand-010** [openresty/openresty#831]
Hello I am new to nginx and openresty.
I am trying to dynamically route tcp connections.
But content_by_lua_block doesn't seems to be working in tcp proxy_pass configuration however it worked with example http configuration.
```
error_log logs/error.log;
events {
    worker_connections 1024;
}

stream {
    # define a TCP server listening on the port 8080:
    server {
        listen 8080;
        set $target '';
        content_by_lua_block {
            ngx.var.target = "127.0.0.1:7000" <-- tried to inject target but it never called
        }
        proxy_pass $target;
    }
}
```
But when i added
`set $target "127.0.0.1:7000";`
It starts working.
I've also tried to paste it inside location / {  } but it also not working.
Please help me.

**Comment by zhuizhuhaomeng** [comment]
content_by_lua_block  and proxy_pass can not coexists.

**Comment by anand-010** [comment]
Any alternative method to achieve it?.
i've seen upstreams in multiple places but not with tcp.
I'm trying to route tcp connections based on lua logic.

**Comment by zhuizhuhaomeng** [comment]
you can change content_by_lua_block to access_by_lua_block

**Comment by zhuizhuhaomeng** [comment]
balancer_by_lua_* may meet your need

**Comment by anand-010** [comment]
Thank you it seems to be working.
