### ISSUE TITLE
A question about the size of openresty 

### ISSUE THREAD

**Issue by Succy** [openresty/openresty#838]
When I try to compile the openresty source code on `CentOS7`，I found 2 question:
1、 In the pre-build rpm distribution, size of `nginx` binary file is 1.9M, But building from source code, size of `nginx` binary file is 17M. Why is the size so different?
2、I used the args from pre-build's `nginx  -V` to compile source code, It dosn't compile succeed, because opt `--with-cc-opt =“... I/usr/local/openresty/openssl111/include ...”` contains `openssl111/include` directory but in the `/usr/local/openresty/openssl111` dosn't have the `include` subdirectory, I want to known why it work on rpm package build phase?

Looking forward to your reply， Thanks！

**Comment by zhuizhuhaomeng** [comment]
the debuginfo was stripped from the bin file, so the pre-build nginx is smaller.
you need to install openresty-debuginfo when you want to debug with gdb

**Comment by zhuizhuhaomeng** [comment]
for the second question,  please refer to 
https://github.com/openresty/openresty-packaging/blob/master/rpm/SPECS/openresty.spec#L194

**Comment by Succy** [comment]
> the debuginfo was stripped from the bin file, so the pre-build nginx is smaller. you need to install openresty-debuginfo when you want to debug with gdb

Thank you very much for your reply! and I want to known how to strip debuginfo from bin file? is with a opt when compile? OK,  I'll search on baidu later

**Comment by Succy** [comment]
> for the second question, please refer to https://github.com/openresty/openresty-packaging/blob/master/rpm/SPECS/openresty.spec#L194

Oh  I known how to strip debuginfo from bin file, In the `bundle/nginx-VERSION/auto/cc/gcc` file comment `CFLAGS = "$CFLAGS -g"`  the nginx bin file will smaller than before.

for the second question, I don't understand very well, It's delete the 'include' directory after build? In my practice, if no include/headerfiles while compile source code will show `undefined reference to XXX`

**Comment by zhuizhuhaomeng** [comment]
For the second question, maybe there are header files in the /usr/include.
