### ISSUE TITLE
Compile error on centos 5.4 since 1.7.7.2

### ISSUE THREAD

**Issue by aseiot** [openresty/openresty#85]
Since openresty version 1.7.7.2, I can not correctly compile it on my system. The error is complained when building luajit.

```
gmake TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/openresty/luajit
==== Building LuaJIT 2.1.0-alpha ====
gmake -C src
gmake[1]: Entering directory `/root/lnmp1.0/ngx_openresty-1.7.10.1/build/LuaJIT-2.1-20150223/src'
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.S
ASM       lj_vm.o
CC        lj_gc.o
BUILDVM   lj_ffdef.h
CC        lj_err.o
CC        lj_char.o
BUILDVM   lj_bcdef.h
CC        lj_bc.o
CC        lj_obj.o
CC        lj_buf.o
CC        lj_str.o
CC        lj_tab.o
CC        lj_func.o
CC        lj_udata.o
CC        lj_meta.o
CC        lj_debug.o
CC        lj_state.o
CC        lj_dispatch.o
CC        lj_vmevent.o
CC        lj_vmmath.o
lj_vmmath.c: In function ‘lj_vm_foldfpm’:
lj_vmmath.c:133: warning: implicit declaration of function ‘exp2’
lj_vmmath.c:133: warning: incompatible implicit declaration of built-in function ‘exp2’
lj_vmmath.c:135: warning: implicit declaration of function ‘log2’
lj_vmmath.c:135: warning: incompatible implicit declaration of built-in function ‘log2’
lj_vmmath.c: In function ‘lj_vm_foldfpm’:
lj_vmmath.c:133: warning: implicit declaration of function ‘exp2’
lj_vmmath.c:133: warning: incompatible implicit declaration of built-in function ‘exp2’
lj_vmmath.c:135: warning: implicit declaration of function ‘log2’
lj_vmmath.c:135: warning: incompatible implicit declaration of built-in function ‘log2’
CC        lj_strscan.o
CC        lj_strfmt.o
CC        lj_api.o
CC        lj_profile.o
CC        lj_lex.o
CC        lj_parse.o
CC        lj_bcread.o
CC        lj_bcwrite.o
CC        lj_load.o
CC        lj_ir.o
lj_ir.c:64: error: ‘exp2’ undeclared here (not in a function)
lj_ir.c:64: error: ‘log2’ undeclared here (not in a function)
gmake[1]: *** [lj_ir.o] Error 1
gmake[1]: Leaving directory `/root/lnmp1.0/ngx_openresty-1.7.10.1/build/LuaJIT-2.1-20150223/src'
gmake: *** [default] Error 2
ERROR: failed to run command: gmake TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/openresty/luajit
```

When switch back to 1.7.7.1, it works.

What should I do to overcome this. THX

My machine is:

```
centos 5.4
x86
gmake 3.81
```

**Comment by agentzh** [comment]
@aseiot What's the version of your gcc and glibc?

**Comment by agentzh** [comment]
@aseiot It seems that recent LuaJIT changes now require relatively new versions of glibc. I've dropped Mike Pall a note. Hopefully he can commit a workaround to continue supporting older versions of glibc.

**Comment by agentzh** [comment]
@aseiot According to Mike Pall, the culprit might be the `CC=cc` argument passed to LuaJIT's build system (which defaults to `CC=gcc`) by OpenResty's build system. I've removed it in the following OpenResty source tarball:

http://openresty.org/download/ngx_openresty-1.7.10.2rc0.tar.gz

Please test it out on your side. Thank you!

**Comment by aseiot** [comment]
Thanks for your rapidly response.
I have just test the modified version. However, it doesn't works!
The complained error is same as before. 
```
==== Building LuaJIT 2.1.0-alpha ====
gmake -C src
gmake[1]: Entering directory `/root/lnmp1.0/ngx_openresty-1.7.10.2rc0/build/LuaJIT-2.1-20150223/src'
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.S
ASM       lj_vm.o
CC        lj_gc.o
BUILDVM   lj_ffdef.h
CC        lj_err.o
CC        lj_char.o
BUILDVM   lj_bcdef.h
CC        lj_bc.o
CC        lj_obj.o
CC        lj_buf.o
CC        lj_str.o
CC        lj_tab.o
CC        lj_func.o
CC        lj_udata.o
CC        lj_meta.o
CC        lj_debug.o
CC        lj_state.o
CC        lj_dispatch.o
CC        lj_vmevent.o
CC        lj_vmmath.o
lj_vmmath.c: In function ‘lj_vm_foldfpm’:
lj_vmmath.c:133: warning: implicit declaration of function ‘exp2’
lj_vmmath.c:133: warning: incompatible implicit declaration of built-in function ‘exp2’
lj_vmmath.c:135: warning: implicit declaration of function ‘log2’
lj_vmmath.c:135: warning: incompatible implicit declaration of built-in function ‘log2’
lj_vmmath.c: In function ‘lj_vm_foldfpm’:
lj_vmmath.c:133: warning: implicit declaration of function ‘exp2’
lj_vmmath.c:133: warning: incompatible implicit declaration of built-in function ‘exp2’
lj_vmmath.c:135: warning: implicit declaration of function ‘log2’
lj_vmmath.c:135: warning: incompatible implicit declaration of built-in function ‘log2’
CC        lj_strscan.o
CC        lj_strfmt.o
CC        lj_api.o
CC        lj_profile.o
CC        lj_lex.o
CC        lj_parse.o
CC        lj_bcread.o
CC        lj_bcwrite.o
CC        lj_load.o
CC        lj_ir.o
lj_ir.c:64: error: ‘exp2’ undeclared here (not in a function)
lj_ir.c:64: error: ‘log2’ undeclared here (not in a function)
gmake[1]: *** [lj_ir.o] Error 1
gmake[1]: Leaving directory `/root/lnmp1.0/ngx_openresty-1.7.10.2rc0/build/LuaJIT-2.1-20150223/src'
gmake: *** [default] Error 2
ERROR: failed to run command: gmake TARGET_STRIP=@: CCDEBUG=-g PREFIX=/usr/local/luajit
```

My gcc & glibc version are
```
gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)
ldd (GNU libc) 2.5
```

Many thanks for your kindly help!

**Comment by agentzh** [comment]
@aseiot Thanks for your feedback! Now let's dig deeper :)

Will you send me the output of the following commands in that system?

    gcc -E src/lj_ir.c
    gcc -E src/lj_vmmath.c

assuming you have entered the directory `ngx_openresty-1.7.10.2rc0/bundle/LuaJIT-2.1-20150223/`

The output can be huge. Feel free to attach the *complete* output to the `gist.github.com` site or somewhere like that and just share the link here.

Thanks!

**Comment by aseiot** [comment]
@agentzh Thanks
The outputs are linked here:
https://gist.github.com/aseiot/2dde65074f12ce03e62c#file-output-of-build-lj_ir-c
https://gist.github.com/aseiot/2dde65074f12ce03e62c#file-output-of-build-lj_vmmath-c

**Comment by agentzh** [comment]
@aseiot Thanks for the feedback! Okay, good, the `exp2` are `exp1` functions are indeed shielded away. So it seems that we need to define some special macros to make them visible from your `math.h`.

Let's keep digging. I need the following more information from you to nail down the root cause:

1. Please provide the output of the command

    ```
gcc -E -dM src/lj_ir.c
gcc -E -dM src/lj_vmmath.c
    ```
    assuming you're still in the directory `ngx_openresty-1.7.10.2rc0/bundle/LuaJIT-2.1-20150223/`.

1. Please provide the complete file `/usr/include/bits/mathcalls.h` from your system.

We're close ;)

**Comment by aseiot** [comment]
The outputs and c head file have been attached to the following address.
https://gist.github.com/aseiot/5f063d636cd75656748f
Wish it is helpful.
Thanks!

**Comment by agentzh** [comment]
@aseiot Okay, the most interesting snippet is

```C
#ifdef __USE_ISOC99
__BEGIN_NAMESPACE_C99
/* Compute base-2 exponential of X.  */
__MATHCALL (exp2,, (_Mdouble_ __x));
 
/* Compute base-2 logarithm of X.  */
__MATHCALL (log2,, (_Mdouble_ __x));
__END_NAMESPACE_C99
#endif
```

So the functions `exp2` and `log2` are guarded by the `__USE_ISOC99` macro. But from your `-E -dM` output, this `__USE_ISOC99` macro is not defined by gcc by default.

In recent versions of gcc (like 4.7 and 4.8), the `__USE_ISOC99` macro is defined by default, as witnessed by the `-E -dM` output on my side:

```C
#define __USE_ISOC99 1
```

So a simple work-around is to build OpenResty with something like this:

```bash
./configure --with-luajit-xcflags='-D__USE_ISOC99=1'
```

Will you try it out on your side if it fixes the build problems?

Thanks for digging this up :)

**Comment by aseiot** [comment]
It's ok now!
Many thanks for your kindly help!

**Comment by agentzh** [comment]
@aseiot Glad to know it works for you :) I've asked Mike Pall to consider making it the default in LuaJIT's build system :)
