### ISSUE TITLE
OpenResty(v1.21.4.1) fails to forward request to backend server after reading request body with ngx.req.get_body_data()

### ISSUE THREAD

**Issue by xseruer** [openresty/openresty#894]
I'm currently experiencing an issue with OpenResty where it fails to forward a request to the backend server after reading the request body using the ngx.req.get_body_data() method in the content_by_lua_file directive.

I have a configuration file that uses the content_by_lua_file directive to load a Lua script that reads the request body using ngx.req.get_body_data(). The script then sets a variable based on the contents of the request body. However, after the request body is read, the request is not forwarded to the backend server.

I suspect that this may be a bug in OpenResty or a limitation of the ngx.req.get_body_data() method. However, I'm not sure how to proceed with troubleshooting or reporting the issue.

Configuration File:
```js
log_format chat_log '$log_time $remote_addr $remote_user [$prompt]';

server {
    listen 80;
    listen 443 ssl http2;
    server_name *********;
    server_name _;

    ssl_certificate /etc/nginx/conf.d/cert/[*********].pem; 
    ssl_certificate_key /etc/nginx/conf.d/cert/[*******].key; 

    set $prompt '';
    client_body_buffer_size 1m;
    client_max_body_size 1m;

    location /api/chat-process {
        proxy_pass http://[*******]:3002;

        # Define Lua script to format $msec as yyyy-mm-dd hh:mm:ss
        set_by_lua_block $log_time {
            return os.date("%Y-%m-%d %H:%M:%S", ngx.time() + ngx.var.msec / 1000)
        }

        # Define Lua script to format $time_local as yyyy-mm-dd
        set_by_lua_block $date {
            return os.date("%Y%m%d", ngx.time())
        }

        # Disable log encoding to avoid display issues with Chinese characters
        log_escape_non_ascii off;

        # Record access log
        access_log /etc/nginx/conf.d/logs/chat-$date.log chat_log;

        # Load Lua script to read request body
        content_by_lua_file "/etc/nginx/conf.d/chatlog.lua"; 
    }

    auth_basic "Please enter your username and password";
    auth_basic_user_file "/etc/nginx/conf.d/chatgpt-htpasswd.txt"; 

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;

    chunked_transfer_encoding on;
    proxy_request_buffering off;
    proxy_read_timeout 3600s;
}
```
Lua Script (chatlog.lua):
```lua
ngx.req.read_body()
local body = ngx.req.get_body_data()
if body then
    local json = require("cjson.safe")
    local data = json.decode(body)
    if data then
        ngx.var.prompt = data.prompt
    end
end
```
I hope this description accurately reflects your issue and provides enough information to help OpenResty developers identify the root cause of the problem. If you need further assistance or clarification, please don't hesitate to ask.

**Comment by xseruer** [comment]
I tried replacing `content_by_lua_file` with `access_by_lua_fil`e and it works fine for forwarding and logging. But `log_by_lua_file` and `content_by_lua_file` does not work.

I don't know if this feature meets the code design expectations, if it does please help me close my current issues.

**Comment by zhuizhuhaomeng** [comment]
content_by_lua_* and proxy_pass are mutually exclusive.
So content_by_lua_file can not meet your need.
