### ISSUE TITLE
Support for NGINX 1.22.1+

### ISSUE THREAD

**Issue by liujin1993** [openresty/openresty#905]
Hi, Are there any plans to update nginx to v1.22.1+?

https://github.com/kubernetes/ingress-nginx/issues/9771

**Comment by zhuizhuhaomeng** [comment]
We will provide support of nginx-1.25  in the second half of the year

Tobias Birmili ***@***.***> 于2023年5月10日周三 19:30写道：

**Comment by splitice** [comment]
Is that to include support for https://github.com/openresty/openresty/issues/741 ?

**Comment by komapa** [comment]
Any Release Candidates at least any time soon?

Thank you!

**Comment by kszyntar** [comment]
Another reason for this currency update is the upcoming EOL of OpenSSL 1.1.1: https://www.openssl.org/blog/blog/2023/06/15/1.1.1-EOL-Reminder/

**Comment by dominykas** [comment]
I'm trying to understand where things are and whether I can help by making some code contributions.

I can seen that there are patches for 1.23.0 in the `patches` folder - does that mean that 1.23.x should work? Or are these simply lying around? I can see a mention of 1.25.x in this thread - but does that mean that 1.23 will get skipped entirely?

I was not able to get the 1.21.4 tests to run (so far... I might try again, if it's worth it), so I can't verify the 1.23.x either.

Is there anything else one can do to help speed up the rollout?

**Comment by zhuizhuhaomeng** [comment]
@dominykas 1.23.x will be skipped entirely.
1.25.x is a better choice for the next openresty release.
We need to make all the openresty related repo works correctly before we can publish a new release.
Eg. lua-nginx-module, lua-resty-core, stream-lua-nginx-moddule, headers-more-nginx-module and so on.

**Comment by yslab1** [comment]
Is there any news about the **support of nginx-1.25?** 
@zhuizhuhaomeng 

Thank you!

**Comment by computinglife** [comment]
Hi, is this release still expected to happen this year?

**Comment by AlexGluck** [comment]
Hi, can please give some feedback about expected schedule for new release?

**Comment by weisjohn** [comment]
for those on the thread, it appears that this is done with the 1.25 series release:
https://openresty.org/en/ann-1025003001.html

I think this issue could be closed.
