### ISSUE TITLE
Request to resume regular updates for openresty

### ISSUE THREAD

**Issue by easyhhvm** [openresty/openresty#919]
openresty is a great open source web server that provides high performance and stability. However， it appears development has stalled， with the last release being over a year ago.
As an active user of openresty . I wanted to kindly request that the development team consider resuming regular updates to the project. New releases with bug fixes， security patches and enhancements would be very beneficial for the community.

**Comment by zhuizhuhaomeng** [comment]
@easyhhvm  we have just released openresty-1.21.4.2.
