### ISSUE TITLE
openresty-1.21.4 compile error

### ISSUE THREAD

**Issue by auqf** [openresty/openresty#924]
![image](https://github.com/openresty/openresty/assets/8895540/c6b014d4-9deb-4c21-a857-3e4e3b369032)

![image](https://github.com/openresty/openresty/assets/8895540/77e2d056-b1e1-4b7d-99ee-85d5998584b1)

**Comment by lynch1981** [comment]
gcc releases from 5.5 to 10.4 default to -std=gnu11, redefine of typedef is allowed since c11.
the gcc version of centos6.8 is too old.
