### ISSUE TITLE
Linux Debian 11 install the openresty package in parts.

### ISSUE THREAD

**Issue by bagasik** [openresty/openresty#936]
Hello.
We have a current project, it works on the FreeBSD system, everything suits us.
We decided to adapt it to Debian Linux. There was a misunderstanding of how and what to install.

We don't want to be dependent on the full build of the openresty package.
How can we install these packages separately?

In system FreeBSD installed soft
lua-resty-core-0.1.27
lua-resty-lrucache-0.13
lua53-5.3.6
luajit-openresty-2.1.20230911_1
nginx-1.24

I don't see any such packages on Debian.
lua-resty-core-0.1.27
lua-resty-lrucache-0.13
luajit-openresty-2.1.20230911_1
How do I install these packages on debian 11?

**Comment by zhuizhuhaomeng** [comment]
you'd better to use the tarball from https://openresty.org

**Comment by bagasik** [comment]
In this case, I will be dependent on the openresty developers.
To me cannot install a third-party module in nginx, and cannot downgrade or upgrade the nginx version.

**Comment by zhuizhuhaomeng** [comment]
For lua-resty-core-0.1.27, lua-resty-lrucache-0.13
You can download them through github.com and put them in the directory you want.
For luajit-openresty-2.1.20230911_1, you need to download and build it yourself.
The lua-nginx-module requires luajit when building the nginx.

**Comment by bagasik** [comment]
lua-resty-core-0.1.27, lua-resty-lrucache-0.13
I don’t understand what it means to download and place in the right place?

**Comment by zhuizhuhaomeng** [comment]
If you want to compile openresty yourself, why not use the tarball from openresty.org?

**Comment by zhuizhuhaomeng** [comment]
If you want to compile openresty yourself, why not use the tarball from openresty.org?

**Comment by bagasik** [comment]
Installed in debian 12.
apt list --installed | egrep 'lua|nginx'
libluajit2-5.1-2/stable,now 2.1-20230119-1 amd64 [installed,automatic]
libluajit2-5.1-common/stable,now 2.1-20230119-1 all [installed,automatic]
libnginx-mod-http-lua/stable,now 1:0.10.23-1 amd64 [installed]
libnginx-mod-http-ndk/stable,now 1:0.3.2-3 amd64 [installed,automatic]
lua-resty-core/stable,now 0.1.25-1 all [installed,automatic]
lua-resty-lrucache/stable,now 0.13-10 all [installed,automatic]
lua5.3/stable,now 5.3.6-2 amd64 [installed]
nginx-common/stable,now 1.22.1-9 all [installed,automatic]
nginx/stable,now 1.22.1-9 amd64 [installed,automatic]

Looking at package information.
apt search openresty

libluajit2-5.1-2/stable,now 2.1-20230119-1 amd64 [installed,automatic]
  OpenResty-maintained branch of LuaJIT (shared objects)

libluajit2-5.1-common/stable,now 2.1-20230119-1 all [installed,automatic]
  OpenResty-maintained branch of LuaJIT (common files)

**Comment by bagasik** [comment]
Luajit-openresty-2.1
Where can I get it for the Linux Debian 12 system?


Now installed in Debian 12.

apt list --installed | egrep 'lua|nginx'

libluajit2-5.1-2/stable,now 2.1-20230119-1 amd64 [installed,automatic]
libluajit2-5.1-common/stable,now 2.1-20230119-1 all [installed,automatic]
libnginx-mod-http-lua/stable,now 1:0.10.23-1 amd64 [installed]
libnginx-mod-http-ndk/stable,now 1:0.3.2-3 amd64 [installed,automatic]
lua-resty-core/stable,now 0.1.25-1 all [installed,automatic]
lua-resty-lrucache/stable,now 0.13-10 all [installed,automatic]
lua5.3/stable,now 5.3.6-2 amd64 [installed]
luajit2/stable,now 2.1-20230119-1 amd64 [installed]
nginx-common/stable,now 1.22.1-9 all [installed,automatic]
nginx/stable,now 1.22.1-9 amd64 [installed,automatic]


Processing images on the site using lua does not work.

maybe it's in the package luajit-openresty-2.1.20230911_1

**Comment by zhuizhuhaomeng** [comment]
The packages you listed are not officially provided by openresty, so you'll have to consult the owner of the repository that provides them.
