### ISSUE TITLE
The server_name does not match, but it can pass through the proxy via port 444.

### ISSUE THREAD

**Issue by zhangairen** [openresty/openresty#937]
Hello.
We have a current project, OpenResty configuration file. Create a server_name domain and listen on ports 443 and 444 with SSL. Allow access to port 444 even if there is no matching server_name domain. Proxy the requests to the backend.

nginx version: openresty/1.21.4.2

configuration like this
<img width="741" alt="image" src="https://github.com/openresty/openresty/assets/34363408/c1e6881a-a356-453e-8c4d-0624123f1820">

**Comment by manoaratefy** [comment]
Hello,

I think this is a thing related to nginx, not directly openresty.

You should play with `server_name _;` (catch-all) directive and the `server{}` block order to allow/disallow your current server block handling any unmatched server_name. nginx seems to catch the first server block if there's no server_name matched.
