### ISSUE TITLE
error installing openresty in redhat 9 due to sha-1 signing deprecated

### ISSUE THREAD

**Issue by danielkauf** [openresty/openresty#939]
I am trying to install openresty using Redhat 9 docker image, but is failing. The problem seem to be because sha-1 signing is being deprecated starting in redhat 9
https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9

I am using this Dockerfile (uploaded in a zip since it uploading directly is not allowed by github: [Dockerfile.zip](https://github.com/openresty/openresty/files/13460043/Dockerfile.zip)
Output when running docker file ("docker build .") is the following:

...
43.50 Total                                           3.8 MB/s | 118 MB     00:30     
43.75 Official OpenResty Open Source Repository for R 7.5 kB/s | 1.6 kB     00:00    
43.87 Importing GPG key 0xD5EDEB74:
43.87  Userid     : "OpenResty Admin <admin@openresty.com>"
43.87  Fingerprint: E522 18E7 0878 97DC 6DEA 6D6D 97DB 7443 D5ED EB74
43.87  From       : https://openresty.org/package/pubkey.gpg
43.87 warning: Signature not supported. Hash algorithm SHA1 not available.
49.12 Key import failed (code 2). Failing package is: openresty-1.21.4.3-1.el9.x86_64
49.12  GPG Keys are configured as: https://openresty.org/package/pubkey.gpg
49.12 Public key for openresty-doc-1.21.4.3-1.el9.noarch.rpm is not installed. Failing package is: openresty-doc-1.21.4.3-1.el9.noarch
...

**Comment by zhuizhuhaomeng** [comment]
I think you used the wrong key.
See https://openresty.org/en/linux-packages.html#rhel-9-or-later for more details.

**Comment by danielkauf** [comment]
Right, I missed that the repo was different in redhat 9 (I am upgrading a redhat 8 to 9). Thank you a lot. I worked fine once I changed the repo.
