### ISSUE TITLE
there is a mistake  in the artical about installation

### ISSUE THREAD

**Issue by wangchunpeng** [openresty/openresty#946]
In the Openresty offical website, there is a mistake  in the artical about installation, 

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/openresty.gpg] http://openresty.org/package/arm64/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/openresty.list > /dev/null 

“http://openresty.org/package/arm64/ubuntu“ should be ” http://openresty.org/package/ubuntu“ ？

**Comment by zhuizhuhaomeng** [comment]
I have verified on Ubuntu 22 arm64. There was no error at all.
