### ISSUE TITLE
Package Request: Openresty official pre-built package for Amazon Linux 2023

### ISSUE THREAD

**Issue by yufengzheng4** [openresty/openresty#947]
We would like to get official pre-built package for Amazon Linux 2023 (https://aws.amazon.com/linux/amazon-linux-2023/). The currently pre-built page only has package for Amazon Linux 1 and 2: https://openresty.org/en/linux-packages.html#amazon-linux

Thank you very much.

**Comment by zhuizhuhaomeng** [comment]
Thank you for your feedback, we will add it as soon as possible.

**Comment by xiaocang** [comment]
Hi @yufengzheng4, We've added support for amazon linux 2023, so you can try it out, and if you run into problems, feel free to give us feedback!
