### ISSUE TITLE
Tag Problem in OpenResty v1.21.4.3

### ISSUE THREAD

**Issue by catatsuy** [openresty/openresty#948]
Hello,

I found a problem with the tag for OpenResty v1.21.4.3 on GitHub. The tag includes newer commits that should not be there. This is confusing.

Can you please check and fix the tag? @xiaocang 

Thank you.

**Comment by xiaocang** [comment]
Thanks for the report, first of all. Exactly which commits are you referring to as newer commits? I didn't find any errors when I checked

**Comment by catatsuy** [comment]
I am sorry for my mistake about the OpenResty v1.21.4.3 tag. I looked again and saw that there was no problem.

Thank you for checking it. I am sorry for the confusion. @xiaocang
