### ISSUE TITLE
When a large number of requests are time-consuming, they affect each other, causing 499

### ISSUE THREAD

**Issue by funky-eyes** [openresty/openresty#951]
When a request has a large number of high rt, some normal requests will not respond normally, resulting in 499. When the relevant high rt application solves the problem of high rt, 499 will disappear
I don't know if it has anything to do with the version of openrestry I use.
openresty/1.13.6.2
centos：7.9.2009
kernel：3.10.0-1160.81.1.e17.x86_64
ulimit openfiles: 1000000
![image](https://github.com/openresty/openresty/assets/19943636/1be422fc-9000-41e3-ba34-df65ee98c462)

**Comment by oowl** [comment]
HTTP 499 in Nginx means that the client closed the connection before the server answered the request. In my experience is usually caused by client-side timeout.  So the problem seems your upstream server does not respond anything when HTTP client timeout occurs.

**Comment by zhuizhuhaomeng** [comment]
> a request has a large number of high rt
What exactly does the high rt mean?
Does it mean the request will block the nginx cycle and nginx cannot serve other requests?
Or does it mean that the upstream of the high rt request response slowly?

If it is the latter, then it is abnormal.
If it is the first, you can try to yield in the high rt request or don't use the blocking api.

**Comment by funky-eyes** [comment]
I have multiple upstream services. For example, when the qps of my service A reaches 230 and rt30ms, service B will be affected by service A, resulting in 499 rt jitter. When I migrate the A service to another Openrestry cluster, the problem is solved immediately. The following is the monitoring chart at that time. The cpu, io, and load are not abnormal. The Openrestry cluster is very healthy.
![image](https://github.com/openresty/openresty/assets/19943636/c95c91d6-6432-4384-b971-2d2ad14c460d)
![image](https://github.com/openresty/openresty/assets/19943636/bd1d83f0-4478-43b0-8bc1-05e81b2aadb6)
![image](https://github.com/openresty/openresty/assets/19943636/016b0afe-f876-43b0-b88a-787c7fac4140)

**Comment by zhuizhuhaomeng** [comment]
You can use OpenResty XRay to analyze this issue.
Please goto https://xray.openresty.com

**Comment by funky-eyes** [comment]
I will try to use it to analyze it, thanks for the reply

**Comment by hujun-w-2** [comment]
have you resloved?
