### ISSUE TITLE
Why add --without-pcre2 to configure arguments?

### ISSUE THREAD

**Issue by devhaozi** [openresty/openresty#955]
![image](https://github.com/openresty/openresty/assets/115467771/be79a6c5-8667-4227-be20-e02707a70b4e)

I try to build openresty-1.25.3.1 with pcre2, then I found that `--without-pcre2` was added to the configure arguments by default. I think it's caused by here:

https://github.com/openresty/openresty/blob/ad33f56e911d48d47f3cc6f5384fdb165d2d8d81/util/configure#L557-L558

**Comment by zhuizhuhaomeng** [comment]
@devhaozi We have removed the limitation.

**Comment by zhuizhuhaomeng** [comment]
please refer to  https://github.com/openresty/openresty/pull/956
