### ISSUE TITLE
bump to nginx-1.25.4

### ISSUE THREAD

**Issue by NiuBlibing** [openresty/openresty#960]
According to [the nginx news](https://nginx.org/en/security_advisories.html), 1.25.3 is Vulnerabld, we need to bump it to 1.25.4

**Comment by imkebe** [comment]
bump

**Comment by Lathanderjk** [comment]
nginx 1.25.5 relased, it will be nice to bump directly to it.

**Comment by NiuBlibing** [comment]
https://github.com/openresty/openresty/issues/976
