### ISSUE TITLE
使用软件源方式yum安装openresty 1.25.3版本，无法开启http3

### ISSUE THREAD

**Issue by mpv945** [openresty/openresty#975]
我另外一台服务器安装的是nginx 1.25.4 根据官网和网上教程配置了http

全局配置
quic_retry on
quic_gso on
虚拟主机配置quic
listen  [::]:443 quic reuseport default_server

这些配置都无法使用，看nginx官网，在1.25版本就开始支持http3了。目前我的版本是：nginx version: openresty/1.25.3.1 
这个版本应该能完整支持http3的配置

**Comment by devhaozi** [comment]
yum安装的好像没用openssl3版本编译？

运行`nginx -V`看看。
