### ISSUE TITLE
Build Openresty-1.25.3.1+HTTP3 error

### ISSUE THREAD

**Issue by lizj3624** [openresty/openresty#977]
1、version: Openresty-1.25.3.1，OpenSSL-1.1.1w，CentOS6，gcc version 4.4.7 20120313

2、configure
```shell
OPENSSL=/opt/openssl-1.1.1w
PREFIX=/opt/openresty-1.25.3.1
THIRDPARTY_DIR=/opt/op-1.25.3.1
ZLIB=zlib-1.2.8
PCRE=pcre-8.39
./configure --prefix=${PREFIX} --with-threads --with-http_ssl_module --with-http_v2_module --with-http_v3_module --with-stream_ssl_module --with-stream --with-cc-opt="-ggdb -O2 -I${PREFIX}/include -I${OPENSSL}/include" --with-ld-opt="-L${OPENSSL}/lib" --with-pcre=${THIRDPARTY_DIR}/${PCRE} --with-pcre-jit --with-zlib=${THIRDPARTY_DIR}/${ZLIB} --with-luajit
```
3、make error
```shell
cc -c -I/opt/op-1.25.3.1/openresty-1.25.3.1/build/luajit-root/opt/openresty-1.25.3.1/luajit/include/luajit-2.1 -I/opt/op-1.25.3.1/openresty-1.25.3.1/build/luajit-root/opt/openresty-1.25.3.1/luajit/include/luajit-2.1  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -g -O2 -ggdb -O2 -I/opt/openresty-1.25.3.1/include -I/opt/opensslinclude -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/unix -I ../ngx_devel_kit-0.3.3/objs -I objs/addon/ndk -I ../ngx_lua-0.10.26/src/api -I ../ngx_stream_lua-0.0.14/src/api -I /opt/op-1.25.3.1/pcre-8.39 -I /opt/op-1.25.3.1/zlib-1.2.8 -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/http/v3 -I ../ngx_devel_kit-0.3.3/src -I ../ngx_devel_kit-0.3.3/src -I ../ngx_devel_kit-0.3.3/objs -I objs/addon/ndk -I /opt/op-1.25.3.1/openresty-1.25.3.1/build/luajit-root/opt/openresty-1.25.3.1/luajit/include/luajit-2.1 -I src/stream -I /opt/op-1.25.3.1/openresty-1.25.3.1/build/luajit-root/opt/openresty-1.25.3.1/luajit/include/luajit-2.1 \
		-o objs/addon/src/ngx_http_lua_log.o \
		../ngx_lua-0.10.26/src/ngx_http_lua_log.c
In file included from ../ngx_lua-0.10.26/src/ngx_http_lua_util.h:19,
                 from ../ngx_lua-0.10.26/src/ngx_http_lua_log.c:15:
../ngx_lua-0.10.26/src/api/ngx_http_lua_api.h:25: error: redefinition of typedef ‘ngx_http_lua_co_ctx_t’
../ngx_lua-0.10.26/src/ngx_http_lua_common.h:166: note: previous declaration of ‘ngx_http_lua_co_ctx_t’ was here
make[2]: *** [objs/addon/src/ngx_http_lua_log.o] Error 1
make[2]: Leaving directory `/opt/op-1.25.3.1/openresty-1.25.3.1/build/nginx-1.25.3'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/opt/op-1.25.3.1/openresty-1.25.3.1/build/nginx-1.25.3'
make: *** [all] Error 2
```

**Comment by keysLo** [comment]
I suggest you learn more about openssl. OpenSSL-1.x does not support QUIC.

**Comment by lizj3624** [comment]
I'm using OpenSSL Version： https://github.com/quictls/openssl/tree/OpenSSL_1_1_1w-quic1，support QUIC

**Comment by zhuizhuhaomeng** [comment]
I don't know which gcc version did you use?
The error you reported should be not an error because they are both typedef.

**Comment by keysLo** [comment]
> > I suggest you learn more about openssl. OpenSSL-1.x does not support QUIC.
> 
> Hi, although OpenSSL 1.x does not support QUIC, Nginx did a lot work to make the OpenSSL 1.x library compatible with QUIC in its implementation. You can refer to this https://github.com/nginx/nginx/blob/master/src/event/quic/ngx_event_quic_openssl_compat.c for details.



> > I suggest you learn more about openssl. OpenSSL-1.x does not support QUIC.
> 
> Hi, although OpenSSL 1.x does not support QUIC, Nginx did a lot work to make the OpenSSL 1.x library compatible with QUIC in its implementation. You can refer to this https://github.com/nginx/nginx/blob/master/src/event/quic/ngx_event_quic_openssl_compat.c for details.



> > I suggest you learn more about openssl. OpenSSL-1.x does not support QUIC.
> 
> Hi, although OpenSSL 1.x does not support QUIC, Nginx did a lot work to make the OpenSSL 1.x library compatible with QUIC in its implementation. You can refer to this https://github.com/nginx/nginx/blob/master/src/event/quic/ngx_event_quic_openssl_compat.c for details.

Thank you for informing nginx to do some processing. I tried OpenSSL 1.1.1w to compile normally.

> > I suggest you learn more about openssl. OpenSSL-1.x does not support QUIC.
> 
> Hi, although OpenSSL 1.x does not support QUIC, Nginx did a lot work to make the OpenSSL 1.x library compatible with QUIC in its implementation. You can refer to this https://github.com/nginx/nginx/blob/master/src/event/quic/ngx_event_quic_openssl_compat.c for details.

Thank you for informing nginx to do some processing. I tried OpenSSL 1.1.1w to compile normally.
# nginx -V
nginx version: openresty/1.25.3.1
built by gcc 12.2.0 (Debian 12.2.0-14) 
built with OpenSSL 1.1.1w  11 Sep 2023
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.3 --add-module=../echo-nginx-module-0.63 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.33 --add-module=../ngx_lua-0.10.26 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.37 --add-module=../array-var-nginx-module-0.06 --add-module=../memc-nginx-module-0.20 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../rds-json-nginx-module-0.16 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.14 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -ljemalloc -Wl,-u,pcre_version' --user=www --group=www --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_v3_module --with-http_ssl_module --with-http_gzip_static_module --with-http_realip_module --with-http_flv_module --with-http_mp4_module --with-openssl=/root/oneinstack/src/openresty-1.25.3.1/../openssl-1.1.1w --with-pcre=/root/oneinstack/src/openresty-1.25.3.1/../pcre-8.45 --with-pcre-jit --with-file-aio --with-threads --with-pcre --with-openssl-opt=-g --with-pcre-opt=-g --with-stream --without-pcre2 --with-stream_ssl_module --with-stream_ssl_preread_module

**Comment by keysLo** [comment]
> > I suggest you learn more about openssl. OpenSSL-1.x does not support QUIC.
> 
> Hi, although OpenSSL 1.x does not support QUIC, Nginx did a lot work to make the OpenSSL 1.x library compatible with QUIC in its implementation. You can refer to this https://github.com/nginx/nginx/blob/master/src/event/quic/ngx_event_quic_openssl_compat.c for details.
Thank you for informing nginx to do some processing. I tried OpenSSL 1.1.1w to compile normally.
# nginx -V
nginx version: openresty/1.25.3.1
built by gcc 12.2.0 (Debian 12.2.0-14) 
built with OpenSSL 1.1.1w  11 Sep 2023
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.3 --add-module=../echo-nginx-module-0.63 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.33 --add-module=../ngx_lua-0.10.26 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.37 --add-module=../array-var-nginx-module-0.06 --add-module=../memc-nginx-module-0.20 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../rds-json-nginx-module-0.16 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.14 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -ljemalloc -Wl,-u,pcre_version' --user=www --group=www --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_v3_module --with-http_ssl_module --with-http_gzip_static_module --with-http_realip_module --with-http_flv_module --with-http_mp4_module --with-openssl=/root/oneinstack/src/openresty-1.25.3.1/../openssl-1.1.1w --with-pcre=/root/oneinstack/src/openresty-1.25.3.1/../pcre-8.45 --with-pcre-jit --with-file-aio --with-threads --with-pcre --with-openssl-opt=-g --with-pcre-opt=-g --with-stream --without-pcre2 --with-stream_ssl_module --with-stream_ssl_preread_module

**Comment by lizj3624** [comment]
Compiled successfully in CentOS7，gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Comment by ljhmily** [comment]
> 1、version: Openresty-1.25.3.1，OpenSSL-1.1.1w，CentOS6，gcc version 4.4.7 20120313
> 
> 2、configure
> 
> ```shell
> OPENSSL=/opt/openssl-1.1.1w
> PREFIX=/opt/openresty-1.25.3.1
> THIRDPARTY_DIR=/opt/op-1.25.3.1
> ZLIB=zlib-1.2.8
> PCRE=pcre-8.39
> ./configure --prefix=${PREFIX} --with-threads --with-http_ssl_module --with-http_v2_module --with-http_v3_module --with-stream_ssl_module --with-stream --with-cc-opt="-ggdb -O2 -I${PREFIX}/include -I${OPENSSL}/include" --with-ld-opt="-L${OPENSSL}/lib" --with-pcre=${THIRDPARTY_DIR}/${PCRE} --with-pcre-jit --with-zlib=${THIRDPARTY_DIR}/${ZLIB} --with-luajit
> ```
> 
> 3、make error
> 
> ```shell
> cc -c -I/opt/op-1.25.3.1/openresty-1.25.3.1/build/luajit-root/opt/openresty-1.25.3.1/luajit/include/luajit-2.1 -I/opt/op-1.25.3.1/openresty-1.25.3.1/build/luajit-root/opt/openresty-1.25.3.1/luajit/include/luajit-2.1  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -g -O2 -ggdb -O2 -I/opt/openresty-1.25.3.1/include -I/opt/opensslinclude -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/unix -I ../ngx_devel_kit-0.3.3/objs -I objs/addon/ndk -I ../ngx_lua-0.10.26/src/api -I ../ngx_stream_lua-0.0.14/src/api -I /opt/op-1.25.3.1/pcre-8.39 -I /opt/op-1.25.3.1/zlib-1.2.8 -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/http/v3 -I ../ngx_devel_kit-0.3.3/src -I ../ngx_devel_kit-0.3.3/src -I ../ngx_devel_kit-0.3.3/objs -I objs/addon/ndk -I /opt/op-1.25.3.1/openresty-1.25.3.1/build/luajit-root/opt/openresty-1.25.3.1/luajit/include/luajit-2.1 -I src/stream -I /opt/op-1.25.3.1/openresty-1.25.3.1/build/luajit-root/opt/openresty-1.25.3.1/luajit/include/luajit-2.1 \
> 		-o objs/addon/src/ngx_http_lua_log.o \
> 		../ngx_lua-0.10.26/src/ngx_http_lua_log.c
> In file included from ../ngx_lua-0.10.26/src/ngx_http_lua_util.h:19,
>                  from ../ngx_lua-0.10.26/src/ngx_http_lua_log.c:15:
> ../ngx_lua-0.10.26/src/api/ngx_http_lua_api.h:25: error: redefinition of typedef ‘ngx_http_lua_co_ctx_t’
> ../ngx_lua-0.10.26/src/ngx_http_lua_common.h:166: note: previous declaration of ‘ngx_http_lua_co_ctx_t’ was here
> make[2]: *** [objs/addon/src/ngx_http_lua_log.o] Error 1
> make[2]: Leaving directory `/opt/op-1.25.3.1/openresty-1.25.3.1/build/nginx-1.25.3'
> make[1]: *** [build] Error 2
> make[1]: Leaving directory `/opt/op-1.25.3.1/openresty-1.25.3.1/build/nginx-1.25.3'
> make: *** [all] Error 2
> ```
关于centos6系列，修复此编译bug方法：
sed -i "/Public API/ i#include \<..\/ngx_http_lua_common.h\>" build/ngx_lua-0.10.26/src/api/ngx_http_lua_api.h
sed -i "s/ngx_http_lua_co_ctx_t;/;/" build/ngx_lua-0.10.26/src/api/ngx_http_lua_api.h

修复后即可编译成功
